### ISSUE TITLE
convert transformations to a single deformation field

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTsPy#100]
I currently have  a bunch of image registrations which have been applied serially and I am using it to inter operate with another tool which expects a single displacement field as input.

Is there a way in ANTSpy to take a transform list and generate a single displacement field out of it? There is a `transform_from_displacement_field` but could not find something in the other direction.

In the docs, I also saw an example where it refers the method: `compose_transforms_to_field` but it does not seem to be an exported method.

**Comment by ntustison** [comment]
In ANTs, this functionality is carried out using ``antsApplyTransforms``.  The equivalent function in ANTsPy is ``ants.apply_transforms``.  Have you tried that?
