### ISSUE TITLE
why ANTsPy is faster than ANTs?

### ISSUE THREAD

**Issue by NovemberSun** [ANTsX/ANTsPy#101]
i used antspy and ANTs(c) for brain MRI registration, and i used default parameter, but ANTsPy performs much faster than ANTs. I think this is a little strange and i wonder is there any differences in the performance of the two tools? Hope for you answer, thank you!
My code are:
 (1) ANTsPy:
out = ants.registration(
    fixed = fixedImage, moving = movingImage,
    type_of_transform = "SyN", 
    verbose = True)
(2) ANTs:
antsRegistrationSyN.sh -d 3 -f xxx -m xxx -o xxx

**Comment by ntustison** [comment]
Those ``antsRegistration`` calls don't use the same SyN parameters.  (2) uses more higher resolution level iterations which explains its longer execution time.
