### ISSUE TITLE
set default value for background after rotation

### ISSUE THREAD

**Issue by vanAmsterdam** [ANTsX/ANTsPy#102]
This issue is similar to issue #95 
For my application, when rotating an image (CT scan), the default background value should be -1024; When using Rotate3D, the voxels that are not in the original scan all get value 0.

A nice solution would yield:
rot = Rotate3D(..., defaultvalue=-1024)

I can think of workarounds: 
a. using ants.contrib.ShiftScaleIntensity (subtract defaultvalue, rotate, add defaultvalue)
b. using padding and cropping:

```
padded_scan = pad_image(scan, ..., value=-1024)
padded_scan = rot.transform(scan)
scan = ants.crop_indices(padded_scan, ....)
```

but a. costs more computation and b is tedious for calculating the required padded shape

**Comment by ntustison** [comment]
Where is this function ``Rotate3D``?  I can't seem to find it.

**Comment by vanAmsterdam** [comment]
it's in here: ants.contrib.sampling.affine3d

**Comment by ntustison** [comment]
So it seems like we need to modify [apply_to_image](https://github.com/ANTsX/ANTsPy/blob/master/ants/core/ants_transform.py#L152) to permit a default value as we did in ``apply_transform`` for the issue referenced above.  In the meantime, however, can you write the transform to disk using ``write_transform`` and then using ``apply_transform`` which has the default value option?

**Comment by vanAmsterdam** [comment]
sounds good; I'll try that out for now and see which code runs fastest. Thanks!
