### ISSUE TITLE
Could you please provide the pre-compiled binary for Window 10?

### ISSUE THREAD

**Issue by qiang-zhang-neu** [ANTsX/ANTsPy#103]
ANTsPy is a really good project. However, the pre-compiled binary is provided for MacOS and Linux, but not for Windows. Could you please provide the binary for Windows? Or could you please provide the tutorial to build binary for python from source code?

In addition, if I have built the Ants, how can I used the ANTs in python?

**Comment by stnava** [comment]
covered in response to other issues.
