### ISSUE TITLE
Installation error:

### ISSUE THREAD

**Issue by qiang-zhang-neu** [ANTsX/ANTsPy#104]
Bug description:

I want to install the ANTsPy by:

```
git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install
```

Error happen:
```

running install
running build_py
running build_ext
Configuring ITK
No local ITK installation found... Building ITK now...
error: [WinError 193] %1 is not a valid win32 application

```
My environment is:

```
Win10
Anaconda 64 bit
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
```

The error show that "1% is not a valid win32 application", thus I install a 32 bit python:

`Python 3.7.5 (default, Oct 31 2019, 14:57:46) [MSC v.1916 32 bit (Intel)] :: Anaconda, Inc. on win32`

However, the same error still happen. 

Any suggestion is appreciated.

**Comment by stnava** [comment]
see the thread on windows installation here

https://github.com/ANTsX/ANTsPy/issues/28

**Comment by elliotresearcher** [comment]
HI you found any solution? i have same error
