### ISSUE TITLE
Bizarre N4 error

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPy#107]
**Describe the bug**
With recent updates, calling N4 *the first time* leads to what appears to be a pipeline error.  the same call repeated the 2nd time runs fine.

**To Reproduce**
install a recent version of antspy, then:

```
python
import ants
image = ants.image_read(ants.get_ants_data('r16'))
outimage = ants.n4_bias_field_correction( image ) # fails
outimage = ants.n4_bias_field_correction( image ) # works
```

tested on OS X but also fails in the same way on travis ( linux ) .... @ntustison ... this is all I know as yet.

**Comment by stnava** [comment]
``` 
>>> import ants
>>> image = ants.image_read(ants.get_ants_data('r16'))
>>> outimage = ants.n4_bias_field_correction( image )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/ANTsPy/ants/utils/bias_correction.py", line 130, in n4_bias_field_correction
    libfn(processed_args)
RuntimeError: /tmp/ANTsPy/itksource/Modules/Core/Common/src/itkDataObject.cxx:348:
Requested region is (at least partially) outside the largest possible region.
>>> outimage = ants.n4_bias_field_correction( image )
>>> 
```

**Comment by ntustison** [comment]
That is weird. Looking at it now.

**Comment by ntustison** [comment]
Okay, so the issue has to do with the accommodation of an arbitrary spline spacing, i.e. this does not work ``spline_param=200`` (default) but this ``spline_param=(5,5)`` does work.  With the former, a new padded image is created and something is going awry with the bookkeeping after the filter completes.  Looking at the latest ANTs code to see what the problem there might be.

**Comment by ntustison** [comment]
It appears that ANTsPy is pulling an older version of ``ANTs/Examples/N4BiasFieldCorrection.cxx``.   If I do a ``diff`` on the two files, I get

```
diff ants/lib/antscore/N4BiasFieldCorrection.cxx ~/Pkg/ANTs/Examples/N4BiasFieldCorrection.cxx 
28c28
< class CommandIterationUpdate : public itk::Command
---
> class CommandIterationUpdate final : public itk::Command
284c284
<           float domain = static_cast<RealType>( originalImageSize[d] - 1 ) * inputImage->GetSpacing()[d];
---
>           float domain = static_cast<float>( originalImageSize[d] - 1 ) * static_cast<float>( inputImage->GetSpacing()[d] );
289c289
<                                                                      - domain ) / inputImage->GetSpacing()[d] + 0.5 );
---
>                                                                      - domain ) / static_cast<float>( inputImage->GetSpacing()[d] ) + static_cast<float>( 0.5 ) );
292c292
<           newOrigin[d] -= ( static_cast<RealType>( lowerBound[d] )
---
>           newOrigin[d] -= ( static_cast<double>( lowerBound[d] )
302c302
<         padder->SetConstant( 0 );
---
>         padder->SetConstant( itk::NumericTraits<typename ImageType::PixelType>::ZeroValue() );
516c516
<         if( maskImage->GetPixel( ItD.GetIndex() ) == itk::NumericTraits<typename MaskImageType::PixelType>::ZeroValue() )
---
>         if( itk::Math::FloatAlmostEqual( maskImage->GetPixel( ItD.GetIndex() ), itk::NumericTraits<typename MaskImageType::PixelType>::ZeroValue() ) )
552c552
<         if( maskImage->GetPixel( ItD.GetIndex() ) == maskLabel )
---
>         if( itk::Math::FloatAlmostEqual( maskImage->GetPixel( ItD.GetIndex() ), static_cast<RealType>( maskLabel ) ) )
```

Can we update the current ANTs version?  It might also solve the issue with the "missing" ``ImageMathHelper.cxx``.

**Comment by ntustison** [comment]
Specifically, the second diff item might be the culprit.

**Comment by stnava** [comment]
is this ants version too old?

https://github.com/ANTsX/ANTsPy/commit/3da37bb2d68b0e0549fd4fa108a550f9e3f40315

ie

https://github.com/ANTsX/ANTs/commit/5412effb168e3e70ddb781b320aeff6cbf52a11a

did you update antspy?

I guess it's possible the itktag needs to be updated ....

**Comment by stnava** [comment]
I rebuilt everything with a clean ITK and ANTs build ( and recent tags ) and still no luck.  all tests pass except n4.

**Comment by ntustison** [comment]
Okay, thanks.  Let me rebuild from scratch and I'll let you know.

**Comment by ntustison** [comment]
Okay, @stnava, see if this [commit](https://github.com/ANTsX/ANTs/commit/4528978446c73ed09927ea5ae1721b280d534dc0#diff-06b7de4cbfdd1e2cd545c132a73b8a4eL144) fixes the issue.  It does on my machine.  For some reason, the ANTsPy pipeline was incompatible with the unsigned short image.  When I replaced that with type int, it appeared to work as expected.

**Comment by stnava** [comment]
that appears to have worked on my local machine.  will wait on travis builds ( may need to clear cache, though, will see )

**Comment by stnava** [comment]
Resolved!  thanks @ntustison
