### ISSUE TITLE
Why are the wheel files not automatically deployed by the CI?

### ISSUE THREAD

**Issue by halirutan** [ANTsX/ANTsPy#108]
ANTsPy uses TravisCI to build and test the code. What I used in past projects is that when I tagged a commit with a version, TravisCI automatically deployed files to the release section on GitHub.

I mention this because the latest two [version tags](https://github.com/ANTsX/ANTsPy/releases) 0.2.1 and 0.2.2 have no files attached to them in the release section and I had to build ANTsPy from the source.

Is there a reason why this is not done?

**Comment by stnava** [comment]
we are hoping to use pypi as we recently were granted the resources that would allow us to deploy in that manner.   no timeline yet - we just want to go through some cleanup and get to a stable point before doing so.   anyway, I don't recall how to set this up on travis / GH and don't have time to set it up but would be happy to consider and refine a pull request that implements your suggestion.

**Comment by halirutan** [comment]
@stnava A PR wouldn't work, because there are several steps that are different because I'm working on a fork. However, I already did the leg-work last night but ran into an unexpected problem, which made it impossible to test if the deployment works. For me, [TravisCI times out](https://travis-ci.org/halirutan/ANTsPy) because there is a hard limit of 50 min, and at this point, ANTsPy is only 97% finished.

That left me confused because I couldn't understand how _you_ are using TravisCI then.  I checked your logs of Travis and lo and behold you are [allowed to use more time](https://travis-ci.org/ANTsX/ANTsPy/builds/637640247). It seems you have special conditions.

In the end, that means that I cannot try it on my end and ensure it works. The version of my travis.yml I was going to test can be found [here](https://travis-ci.org/halirutan/ANTsPy/jobs/638430603/config). There are actually only 3 import points

- Build the wheel and ensure it doesn't time out. Travis stops when there is no log output for 10 min and packing the `whl` needs a bit of time. Therefore, I used `travis_wait` which does things in the background but prints log messages regularly.
- Create an OAuth-token on GitHub that gives you access to deploying the file to GitHub-releases. This token is then put into a secret variable on Travis and used as I did in the line `api_key: $GITHUB_ACCESS_TOKEN`. This gives Travis the right to publish the build to releases
- Create a "deploy" section in `travis.yml` like I did, find the right file and publish it

**Comment by stnava** [comment]
thanks much for this - I will try to work from here but don't have a lot of time for the next couple weeks.  would it helped if I added you as a developer?

**Comment by halirutan** [comment]
@stnava I was looking a bit closer into the documentation and the logs. I think adding me as a developer won't help much. The two things that take much time are

- compiling ITK
- compiling ANTs

**If** these need to be rebuilt, it already takes about 30 min which sums up to [50 min](https://travis-ci.org/ANTsX/ANTsPy/builds/637640247) with building and testing ANTsPy. When ITK and ANTs is already cached in Travis, then the building and testing only need about [11 min](https://travis-ci.org/ANTsX/ANTsPy/builds/616957715).

If the ITK or ANTs dependencies change, they need to be rebuilt and the runtime is very hard on the timout limit already. Adding the deployment as an additional step only increases the Travis time. Additionally, Travis only builds it for Linux at the moment and we'd certainly want the wheel files for Mac as well (maybe also Windoze, but I don't really care for that).
What I'm saying is that doing the same building/testing/deploying process for possibly 3 operating systems will very likely time out on Travis.

One possible solution is to use something like a docker image that already contains the ITK/ANTs dependencies in the version ANTsPy needs. Then the Travis script would essentially only contain grabbing the docker image, building ANTsPy, test and deploy.

@stnava Do you know anyone who works with docker (or similar) who could help?

**Comment by stnava** [comment]
I've made these: https://hub.docker.com/u/stnava 

and @dorianps has a more mature system here https://github.com/dorianps/docker

but we are hoping to use pypi for deployment relatively soon.   just need to get a stable-ish ITK/ANTs/Py code set then get a windows version working ..... 

still, deploying to gh would be useful.   for antsx/antspy builds, timeout does not appear to be an issue.

**Comment by halirutan** [comment]
Alright. Let's wait until the next version tag comes and we'll see if at least the whl for Linux is deployed to GitHub. PyPi would indeed be the best solution.
