### ISSUE TITLE
how can I apply the same transforms (to MNI space) to the corresponding labels as I did to the samples 

### ISSUE THREAD

**Issue by zzz123xyz** [ANTsX/ANTsPy#109]
I'm always frustrated how can I apply the same transforms (to MNI space) to the corresponding labels as I did to the samples.

Supposed, I have samples and labels of nifty format. I want to train a model. 
As preprocessing steps, I have transformed the samples into MNI space. Now I want to apply the same transforms to the corresponding labels. so the labels can perfectly match the samples after transforming.  

I have seen similar function in the Matlab SPM package (https://www.fil.ion.ucl.ac.uk/spm/), the Coregister function. I wonder if there is a similar function in the Antspy? or How can I develop this function myself? 
Thanks

**Comment by stnava** [comment]
yes - this is among the most primitive operations in the world of registration.  in ANTsPy, it is called:  `ants.apply_transforms`  --- see https://github.com/ANTsX/ANTsPy/blob/master/tutorials/concatenateRegistrations.ipynb for an example.
