### ISSUE TITLE
Missing boolean type conversion for iMath functions

### ISSUE THREAD

**Issue by halirutan** [ANTsX/ANTsPy#110]
`iMath.py` contains the following definition (and similar ones)

```python
def iMath_laplacian(image, sigma=0.5, normalize=False):
    return iMath(image, 'Laplacian', sigma, normalize)
```

When using exactly this in a small test

```python
import ants

if __name__ == '__main__':
    img = ants.image_read(ants.get_ants_data('r16'))
    ants.iMath_laplacian(img, sigma=0.5, normalize=False)
```

you get an error

```
  File "/.../ants/utils/iMath.py", line 106, in iMath
    libfn(processed_args)
ValueError: stoi: no conversion
```

The reason is that boolean values `True` and `False` are converted to strings and in the call `libfn(processed_args)` inside `iMath.py` it's tried to convert them to an integer. That naturally doesn't work. The hack to make it work and which _should_ do the same is

```python
ants.iMath_laplacian(img, sigma=0.5, normalize="0")
```

`"0"` for `False"` and `"1"` for `True`? I haven't checked the C-sources, but this looks reasonable. All iMath functions that contain a boolean option are affected. I propose to include a fix in

```python
def _int_antsProcessArguments(args):
```
where things like that are handled.

 - OS: MacOS 10.15.2
- Python: 3.7
 - ANTsPy version: Build from recent commit

**Comment by stnava** [comment]
A fix would be very welcome - and this understandable.   In R, T/F get cast to 1/0 so this has not come up there.

**Comment by stnava** [comment]
thanks for this report - definitely a real bug.    here is a fix:

https://github.com/ANTsX/ANTsPy/commit/81e7358ebce79e66ca13e5ba0fb38d38472fd628

**Comment by stnava** [comment]
please close if this works for you.

**Comment by halirutan** [comment]
Looks good to me. If I find some time, I'll extend the unit test to contain an example of this. I guess the missing test is one reason that this wasn't discovered earlier. Thanks for fix.
