### ISSUE TITLE
Cannot install Mac OSX Wheel

### ISSUE THREAD

**Issue by muschellij2** [ANTsX/ANTsPy#111]
**Describe the bug**
Wheel not supported for Mojave.

**To Reproduce**
pip install https://github.com/ANTsX/ANTsPy/releases/download/Weekly/antspy-0.1.4-cp36-cp36m-macosx_10_7_x86_64.whl

ERROR: antspy-0.1.4-cp36-cp36m-macosx_10_7_x86_64.whl is not a supported wheel on this platform.

**Expected behavior**
Wheel for Modern OSX. OS: 10.14.6 (18G1012)

**Comment by muschellij2** [comment]
Looking at more modern releases, https://github.com/ANTsX/ANTsPy/releases/download/v0.1.8/antspyx-0.1.8-cp37-cp37m-macosx_10_14_x86_64.whl exists, but is for 3.7 vs. 3.6 of older wheel. Should change README.

**Comment by stnava** [comment]
please reopen if issues persists.
