### ISSUE TITLE
Cannot install Linux Wheel

### ISSUE THREAD

**Issue by PLSousa** [ANTsX/ANTsPy#112]
**Describe the bug**
Wheel not supported for Linux (Debian 10).

**To Reproduce**
pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl
ERROR: antspy-0.1.4-cp36-cp36m-linux_x86_64.whl is not a supported wheel on this platform.

**Expected behavior**
A supported wheel for Linux (Debian 10) and Python 3.7

**Desktop (please complete the following information):**
 - OS: Linux Debian 10
- Python 3.7

**Comment by PLSousa** [comment]
Install works using 
**pip3** install [https://github.com/ANTsX/ANTsPy/releases/download/**v0.2.0/antspyx-0.2.0-cp37-cp37m-linux_x86_64.whl**](url)

**Comment by stnava** [comment]
please reopen if issues persists.
