### ISSUE TITLE
Image Orientation Changes when Converting to Numpy array

### ISSUE THREAD

**Issue by willi3by** [ANTsX/ANTsPy#113]
**Describe the bug**
When an ants image is converted to a numpy array, then converted back to an ants image, the orientation changes. 

**To Reproduce**
1. `img = ants.image_read( ants.get_ants_data('mni') )`
2. `img_array = img.numpy()`
3. `img_array = ants.from_numpy(img_array)`

**Expected behavior**
I would expect the orientation of the image to stay the same.

**Screenshots**
![Screen Shot 2020-01-30 at 11 25 50 AM](https://user-images.githubusercontent.com/42728698/73468782-51168b80-4353-11ea-8dbc-91ffe5122efb.png)
![Screen Shot 2020-01-30 at 11 25 59 AM](https://user-images.githubusercontent.com/42728698/73468785-54117c00-4353-11ea-9794-b18ec2709be0.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
ants 0.0.7
python 3.7.3

**Comment by stnava** [comment]
conversion to numpy is lossy.    it's a one to one conversion from antsImage to numpy but a one to many possible outcomes in the other direction.   reopen if you think otherwise and can propose a solution.
