### ISSUE TITLE
pip installation doesn't install dependencies

### ISSUE THREAD

**Issue by ashgillman** [ANTsX/ANTsPy#116]
**Describe the bug**
Pip installation (e.g., `pip3 install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl`) doesn't install dependencies.

This is because pip doesn't look at requriements.txt.

Possible solutions:
1. Move requirements.txt contents to setup.cfg
    e.g., 
    ```
    [options]
    python_requries = >=3.5
    install_requires =
        pandas
        pyyaml
        ...
    ```
2. Move requirements into setup.py
    e.g.,
    ```
    setup(
        ...
        install_requires=['pandas', 'pyyaml', ...],
        ...)
    ```
3. Parse requirements.txt from setup.py
    ```
    with open('requirements.txt', 'r') as fp:
        required = fp.read().splitlines()
    ...
    setup(
        ...
        install_requires=required,
        ...)
    ```

**To Reproduce**
1. On clean python setup, run  `pip3 install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl`.
2. Run `python3 import ants`

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: Linux (probably all)

**Comment by stnava** [comment]
hi - thanks for this - do you mind making a pull request?  we are inching toward a pip release and this would be very helpful.   I am not partial to any particular solution above but we may have to massage dependencies eg not sure all of these are present https://github.com/stnava/ANTsRPy/blob/master/Dockerfile

**Comment by ashgillman** [comment]
No worries. If you aren't to concerned about removing `requriements.txt`, my preferred solution is 1.

I'll make a PR

**Comment by ashgillman** [comment]
Looks like you beat me to it sorry. Unfortunately, I've given up on trying to package this for the Nix package manager, as the installation process seems to be rather "custom".

**Comment by halirutan** [comment]
Great issue report. I also ran into this because I built ANTsPy for the systems in our institute. What I did is using pip to download all packages in `requirements.txt` and put an `ants-requirements.txt` in the system so that all depending packages are also installed. This is obsolete now, thanks for that.

@stnava One minor issue: When you import ants now, you get 

```
UserWarning: Cant import Plotly. Install it `pip install chart_studio` if you want to use ants.render_surface_function
  "Cant import Plotly. Install it `pip install chart_studio` if you want to use ants.render_surface_function"
```

Would it be a good idea to also put `chart_studio` in the dependencies in `setup.py` to give the user a clean install?

**Comment by stnava** [comment]
@halirutan probably worth doing.   re: moving to  pypi - do you think the package is in good enough shape to make a release and push to pypi?   I haven't tried it before - not sure what to expect.

**Comment by halirutan** [comment]
One thing we should discuss is if the following observation is correct: For [this issue](https://github.com/ANTsX/ANTsPy/issues/115) I checked today if I could potentially share my builds with a different Linux system and what I was concerned about is if the build shared libraries have some dependencies that might break. I used `ldd` to check all of the created `.so` files and it seems everything is statically linked and the libraries depend only on standard things like `libstdc++`.

If I'm not mistaken, the package should then work on all similar Linux x86 64bit systems. I can build ANTsPy for Linux and the latest macOS with Python 3.6 and 3.7.

What steps, except for building and uploading the wheels, is missing to provide ANTsPy on the official PyPi repo?

**Comment by stnava** [comment]
@halirutan - I think that is the case .... we lack "proof" that windows builds "work" , though anecdotal evidence suggests it is so.  I can pull the trigger on trying to upload wheels but I don't want to inundate pypi with lots of wheels/releases b/c they are each quite large ( > 200MB ).

**Comment by halirutan** [comment]
[Believing this here](https://www.reddit.com/r/dataisbeautiful/comments/b10cjw/most_usually_and_preferably_used_python_versions/eiiaqoz/) from about a year ago, we should be OK when supporting 3.6 and 3.7

![img](https://i.redd.it/zz2abtyw53m21.png)

It should nowadays cover more than 75% of Python users. That would make two wheels for each system.

**Comment by stnava** [comment]
@halirutan this is relevant : https://www.python.org/dev/peps/pep-0513/

I was able to add this : https://pypi.org/project/antspyx/0.2.4/ but not yet successful with linux .... need to figure out above.

**Comment by stnava** [comment]
also promising: https://github.com/joerick/cibuildwheel

**Comment by stnava** [comment]
I pieced together a solution detailed here.

https://github.com/ANTsX/ANTsPy/wiki/Building-portable-wheels-for-ANTsPy
