### ISSUE TITLE
Registration - "SyNOnly" performs affine step

### ISSUE THREAD

**Issue by jankrepl** [ANTsX/ANTsPy#119]
**Describe the bug**
Based on the [API documentation](https://antspy.readthedocs.io/en/latest/registration.html#ants.registration) setting ``type_of_transform="SyNOnly"`` should lead to no initial affine registration being estimated. However, it actually estimates it.

**To Reproduce**
```
import ants
import numpy as np

img = np.random.random((300, 300))
img_ants = ants.image_clone(ants.from_numpy(img), pixeltype='float')

meta = ants.registration(img_ants,
                         img_ants,
                         type_of_transform='SyNOnly')

print(meta['fwdtransforms'])
# ['/tmp/tmpnm453e9_1Warp.nii.gz', '/tmp/tmpnm453e9_0GenericAffine.mat']
```

**Expected behavior**
I would assume that only a single `nii.gz` file is generated representing the deformable transformation.

**Desktop (please complete the following information):**
- OS: Ubuntu 18.04.2 LTS
- Version: 0.1.7 (installed via your wheel in releases)

**Additional context**
I am using SyN as a benchmark for my research and I would like to see how it performs with and without initial affine transform.

Thank you in advance

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy/blob/a31180518c84385433bb7dbbb18b247b071f54dc/ants/registration/interface.py#L559

this is the location of these settings.  the initial transform is here:

https://github.com/ANTsX/ANTsPy/blob/a31180518c84385433bb7dbbb18b247b071f54dc/ants/registration/interface.py#L300-L301

this sets up a center of mass initialization.   

if you don't want this, then you can pass an identity transform as an initial map.

in any case, you will get a *mat and *Warp back from the method.


regarding evaluating ANTs - the critical things that most people overlook in evaluations:

* metric settings

* regularization parameters

* optimization schedule

* initial pre-processing of images ( including affine alignment, if any )

for new problems, these different parameters should be explored.

**Comment by jankrepl** [comment]
Perfect, I was guessing this might be some center of mass thing.

Just for completeness `initial_transform="identity"` does the job.

I was caught off guard because of this since the docs make it look as if no affine transformation was estimated. Also, intuitively `initial_transform=None` should default to identity in my opinion.

Regarding evaluating ANTs, my goal was to separate out the affine transformation from the ANTs implementation of SyN algorithm to make it comparable to other models that do not have this "initial" step. I am aware of all the hyperparamters one has to search through to make things work well. And it actually does work really well! You and other developers have done a great job.


Thank you very much! Feel free to close this issue
