### ISSUE TITLE
masking array slow and get_mask() kill ipython kernel

### ISSUE THREAD

**Issue by MaximilianHoffmann** [ANTsX/ANTsPy#120]
**Describe the bug**
I am trying to mask a volume before performing the registration, with the good faith, that the masked points won't be used for computing the registration metric.

`im1.mask_image(ants.from_numpy((vol1>0).astype('uint8')))`

takes a very long time, i.e. 5 to 10 s for a 3d array of (500,2000,300).
Additionally,executing 

`mask=im1.get_mask()`
afterwards kills my ipython kernel ca. 50% of the times. 

Do I have the right understanding, of what these functions are supposed to do?

**Comment by stnava** [comment]
here is what you might try:

```
import ants
imgfn = ants.get_ants_data("r16")
img = ants.image_read( imgfn )
msk = ants.get_mask( img ) # does operations beyond just thresholding - slower, more complex
msk2 = ants.threshold_image( img, 10, 255 ) # trivial threshold but fast
img * msk   # just multiply
ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (256, 256)
	 Spacing    : (1.0, 1.0)
	 Origin     : (0.0, 0.0)
	 Direction  : [1. 0. 0. 1.]

```

**Comment by MaximilianHoffmann** [comment]
Ah thanks, sorry, I did not get that the get_mask() function returns a binary mask already.
Thanks. I was hoping , though that the mask somehow enables me to exclude parts of the volume from the registration metric instead of just setting them to zero.

**Comment by stnava** [comment]
see `help( ants.registration ) ` then the `mask` argument which is what you probably want.

note that your volumes are quite large and you should experiment ( parameter choices etc ) on much smaller images ( eg 128x128x128 ).   inspect results at low-res, then scale up as needed.
