### ISSUE TITLE
ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found

### ISSUE THREAD

**Issue by rueberger** [ANTsX/ANTsPy#122]
**Describe the bug**

An `ImportError` is thrown when attempting to import ants, following binary installation

#46 but with CentOS

**To Reproduce**
1. `pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.8/antspy-0.1.7-cp36-cp36m-linux_x86_64.whl`
2. `import ants`

**Expected behavior**

No `ImportError` is thrown

**Additional context**

- CentOS 7.6.1810
- Python 3.6.1 
- GCC 9.1.0

Full traceback:

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-78f96f50f910> in <module>()
----> 1 import ants

~/.local/lib/python3.6/site-packages/ants/__init__.py in <module>()
      5     pass
      6
----> 7 from .core import *
      8 from .utils import *
      9 from .segmentation import *

~/.local/lib/python3.6/site-packages/ants/core/__init__.py in <module>()
      1
----> 2 from .ants_image import *
      3 from .ants_image_io import *
      4
      5 from .ants_transform import *

~/.local/lib/python3.6/site-packages/ants/core/ants_image.py in <module>()
     25 import inspect
     26
---> 27 from .. import utils, registration, segmentation, viz
     28 from . import ants_image_io as iio2
     29

~/.local/lib/python3.6/site-packages/ants/utils/__init__.py in <module>()
      1
----> 2 from .bias_correction import *
      3 from .channels import *
      4 from .convert_nibabel import *
      5 from .crop_image import *

~/.local/lib/python3.6/site-packages/ants/utils/bias_correction.py in <module>()
      7
      8
----> 9 from . import process_args as pargs
     10 from .get_mask import get_mask
     11 from .iMath import iMath

~/.local/lib/python3.6/site-packages/ants/utils/process_args.py in <module>()
     11
     12 from ..core import ants_image as iio
---> 13 from .. import lib
     14
     15 _short_ptype_map = {'unsigned char' : 'UC',

~/.local/lib/python3.6/site-packages/ants/lib/__init__.py in <module>()
      2
      3 ## LOCAL ##
----> 4 from .antiAlias import *
      5 from .antsImage import *
      6 from .antsImageClone import *

ImportError: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/users/a5b/.local/lib/python3.6/site-packages/ants/lib/antiAlias.cpython-36m-x86_64-linux-gnu.so)
```

**Comment by stnava** [comment]
not sure what this is caused by but we are not going back to older releases at this point.

**Comment by rueberger** [comment]
Are you referring to python 3.6.1? Because I installed the latest available binary for linux and python 3.6. 

There is only a 0.1.8 binary for mac and a 0.2.0 binary for linux and py37. 

Am I looking in the [wrong place](https://github.com/ANTsX/ANTsPy/releases) for binaries?

**Comment by stnava** [comment]
I apologize that we don't have binaries worked out.   We just don't have the resources to manage all the containers that would be needed .... anyway, this is also why we are working to get `pypi` releases going, as we recently got approval for the necessary on disk size.  however, we want such a release to be rather stable.  so, at this time, we are focusing on that process.  

GLIBC errors are typically resolved by installing the missing library.

**Comment by rueberger** [comment]
No worries. Thanks for getting back to me so soon.
