### ISSUE TITLE
Recommended route for averaging a list of `ANTsImage`s 

### ISSUE THREAD

**Issue by rueberger** [ANTsX/ANTsPy#124]
I wish to take the voxel-wise average of

`brains = [ANTsImage(....) for _ in range(n_brains)]`

(Assume they all occupy the same physical space)

Something like `np.mean(brains, axis=-1)` is met with 

```
AttributeError                            Traceback (most recent call last)
<ipython-input-49-571ade10cea1> in <module>
----> 1 groupwise_registration(brains)

<ipython-input-48-a2acfe2bd26b> in groupwise_registration(brains, template_type)
     28     # update template to the average of template-warped brains
     29     warped_arrs = [t['warpedmovout'] for t in transforms]
---> 30     return np.mean(warped_arrs, axis=-1)

<__array_function__ internals> in mean(*args, **kwargs)

~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/fromnumeric.py in mean(a, axis, dtype, out, keepdims)
   3255 
   3256     return _methods._mean(a, axis=axis, dtype=dtype,
-> 3257                           out=out, **kwargs)
   3258 
   3259 

~/.pyenv/versions/3.7.1/lib/python3.7/site-packages/numpy/core/_methods.py in _mean(a, axis, dtype, out, keepdims)
    159             ret = arr.dtype.type(ret / rcount)
    160         else:
--> 161             ret = ret.dtype.type(ret / rcount)
    162     else:
    163         ret = ret / rcount

AttributeError: 'str' object has no attribute 'type'
```

Where `ret.dtype == 'float32'`. 

Now I can do the obvious thing of calling `ANTsImage.view` and working with the underlying data, but I wonder if that is the intended route?

Unfortunately I'm still running an old version, this is on antspy 0.1.8. 

PS is there a mailing list for antspy where I can ask such questions?

**Comment by stnava** [comment]
something like this?   antspy lets you treat images as numerical objects, for the most part.

```
import ants
fn = ants.get_ants_data( "r16" )
img1 = ants.image_read( fn )
img2 = ants.image_read( fn )
avg = ( img1 + img2 ) * 0.5   # assumes the images are the same size / in the same physical space
```

see also `ants.build_template`

**Comment by stnava** [comment]
no mailing list .... might start a slack or discourse at some point.

>

**Comment by rueberger** [comment]
Thanks for that!  `build_template` is exactly what I was looking for. 

I would close this but I feel like getting an `AttributeError` counts as a bug (as opposed to throwing `NotImplemented` before getting to that point). I guess you wouldn't 
expect/intend for `np.mean(brains)` to work then?
