### ISSUE TITLE
Comparing an ANTSTransform and itk Euler3DTransform

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTsPy#127]
Is there a way from with ANTS or SimpleITK to get the Euler angles and the translation parameters from an Ants `AffineTransform` file (the transform is actually a rigid transformation). I want to compare the parameters between the parameters of a `Euler3DTransform` as obtained from another method implemented in ITK.

**Comment by stnava** [comment]
`ants.get_ants_transform_parameters` and `ants.read_transform` -- everything gets mapped to affine type .... as long as you do this consistently, you should be able to compare.
