### ISSUE TITLE
cannot set higher order interpolation with apply_ants_transform_to_image

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTsPy#128]
I am resampling an image with some transformation as follows:

```
ants.apply_ants_transform_to_image(transform, img, img, interpolation='linear')
```

Specifying linear interpolation is fine but if I specify some higher order interpolation method as:

```
ants.apply_ants_transform_to_image(x, img, img, interpolation='hammingWindowedSinc')
```

This fails with: 
```
itk::ERROR: ResampleImageFilter(0x7fa1744498f0): Interpolator not set
```

The method does not document which interpolation schemes are available but I was using these strings from the `apply_transforms` method. I could use that method, I guess but do not want to save the transform to file and load it again (as the `apply_transforms` takes file names as input for the transforms).

**Comment by stnava** [comment]
these are probably the supported interpolation types

https://github.com/ANTsX/ANTsPy/blob/master/ants/lib/LOCAL_antsTransform.h#L261-L342

any help with documentation / testing would be appreciated.

**Comment by dagap** [comment]
Somehow the `apply_transforms` support higher order interpolation but I could not make it work with those strings with `apply_ants_transform_to_image`. I just use `apply_transforms` for the moment. I will look a bit deeper why those other methods are not exposed and make a pull request this weekend.

**Comment by stnava** [comment]
should read documentation closely.
