### ISSUE TITLE
saving ants transforms file

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#133]
When i try to save the ants transform file using ants.write_transform it throws an error saying 
 - AttributeError: 'dict' object has no attribute '_libsuffix' 

Is there any other way to save the ants transform object also when i do this registration for two images with dimensions 456 x 320 it takes 3 mins to do it. i run it on 20 cores by setting the

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS = 20

Thanks a ton
Best
Anurag 

 `mytx = ants.registration(fixed=fi, moving=mi, type_of_transform ="Affine" ,aff_metric="CC")
  mywarpedimage = ants.apply_transforms( fixed=fi, moving=mi, 
  transformlist=mytx['fwdtransforms'] )
             
  ants.write_transform(mytx, f'reg_data_affine_graph/{i}_{j}_tx.mat')`

**Comment by stnava** [comment]
here is the example from the help:

```
import ants
tx = ants.new_ants_transform(dimension=2)
tx.set_parameters((0.9,0,0,1.1,10,11))
ants.write_transform(tx, '~/desktop/tx.mat')
```

and your example:

```
# note change of metric
mytx = ants.registration(fixed=fi, moving=mi, type_of_transform ="Affine" ,aff_metric="GC")
redTx = ants.read_transform( mytx['fwdtransforms'][0] )
ants.write_transform( redTx, mytx['fwdtransforms'][0]  )
```

the transform was already on disk.

**Comment by anorak94** [comment]
thanks a lot for your help. i used sitk and now im using ants ants is so much better
