### ISSUE TITLE
AntsPy visualizations function throws keyerror 

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#134]
Are the antspy visualizations functions working because when i do a ants.vol(np_3d_ants_image) i get a key error saying: KeyError: 'antsVol'. The ants.plot function seems to work fine

**Comment by stnava** [comment]
`antsVol` is probably not going to be included (officially) any time soon ... you can build `ANTsPy` yourself with VTK enabled and it will work but we can't add VTK at this time due to space constraints.  now that we have `pypi` support we may, in the future, build these in a separate package.
