### ISSUE TITLE
understanding the concatenate transform example

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTsPy#136]
The example notebook regarding concatenating transformations has the following code:

```
mytx = reg23[ 'invtransforms'] + reg12[ 'invtransforms']
```

This changes the direction of the transformations . So this new transformation can be used to resample image 1 to the space of image 3.

And the transformation is applied as:

```
mywarpedimage = ants.apply_transforms( fixed = img3, 
                                       moving = seg1['segmentation'] , 
                                       transformlist = mytx, 
                                       interpolator  = 'nearestNeighbor', 
                                       whichtoinvert = [True,False,True,False])
```
I do not understand why we are inverting the affine transformation matrices? Is now concatenating just the inverse transformations enough to just generate the transformation with image3 as the fixed image and image1 as the moving image? Why do we additionally need to invert the affine transformation matrices?

**Comment by stnava** [comment]
we use  conventions defined long ago by the ITK and ANTs development teams.   see https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

**Comment by dagap** [comment]
Thanks for such a quick reply. Thanks for clearing this up. I think it would be useful to have this link in the jupyter notebook.
