### ISSUE TITLE
Transformation order in ANTSpy

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTsPy#137]
This might be related to the issue I raised but I am still having issue getting my head around how the transformation concatenations and orderings are handled in ANTSpy.

So, if I perform a registration in ANTS (the usual SyN), I get the following list as my forward transformations an example:

```
'/tmp/tmpdddnbjk41Warp.nii.gz', '/tmp/tmpdddnbjk40GenericAffine.mat']
```
So the first entry is the non linear deformation field and the second one is the initial affine map.

Now, I can use apply_transforms to apply the map. However, what I know about `antsApplyTransform`, the transforms are applied in the order in which they are encountered on the command line and I think ANTSpy passes them on by simply going through the list.

My question is would this not result in the non linear warp being applied before the affine? 

Also, on a related note if I combone two transformation list as:

```
final = t1 + t2
```

and use this in `apply_transforms` would the resulting transformation be ```t2(t1(x))``` where x are the spatial coordinates i.e. t1 first and then t2?

**Comment by stnava** [comment]
yes on both accounts.  `ANTs` `ANTsR` and `ANTsPy` all use identical code and consequently the definitions of physical space, transformations, etc are also the same.

**Comment by dagap** [comment]
Thanks again for this incredible quick reply. So, for my first question how is applyTransform working then because it will apply the affine AFTER the non-linear warp? Usually the affine needs to be applied first. I was expecting the transform list to have the affine first and then the non-linear warp.

**Comment by stnava** [comment]
that is not how it works in ANTs.

**Comment by dagap** [comment]
hmmmmm.... could you point me to some documentation on this? Where exactly is my misunderstanding/mistake in this?

**Comment by stnava** [comment]
there will be discussions of this in various places here https://github.com/ANTsX/ANTs/wiki and in the papers https://github.com/ANTsX/ANTs/wiki as well as in `ants*pdf` documentation.

the core reasons are mathematical and practical :  

* mathematical: we use `Diff_0` which requires fixed boundary conditions.  as such, images are mapped to the fixed space by an affine transformation.  within the fixed domain, we compute the diffemorphism, member of `Diff_0`.     

* practical:  transformations are only dense under *pull back* not *push forward*

**Comment by stnava** [comment]
edited wrong link

**Comment by stnava** [comment]
edit: 3rd reason

**Comment by MaKh001** [comment]
I have a possible explanation, is it because the transition from a floating image to a fixed image is an advanced affine transformation and then a deformable transformation, so the transformation of a point from a fixed image to a floating image needs to be transformed first and then transformed Affine transformation, is this correct?
