### ISSUE TITLE
ANTSpy to SimpleITK image and back

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTsPy#139]
Is there a way to go back and forth between an ANTSpy image and a SimpleITK image? Currently, I am writing to file and then loading it from there but is there a conversion method for this or is it something simple to hack? I see there are similar methods for nibabel.

**Comment by stnava** [comment]
I am not aware of anyone trying this.  the underlying classes (itk image) are the same but the python wrapping is different.  you could write a function that uses both sitk => numpy and antspy => from numpy as a hack.   you'd just have to copy physical space parameters over appropriately.  if you write such a function, please contribute it back to antspy.    at least as a comment here so others might benefit.

**Comment by ntustison** [comment]
Not a solution but just an attempt to outline the quirks of a potential conversion.  Suppose I do the following:

```
>>> import SimpleITK as sitk
>>> import ants
>>> 
>>> array = np.zeros((3,4,5)) 
>>> ants_image = ants.from_numpy(array)
>>> ants_image
ANTsImage (RAI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (3, 4, 5)
	 Spacing    : (1.0, 1.0, 1.0)
	 Origin     : (0.0, 0.0, 0.0)
	 Direction  : [1. 0. 0. 0. 1. 0. 0. 0. 1.]
>>> sitk_image = sitk.GetImageFromArray(array)
>>> print(sitk_image)
Image (0x7f801720b340)
  RTTI typeinfo:   itk::Image<double, 3u>
  Reference Count: 1
  Modified Time: 1281
  Debug: Off
  Object Name: 
  Observers: 
    none
  Source: (none)
  Source output name: (none)
  Release Data: Off
  Data Released: False
  Global Release Data: Off
  PipelineMTime: 0
  UpdateMTime: 0
  RealTimeStamp: 0 seconds 
  LargestPossibleRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [5, 4, 3]
  BufferedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [5, 4, 3]
  RequestedRegion: 
    Dimension: 3
    Index: [0, 0, 0]
    Size: [5, 4, 3]
  Spacing: [1, 1, 1]
  Origin: [0, 0, 0]
  Direction: 
1 0 0
0 1 0
0 0 1

  IndexToPointMatrix: 
1 0 0
0 1 0
0 0 1

  PointToIndexMatrix: 
1 0 0
0 1 0
0 0 1

  Inverse Direction: 
1 0 0
0 1 0
0 0 1

  PixelContainer: 
    ImportImageContainer (0x7f80405f0db0)
      RTTI typeinfo:   itk::ImportImageContainer<unsigned long, double>
      Reference Count: 1
      Modified Time: 1282
      Debug: Off
      Object Name: 
      Observers: 
        none
      Pointer: 0x7f80165fead0
      Container manages memory: true
      Size: 60
      Capacity: 60
>>> ants.image_write(ants_image, "ants_image.nii.gz")
>>> writer = sitk.ImageFileWriter()
>>> writer.SetFileName("sitk_image.nii.gz")
>>> writer.Execute(sitk_image)
```

Looking at both images, SNAP will load them differently but say they're both RAI orientation.  Notice that the x, y, z dimensions are (3, 4, 5) in the ants_image but (5, 4, 3) in the sitk_image.

<img width="1966" alt="Screen Shot 2020-05-13 at 2 48 18 PM" src="https://user-images.githubusercontent.com/324811/81869390-d26fe380-9528-11ea-893c-7cba4e95ddf7.png">

**Comment by stnava** [comment]
Seems stale / dead end.

**Comment by emergencyd** [comment]
you can use ants.from_numpy(), just set corresponding direction, spacing, etc

**Comment by VincentMorard** [comment]
Hi, here is the python for the conversion
```
def ants_2_itk(image):
    imageITK = sitk.GetImageFromArray(image.numpy().T)
    imageITK.SetOrigin(image.origin)
    imageITK.SetSpacing(image.spacing)
    imageITK.SetDirection(image.direction.reshape(9))
    return imageITK

def itk_2_ants(image):
    image_ants = ants.from_numpy(sitk.GetArrayFromImage(image).T, 
                                 origin=image.GetOrigin(), 
                                 spacing=image.GetSpacing(), 
                                 direction=np.array(image.GetDirection()).reshape(3, 3))
    return image_ants
```

**Comment by Momentum-TN** [comment]
> Hi, here is the python for the conversion
> 
> ```
> def ants_2_itk(image):
>     imageITK = sitk.GetImageFromArray(image.numpy().T)
>     imageITK.SetOrigin(image.origin)
>     imageITK.SetSpacing(image.spacing)
>     imageITK.SetDirection(image.direction.reshape(9))
>     return imageITK
> 
> def itk_2_ants(image):
>     image_ants = ants.from_numpy(sitk.GetArrayFromImage(image).T, 
>                                  origin=image.GetOrigin(), 
>                                  spacing=image.GetSpacing(), 
>                                  direction=np.array(image.GetDirection()).reshape(3, 3))
>     return image_ants
> ```

@VincentMorard Thank you for sharing this snippet. 
I would like to know why you transposed the array in both functions

**Comment by reox** [comment]
stumbled across this, because I needed it as well for some prototyping. I think it would be nice to have these functions inside ANTs as well - guess they can be very useful when working with SimpleITK code.

@Momentum-TN 
>  I would like to know why you transposed the array in both functions

The reason is that an image with voxel sizes (x, y, z) is accessible in ITK as (x, y, z) but when using `sitk.GetArrayFromImage` you end up with an ndarray of shape (z, y, x). However, ANTs is using a numpy array of (x, y, z) instead.
Thus, you need to transpose.

**Comment by reox** [comment]
Thanks! These are very useful!
