### ISSUE TITLE
Error 'No such file or directory: '/home/ytsyganova/.antspy/''

### ISSUE THREAD

**Issue by LarisaKozhekina** [ANTsX/ANTsPy#140]
**Describe the bug**
Don't work function  ants.get_ants_data('mni')

**To Reproduce**
1. pip3 install antspyx
2. import ants
3. ants.get_ants_data('mni')
4. I got this error:
![4](https://user-images.githubusercontent.com/16781515/78276411-ade11e80-751b-11ea-9577-a6196924cbbf.PNG)

**Desktop:**
 - OS:  Ubuntu 16.04.3 LTS (GNU/Linux 4.15.0-88-generic x86_64)
- numpy 1.18.2
 - scipy 1.1.0
 - scikit-learn 0.21.3

**Comment by stnava** [comment]
thanks- that's *probably* a real bug related to the pip wheels vs source install.   I am not sure how to resolve that .... will have to look into it and handle in future releases.

in the mean time, you can make such a directory yourself.

the data is here:  https://github.com/ANTsX/ANTsPy/tree/master/data

**Comment by LarisaKozhekina** [comment]
> thanks- that's _probably_ a real bug related to the pip wheels vs source install. I am not sure how to resolve that .... will have to look into it and handle in future releases.
> 
> in the mean time, you can make such a directory yourself.
> 
> the data is here: https://github.com/ANTsX/ANTsPy/tree/master/data

Thank you!

**Comment by rueberger** [comment]
I believe this is easily resolved. See linked PR.
