### ISSUE TITLE
parts to whole registration

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#142]
is it possible to register a fluoroscent dapi stained 2d image of the cerebellum to a whole slice of a 2d reference atlas using antspy. i tried to do it by cropping off the cerebellum from the nissl stained reference atlas and then registering the dapi stained 2d image to only the reference cerebellum sections but it doesnt work very well. i think that because the field of view and intensities are so different it completely throws off the algorithm, is it possible to use some kind of intensity normalization in ants or landmark based registration to do this task. 

 i also tried manually cropping off the picture and then doing histogram matching and then registering the images i find a transform between the two and the transformed images matches the nissl stained image in terms of the boundaries etc but the mutual information metric is not the highest for the corresponding slice from the reference atlas but is maximum for some other slice which is obviously not the correct match for the moving image

**Comment by anorak94** [comment]
![0](https://user-images.githubusercontent.com/45297533/78509115-fdc61c80-778b-11ea-8501-0b223ef70d88.png)
![17](https://user-images.githubusercontent.com/45297533/78509121-0880b180-778c-11ea-844d-eb9cf44afa41.png)

these are the two registrations i tried to do and the registration score is not proportional to the appropriateness of the matching slice

**Comment by stnava** [comment]
can you make a clearer example with better explanation of the images?  the above example is not clear.  you might also attach the real data so that someone else could try it.

**Comment by anorak94** [comment]
![dapi (2)](https://user-images.githubusercontent.com/45297533/78511048-eaba4900-7799-11ea-8026-a898cd1ac88b.png)

this is the reference image i have and i would like to align it to a reference atlas. the image is taken from the cerebellum of a mouse brain

**Comment by anorak94** [comment]
Is this much information alright i cant post the  allen reference  atlas dataset its too big

**Comment by stnava** [comment]
its not at all clear by what you mean by "image 1" and "image 2" --- these are not the names you used.  you also didnt provide any code to help us understand what you've done already.  

lastly, all metrics are *minimized*

**Comment by anorak94** [comment]
https://drive.google.com/open?id=1gE1oV0TZyLL5KM9B6vsbm89votfwOuwm 

this is the link to the notebook containing the data and the code i have so far
 
just a stupid doubt . mutual information measures how well we can explain one data with the help of the other shouldnt it be maximized to ensure that the images are matched one image explains the other well if the score is higher

It measures how much knowing one of these variables reduces uncertainty about the other.
Moreover, mutual information is nonnegative (wikipedia)
unless of course we minimize negative of mattes 

"image1" and "image2" are the two green images which i put up at the very beginning

**Comment by stnava** [comment]
1.  all ants and itk metrics are set to be better under **minimization** 

2.  remove the "metric = GC" call 

```
    tx   = ants.registration(fixed=imft, moving=immt, type_of_transform = 'SyN' )
```

3. mask out the junk from your images ( below mostly works but no promises )

```
    imft_mask = ants.get_mask( imft )
    immt_mask = ants.get_mask( immt )
    imft = imft * imft_mask
    immt = immt * immt_mask
```

4.  use the metrics `sc = ants.image_similarity(imft,tx["warpedmovout"],metric_type='Correlation')` for more granular control `create_ants_metric`

**Comment by anorak94** [comment]
hey thanks it looks much better than my approach. i was skeptical of using the get_mask function it doesnt always work very well i guess the logic of using correlation is that we sample all pixels for computing the loss function am i right but thanks a lot i love using antspy

**Comment by stnava** [comment]
ok. the rest is in your hands.

1. optimize the registration , trying different metrics etc

2. improve the mask - `get_mask` has parameters that you might optimize over or use ants.atropos perhaps combined with `label_clusters` or other statistics
