### ISSUE TITLE
registration of time series in ANTSpy

### ISSUE THREAD

**Issue by pamparana34** [ANTsX/ANTsPy#143]
I have a question regarding using ANTSpy for 2D time series registration. So what I have is a very large 2D sequence (~500 images) and I am trying to register everything to the middle time point in the 2D sequence.

I tried to use something like the multistage ANTS registration example (https://github.com/ANTsX/ANTsPy/blob/master/tutorials/concatenateRegistrations.ipynb) as I though propagating the registration through each successive time point might be an "easier" registration problem. So, I formulated it as in the example where the difference is that instead of 3 images, I have many 100s.

What I noticed is that each neighbourhood registration results look really good but when I concatenate the registrations as described in that example, after 20 or so time points, the images start to look very warped and not really plausible (although every pairwise sequential image registration looks quite good).

I was wondering if there is some advise regarding registration of such time series. I am using default SyN registration for the moment.

**Comment by stnava** [comment]
that's  an interesting question.  

the problem you mention is a real limitation that can be overcome with a variety of strategies.  not exactly what you want but  we've done things like this:

https://link.springer.com/chapter/10.1007/11784012_28

which is related to template building and may help alleviate the problem you mentioned.

it would need some tweaks for your case.

another related application / solution https://www.ncbi.nlm.nih.gov/pubmed/26950745

which is a variation on template building ( I believe this is called `build_template` in ANTsPy ).

I would suggest building a template and then doing concatenation from the resulting transforms to your target slice.  you can initialize the template with the target slice.

**Comment by pamparana34** [comment]
Thank you for this recommendation.

Just to confirm -> I will create this template image and then register all the images to this template image and then basically take the path to my image of interest through  this template image.

You mentioned I might  need some tweaks. Can you elaborate on what  things you  were thinking of?

**Comment by stnava** [comment]
yes - that is a straightforward approach 

there are many tweaks you might use after that but you'd have to look at your results first to help define the next steps

**Comment by pamparana34** [comment]
This was very helpful. Thank you!
