### ISSUE TITLE
Creating a 2D slice from a 4D ants image

### ISSUE THREAD

**Issue by pamparana34** [ANTsX/ANTsPy#144]
I am loading a nifti image into antspy with the usual `image_read` function and the image has the following meta information:

```
ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (400, 400, 1, 33)
	 Spacing    : (1.0, 1.0, 10.0, 0.003)
	 Origin     : (-158.6705, -63.4228, -296.4373, 0.0)
	 Direction  : [ 1.  0.  0.  0.  0. -0.  1.  0.  0.  1. -0.  0.  0.  0.  0.  1.]
```

Now what I want to do is extract a 2D slice at a given time from it as an ants image. So I want to retain the image orientation and direction properties. So I tried the following:

```
x = ants.image_read('image_4D.nii')
data = np.squeeze(image.numpy())
sl = data[..., 0]

im = ants.from_numpy(sl, origin=x.origin[:2], direction=x.direction[:2], spacing=x.spacing[:2])  
```
However, this returns:
```
itk::ERROR: Image(0x56117bebe450): Bad direction, determinant is 0. Direction is 1 0
0 0
```
I tried something like:
```
im = ants.from_numpy(sl, origin=x.origin[:2], direction=x.direction[:2, :2], spacing=x.spacing[:2])  
```

but this seg faults and I am guessing at this point anyway.

Is it possible with antspy to extract this 2D slice from this 4D embedding while retaining the relevant geometric information?

**Comment by stnava** [comment]
help( ants.slice_image )


brian
