### ISSUE TITLE
How to write .mat after AffineFast registration?

### ISSUE THREAD

**Issue by srbnghosh99** [ANTsX/ANTsPy#145]
Hi,

After applying AffineFast I have got the  'fwdtransforms': ['/tmp/tmpejjqnake0GenericAffine.mat'], 'invtransforms': ['/tmp/tmpejjqnake0GenericAffine.mat']}
How can write image from .mat file.
I am trying to use ants.images_from_matrix(data_matrix, mask)
In that case, how should be the mask value?

Thanks in advance.

Regards
Shrabani Ghosh

**Comment by stnava** [comment]
the mat file does not need to be written.  it is already on disk.  

```
/tmp/tmpejjqnake0GenericAffine.mat
```
is the filename.

it's an ITK transformation matrix.

if you want the transformed image, see `help( ants.registration)` which shows:

```
    Returns
    -------
    dict containing follow key/value pairs:
        `warpedmovout`: Moving image warped to space of fixed image.
        `warpedfixout`: Fixed image warped to space of moving image.
        `fwdtransforms`: Transforms to move from moving to fixed image.
        `invtransforms`: Transforms to move from fixed to moving image.
```

meaning you can do:

```
import ants
fi = ants.image_read(ants.get_ants_data('r16'))
mi = ants.image_read(ants.get_ants_data('r64'))
fi = ants.resample_image(fi, (60,60), 1, 0)
mi = ants.resample_image(mi, (60,60), 1, 0)
mytx = ants.registration(fixed=fi, moving=mi, type_of_transform = 'SyN' )
ants.plot( mytx['warpedmovout'])
```

**Comment by srbnghosh99** [comment]
Thank You. I understood that it is in the dict. But I searched it in the disk, it's not saved.  Even if it is in mat format, can't I save it in mha or nii so that I can visualize it?

Thank you so much for your quick response.

**Comment by stnava** [comment]
please read and/or search the documentation before posting issues.
https://antspyx.readthedocs.io/en/latest/search.html?q=write

**Comment by srbnghosh99** [comment]
Hi,

Thank You.  After registration, I can see the top(screenshot attached) or
bottom parts are getting blank because of translation I guess. How can I
resolve that issue?

Regards
Shrabani Ghosh
