### ISSUE TITLE
Gaussian Regularization in SyN in antspy

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#147]
I am trying to reproduce the results in this paper which uses ANTs.
"Histology-derived volumetric annotation of the human hippocampal subfields in postmortem MRI"

In the deformable registration part the authors write that it was done using the following settings 

Symmetric Normalization (SyN) transformation model in the ANTs package (Avants et al., 2008) using the following settings: three multi-resolution levels with a maximum of 1000 iterations per level, 0.25 gradient step size, and Gaussian regularization with 3.0 pixel standard deviation.

My doubt is how do you do the gaussian regularization in ANTsPy with the 3.0 pixel standard deviation

**Comment by stnava** [comment]
```
flow_sigma=3, total_sigma=0
```
