### ISSUE TITLE
Linear Combinations of custom ants metric 

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#148]
I understand that ants has an option to create combinations of metrics using 

 metric1 = ants.create_ants_metric(fixed, moving, "MattesMutualInformation")
 metric2 = ants.create_ants_metric(fixed, moving, "Correlation")

how can i do a linear combinations of these metrics like 
metric 3 = 0.3metric1 + 0.24metric2

**Comment by anorak94** [comment]
https://github.com/ANTsX/ANTsPy/wiki/Multi-metric-registration i have this but it doesnt tell how to do linear combinations of the two metrics

**Comment by stnava** [comment]
just follow the help twice then add up values:

```
import ants
fixed = ants.image_read(ants.get_ants_data('r16'))
moving = ants.image_read(ants.get_ants_data('r64'))
metric_type = 'Correlation'
metric = ants.create_ants_metric(fixed, moving, metric_type)
metric2 = ants.create_ants_metric(fixed, moving, metric_type)
metric.get_value() + metric2.get_value()*5
```

**Comment by anorak94** [comment]
nice i was missing the addition part with get_value()
just adding two metric doesnt do it when i do metric3 = metric.get_value() + metric2.get_value()*.5
and pass this to the registration call it works 

thanks

**Comment by anorak94** [comment]
on a related note is it possible to align one fixed image to three moving images simultaneously. i can create 3 different metrics each with the corresponding moving image and metric and make a combined metric out of it but when i do the registration call which moving image should i choose

**Comment by stnava** [comment]
these are only metrics - they do not do or impact registration.

see `ants.build_template`

**Comment by anorak94** [comment]
`wt = 1.0 / len( image_list )
    if initial_template is None:
        initial_template = image_list[ 0 ] * 0
        for i in range( len( image_list ) ):
            initial_template = initial_template + image_list[ i ] * wt

    xavg = initial_template.clone()
    for i in range( iterations ):
        for k in range( len( image_list ) ):
            w1 = registration( xavg, image_list[k],
              type_of_transform=type_of_transform, **kwargs )
            if k == 0:
              wavg = iio.image_read( w1['fwdtransforms'][0] ) * wt
              xavgNew = w1['warpedmovout'] * wt
            else:
              wavg = wavg + iio.image_read( w1['fwdtransforms'][0] ) * wt
              xavgNew = xavgNew + w1['warpedmovout'] * wt
        print( wavg.abs().mean() )
        wscl = (-1.0) * gradient_step
        wavg = wavg * wscl
        wavgfn = mktemp(suffix='.nii.gz')
        iio.image_write(wavg, wavgfn)
        xavg = apply_transforms( xavgNew, xavgNew, wavgfn )

    return xavg
`

**Comment by stnava** [comment]
see `help( ants.build_template) ` for how to use this code.

**Comment by anorak94** [comment]
yeah i did but it just says this 

```
Help on function build_template in module ants.registration.build_template:

build_template(initial_template=None, image_list=None, iterations=3, gradient_step=0.2, **kwargs)
    Estimate an optimal template from an input image_list
    
    ANTsR function: N/A
    
    Arguments
    ---------
    initial_template : ANTsImage
        initialization for the template building
    
    image_list : ANTsImages
        images from which to estimate template
    
    iterations : integer
        number of template building iterations
    
    gradient_step : scalar
        for shape update gradient
    
    kwargs : keyword args
        extra arguments passed to ants registration
    
    Returns
    -------
    ANTsImage
    
    Example
    -------
    >>> import ants
    >>> image = ants.image_read( ants.get_ants_data('r16') , 'float')
    >>> image2 = ants.image_read( ants.get_ants_data('r27') , 'float')
    >>> image3 = ants.image_read( ants.get_ants_data('r85') , 'float')
    >>> timage = ants.build_template( image_list = ( image, image2, image3 ) )

```

there is nothing about how to do a weighted combination which is what im after

**Comment by stnava** [comment]
so you want to control how each image is weighted yourself;  in that case, we would appreciate if you made a pull request to allow user-defined weights

**Comment by anorak94** [comment]
yes that is what i want to do but you do something similar in this paper 

Histology-derived volumetric annotation of the human hippocampal subfields in postmortem MRI

where in the deformable registration step each image is registered to a weighted combination of the image before, image after and the corresponding mri slice according to some given weights so i thought this option was available in ANTs

**Comment by stnava** [comment]
you can ask that question here:  https://github.com/ANTsX/ANTs/issues
