### ISSUE TITLE
iMath_grad crashing

### ISSUE THREAD

**Issue by pamparana34** [ANTsX/ANTsPy#149]
I am using antsy version `0.2.2`

I am trying the multi metric image registration example in the example scripts and the line:

```
g1 = ants.iMath_grad(image)
```

is crashing with the error

```
ValueError: stoi
```

I am guessing it has something to do with the parsing of the parameters on the C++ side. Setting sigma to  some other value like 1 did not make any difference.

**Comment by stnava** [comment]
try a newer release.
