### ISSUE TITLE
n4_bias_field_correction crashing

### ISSUE THREAD

**Issue by vnckppl** [ANTsX/ANTsPy#150]
**Issue**
When I run n4_bias_field_correction, it crashes with Segmentation fault: 11.

**To Reproduce**
For this example, I use an FSL standard image as the input image (${FSLDIR}/data/standard/MNI152_T1_1mm.nii.gz)

```
import ants

image = '/Applications/fsl/fsl_6.0.1/data/standard/MNI152_T1_1mm.nii.gz'

img_in = ants.image_read(image)

myObject = ants.n4_bias_field_correction(img_in, convergence={'iters': [5], 'tol': 1e-07}, shrink_factor=2, verbose=True)
```

This results in the terminal output:

> Running N4 for 3-dimensional images.
> 
> Original intensity range:  [850, 9999]
> Specified spline distance: 200mm
>   original image size:  [182, 218, 182]
>   padded image size:  [201, 401, 201]
>   number of control points:  [4, 5, 4]
> 
> Current level = 1
>   Iteration 1 (of 5).   Current convergence value = 0.000130458 (threshold = 0)
>   Iteration 2 (of 5).   Current convergence value = 0.000129667 (threshold = 0)
>   Iteration 3 (of 5).   Current convergence value = 0.000128859 (threshold = 0)
>   Iteration 4 (of 5).   Current convergence value = 0.000128014 (threshold = 0)
>   Iteration 5 (of 5).   Current convergence value = 0.000127142 (threshold = 0)
>    N4BiasFieldCorrectionImageFilter (0x7fb3acb49360)
>      RTTI typeinfo:   itk::N4BiasFieldCorrectionImageFilter<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u> >
>      Reference Count: 1
>      Modified Time: 397
>      Debug: Off
>      Object Name:
>      Observers:
>        IterationEvent(Command)
>      Inputs:
>        ConfidenceImage: (0x0)
>        MaskImage: (0x7fb3acb4a570)
>        Primary: (0x7fb3acb49eb0) *
>      Indexed Inputs:
>        0: Primary (0x7fb3acb49eb0)
>        1: MaskImage (0x7fb3acb4a570)
>        2: ConfidenceImage (0x0)
>      Required Input Names: Primary
>      NumberOfRequiredInputs: 1
>      Outputs:
>        Primary: (0x7fb3acb49700)
>      Indexed Outputs:
>        0: Primary (0x7fb3acb49700)
>      NumberOfRequiredOutputs: 1
>      Number Of Work Units: 8
>      ReleaseDataFlag: Off
>      ReleaseDataBeforeUpdateFlag: Off
>      AbortGenerateData: Off
>      Progress: 0
>      Multithreader:
>        RTTI typeinfo:   itk::PoolMultiThreader
>        Reference Count: 1
>        Modified Time: 144
>        Debug: Off
>        Object Name:
>        Observers:
>          none
>        Number of Work Units: 8
>        Number of Threads: 2
>        Global Maximum Number Of Threads: 128
>        Global Default Number Of Threads: 2
>        Global Default Threader Type: PoolMultiThreader
>        SingleMethod: 0
>        SingleData: 0x0
>      DynamicMultiThreading: On
>      CoordinateTolerance: 1e-06
>      DirectionTolerance: 1e-06
>      Use Mask Label: 0
>      Mask label: 1
>      Number of histogram bins: 200
>      Wiener filter noise: 0.01
>      Bias field FWHM: 0.15
>      Maximum number of iterations: [5]
>      Convergence threshold: 0
>      Spline order: 3
>      Number of fitting levels: [1, 1, 1]
>      Number of control points: [4, 5, 4]
>      CurrentConvergenceMeasurement: 0.000127142
>      CurrentLevel: 1
>      ElapsedIterations: 6
>      LogBiasFieldControlPointLattice:
>        Image (0x7fb3acdf1010)
>          RTTI typeinfo:   itk::Image<itk::Vector<float, 1u>, 3u>
>          Reference Count: 1
>          Modified Time: 4648
>          Debug: Off
>          Object Name:
>          Observers:
>            none
>          Source: (none)
>          Source output name: (none)
>          Release Data: Off
>          Data Released: False
>          Global Release Data: Off
>          PipelineMTime: 0
>          UpdateMTime: 0
>          RealTimeStamp: 0 seconds
>          LargestPossibleRegion:
>            Dimension: 3
>            Index: [0, 0, 0]
>            Size: [4, 5, 4]
>          BufferedRegion:
>            Dimension: 3
>            Index: [0, 0, 0]
>            Size: [4, 5, 4]
>          RequestedRegion:
>            Dimension: 3
>            Index: [0, 0, 0]
>            Size: [4, 5, 4]
>          Spacing: [198, 199, 198]
>          Origin: [-198, 199, -198]
>          Direction:
> 1 0 0
> 0 -1 0
> 0 0 1
> 
>          IndexToPointMatrix:
> 198 0 0
> 0 -199 0
> 0 0 198
> 
>          PointToIndexMatrix:
> 0.00505051 0 0
> 0 -0.00502513 0
> 0 0 0.00505051
> 
>          Inverse Direction:
> 1 0 0
> 0 -1 0
> 0 0 1
> 
>          PixelContainer:
>            ImportImageContainer (0x7fb3acde8380)
>              RTTI typeinfo:   itk::ImportImageContainer<unsigned long, itk::Vector<float, 1u> >
>              Reference Count: 1
>              Modified Time: 4645
>              Debug: Off
>              Object Name:
>              Observers:
>                none
>              Pointer: 0x7fb3acdec400
>              Container manages memory: true
>              Size: 80
>              Capacity: 80
> Elapsed time: 8.77449
> Segmentation fault: 11

**Desktop**
 - OS: Mac OSX 10.14.6 (Mojave)
 - Python: 3.7.7
 - ANTsPy: antspyx==0.2.4 (Built with pip on April 7, 2020)

**Additional context**
Running N4 in a shell:
```N4BiasFieldCorrection -i ${FSLDIR}/data/standard/MNI152_T1_1mm.nii.gz -o ~/Desktop/myTest.nii.gz -c [5, 1e-07] -s 2 -v```
runs fine.

**Comment by stnava** [comment]
the closest thing we can do to look at this is run something that is reproducible:

```
img_in = ants.image_read(  ants.get_data( "ch2" )  )
myObject = ants.n4_bias_field_correction(img_in, convergence={'iters': [5], 'tol': 1e-07}, shrink_factor=2, verbose=True)
```

which runs fine.  

anyway, this may get fixed "naturally" when we update ITK and ANTs tags.   Currently, no timetable for that.    

alternatively, try writing the image with `ants.image_write` then re-reading it to see if that has any impact.

**Comment by vnckppl** [comment]
Thank you for your reply.

I tried reading the image in, writing it out with ants.image_write and using the output file as input. That gave me the same error.

I also upgraded my Python version to 3.8.2 and set up a fresh virtual environment with nothing but ipython and ants installed. I then ran the code you provided, but I still receive the same error:

```Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ants
>>> img_in = ants.image_read(  ants.get_data( "ch2" )  )
>>> myObject = ants.n4_bias_field_correction(img_in, convergence={'iters': [5], 'tol': 1e-07}, shrink_factor=2, verbose=True)

Running N4 for 3-dimensional images.

Original intensity range:  [20, 133]
Specified spline distance: 200mm
  original image size:  [181, 217, 181]
  padded image size:  [201, 401, 201]
  number of control points:  [4, 5, 4]

Current level = 1
  Iteration 1 (of 5).   Current convergence value = 0.000484283 (threshold = 1e-07)
  Iteration 2 (of 5).   Current convergence value = 0.00047417 (threshold = 1e-07)
  Iteration 3 (of 5).   Current convergence value = 0.000463484 (threshold = 1e-07)
  Iteration 4 (of 5).   Current convergence value = 0.00045349 (threshold = 1e-07)
  Iteration 5 (of 5).   Current convergence value = 0.000443552 (threshold = 1e-07)
   N4BiasFieldCorrectionImageFilter (0x7fe64003c850)
     RTTI typeinfo:   itk::N4BiasFieldCorrectionImageFilter<itk::Image<float, 3u>, itk::Image<float, 3u>, itk::Image<float, 3u> >
     Reference Count: 1
     Modified Time: 400
     Debug: Off
     Object Name:
     Observers:
       IterationEvent(Command)
     Inputs:
       ConfidenceImage: (0x0)
       MaskImage: (0x7fe6403d2210)
       Primary: (0x7fe6403d1cb0) *
     Indexed Inputs:
       0: Primary (0x7fe6403d1cb0)
       1: MaskImage (0x7fe6403d2210)
       2: ConfidenceImage (0x0)
     Required Input Names: Primary
     NumberOfRequiredInputs: 1
     Outputs:
       Primary: (0x7fe6400e3e00)
     Indexed Outputs:
       0: Primary (0x7fe6400e3e00)
     NumberOfRequiredOutputs: 1
     Number Of Work Units: 8
     ReleaseDataFlag: Off
     ReleaseDataBeforeUpdateFlag: Off
     AbortGenerateData: Off
     Progress: 0
     Multithreader:
       RTTI typeinfo:   itk::PoolMultiThreader
       Reference Count: 1
       Modified Time: 144
       Debug: Off
       Object Name:
       Observers:
         none
       Number of Work Units: 8
       Number of Threads: 2
       Global Maximum Number Of Threads: 128
       Global Default Number Of Threads: 2
       Global Default Threader Type: PoolMultiThreader
       SingleMethod: 0
       SingleData: 0x0
     DynamicMultiThreading: On
     CoordinateTolerance: 1e-06
     DirectionTolerance: 1e-06
     Use Mask Label: 0
     Mask label: 1
     Number of histogram bins: 200
     Wiener filter noise: 0.01
     Bias field FWHM: 0.15
     Maximum number of iterations: [5]
     Convergence threshold: 1e-07
     Spline order: 3
     Number of fitting levels: [1, 1, 1]
     Number of control points: [4, 5, 4]
     CurrentConvergenceMeasurement: 0.000443552
     CurrentLevel: 1
     ElapsedIterations: 6
     LogBiasFieldControlPointLattice:
       Image (0x7fe6400e58e0)
         RTTI typeinfo:   itk::Image<itk::Vector<float, 1u>, 3u>
         Reference Count: 1
         Modified Time: 4651
         Debug: Off
         Object Name:
         Observers:
           none
         Source: (none)
         Source output name: (none)
         Release Data: Off
         Data Released: False
         Global Release Data: Off
         PipelineMTime: 0
         UpdateMTime: 0
         RealTimeStamp: 0 seconds
         LargestPossibleRegion:
           Dimension: 3
           Index: [0, 0, 0]
           Size: [4, 5, 4]
         BufferedRegion:
           Dimension: 3
           Index: [0, 0, 0]
           Size: [4, 5, 4]
         RequestedRegion:
           Dimension: 3
           Index: [0, 0, 0]
           Size: [4, 5, 4]
         Spacing: [198, 199, 198]
         Origin: [198, 199, -198]
         Direction:
-1 0 0
0 -1 0
0 0 1

         IndexToPointMatrix:
-198 0 0
0 -199 0
0 0 198

         PointToIndexMatrix:
-0.00505051 0 0
0 -0.00502513 0
0 0 0.00505051

         Inverse Direction:
-1 0 0
0 -1 0
0 0 1

         PixelContainer:
           ImportImageContainer (0x7fe63e0aa650)
             RTTI typeinfo:   itk::ImportImageContainer<unsigned long, itk::Vector<float, 1u> >
             Reference Count: 1
             Modified Time: 4648
             Debug: Off
             Object Name:
             Observers:
               none
             Pointer: 0x7fe6400ccf90
             Container manages memory: true
             Size: 80
             Capacity: 80
Elapsed time: 1.93107
Segmentation fault: 11```

Do you have any other suggestions?

**Comment by ntustison** [comment]
There have been a number of updates since the releases and there were some relatively recent fixes to N4.  Try installing directly from the repo:

```
git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install
```

**Comment by stnava** [comment]
I updated ANTs and ITK tags this morning which may help if you do a source build.    worked for me on osx Catalina  and in circle ci builds / tests  and travis builds / tests

**Comment by vnckppl** [comment]
Hi Nick,

Even this did not solve my issue. It must be some system setting perhaps. I have now built a Docker image based on ubuntu with python3.6.2 and antspyx and that seems to work.
