### ISSUE TITLE
explanation of variables in multimetric registration in antspy

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#151]
in antspy i do
`ccMetric1 = ['MattesMutualInformation', fx_wm, mv_wm, 2, 1 ] 
`what are 2 and 1 in this list 
```
metrics = list() 
metrics.append(ccMetric1)
reg=ants.registration(fx_wm,mv_wm,'SyNOnly', syn_metric='mattes', reg_iterations=( 300,150, 50, 20 ), syn_sampling=2, verbose=1, total_sigma=0.0, multivariate_extras=metrics )
```

**Comment by stnava** [comment]
see the metric discussion here https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call

basically, these depend on which metric you use ... the raw ants help will help explain as well.

**TODO**: probably should document in antsr and antspy registration help, following the antsRegistration C++ command line.

**Comment by anorak94** [comment]
```
--metric CC[$t1brain,$template,1,4] \
--metric MI[$t1brain,$template,1,32,Regular,0.25] \
```

i did and these are the two i found i want to do something like
`--metric MI[$t1brain,$template,1,32,Regular,0.25] \
`
but im not sure how to do this in antspy for my use case id like to have multiple lines of the above command maybe i can do it in this 
```
metrics = list() 
metrics.append(ccMetric1)
reg=ants.registration(fx_wm,mv_wm,'SyNOnly', syn_metric='mattes', reg_iterations=( 300,150, 50, 20 ), syn_sampling=2, verbose=1, total_sigma=0.0, multivariate_extras=metrics )
```
but im not sure how to go about writing this in antspy

**Comment by matham** [comment]
You can do something like `metric=['mattes, img1, img2, 1, "1,Regular,32,whatever"] ` and it seemingly gets passed on to the command line.
