### ISSUE TITLE
ants.build_template: images do not occupy same physical space

### ISSUE THREAD

**Issue by vnckppl** [ANTsX/ANTsPy#152]
**Describe the bug**
When I run ants.build_template with two T1 images as input, I receive the error `ValueError: images do not occupy same physical space`.

**To Reproduce**
```
import ants
image1=ants.image_read('/Users/vincent/Data/tmp/sub-A_ses-01_T1w.nii.gz')
image2=ants.image_read('/Users/vincent/Data/tmp/sub-A_ses-02_T1w.nii.gz')
timage = ants.build_template(image_list = (image1, image2))
```

Running this batch with ANTs' example data ('r16' and 'r27') works. And there are no issues when I run the batch with the same image as input twice. Furthermore, if I provide an an initial template (initial_template), this problem does not occur, suggesting that the issue is with calculating the initial template. 

**Expected behavior**
I was expecting that ants.build_template would be the Python equivalent of antsMultivariateTemplateConstruction.sh (which has no issues with creating an unbiased template from the above referenced input files). 

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.14.6 (Mojave)
 - Python 3.8.2
 - ANTs Version 0.2.5

**Comment by stnava** [comment]
ok - should be fixed now.  thanks for the catch.

we still recommend the bash script for larger studies because it includes parallelization which is not as yet added to antspy.

**Comment by vnckppl** [comment]
Thanks, I can confirm this is working now with my data.
