### ISSUE TITLE
ANTsPy equivalent of antsBrainExtraction.sh or abpBrainExtraction?

### ISSUE THREAD

**Issue by vnckppl** [ANTsX/ANTsPy#155]
I would like to use ANTsPy to create a brain mask. I was wondering if there is an ANTsPy equivalent of antsBrainExtraction.sh or abpBrainExtraction?

**Comment by stnava** [comment]
@ntustison can you share the location of the py bxt tool?

**Comment by stnava** [comment]
I mean the unet

**Comment by ntustison** [comment]
Sure.  See below.  Note that you need to install ANTsPyNet but you don’t need special hardware.  https://github.com/ANTsXNet/BrainExtraction/blob/master/README.md

**Comment by vnckppl** [comment]
Thanks!
