### ISSUE TITLE
'fwdtransforms' to The pose 4x4 matrix

### ISSUE THREAD

**Issue by wangyibin0011** [ANTsX/ANTsPy#158]
Thank you for your outstanding work。And I have a question for you，How can the process of move2fix be designed as a 4x4 matrix using mat files in 'fwdtransforms'？So that I can multiply a voxel file by this matrix in VTK or ITK and get the same effect as the Ants registration, which I think is worth exploring.May I ask how the current mat file describes the registration process? If possible, I want to make clear the matrix form of the three registration methods of Rigid, Similarity and affine. thank you

**Comment by wangyibin0011** [comment]
I saw related introduction at https://github.com/ANTsX/ANTsPy/issues/71, but I still confused this part to compare. After I used ants_to_human in this problem, the result seems to be unable to realize my expectation. Do you have any solution to this problem? Any boot is very useful

**Comment by stnava** [comment]
`ants.apply_transforms` is the way to do this.   `sitk` should be able to read the `.mat` files that we produce.  I do not encourage you to try to reimplement physical space transformations that are done in `itk` style as there is much to it and the tools already exist here and in simple itk.
