### ISSUE TITLE
Getting coordinates of images after resampling operations 

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#159]
If i have a large image and i resample it to a smaller size. How can i apply the same transformation to the coordinates in the larger image. Specifically, if I resample an image to a smaller size, what are the new coordinates of the points in the larger image and how can i get them in the new coordinate system. It seems that multiple coordinates in the larger image should get mapped to the same coordinates in the smaller image. But i have no idea how to go about getting the transformed coordinates

**Comment by stnava** [comment]
is this an ANTsPy question?  just seems like a generic question.    in `ANTsPy` we have `ants.apply_transforms` and `ants.resample_image*`.

**Comment by anorak94** [comment]
i use ants resample image to resample my image can i get coordinates after this resampling operation

**Comment by stnava** [comment]
see `ants.transform_index_to_physical_point` and `ants.transform_physical_point_to_index`

that's how you map from pixel/voxel to physical space.  all ants and itk images have the coordinates stored internally through the header.

**Comment by anorak94** [comment]
`ncb_phy_pts = ants.transform_index_to_physical_point(moving,clist[0])
`the output is (9308, 3621)

when i try to do the reverse using 
`pt = ants.transform_physical_point_to_index(movout, (9308., 3621.))
`the output is again (9308, 3621) shouldnt it be the array indices of the movout image

**Comment by stnava** [comment]
please invest the time to learn about the difference between physical space and index space.  we don't have time to answer questions that are covered in a very clear manner elsewhere.  there is no bug in this code - the bug is in your understanding of how to use it.

**Comment by anorak94** [comment]
moving_res = ants.resample_image(moving, (403, 724),True,0)
```
ncb_phy_pts = ants.transform_index_to_physical_point(moving,(9308, 3621))
ncb_phy_pts = array([9308., 3621.])

pt = ants.transform_physical_point_to_index(moving_res, (9308., 3621.))
pt = array([423.71374512, 194.11158752])
```
