### ISSUE TITLE
3D stack images format

### ISSUE THREAD

**Issue by areiasfi** [ANTsX/ANTsPy#160]
**Is your feature request related to a problem? Please describe.**
Hi! I am trying to use ANTSPy and I would like to know what is the best way to translate my data, which is mat file (matlab files) with 3D stacks with different time points (4D), to ANTsPy file types. Do you have recommendations for this? 

**Describe the solution you'd like**
I am considering translate the dat file to numpy and then from numpy to ANTs format, but not sure if this is the most efficient way.

Thank you for your help!

**Comment by stnava** [comment]
we don't use matlab so no guidance there.  I would recommend googling "Matlab to numpy" ... then you can use 

```
>>> import ants
>>> import numpy as np
>>> image = ants.from_numpy(
...             np.asarray([[[0, 2], [1, 3]], [[4, 6], [5, 7]]]).astype("float32")
...         )
>>> 

```

**Comment by areiasfi** [comment]
> we don't use matlab so no guidance there. I would recommend googling "Matlab to numpy" ... then you can use
> 
> ```
> >>> import ants
> >>> import numpy as np
> >>> image = ants.from_numpy(
> ...             np.asarray([[[0, 2], [1, 3]], [[4, 6], [5, 7]]]).astype("float32")
> ...         )
> >>> 
> ```

Ok, thank you!

**Comment by areiasfi** [comment]
Sorry, but I have another question. From what I understand from the examples and the documentation, antsRegistration function takes two 2D images (the fixed and the moving image), so I will have to apply this function to each plane of the time lapse data set, right? I just want to make sure that there isn't already a 3D volume correction already implemented.
Thank you very much for your help!
Best wishes,
Edite

**Comment by stnava** [comment]
same code whether 2D or 3D - supports both
