### ISSUE TITLE
Usage of ants.apply_transforms_to_points

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#161]
This is not really a bug but more of a usage issue. I have an image and an associated mask. I want to register the image to a reference atlas and then find the corresponding masking points in the warpedmovout image. Sometimes the registration works sometimes it doesnt also when it works the points never get transformed correctly. I am sure im doing something wrong but i cant figure it out 

the first image is the moving image and the second is the fixed image
![p4_atlas](https://user-images.githubusercontent.com/45297533/80238140-32781600-865e-11ea-8a73-8a0f22efca43.png)
 
![p4_hist](https://user-images.githubusercontent.com/45297533/80238015-f6dd4c00-865d-11ea-8206-6e6fa5b21b9f.png)

the masking points - https://we.tl/t-y31rP8YtAa
the notebook link - https://we.tl/t-ZkoIkUIlYH

**Comment by stnava** [comment]
your points need to be defined in the physical space of the image.   not in voxel/pixel coordinates.

also, see this example and make sure you can run and understand it:  https://github.com/stnava/chicken

you may need to translate the example to python.

**Comment by anorak94** [comment]
is the pse metric available in antspy doing a simple call gives a ValueError: `type_of_transform` does not exist

**Comment by stnava** [comment]
it's a metric, not a transform.   unsupported anyway.
