### ISSUE TITLE
N4:  return_as_bias_field?

### ISSUE THREAD

**Issue by ntustison** [ANTsX/ANTsPy#163]
Hey @stnava ,

As you see [here](https://github.com/ANTsX/ANTsPy/blob/master/ants/utils/bias_correction.py#L44-L51), this function doesn't have the option of returning the bias field instead of the bias corrected image as does the R analog.  Am I correct in assuming that it would be relatively straightforward for me to add this option?

Nick

**Comment by stnava** [comment]
yes - I think so ... but I have to figure out how to make such changes each time .... can't recall the procedure though there is a tutorial somewhere.

**Comment by ntustison** [comment]
Great.  Thanks.  I'll see if I can figure it out.

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsPy/pull/164
