### ISSUE TITLE
Problems with nifti images orientation

### ISSUE THREAD

**Issue by pietroastolfi** [ANTsX/ANTsPy#173]
The orientation indicated by ants does not match with the one indicated by nibabel.
Furthermore, despite using the  function `ants.image_read` with `reorient=False` the image loaded present a modified orientation.

Example:
```
aff = nib.load(fixed_fn).affine
print(aff)
nib.aff2axcodes(aff)
```
[[  -1.25    0.      0.     90.  ]
 [   0.      1.25    0.   -126.  ]
 [   0.      0.      1.25  -72.  ]
 [   0.      0.      0.      1.  ]]
('L', 'A', 'S')
```
fixed = ants.image_read(fixed_fn, reorient=False)
aff = np.eye(4)
aff[:3,:3] = fixed.direction
aff[:3,3] = fixed.origin
print(aff)
nib.aff2axcodes(aff)
```
[[  1.   0.   0. -90.]
 [  0.  -1.   0. 126.]
 [  0.   0.   1. -72.]
 [  0.   0.   0.   1.]]
('R', 'P', 'S')

and RPS does not coincide with the belief of ants, which says that the image is in RPI orientation:

```
print(fixed)
```
ANTsImage (RPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (145, 174, 145)
	 Spacing    : (1.25, 1.25, 1.25)
	 Origin     : (-90.0, 126.0, -72.0)
	 Direction  : [ 1.  0.  0.  0. -1.  0.  0.  0.  1.]

Also, if I try to load the image specifying a LAS orientation I obtain an image with different values in the affine:

```
fixed = ants.image_read(fixed_fn, reorient='LAS')
aff = np.eye(4)
aff[:3,:3] = fixed.direction
aff[:3,3] = fixed.origin
print(aff)
nib.aff2axcodes(aff)
```
[[ -1.     0.     0.    90.  ]
 [  0.     1.     0.   -90.25]
 [  0.     0.    -1.   108.  ]
 [  0.     0.     0.     1.  ]]
('L', 'A', 'I')

Can you also explain to me why the reorientation that `image_read` does change the origin instead of just inverting the sign?

**Desktop**
 - OS: Mac OS 10.13
 - antspy: 0.2.4 installed via pip
 - python: 3.7

**Comment by stnava** [comment]
we only use ITK standards for image orientation.   can't support all possible uses of nifti especially what is done in FSL, SPM, etc to the header.   if you can share the image , we can look further but it is  unlikely any of this will change.

**Comment by pietroastolfi** [comment]
Yes here's the image: [(https://drive.google.com/file/d/1AnDLcEmbAVEmGBDr0cr9wbjpwhG0MN_c/view?usp=sharing)]

What about the fact that `image_read` changes the orientation even if `reorient=False`?

Why changing orientation changes the values of the origin instead of the changing just the sign of them?

**Comment by stnava** [comment]
you are mixing different systems of representing images.  we use itk and itk does not equal nibabel.  printing things from one and comparing to the other will only make sense if you understand both systems.  we've done a bunch of testing on this stuff in the past and recommend using `ants.from_nibabel` and `ants.to_nibabel` to work with nibabel.  however, we don't use that stuff ourselves so rely on other people to determine if it works for them.

ITK-snap, simple itk and ants agree about this image and our internal systems are consistent.  the orientation is not "changed" in reality.   

```
reader = sitk.ImageFileReader()
reader.SetImageIO("NiftiImageIO")
reader.SetFileName("sub-105014_space-dwi_T1w.nii.gz")
image = reader.Execute()
print( image )
```

also see https://github.com/ANTsX/ANTsPy/blob/2fb3ca3f67e9ddc2f6e962d712c80ce222c491d2/tests/test_core_ants_image_io.py#L270-L277

if you want to learn more then read this stuff:

https://discourse.itk.org/t/orientimagefilter-changes-the-origin-of-the-image/2200/19

**Comment by pietroastolfi** [comment]
Thanks for the explanation, it's been always hard to me to understand this fact of the orientation convention. Actually as you suggested loading with ants and moving `to_nibabel()` works as expected.
