### ISSUE TITLE
Enable deterministic sampling beyond random seed

### ISSUE THREAD

**Issue by MaximilianHoffmann** [ANTsX/ANTsPy#177]
**Is your feature request related to a problem? Please describe.**

My sample are rather sparse and I therefore want to specify the points taken for the registration deterministically. It think it's possible in ANTs and it would be nice to expose this feature.

**Describe the solution you'd like**
Take samples at two supplied sampling masks for moving and fixed?

**Comment by stnava** [comment]
try:

```
import os
os.environ["ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS"] = "1"
import ants
fi = ants.image_read( ants.get_data( "r16" ) ) - 128
mi = ants.image_read( ants.get_data( "r64" ) )
reg = ants.registration( fi, mi, 'Rigid', aff_random_sampling_rate=1, random_seed=1, verbose=1 )
reg = ants.registration( fi, mi, 'Rigid', aff_random_sampling_rate=0.1, random_seed=1, verbose=1 )
```

both should be highly repeatable if not perfectly so.

**Comment by MaximilianHoffmann** [comment]
Hi, 
thanks for the answer, I understood that fixing the random seed would make it repeatable. I was rather looking for a solution for choosing which samples to take from fixed and moving.

**Comment by stnava** [comment]
you can pass a mask

brian

**Comment by MaximilianHoffmann** [comment]
Would the sampling fraction be with respect to the unmasked voxels?

**Comment by stnava** [comment]
I'm not sure - @ntustison may know .... I believe this was changed
relatively recently

brian

**Comment by ntustison** [comment]
Yeah, I vaguely remember something about this being changed but I don't remember exactly.

**Comment by MaximilianHoffmann** [comment]
[This](https://github.com/ntustison/antsRegistrationWithMaskExample/blob/master/antsRegistrationExampleCommand.py) seems to work only with one mask, but it kind of suggests when loading to masks, that it would use two separate masks for fixed and moving.

**Comment by ntustison** [comment]
One (fixed) or two masks (fixed and moving) can be used in the main ``antsRegistration`` program but ``ants.registration`` and it's R analog are simplified interfaces to that program.  We might consider a pull request that integrates the latter two-mask option but it's not a high priority for us.

**Comment by stnava** [comment]
agree
