### ISSUE TITLE
Double or single precision with antsy

### ISSUE THREAD

**Issue by pamparana34** [ANTsX/ANTsPy#178]
Does ANTSpy use double precision by default? What would be a way to change the precision level for an affine registration problem?

**Comment by stnava** [comment]
`float` - why does this question come up?

**Comment by pamparana34** [comment]
I am trying to figure out how to change/increase the precision to minimise reproducibility errors due to multithreading but I am guessing it is already using 64 bit precision?

**Comment by stnava** [comment]
we have ample discussion here 
https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues
but antspy is not focused on that issue.
