### ISSUE TITLE
Follow "Anatomy of ANTsRegistration call" with ANTsPy

### ISSUE THREAD

**Issue by dpedrosac** [ANTsX/ANTsPy#182]
To get familiar with the way ANTsPy works, I am trying to reproduce some of the steps that I think may be useful. One of these is the multistep registration similar to what was reported here: https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call

Yet, I'm not sure how to do this in one call (if possible at all). I have looked through the code, but the closest I have found is the multivariate_extras option in interface.py, which apparently only works if "SyNOnly" is selected. What would be the way to go here? is it stepwise registrations one after the other and would you recommend including the previous steps as initial_transform? Or am I completely wrong?

**Comment by ntustison** [comment]
That wiki page describes the core ``antsRegistration`` program available in the ANTs package.  I would say that it is one of the more complex programs that I've seen, not just used.  But the reason for the complexity is that there is quite a bit of functionality that we wanted to be able to access.  However, at the same time, we understand that the vast majority of users won't need all those options and so we've created a number of front-ends for that program.  These include ``antsRegistrationSyNQuick.sh`` and ``antsRegistrationSyN.sh`` in ANTs, ``ants.registration`` in ANTsPy, and ``antsRegistration`` in ANTsR.  The way we've simplified the interface in the latter two is to create use cases (``typeofTransform``), such as ``SyNOnly``, which is quite different than what you'd probably glean from the wiki page.  

So what I would recommend is to start with the Example

```
>>> import ants
>>> fi = ants.image_read(ants.get_ants_data('r16'))
>>> mi = ants.image_read(ants.get_ants_data('r64'))
>>> fi = ants.resample_image(fi, (60,60), 1, 0)
>>> mi = ants.resample_image(mi, (60,60), 1, 0)
>>> mytx = ants.registration(fixed=fi, moving=mi, type_of_transform = 'SyN' )
```

and then try incorporate your own data.  You can then let us know when you get stuck.

**Comment by dpedrosac** [comment]
Alright, now I get it. I did not have a look in detail at the parts of the interface.py as I was assuming it's the opposite, namely these are the special cases. But setting the transform to "SyNRA" does exactly what I wanted and it works as expected. And I now got the idea how to fiddle with the args to customize registration in case I need it in a future. Thank you so much!
