### ISSUE TITLE
Write deformation field & transform deformation field to displacement field.

### ISSUE THREAD

**Issue by myldh33** [ANTsX/ANTsPy#184]
First of all, Thanks for providing a great library. 

After register images, I want to transform the deformation field to NumPy array. 

Can you advise how to transform deformation field to NumPy array?

**Comment by stnava** [comment]
run a registration, then read the warp image 
```
temp = ants.image_read( mytx['fwdtransforms'][0] )
mynp = temp.numpy()
```
