### ISSUE TITLE
Mapping T1 to MNI template

### ISSUE THREAD

**Issue by jct0024** [ANTsX/ANTsPy#189]
Good Morning,
Notice in the ants github that there is a way to map two images that are not in the same space. I was wondering if that function is also possible with ANTsPy or is it necessary to use another method to be able to do it from python.
Thanks for your attention, Jesus.

**Comment by stnava** [comment]
ANTs (whether in R, python or C++) is indeed made for mapping two images not in the same space.  This is the role of low-dimensional transformation step ( translation, rigid or affine ).   See the documentation for examples.
