### ISSUE TITLE
Smudging in ants registration 

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#191]
I have been using ants for registering cerebellum slices to a reference atlas. for most parts it works correctly but sometimes i get a weird smudging in my registered images 
<img width="772" alt="Screenshot 2020-06-25 at 02 02 34" src="https://user-images.githubusercontent.com/45297533/85639215-4ce36580-b688-11ea-9cf2-d411ea41117b.png">
<img width="786" alt="Screenshot 2020-06-25 at 02 02 14" src="https://user-images.githubusercontent.com/45297533/85639218-4e149280-b688-11ea-8ecb-c44764eeb69c.png">
<img width="769" alt="Screenshot 2020-06-25 at 02 01 48" src="https://user-images.githubusercontent.com/45297533/85639224-5076ec80-b688-11ea-937e-4574b5505579.png">

this is my ants call 
   ```
    fixed_contour = ants.from_numpy(rssm_contour)
    moving_contour  = ants.from_numpy(dapi_contour)
    
    reg_contour = [cntr_metric, fixed_contour, moving_contour, weight, 64, "Regular", 0.85 ]

    metrics = list()
    metrics.append(reg_contour)
    imft1 = rss
    immt2 = ants.from_numpy(match_histograms(immt1.numpy(), imft1.numpy()))
    tx   = ants.registration(fixed=imft1, moving=immt2, type_of_transform ="SyN", metric ="MattesMutualInformation",
                             reg_iterations = (500, 500, 500, 500, 500), 
                                 grad_step = 0.25, aff_iterations=(5000, 5000, 5000, 5000, 5000), 
                                 aff_shrink_factors=(4, 2, 2, 1, 1), 
                                 aff_smoothing_sigmas=(3, 2, 1, 0, 0),
                             
                             multivariate_extras = metrics)
    mywarpedimage = ants.apply_transforms( fixed=imft1, moving=immt2,
                                           transformlist=tx['fwdtransforms'] )
```
is there a way to mitigate this smudging effect. 

The images in which it works well 
<img width="763" alt="Screenshot 2020-06-25 at 02 01 10" src="https://user-images.githubusercontent.com/45297533/85639285-874d0280-b688-11ea-95be-0d58cf4b8299.png">
<img width="714" alt="Screenshot 2020-06-25 at 02 07 08" src="https://user-images.githubusercontent.com/45297533/85639312-a055b380-b688-11ea-8f97-270f085032ca.png">

**Comment by stnava** [comment]
sounds like a nice project.  do you have data that you can share ie a reproducible example that illustrates this?

**Comment by stnava** [comment]
also I can't see any smudging but that may be because I don't know what you mean by the term.

https://en.wikipedia.org/wiki/Smudging

**Comment by anorak94** [comment]
sorry i mean the green from the image has been smudged all over the place instead of only being confined to the boundaries of the cerebellum where it should be

**Comment by anorak94** [comment]
<img width="671" alt="Screenshot 2020-06-25 at 02 13 40" src="https://user-images.githubusercontent.com/45297533/85639611-89639100-b689-11ea-80d7-ef3f23110df8.png">

here you go you made me doubt myself for a second

**Comment by anorak94** [comment]
https://we.tl/t-88ZFVRXWGe heres the data and the notebook

**Comment by stnava** [comment]
can you provide a cleaner and tighter example.  I'd have to rewrite this one to figure out what is going and, even then, it's hard to know what you mean by smudging.   need a very specific and very clear example.

**Comment by anorak94** [comment]
<img width="666" alt="Screenshot 2020-06-25 at 15 07 08" src="https://user-images.githubusercontent.com/45297533/85725638-95853800-b6f5-11ea-9061-5aa99385b3e1.png">
i ll do that

**Comment by anorak94** [comment]
is it clear now or should i provide some more clarifications

**Comment by stnava** [comment]
it is not clear enough to me.  I don't have time to unpack your code so that it could be (first) understood and (2nd) debugged.  it's also not at all clear what your data is supposed to represent and what your issue is.  that being said, I can run your example but I don't have the 2 hours it would take to rewrite it etc.     ideally you would provide : 

1.  a clear explanation of what the data is and what it's supposed to represent + demonstrate that it's not just garbage in 

2.  a step by step *script* (not a function) that shows the problem 

3. explanation of what you think the issue might be

I may eventually look at the ipynb but who knows how long that could take.

**Comment by anorak94** [comment]
![ref](https://user-images.githubusercontent.com/45297533/85767000-dd1cbb80-b717-11ea-8f64-68affc54c6a8.png)
![ref_c](https://user-images.githubusercontent.com/45297533/85767006-ddb55200-b717-11ea-9ca6-705b8fe536aa.png)
![dapi_c](https://user-images.githubusercontent.com/45297533/85767010-dee67f00-b717-11ea-9b77-71d1500d2a1b.png)
![dapi](https://user-images.githubusercontent.com/45297533/85767059-eb6ad780-b717-11ea-9dc6-cace0d6b6da1.png)

```

dapi = ants.image_read("dapi.png")
ref = ants.image_read("ref.png")
dapi_c  =ants.image_read("dapi_c.png")
ref_c = ants.image_read("ref_c.png")

reg_contour = ["MattesMutualInformation", ref_c, dapi_c, 500, 64, "Regular", 0.85 ]
metrics = list()
metrics.append(reg_contour)

## the actual registration 

immt2 = ants.from_numpy(match_histograms(dapi.numpy(), ref.numpy()))  ## moving image after histogram matching
tx   = ants.registration(fixed=ref, moving=immt2, type_of_transform = "SyN", metric = "MattesMutualInformation",
                         reg_iterations = (500, 500, 500, 500, 500), 
                             grad_step = 0.25, aff_iterations=(5000, 5000, 5000, 5000, 5000), 
                             aff_shrink_factors=(4, 2, 2, 1, 1), 
                             aff_smoothing_sigmas=(3, 2, 1, 0, 0),
                                multivariate_extras = metrics)

mywarpedimage = ants.apply_transforms( fixed=ref, moving=immt2,
                                       transformlist=tx['fwdtransforms'] )
## run the registration

## plot the results ##0 - is the fixed image, 1 is the moving image, 2 is the transformed image
f, a = plt.subplots(1, 3, figsize=(12, 12))
a[0].imshow(ref.numpy())
a[1].imshow(dapi.numpy())
a[2].imshow(mywarpedimage.numpy())
plt.show()
## overlay the transformed image on the reference image 
ref.plot(overlay=mywarpedimage, overlay_alpha = 0.3)

```

**Comment by anorak94** [comment]
i have put the code snippet and the images
my problem is that the registration quality is not good 
the fixed image is the cerebellum cropped from a reference atlas at P7 and the moving image is a slice collected experimentally dapi_c and ref_c are the contours from the cerebellum and experimental image which i extract using another algorithm i am passing those as contraints to guide the registration because i want the folds to line up to get a more geometrically correct result

**Comment by anorak94** [comment]
https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

**Comment by stnava** [comment]
yes - this is an improved example.   I can look at this.

regarding reproducibility :  see `help( ants.registration )` and the information regarding `random seed`

**Comment by stnava** [comment]
one issue with the above is I don't have the png images.

**Comment by anorak94** [comment]
https://we.tl/t-13eAFd802a

**Comment by stnava** [comment]
can you try the following:

1. convert all your data from png to nrrd or nifti ( on disk ) 

```
img = ants.image_read( "filename.png")
ants.image_write( img, "filename.nrrd")
```

2. rerun your script with the nrrd data as input

and let me know if you see anything different.

**Comment by anorak94** [comment]
the same problem persists 
<img width="670" alt="Screenshot 2020-06-26 at 01 24 22" src="https://user-images.githubusercontent.com/45297533/85805159-d7d96400-b74b-11ea-9292-89f0fc51d77d.png">
```
dapi = ants.image_read("dapi.nrrd")
ref = ants.image_read("ref.nrrd")
dapi_c  =ants.image_read("dapi_c.nrrd")
ref_c = ants.image_read("ref_c.nrrd")

reg_contour = ["MattesMutualInformation", ref_c, dapi_c, 500, 64, "Regular", 0.85 ]
metrics = list()
metrics.append(reg_contour)

## the actual registration 

immt2 = ants.from_numpy(match_histograms(dapi.numpy(), ref.numpy()))  ## moving image after histogram matching
tx   = ants.registration(fixed=ref, moving=immt2, type_of_transform = "SyN", metric = "MattesMutualInformation",
                         reg_iterations = (500, 500, 500, 500, 500), 
                             grad_step = 0.25, aff_iterations=(5000, 5000, 5000, 5000, 5000), 
                             aff_shrink_factors=(4, 2, 2, 1, 1), 
                             aff_smoothing_sigmas=(3, 2, 1, 0, 0),
                                multivariate_extras = metrics)

mywarpedimage = ants.apply_transforms( fixed=ref, moving=immt2,
                                       transformlist=tx['fwdtransforms'] )
## run the registration

## plot the results ##0 - is the fixed image, 1 is the moving image, 2 is the transformed image
f, a = plt.subplots(1, 3, figsize=(12, 12))
a[0].imshow(ref.numpy())
a[1].imshow(dapi.numpy())
a[2].imshow(mywarpedimage.numpy())
plt.show()
## overlay the transformed image on the reference image 
ref.plot(overlay=mywarpedimage, overlay_alpha = 0.3)


```

**Comment by anorak94** [comment]
<img width="667" alt="Screenshot 2020-06-26 at 01 25 36" src="https://user-images.githubusercontent.com/45297533/85805216-fe979a80-b74b-11ea-8ab7-7bea41186f4c.png">
second run

**Comment by anorak94** [comment]
<img width="679" alt="Screenshot 2020-06-26 at 01 27 19" src="https://user-images.githubusercontent.com/45297533/85805294-369edd80-b74c-11ea-9f76-c5ee9fad820d.png">
fifth run is better but this kind of problem makes it harder to have ants as a part of a high throughput fully automated pipeline because then somebody needs to go and rerun the images that failed

**Comment by stnava** [comment]
I get highly repeatable and reasonable results with this code.  let me know if you see the same.

```
import ants
from skimage.exposure import match_histograms
import matplotlib.pyplot as plt
import numpy as np
from skimage.color import rgb2gray
import pickle
from scipy.spatial import ConvexHull
from scipy import ndimage
from PIL import Image, ImageDraw
from scipy.ndimage import gaussian_filter
refB=ants.image_read( '~/Downloads/ref.nrrd' )
immt2B=ants.image_read( '~/Downloads/immt2.nrrd' )
tx  = ants.registration(
  fixed=refB,
  moving=immt2B,
  type_of_transform = "Affine",
  aff_iterations=(200,200,200,200,0,0,0),
  aff_smoothing_sigmas=(16,8,4,2,1,1,1),
  aff_shrink_factors=(16,8,4,2,1,1,1) )

txSyN   = ants.registration(
  fixed=refB,
  moving=immt2B,
  initial_transform = tx['fwdtransforms'][0],
  total_sigma = 3.0,
  flow_sigma = 5.0,
  syn_sampling = 2,
  syn_metric = 'CC',
  reg_iterations = (40,20,10),
  type_of_transform = "SyN", verbose = True )

mywarpedimage = ants.apply_transforms( fixed=refB, moving=immt2B,
                                       transformlist=txSyN['fwdtransforms'] )

## plot the results ##0 - is the fixed image, 1 is the moving image, 2 is the transformed image
f, a = plt.subplots(1, 3, figsize=(12, 12))
a[0].imshow(refB.numpy())
a[1].imshow(immt2B.numpy())
a[2].imshow(mywarpedimage.numpy())
plt.show()
## overlay the transformed image on the reference image
refB.plot(overlay=mywarpedimage, overlay_alpha = 0.3)
```

[temp.zip](https://github.com/ANTsX/ANTsPy/files/4834338/temp.zip)

**Comment by stnava** [comment]
I agree that naive users have a hard time building reliable code.   I doubt that has anything to do with ants, though.

**Comment by anorak94** [comment]
yeah thats true i wouldnt call myself an expert on building highly reliable and scalable code and ants is wonderful i really enjoy using it sorry if i was too careless with my words

**Comment by anorak94** [comment]
could you tell me how you go about choosing parameters such as aff_iterations , aff_smoothing_sigmas, aff_shrink_factors i kind of know what they are but choosing those parameter values seem kind of arbitrary to me and even in the syn call.
The only step i was missing was the intial transform

**Comment by stnava** [comment]
there are two fields of computer vision that relate to what we do in ants ( parameters etc )
 
https://www.kth.se/profile/tony/page/scale-space-theory

and 

https://en.wikipedia.org/wiki/Pattern_theory

in addition to basic ideas from optimization.

**Comment by anorak94** [comment]
and also how does flow_sigma and total_sigma influence the registration process because i see that it is smoothing for the total field and the smoothing for the update field but how does this manifest itself in the registration process

**Comment by stnava** [comment]
you can run experiments to answer those questions with detail for your data.  it's too complex to give a simple answer here as it is a function of all possible input images / matching problems etc.
