### ISSUE TITLE
Does AntsPy support 3d registration?

### ISSUE THREAD

**Issue by kaiwen2020** [ANTsX/ANTsPy#194]
I am trying to use AntsPy to register two 3d MR images. I followed the tutorial, however, the fwdtransform returned by the registration function is empty.  

An error occurred when I tried to display a 3d image:   IndexError: index 20 is out of bounds for axis 0 with size 20

I guess that's because AntsPy only works for 2d images and it does not support 3d image registration, isn't it? Thank you.

**Comment by ntustison** [comment]
ANTsPy does handle 3-D images and that scenario probably constitutes the majority of use cases.  You seem to have multiple issues, not all of which solely concern image registration.  Can you please provide a reproducible example, with data, for us to see where you went wrong?

**Comment by kaiwen2020** [comment]
Thank you for your conformation. The image I used is not a real 3d image, it's a slice. It's actually a 2d image with dimension 1 in the third direction. Maybe that's the reason why I got this error... It works after I removed the third direction.
