### ISSUE TITLE
Metric evaluation

### ISSUE THREAD

**Issue by petr-henys** [ANTsX/ANTsPy#195]
Hi,
is there any way how to evaluate metrics locally?With an output as ANTsImage?

**Comment by stnava** [comment]
for intensity difference:

```
fi = ants.image_read( ants.get_data("r16") )
mi = ants.image_read( ants.get_data("r64") )
ssd = ( fi - mi )**2
```

for neighborhood correlation

```
import numpy as np
mask = ants.get_mask(fi)
mat = ants.get_neighborhood_in_mask( fi, mask, radius=(2,2))
mat2 = ants.get_neighborhood_in_mask( mi, mask, radius=(2,2))
corvec = np.zeros( mat2.shape[1] )
for x in range( mat2.shape[1] ):
  corvec[ x ] = np.corrcoef( mat[:,x], mat2[:,x] )[1,1]
# corvec = nan_to_num( corvec ) # fix NaNs
corimg = ants.make_image( mask, corvec ) 
```

you can do something similar to the above with mutual information but it's trickier and would need to use `ants.image_similarity` - main thing would be to initialize the joint histogram globally then query values locally.  not sure how much code this would take to achieve.   there would be several other ways to do this with scipy etc.

**Comment by petr-henys** [comment]
Thank you!
this helps a lot. The demons metric is actually ssd metric, am I right?

best,
Petr

**Comment by petr-henys** [comment]
Thank you Brian,
i found this study describing ants metrics "A Reproducible Evaluation of ANTs Similarity Metric Performance in Brain Image Registration", but there is no mention of "demons" metric. Where should i look at?

Petr
