### ISSUE TITLE
minor syntax error?

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPy#20]
on `Linux  3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` with `Python 2.7.5`

```
>>> import ants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/ants/__init__.py", line 7, in <module>
    from .core import *
  File "/usr/lib64/python2.7/site-packages/ants/core/__init__.py", line 2, in <module>
    from .ants_image import *
  File "/usr/lib64/python2.7/site-packages/ants/core/ants_image.py", line 603
    def image_physical_space_consistency(*images, tolerance=1e-2, datatype=False):
                                                          ^
SyntaxError: invalid syntax
```

**Comment by ncullen93** [comment]
yeah it's a python 2 thing ... doesnt support `*images` to accept an arbitrary number of input images.. I'll change it back to the ANTsR version which just accepts two.

**Comment by stnava** [comment]
got it - other errors exist with `python2.x` - might note in documentation that development is based on python3.x or whatever.

**Comment by ncullen93** [comment]
ok . I guess I'll add py2 support and test on travis in the near future. thanks
