### ISSUE TITLE
error when using ants.n4_bias_field_correction Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zzz123xyz** [ANTsX/ANTsPy#202]
**Describe the bug**

encounter the  `Segmentation fault (core dumped) error`
when I run the `ants.n4_bias_field_correction`

**To Reproduce**
I test a simple sample in IXI dataset (a commonly used one)

**Expected behavior**
run it through with the following code:
```
img_fn = "<my path to sample>/test_3_samples_preprocess_in_mni/IXI002-Guys-0828-T1.nii.gz"
img = ants.image_read(img_fn)
out = ants.n4_bias_field_correction(img)
```
output is:
`Segmentation fault`
in another server output is:
`Segmentation fault (core dump)`

**Desktop (please complete the following information):**
 - OS: Linux 3.10.0-862.14.4.el7.x86_64 x86_64

**Additional context**
python information:

```
Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0] :: Anaconda, Inc. on linux
```

antspy version information:
`antspyx                       0.2.4`

**Comment by stnava** [comment]
we cannot reproduce this error.  if you can provide a reproducible example based on a recent release (not an old one) then we can address.

**Comment by zzz123xyz** [comment]
> we cannot reproduce this error. if you can provide a reproducible example based on a recent release (not an old one) then we can address.

Hi stnava
Thanks, I use the latest version of antspy, I still cannot make it work

I reinstall all the thing again, This time I downgrade the python version: 
```
Python 3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```
Therefore, I can install the latest version of ANTSpy which only support python 3.6
`antspyx                   0.2.5                    pypi_0    pypi
`

I also use the MNI template in the ANTS package to do the test.  the test code is as follow:

```
>>> import ants
>>> data_path='/scratch/itee/uqlliu10/ANTsPy-master/data/'
>>> mni = ants.image_read(data_path+'mni.nii.gz' )
>>> out = ants.n4_bias_field_correction(mni)
```
the results are still 
`Segmentation fault`

I don't know what to do now. I test the function ants.n4_bias_field_correction() with 2D sample such as r16slice.jpg and r64slice.jpg. It seem to work. Does this function only work for 2D??

**Comment by zzz123xyz** [comment]
> Try installing directly from the GitHub repo:
> 
> ```
> git clone https://github.com/ANTsX/ANTsPy
> cd ANTsPy
> python3 setup.py install
> ```

Thanks so much Nick
That works. I actually tried the method several times on a cluster. I always experience dependency problems such as ITK and Cmake. Directly build the package on the head node solve the problem this time. Maybe, you should update those pre build wheels now. I install the package with the wheel while ago. It worked fine. But this time the old installation does not work anymore with the segmentation fault error. That really confuses me. Maybe some system update on Linux has ruin the old installation. Anyway really appreciate your help. Thanks

Lance
