### ISSUE TITLE
AttributeError: module 'ants' has no attribute 'compose_transforms_to_field'

### ISSUE THREAD

**Issue by zzz123xyz** [ANTsX/ANTsPy#203]
**Describe the bug**
I install the antapy package with `python install antspyx`, I test use the code in instruction, 

https://antspy.readthedocs.io/en/latest/core.html?highlight=compose_transforms_to_field
```
>>> import ants
>>> image = ants.image_read( ants.get_ants_data( "r16" ) )
>>> image = ants.threshold_image( image, 90, 120 )
>>> image = ants.label_clusters( image, 10 )
>>> cents = ants.get_centroids( image )
```
it reports an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ants' has no attribute 'compose_transforms_to_field'
```

anybody know what is wrong with the package???

**Additional context**
Desktop (please complete the following information):

OS: Linux 3.10.0-862.14.4.el7.x86_64 x86_64
Additional context
python information:

Python 3.7.7 (default, May  7 2020, 21:25:33)
[GCC 7.3.0] :: Anaconda, Inc. on linux
antspy version information:
antspyx 0.2.4

**Comment by stnava** [comment]
you may want to read about `ants.apply_transforms` and the `compose` option.  the documentation was out of date and is now fixed in the main repository.

**Comment by zzz123xyz** [comment]
> you may want to read about `ants.apply_transforms` and the `compose` option. the documentation was out of date and is now fixed in the main repository.

Sorry the code I post is not correct. it is this code 
```
>>> import ants
>>> fi = ants.image_read(ants.get_ants_data('r16') )
>>> mi = ants.image_read(ants.get_ants_data('r64') )
>>> fi = ants.resample_image(fi,(60,60),1,0)
>>> mi = ants.resample_image(mi,(60,60),1,0) # speed up
>>> mytx = ants.registration(fixed=fi, moving=mi, type_of_transform = ('SyN') )
>>> compfield = ants.compose_transforms_to_field( fi, mytx['fwd'] )
```
give me the error as above

**Comment by stnava** [comment]
it's very rare to need to do that.  what are you trying to achieve?  anyway, see the `compose` option in `ants.apply_transforms`.
