### ISSUE TITLE
apply_transforms_to_points raises error with one 3D point

### ISSUE THREAD

**Issue by tommydino93** [ANTsX/ANTsPy#204]
**Describe the bug**
I would like to apply a transformation to one 3D point using ants.apply_transforms_to_points, but the function raises the pandas error **ValueError('Length of values does not match length of index')** in the line 307 of this [script](https://github.com/ANTsX/ANTsPy/blob/master/ants/registration/apply_transforms.py), namely line:

`pointsOutDF['x'] = mynp[:,0]`

A few things to note:

- the point is already in physical space

- the issue does not occur if I run the same command from terminal like:

`'antsApplyTransformsToPoints', '-d', '3', '-i', csv_path, '-o', output_path_struct, '-t', struct_2_tof_mat_path_`

**To Reproduce**
1. I created a Drive folder with my files (.mat file and csv file). Please go to:

 https://drive.google.com/drive/folders/1BTOnGOlzdNy-B7AhCe5SmW1Qr7GerzyR?usp=sharing

and download the files locally

2. Create the following script:

`import ants`
`import pandas as pd`

`# modify this path to the downloaded .mat file`
`mat_file_path = "/PATH/TO/out_struct_2_TOF_0GenericAffine.mat"`

`# modify this path to the downloaded .csv file`
`point_df = pd.read_csv("/PATH/TO/Center_Coordinate_TOF_in_mm.csv")`

`tof_2_struct_points_df = ants.apply_transforms_to_points(dim=3,
                                                         points=point_df,
                                                         transformlist=[mat_file_path])`

**Expected behavior**
I would expect that an output dataframe is created without raising errors

**Desktop (please complete the following information):**
 - OS: Ubuntu Xenial
 - Version 16.04
- Python 3.5

**Comment by stnava** [comment]
I think if you repeat the point twice then it will work.

**Comment by tommydino93** [comment]
Hi @stnava!

You mean like:
x,                y,         z,         t
-45.4,   -49.3,       37.6,        0
-45.4,   -49.3,       37.6,        0

similar to the example in the [docs](https://antspyx.readthedocs.io/en/latest/_modules/ants/registration/apply_transforms.html)?

Thanks a lot in advance :)

**Comment by stnava** [comment]
yes - I think so - sorry I knew about this "one point" issue but haven't figured out this special case

**Comment by tommydino93** [comment]
Yes, it works. The script in the above comment becomes:

`import ants`
`import pandas as pd`

`# modify this path to the downloaded .mat file`
`mat_file_path = "/PATH/TO/out_struct_2_TOF_0GenericAffine.mat"`

`# modify this path to the downloaded .csv file`
`point_df = pd.read_csv("/PATH/TO/Center_Coordinate_TOF_in_mm.csv")`
`# create new dataframe and replicate coordinate as second row`
`new_df = pd.DataFrame(np.repeat(point_df.values, 2, axis=0))`
`new_df.columns = point_df.columns`


`tof_2_struct_points_df = ants.apply_transforms_to_points(dim=3,
                                                         points=new_df,
                                                         transformlist=[mat_file_path])`
