### ISSUE TITLE
Warping brains across time

### ISSUE THREAD

**Issue by mariakesa** [ANTsX/ANTsPy#208]
Hello,

Is it possible to morph a single file with 4 dimensions (e.g. including time) onto a reference brain using SyN?

Thank you for your help!

Maria

**Comment by gdevenyi** [comment]
antsApplyTransforms --help has:
```

     -e, --input-image-type 0/1/2/3/4 
                            scalar/vector/tensor/time-series/multichannel 
          Option specifying the input image type of scalar (default), vector, tensor, time 
          series, or multi-channel. A time series image is a scalar image defined by an 
          additional dimension for the time component whereas a multi-channel image is a 
          vector image with only spatial dimensions. 
          <VALUES>: 0

```

**Comment by stnava** [comment]
Yes, split the image using slice image and then Use the function build
template or just directly register each time slice to the target.

the ants longitudinal thickness pipeline paper explains another way to
achieve this.

**Comment by mariakesa** [comment]
Thanks so much! Very useful!
