### ISSUE TITLE
ValueError: `type_of_transform` does not exist when using "antsRegistrationSyNQuick[b]"

### ISSUE THREAD

**Issue by J-Yash** [ANTsX/ANTsPy#209]
I am trying to use the registration module and I get an error when I use 
`type_of_transform="antsRegistrationSyNQuick[b]"`.

The following is the error:
`ValueError: 'type_of_transform' does not exist`

 This is the code snippet that I try to use for registration:
`registration = ants.registration(fixed=fixed_image, moving=moving_image, type_of_transform="antsRegistrationSyNQuick[b]")`

Other values for `type_of_transform` work perfectly such as `type_of_transform="SyN"`.

I am running on MacOS and using Jupyter Notebook to run this code. I have installed ANTs as well as AntsPy.

**Comment by ntustison** [comment]
I have no problem running the following:

```
>>> import ants
>>> r16 = ants.image_read(ants.get_data("r16"))
>>> r64 = ants.image_read(ants.get_data("r64"))
>>> registration = ants.registration(fixed=r16, moving=r64, type_of_transform="antsRegistrationSyNQuick[b]", verbose=True)
```

When was the last time you updated?

**Comment by J-Yash** [comment]
I updated last night. Does `antsRegistrationSyNQuick[b]` depend on ANTs installation? Could it be a $ANTSPATH issue?

**Comment by ntustison** [comment]
No.  

When you say you updated, did you compile from source?

git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install

**Comment by J-Yash** [comment]
I had been using the pip installation (via `pip install antspyx`).
I removed the pip installation and compiled from source and it works fine now.
Thank you for your help.
