### ISSUE TITLE
DOC: centos7 dev installation

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPy#21]
background:

* followed python3.6 installation from [here](https://www.digitalocean.com/community/tutorials/how-to-install-python-3-and-set-up-a-local-programming-environment-on-centos-7)

* created a virtual environment.

* cloned `ANTsPy`

then called

```
sudo python3.6 setup.py develop --vtk
```

result is successful.

to use the toolkit, i then need:

```
 pip3.6 install numpy
 pip3.6 install pandas
 pip3.6 install pillow
 pip3.6 install sklearn
 pip3.6 install scikit-image
 pip3.6 install webcolors
 pip3.6 install plotly
 pip3.6 install matplotlib
 sudo yum --enablerepo=ius-archive install python36u-tkinter
 ```
after this, i am successful at running the examples in:

```
help( ants.vol )
help( ants.sparse_decom2 )
```

**Comment by ncullen93** [comment]
added to readme thanks. planning to cut down a few of those 3rd party dependencies or have them install automatically.
