### ISSUE TITLE
KeyError: 'antsVol' when trying to use ants.vol()

### ISSUE THREAD

**Issue by J-Yash** [ANTsX/ANTsPy#210]
I am trying to plot an ANTsImage as a volume. But I am getting the following error:
`KeyError: 'antsVol'`

This is the code I am using:
`mnipath = ants.image_read(ants.get_ants_data('surf'))`
`ants.vol(mnipath)`

It is my understanding that `ants.vol()` should be able to render a 3-D image as a volume and that the provided image `surf` is a 3-D image. 

I am running this on MacOS and have installed ANTsPy by compiling from source. Do I need to separately install VTK(from source) as well to use this? I currently have VTK installed via pip.

Screenshot of error:
![image](https://user-images.githubusercontent.com/17974911/93513811-63e6cc00-f8f4-11ea-80d8-3800c0e1c481.png)

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsPy/blob/master/CONTRIBUTING.md#what-happens-when-i-install-antspy

**Comment by J-Yash** [comment]
So, am I supposed to run `make install` (for ITK and VTK) after ANTsPy is built? If yes, could you guide me as to which directory to run `make install` in? If no, what could be the potential reason for the error that I am getting?

**Comment by morales-gregorio** [comment]
Hi,

I get the same problem with the pip version of antspy, does anyone know how to solve it?

Best,
Aitor

**Comment by ntustison** [comment]
Perhaps @stnava would know but I'm not sure it's possible with the current pip version of antspy.  YOu're probably best off recompiling the repo from scratch.

**Comment by stnava** [comment]
i dont think this functionality is finished yet --- any contributions to
its development would be welcome .... it's just a matter of wrapping the
relevant ANTs functions but this does indeed require another compilation
strategy beyond what is instantiated by default.

brian

**Comment by J-Yash** [comment]
Does this functionality work if compiled from source?

**Comment by stnava** [comment]
probably not without some hacking --- has not been tested in over 2 years

brian
