### ISSUE TITLE
Saving a transform from diffeomorphic transform function

### ISSUE THREAD

**Issue by mariakesa** [ANTsX/ANTsPy#211]
Hello:-)

I am creating a transform like this:
diffeomorphic_transform = ants.registration(fixed=atlas , moving=moving ,
                                type_of_transform = 'SyN', syn_metric='CC', grad_step=0.25,
                                flow_sigma=6,total_sigma=0.5, reg_iterations=[200,200,200,200,10],syn_sampling=2)
transform=diffeomorphic_transform['fwdtransforms']

How can I save this transform? 
ants.write_transform(transform, transform_out_file)
throws an error at this line:
libfn = utils.get_lib_fn('writeTransform%s' % (transform._libsuffix))

Any help would be appreciated!

Thank you!

Maria

**Comment by ntustison** [comment]
So ``diffeomorphic_transform['fwdtransforms']`` isn't actually an ants transform object.  Rather it's a string to the transform file located, in your case, in a temporary file.  You can actually save the transforms to a specific place by specifying the ``outprefix`` argument in the ``ants.registration`` call.

**Comment by mariakesa** [comment]
Thank you so much! Very helpful!
