### ISSUE TITLE
Plotting RGB(Multi channel) image using ants.plot()

### ISSUE THREAD

**Issue by J-Yash** [ANTsX/ANTsPy#220]
I am trying to read an rgb image(.jpg) and plot it using ants.plot() but it does not plot the image properly and instead plots noise.
Here is my image : 
![bird](https://user-images.githubusercontent.com/17974911/96207069-4ed37c00-0f38-11eb-8118-ae8acb88497f.jpg)
(This is just a sample image I am using to test plotting of rgb images)

Code to read/plot image : 
`im = ants.image_read(PATH_TO_IMAGE)`
`im.plot()`

The image that is being plotted looks like this:
![image](https://user-images.githubusercontent.com/17974911/96207250-c0abc580-0f38-11eb-87b4-221afbdec2a2.png)

The ANTsImage object header using `print(im)` gives:
![image](https://user-images.githubusercontent.com/17974911/96207313-eb961980-0f38-11eb-9b08-3e483cf79ca0.png)

**Is there a specific way to use rgb images in ANTs? Please advise.**

Thank you.

**Comment by ntustison** [comment]
I stumbled across this the other day and had to use ``imageio`` as a [workaround](https://github.com/ANTsXNet/TestingScripts/blob/master/testNeuralStyleTransfer.py#L7-L16).  Note that if you save ``starry_night_ants`` as a ``nii.gz`` file, you can then read it back in using ``ants.image_read``.   I have this on my list of things to fix but just haven't gotten to it yet.

**Comment by J-Yash** [comment]
1. So I tried using your suggested method to get the ANTs image but plotting that using ants.plot() still plots noise. Is there another way I could plot this ANTs image?

2. Even though the plotting is buggy, does the ants.registration() method work fine on such RGB images?

**Comment by ntustison** [comment]
It works for me.  

```
>>> starry_night = ants.image_read("starry_night.nii.gz")
>>> ants.plot(starry_night.vector_to_rgb())
```

>> Even though the plotting is buggy, does the ants.registration() method work fine on such RGB images?

Multi-component images, including RGB, have to be split up and any components beyond the first would need to be plugged into the ``multivariate_extras`` argument of ``ants.registration``.

**Comment by J-Yash** [comment]
That solves my issue. Thank you.
Although I was curious: Does using an RGB image lead to better registration? Or simply converting my image to grayscale(Or simply using one channel) and then doing the registration would give similar results?

**Comment by ntustison** [comment]
Medical imaging doesn't typically utilize RGB images so we don't have direct experience. However, since the RGB channels are highly correlated and since our go to metric is cross- correlation, you probably won't gain much using all three channels separately.

**Comment by J-Yash** [comment]
That's very helpful. Thank you.
