### ISSUE TITLE
Intensity Normalization improves the output?

### ISSUE THREAD

**Issue by asmaharry** [ANTsX/ANTsPy#221]
Hi,
I want to register a lesioned brain T1 scan to healthy brain atlas using diffeomorphic registration. 
I read here "https://github.com/ANTsX/ANTs/wiki/Anatomy-of-an-antsRegistration-call" 
"Run a bias correction before antsRegistration (i.e. N4). It helps getting better registration"
what about intensity normalization? Does intensity normalization of T1 scan makes any difference in registration or not?

Thank you.

**Comment by ntustison** [comment]
It could but you'd have to test on your own data.

**Comment by asmaharry** [comment]
What is the normal practice? do you people prefer to use it at your end?

**Comment by ntustison** [comment]
Well, by default it is off in the well-used scripts ``antsRegistrationSyN[Quick].sh`` (``-j 0``).   However, it is one of the few options that we expose to user in these scripts which points to the fact that it could be useful.

**Comment by asmaharry** [comment]
Thank you for the reply.
