### ISSUE TITLE
build_template() raises IndexError

### ISSUE THREAD

**Issue by dakota-hawkins** [ANTsX/ANTsPy#222]
Hello! Thanks for all your great work on this project. I'm finding it incredibly useful in my current work. When trying to build a template image, I have run into the following issue:

**Describe the bug**
When trying to build a template image using the `ants.build_template()` function, I receive an index error. The index error is not thrown when running the example found in the documentation.

```python
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-59-1d354803f467> in <module>
----> 1 ants.build_template(image_list=tuple(image_list))

~/anaconda3/envs/registration/lib/python3.8/site-packages/ants/registration/build_template.py in build_template(initial_template, image_list, iterations, gradient_step, blending_weight, weights, **kwargs)
     85             )
     86             if k == 0:
---> 87                 wavg = iio.image_read(w1["fwdtransforms"][0]) * weights[k]
     88                 xavgNew = w1["warpedmovout"] * weights[k]
     89             else:

IndexError: list index out of range
```

**To Reproduce**

I was originally working with 3D confocal image slices, but this is a minimal example that throws the index error.

```python
import numpy as np
import ants

img = np.zeros((3, 3))
img1 = img.copy()
img1[2, 2] = 1
img2 = img.copy()
img2[1, 1] = 1
img3 = img.copy()
img3[0, 1] = 1
image_list = [ants.from_numpy(x) for x in [img1, img2, img3]]
ants.build_template(image_list=image_list)
```

**Expected behavior**
An aligned and averaged template image as in the example:

```
image = ants.image_read( ants.get_ants_data('r16') )
image2 = ants.image_read( ants.get_ants_data('r27') )
image3 = ants.image_read( ants.get_ants_data('r85') )
timage = ants.build_template( image_list = ( image, image2, image3 ) ).resample_image( (45,45))
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: elementary OS 5.1.7 Hera, Built on Ubuntu 18:04.4 LTS. Linux 4.15.0-118-generic. GTK 3.22.30
 - Browser: Firefox
 - `antspy` version 0.2.5 installed directly from github.

**Additional context**
 In my testing I have always converted from processed `numpy` arrays to `ants` images. Perhaps this is causing the issue?

**Comment by stnava** [comment]
thanks for the reproducible example.  if you run:

```
ants.build_template(image_list=image_list,verbose=True)
```

you will get insight into the problem.

you might pad the images or something else to overcome this limitation.

**Comment by stnava** [comment]
error should read;

```
Exception caught: 
itk::ExceptionObject (0x7fb90c8499c0)
Location: "unknown" 
File: /Users/stnava/code/ANTsPy/itksource/Modules/Filtering/Smoothing/include/itkSmoothingRecursiveGaussianImageFilter.hxx
Line: 217
Description: itk::ERROR: SmoothingRecursiveGaussianImageFilter(0x7fb90c848750): The number of pixels along dimension 0 is less than 4. This filter requires a minimum of four pixels along the dimension to be processed.

```

**Comment by dakota-hawkins** [comment]
Interesting. The original images I was working with had a shape of (246, 512, 512) and still raised the error. When I set the dummy example dimensions to (5,5,5) the error is also still raised. Unfortunately, when I set `verbose=True`, I also just receive the same error message. Perhaps it's an installation issue on my end?

**Comment by stnava** [comment]
No error

```
import numpy as np
import ants

img = np.zeros((64, 64))
img1 = img.copy()
img1[2, 2] = 1
img2 = img.copy()
img2[1, 1] = 1
img3 = img.copy()
img3[0, 1] = 1
image_list = [ants.from_numpy(x) for x in [img1, img2, img3]]
ants.build_template(image_list=image_list)
```

the insight gained is that a registration that is expected to succeed --- is failing.  it could fail for different reasons with your real data.  e.g. if images are not standardized to have a minimum value of zero or something like that.

**Comment by dakota-hawkins** [comment]
Interesting. Your example also works on my machine. Thanks for the insight. I'll try different things and see if I can't figure it out. Since it appears to be an issue with my own data and not the function I'll close the issue. Thanks again for the help!
