### ISSUE TITLE
Example scripts or Jupyter notebook

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTsPy#224]
Dear experts of ANTsPy and ANTsPyNET,

I wonder if there are any script.py or Jupyter notebook examples/templates on brain extraction, registration, lesion filling, and segmentation. Alternatively, script.R or script.Rmd will work fine for me. 
Any helpful links and actual scripts/notebooks will be appreciated. 

Thank you,
Seongjin

**Comment by ntustison** [comment]
See the examples listed in the readme.md of the ANTsX/ANTs github repo.
