### ISSUE TITLE
ants (on linux) does not give a brain extracted. 

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTsPy#225]
#!/bin/bash

dirWORK=/media/sf_D_DRIVE/Temp_DATA/ANTs_Segmentation_test
dirMASK=/home/xubuntu/Desktop/ANTs_Templates/Kirby

scanlist ()
{
	echo "7TMS_049_09JUN2017"
}

for scancode in $(scanlist)

do
	cd ${dirWORK}/${scancode}
	echo ">>> Working in ${dirWORK} ..."
	#>>> Denoised MP2RAGE T1W #####
	input=USS-pre-denoized_T1W
	output=pre-T1W

	if [ ! -f ${scancode}-${output}-BrainExtractionBrain.nii.gz ]; then
	echo ">>> Working on ${scancode}-T1W_UNI ..."
	echo ">>> Extracting brain of ${scancode} ..." 
	time ${ANTSPATH}/antsBrainExtraction.sh \
				        -d 3 \
					-a ${scancode}-${input}.nii.gz \
					-e ${dirMASK}/S_template3.nii.gz \
					-m ${dirMASK}/S_template3_BrainCerebellumProbabilityMask.nii.gz \
					-o ${scancode}-${output}-
	elif [ -f ${scancode}-${output}-BrainExtractionBrain.nii.gz ]; then
		echo ">>> ${scancode}-T1W-BrainExtractionBrain.nii.gz already exists."
	fi
done

I used the script above for a test brain extraction using the installed ants on my Linux (Xubuntu 18.04 LTS). It appears to work except for the final results.  I see many intermediate files generated in the folder. However, there is no image named neither "7TMS_049_08JUN2016-pre-T1W-BrainExtractionBrain.nii.gz" nor "7TMS_049_08JUN2016-pre-T1W-BrainExtractionMask.nii.gz."

The ants (ver. 2.1, I guess) installed on my Linux has been working great for registration without any glitch in the processing. 

Could anyone point out where I should fix it in my script?

Thank you in advance,
Seongjin

**Comment by ntustison** [comment]
Here's the link to an example.

https://github.com/ntustison/antsBrainExtractionExample

make sure you can get it to work.

**Comment by s-j-choi** [comment]
I resolved the issue! 
Thank you for your help.

**Comment by zbjbiubiubiu** [comment]
Is it only ANTsR that provides the function of ’abpBrainExtraction‘? How is this function implemented in antspy?
