### ISSUE TITLE
effect of mask on diffeomorphic and affine registration 

### ISSUE THREAD

**Issue by asmaharry** [ANTsX/ANTsPy#226]
Hi,
I am doing the diffeomorphic and affine registration with the lesion mask. The results for diffeomorphic (SYNRA) registration with the lesion mask are good but for the affine registration the results are worst with the lesion mask but without lesion mask affine gives good results. 
My question is if I want to achieve the good results for the affine registration with the lesion mask, what should be optimization parameters (like number of iteration???)
what does parameter mask means  in ants.registration() function, is it a lesion mask or brain mask?

Thank you.

**Comment by ntustison** [comment]
Just run it in two steps.  Do an affine transformation without the mask and then use those results in a second call to ``ants.registration`` using "SyNOnly" with a mask.

**Comment by asmaharry** [comment]
Thank you for your reply. but what if I need both registrations separately, like if i want to see an affine registered image and diffeomorphic registered image. 
the term mask means lesion mask, am i right?

**Comment by ntustison** [comment]
> but what if I need both registrations separately, like if i want to see an affine registered image and diffeomorphic registered image.

I don't see how my suggestion affects this situation.  Apply the mask as you see fit based on performance. I was simply pointing out a strategy for separating the registration stages.  If you're not getting good results with a mask, it is unlikely that changing something like the number of iterations is going to be the key factor in improving results.  There's probably something more fundamental going on.

> the term mask means lesion mask, am i right?

The mask generically refers to any region in the image where the similarity metric is to be calculated.

**Comment by asmaharry** [comment]
Thank you, I got your point. 
What strategy one should use to choose the number of iterations for perfect registration especially for affine registration?

**Comment by ntustison** [comment]
> perfect registration

No such thing in real world scenarios.  What we do is formulate general use cases for the specified transforms available in ``ants.registration`` based on past experience.  You're unlikely to improve your results by deviating from those specified parameters unless your registration scenarios are completely different from what we've encountered in the past.

**Comment by asmaharry** [comment]
Thank you for the reply.
According to your suggestion "Just run it in two steps. Do an affine transformation without the mask and then use those results in a second call to ants.registration using "SyNOnly" with a mask."
I performed the two registrations separately (using ants.registration) and then concatenate these two transformations and apply it on the the image (using apply_transforms) , when i open the resultant image in ITK-SNAP it shows only a part of the image. Can you please tell me what is the problem and how i can fix this.
<img width="744" alt="snapshot0001" src="https://user-images.githubusercontent.com/61156349/99295657-f993ce80-2845-11eb-8dab-9ee4cccdf1a7.png">
Thank you.

**Comment by ntustison** [comment]
What were your command calls?

**Comment by asmaharry** [comment]
The Commands are
mytx1       = ants.registration(fixed_image, moving_image, type_of_transform = 'Affine', aff_metric='mattes', aff_iterations=(1000,500,250,125) )
mytx2       = ants.registration(fixed_image, moving_img, mask = lesionnMask, type_of_transform = 'SyNOnly', syn_metric='mattes', syn_iterations=(1000,500,250,125))

mytx = mytx1['fwdtransforms'] + mytx2['fwdtransforms']
mywarpedimage = ants.apply_transforms( fixed_image, moving_image, transformlist=mytx ,interpolator='nearestNeighbor')

Thank you.

**Comment by stnava** [comment]
you need to initialize the 2nd call with the output from the first

brian

**Comment by asmaharry** [comment]
mytx1 = ants.registration(fixed_image, moving_image, type_of_transform = 'Affine', aff_metric='mattes', aff_iterations=(1000,500,250,125) )
mytx2 = ants.registration(fixed_image, moving_img, mask = lesionnMask, type_of_transform = 'SyNOnly', initial_transform=mytx1, syn_metric='mattes', syn_iterations=(1000,500,250,125))
here in mytx2 command use initial_transform=mytx1, but it gives me error.
Description: itk::ERROR: CommandLineParser(0x5603b8de2a90): Incorrect command line specification. ['warpedmovout': ANTsImage (RAI)
and then not able to run apply_transforms function.
could you please help me in fixing this error.

**Comment by ntustison** [comment]
Did you consult the help?  You're specifying the entire registration call output from ``mytx1`` but that's not what the help menu indicates is required for the initial transform.

**Comment by stnava** [comment]
mytx2['fwdtransforms'][0]

brian

**Comment by asmaharry** [comment]
Thank yo so much, It works.
