### ISSUE TITLE
Accessing Cost Function for ANTsPy Registration

### ISSUE THREAD

**Issue by rohandivate** [ANTsX/ANTsPy#227]
Hi,
I am a research assistant using ANTs for research on brain image registration. 
I was wondering if it is possible to access the cost/loss function that ANTs uses to compute the registration. I want to try experimenting with a custom loss function and was wondering if there is a way to use a custom loss function in the ANTS registration algorithm.
It would really be helpful in my research.
Thanks.

**Comment by ntustison** [comment]
The similarity functions used by ants registration were developed by the ANTs team as part of work we did a few years back in overhauling the ITK image registration framework.  All metrics are derived from [this base class](https://itk.org/Doxygen/html/classitk_1_1ImageToImageMetricv4.html) so any customization should probably start there.

**Comment by rohandivate** [comment]
It looks like the class you mentioned is written in C++. I don't have much experience with C++ and I'm not sure how to start with defining a custom loss function. I looked through the ANTsPy source code and found a file called LOCAL_antsImageToImageMetric.cxx. Is that the file you were talking about in the previous post? I am just confused on how to begin. The custom loss function I want to make is a function that computes two image registrations and gives equal weight to each registration's loss to compute a combined transformation that I can apply to an image. Is there a feasible way to do this?
Thanks.

**Comment by ntustison** [comment]
Yes, ANTs is C++ underneath the Python layer.  You'd have to be comfortable with that C++ layer if you wanted to make any custom changes to ``ants.registration``.  However, it sounds like the customization you want is pretty simple and would be available from the command line call of the ANTs command (C++) ``antsRegistration``.  Limited multivariate capabilities are available through (Python) ``ants.registration``.  See (``help(ants.registration)`` ---> ``multivariate_extras``).

**Comment by rohandivate** [comment]
Thanks for your response. I have tried using the `multivariate_extras` argument in ants python registration and I want to understand if I am using it correctly. So, I have fixed image1, moving image1, fixed image2, and moving image2. I want the deformation to put different weights on the loss of each registration. If I want, for example, 0.25 weight on the registration between fixed1, moving1 and 0.75 weight on fixed2, moving2, would the correct python function call be 
`ants.registration(fixed=fixed1, moving=moving1, multivariate_extras=( ("Mattes", fixed2, moving2, 0.75, 0) ) )`?

**Comment by ntustison** [comment]
The weighting is simply normalized. So pairing 1 would have a weighting of 1 and if you wanted the second pairing to be 3 times the first, you should simply set it to 3. Normalization occurs internally.

**Comment by rohandivate** [comment]
Thanks. Also, I noticed that the antspy documentation mentions `multivariate_extras` only works with the `SynOnly` transform. Is there a way to make the multivariate_extras work with the `SyN` transformation? If not in antspy is there a way to use multivariate_extras with `SyN` on command line or antsR?

**Comment by ntustison** [comment]
Something like (cf ``antsRegistration --help``):

```
antsRegistration -d 3 \
  -o ${outputPrefix} \
  -v 1 \
  -t Rigid[0.15] \
    -m MI[${fixed},${moving},1,32,0.25] \
    -f 8x4x2 \
    -s 2x1x0 \
    -c 500x500x500 \
  -t Affine[0.15] \
    -m MI[${fixed},${moving},1,32,0.25] \
    -f 8x4x2 \
    -s 2x1x0 \
    -c 500x500x500 \
 -t SyN[0.15,3,0] \
    -m MI[${fixed},${moving},0.25,32,0.25] \
    -m CC[${fixed},${moving},0.75,4] \
    -f 4x2x1 \
    -s 2x1x0 \
    -c 70x40x5 
```

Note the double metric for the SyN registration stage.

**Comment by stnava** [comment]
thats right - you can do the same thing in ANTsR or ANTsPy via

tx1 = ants.registration( ... , "Affine" )
tx2 = ants.registration( ...., ..., multivariate_extras = ... ,
initial_transform = tx1['fwdtransforms'])

brian

**Comment by rohandivate** [comment]
I tried using the method in ANTsPy that you mentioned above but I am getting some confusing results. I have four images: fixed1, moving1, fixed2, and moving2. I ran the following registration commands:  
```
tx1 = ants.registration( fixed2, moving2 , "Affine" )
mytx = ants.registration(fixed1, moving1, multivariate_extras=( ("Mattes", fixed2, moving2, weight=10000, 32) ), initial_transform = tx1['fwdtransforms'] )
```
and 
`mytx = ants.registration(fixed2, moving2)
`
I then applied the transformation I got from both registrations to the `moving1` image. I expected to get very similar images from applying both transformations to `moving1` because I set the weight extremely high on `fixed2` and `moving2` in the first registration with `multivariate_extras` but the two images I got were vastly different. Is there something I am doing incorrectly?

**Comment by stnava** [comment]
yes - probably you are doing something wrong.  perhaps simplify your
example and/or rewrite it from scratch following the documentation closely
and making sure you understand existing examples eg

https://github.com/stnava/structuralFunctionalJointRegistration/blob/master/src/sfJointReg.py

brian

**Comment by rohandivate** [comment]
Hi, I've tried running the functions above again and doing simpler examples but it still isn't working for me.
I tried another experiment and ran the following: 
`mytx1 = ants.registration(fixed=fixed1, moving=moving1, multivariate_extras=( ("mattes", fixed2, moving2, 1000000000000000000000000000000000, 0) ))
`
and 
`mytx3 = ants.registration(fixed=fixed1, moving=moving1, multivariate_extras=( ("mattes", remove_both_fixed, remove_both_moving, 0.00000000000000000000000000000001, 0) ))
`
I made the weight extremely high for `fixed2` and `moving2` registration on one and really low on the other. When I apply the transformation I get from both on `moving1` the images I get are pretty similar for some reason according to irmse (around 4).

When I do normal registration:
```
ants.registration(fixed=fixed1, moving=moving1)
ants.registration(fixed=fixed2, moving=moving2)
```
and then apply the transforms I get from both registrations onto moving1, the two images I get are different (irmse about 77). Is there a reason why the multivariate extras are not producing transforms similar to the normal registrations? Do the images fixed1,moving1 and fixed2,moving2 have to be similar?

**Comment by stnava** [comment]
does the bold text below help at all?   

multivariate_extras : additional metrics for multi-metric registration
        list of additional images and metrics which will
        trigger the use of multiple metrics in the registration
        process in the deformable stage. Each multivariate metric needs 5
        entries: name of metric, fixed, moving, weight,
        samplingParam. the list of lists should be of the form ( (
        "nameOfMetric2", img, img, weight, metricParam ) ). Another
        example would be  ( ( "MeanSquares", f2, m2, 0.5, 0
          ), ( "CC", f2, m2, 0.5, 2 ) ) .  **This is only compatible
        with the SyNOnly transformation.**

**Comment by rohandivate** [comment]
Hi, I tried using your suggestion mentioned a couple posts above to get around the SyNOnly problem. I essentially tried using: 

```
tx1 = ants.registration(fixed, moving , type_of_transform="Affine" )
mytx = ants.registration(fixed, moving, initial_transform = tx1['fwdtransforms'], type_of_transform="SyNOnly")
```

This should produce the same transformation as the registration below right?

`mytx = ants.registration(fixed2, moving2, type_of_transform="SyN")
`

**Comment by stnava** [comment]
see https://github.com/ANTsX/ANTsPy/blob/master/tutorials/Multi-metric%20registration.ipynb  which I updated to include an affine initialization

and also https://github.com/ANTsX/ANTsRCore/blob/master/exec/lm.R 

data for the latter is https://github.com/ANTsX/ANTsRCore/tree/master/inst/extdata

**Comment by rohandivate** [comment]
Thanks for providing the example notebook I got the multivariate extras to work as intended. Thanks so much for your help!
