### ISSUE TITLE
3D U-Next Brain Extraction

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTsPy#228]
Dear ANTsPy/ANTsPyNet experts,

I ran the script below. The script was based on this link: https://github.com/neuronets/trained-models/releases. 
----
import nobrainer
import tensorflow as tf

model = tf.keras.models.load_model('/home/xubuntu/anaconda3/lib/python3.7/site-packages/nobrainer/models/trained-models/neuronets/brainy/0.1.0/brain-extraction-unet-128iso-model.h5')

And I got this warning message.
"
WARNING:tensorflow:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
"

Unfortunately, I have no idea how to do deal with it. 
Any help will be appreciated.

Thanks in advance,
Seongjin

**Comment by ntustison** [comment]
That's not our code.  If you want to use it through ANTsPyNet, you can view the help in ``antspynet.brain_extraction``.
