### ISSUE TITLE
Jupyter kernel keeps dying in the middle of process.

### ISSUE THREAD

**Issue by s-j-choi** [ANTsX/ANTsPy#229]
Dear ANTsPy/ANTsPyNet experts,

I am attempting brain extraction using ANTsPyNet. 
It works fine with the option 'modality = "t1".'
However, the kernel keeps dying whenever I attempted the option 'modality = "t1nobrainer".'  
![image](https://user-images.githubusercontent.com/8732330/99474983-95dbd500-291b-11eb-8f72-87ab8e97c603.png)

Further, it stops with an error message related to the morphological radius. I attempted the option 'modality = "t1combined." Its default value is 12 according to help. I understood as it will take 12 with no specifying it. However, it issued an error and stopped.

WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f4382d02680> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7f4382d02680> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

Any helpful advice will be appreciated.

Seongjin

**Comment by ntustison** [comment]
Probably running out of memory.  "t1nobrainer" is much more computationally intensive than "t1".  "t1combined" calls "t1nobrainer" so you're going to also run into the same problems there.

**Comment by s-j-choi** [comment]
Thanks for your suggestion. 
I will try it again with more memory.

**Comment by s-j-choi** [comment]
I tried it with more memory. The second option worked this time. 
However, the third option (i.e., t1combined) did not work. 
Its error message is different from one from the previously failed 2nd option (i.e., t1nobrainer). 
Do you have any suggestions?
![image](https://user-images.githubusercontent.com/8732330/99543097-c4d86200-2980-11eb-81b4-bf05b992e478.png)

**Comment by ntustison** [comment]
I just ran it and it finishes as expected.  I can't reproduce the error.  Make sure everything is up to date, including ANTsPy.

**Comment by s-j-choi** [comment]
Do you mean it should work on a system entirely relying on CPU? I use 4 cores and RAM over 40 GB, but no GPU support.

**Comment by ntustison** [comment]
Yes, most of the processing I do is on CPU-only platforms.

I have no idea why it's throwing that error.  It has to do with this [section of code](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/brain_extraction.py#L86-L88).  The morphological radius should be ``12`` by default and unless you specify ``"t1combined[X]`` where ``X`` is an integer, line 88 should never execute.  However, something seems to be wrong on your system where this isn't being read correctly.  Since I can't reproduce, you'll have to investigate on your own.

**Comment by s-j-choi** [comment]
Is there any restriction on the TensorFlow version?

**Comment by ntustison** [comment]
I believe it should be tensor flow >2.0. You should change your local file to print out the morphological radius just to make sure it's an actual number. More generally, though, you're going to need to debug it yourself. Fortunately, though, it looks petty straightforward.

**Comment by s-j-choi** [comment]
I used the same Anaconda3 env for Python 3.7 with ANTsRNet. It worked with an increased RAM of 58GB. It uses the same Python installation configured for ANTsPyNet. This was not what I expected at all. I thought ANTsPyNet should work better ANTsRNet. However, in my case, ANTsRNet works and completes the task (DTK segmentation and other t1combined Brain Extraction) while ANTsPyNet stops with an error message. At least, ANTsRNet works and I can do what wanted to do, but it still bugs me.

**Comment by ntustison** [comment]
> I used the same Anaconda3 env for Python 3.7 with ANTsRNet

My set-up is the same on multiple Macs.

>  I expected that ANTsPyNet should work better than ANTsRNet since it does not use "reticulate" to utilize Python-TensorFlow-Keras under the hood.

This has been my experience.

**Comment by s-j-choi** [comment]
Just a question from a hunch. I noticed a slight difference in ANTsPy versions between MacOS and Linux.

![image](https://user-images.githubusercontent.com/8732330/100145930-142dff00-2e67-11eb-9d39-8642bde619a2.png)

The ANTsPy Version for MacOS is 0.1.8, while the version for Linux is 0.2.0. As far as I understand, ANTsPyNet requires ANTsPy. Your Python env is on Mac and mine is on Linux (Xubuntu 18.04 LTS). So both systems do not have the same ANTsPy versions installed. I just want to try if it works or not with version 0.1.8 for my Linux. Would it work replacing 0.1.8 for 0.2.0 to install ANTsPy version 0.1.8. on Liunux? If not, could you guide me on how to install version 0.1.8?

Many thanks.

**Comment by ntustison** [comment]
ANTsPyNet does require ANTsPy (just as ANTsRNet requires ANTsR).   But all configurations (both on my Mac and on my university's Linux cluster) are kept up to date with the latest clone from all GitHub repositories.

**Comment by s-j-choi** [comment]
Thanks for your clarification.

**Comment by s-j-choi** [comment]
Thanks for your clarification.
