### ISSUE TITLE
Canny overlay is not visualized

### ISSUE THREAD

**Issue by leonardocerliani** [ANTsX/ANTsPy#230]
I tried to overlay the edges of the sample image `r16` with `ants.plot` but it didn't work, although the edges were correctly detected

```
import ants

img = ants.image_read(ants.get_ants_data('r16'))
img2 = ants.iMath(img, 'Canny', 1, 5, 12)
ants.plot(img2)
ants.plot(img, img2, overlay_cmap='autumn')
```

It looks like it has to do with either the definition of the colormap, or some thresholding applied to the overlay before visualization. For instance this kinda works:
```
from matplotlib import colors
cmap = colors.ListedColormap(['red'])

img2_smooth = ants.smooth_image(img2,0.1)
ants.plot(img, img2_smooth, overlay_cmap='autumn',figsize=4)
ants.plot(img, img2_smooth, overlay_cmap=cmap,figsize=4)
```

Thanks a lot in advance for your help!

leonardo

**Environment**
- python 3.7
- linux ubuntu 18.04
- colab notebook with remote kernel

**Comment by ntustison** [comment]
Thanks for providing a easy-to-reproduce example.  Are you up-to-date on the latest ANTsPy repo?  When I run the first section of code, I get the following:

![Screen Shot 2020-11-19 at 8 14 59 AM](https://user-images.githubusercontent.com/324811/99692825-953c5f00-2a3f-11eb-85c2-5695b2c8faac.png)

**Comment by leonardocerliani** [comment]
Hi Nick,

I used the `pip install antspyx` since the compilation from the git did not succeed (the module could not be imported because some ants core binaries were missing).

Anyway, for the moment I will use the workaround. 

P.S. sorry, I should have put some screenshots. Here they are:

```
import ants

img = ants.image_read(ants.get_ants_data('r16'))
img2 = ants.iMath(img, 'Canny', 1, 5, 12)
ants.plot(img2)
```
![1](https://user-images.githubusercontent.com/1486312/99761486-849af000-2af6-11eb-9b3a-f9e05b142c83.png)

`ants.plot(img, img2, overlay_cmap='autumn')`
![2](https://user-images.githubusercontent.com/1486312/99761496-89f83a80-2af6-11eb-8100-cedb8561c813.png)

```
from matplotlib import colors
cmap = colors.ListedColormap(['red'])

img2_smooth = ants.iMath(img, 'Canny', 1, 5, 12).smooth_image(0.01)
ants.plot(img, img2_smooth, overlay_cmap='autumn',figsize=4)
```
![3](https://user-images.githubusercontent.com/1486312/99761521-95e3fc80-2af6-11eb-8737-eab92dec20a9.png)

`ants.plot(img, img2_smooth, overlay_cmap=cmap,figsize=4)`
![4](https://user-images.githubusercontent.com/1486312/99761538-a09e9180-2af6-11eb-9f0b-62e77f368eb6.png)

**Comment by ntustison** [comment]
> I used the pip install antspyx since the compilation from the git did not succeed (the module could not be imported because some ants core binaries were missing).

This is unfortunate because there have been quite a few bug fixes and feature additions.  It might be worth it to figure that out.
