### ISSUE TITLE
Understanding "spacing" attribute of ANTsImage Object

### ISSUE THREAD

**Issue by J-Yash** [ANTsX/ANTsPy#233]
Hi, I am confused about what exactly the "spacing" attribute in an ANTsImage object means? Is it used for defining the unit measurement of one voxel when data is converted from a geometric format like stl to voxelized format like nifti?

**Comment by ntustison** [comment]
Ants was developed for medical images which require a precise representation of sampled geometry. That's why ants images have associated information such as voxel spacing and orientation which your everyday web JPEG won't have.
