### ISSUE TITLE
`apply_transform` output is different from mytx['fwdtransforms'] when using ants.registration.

### ISSUE THREAD

**Issue by veritas9872** [ANTsX/ANTsPy#234]
**Describe the bug**
I am currently using ANTsPy and trying out SyN registration.
However, I am in a situation where I must use the same registration map on many different images.
To be precise, I need to send coordinates from the moving image to coordinates in the fixed image.
To verify that `apply_transform` gave the same outputs as `ants.registration`, 
I compared the numpy array values for the two ANTs images `mytx['fwdtransforms']` and `myWarpedImage `, 
where `myWarpedImage = ants.apply_transforms(fixed=fixed, moving=moving, transformlist=fwdtransforms)`.

However, I find that the two images have different values, at least when measured by their view arrays.
Moreover, this does occur when the same image is registered to itself but only when one image is registered to a different image.

This is not what I expected after seeing the [registration tutorial](https://notebook.community/ANTsX/ANTsPy/tutorials/10minTutorial), which led me to expect that `apply_transform` would give the same result as `mywarpedImage `.

**To Reproduce**

`fixed = ants.from_numpy(fixed.astype(np.float32), spacing=fixed_spacing)
moving = ants.from_numpy(moving.astype(np.float32), spacing=moving_spacing)
mytx = ants.registration(fixed=fixed, moving=moving,
                             type_of_transform=type_of_transform)
fwdtransforms = mytx['fwdtransforms']
myWarpedImage = ants.apply_transforms(
        fixed=fixed, moving=moving, transformlist=fwdtransforms)
check = np.all(myWarpedImage.view() == mytx['warpedmovout'].view())
out = 'Success' if check > 0 else 'Fail'
print(f'Algorithm Forward Check: ', out)`

**Expected behavior**
The output should be "Success" but gives "Fail".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu18 Docker
 - Version: antspyx 0.2.5

**Additional context**

"SyN" is a non-affine transform and gives a .nii.gz file as well as a .mat file. This may have something to do with the problem. I have found that I cannot use `read_transform` on the `.nii.gz` file created by `registration`.

**Comment by ntustison** [comment]
Please provide an easy-to-reproduce example with input images.  For example, a possibility includes a 2-D fixed/moving image pair with an additional image in the space of the moving image that doesn't get warped properly.

**Comment by veritas9872** [comment]
@ntustison Thank you for your reply.

I think that setting `fixed=np.random.rand(324, 512, 512), moving=np.random.rand(354, 512, 512), fixed_spacing=(1, 0.6495, 0.6495), moving=(1, 0.8967, 0.8967)` may work. 

My apologies for not being able to provide a better example, but I am currently using private CT data.

Also, I have confirmed that `ants.read_transform` will not work on `.nii.gz` files.

**Comment by stnava** [comment]
* `read_transform` is for transform files i.e.   mat and txt 
* `read_image` is for nii.gz files
* a reproducible example:

```
fi=ants.image_read( ants.get_data( "r16" ))
mi=ants.image_read( ants.get_data( "r64" ))
reg=ants.registration(fi,mi,'SyN')
w1=reg['warpedmovout']
w2=ants.apply_transforms(fi,mi,reg['fwdtransforms'])
 w1.mean()
# 47.718834
w2.mean()
# 47.718834
w1.std()
# 79.931145
w2.std()
# 79.931145
```

shows the results are the same.

**Comment by veritas9872** [comment]
@stnava Thank you for your help.
Is there a way to load the `.nii.gz` file as a transform?

**Comment by stnava** [comment]
`help( ants.transform_from_displacement_field )`
