### ISSUE TITLE
Issue with ants.threshold_image not returning binary mask

### ISSUE THREAD

**Issue by dpedrosac** [ANTsX/ANTsPy#236]
When using ants.threshold_image on a probability mask, it only returns a matrix of 1's for every voxel, although the probabilities are scalar and at a range between (0,1). 

Here you can find the file:

https://www.jottacloud.com/s/089bdc2a071a1e74be1b80e54168c432c72

And this code is what I would expect to result in a binary mask:

`mask = ants.threshold_image(probability_mask, 0.5, 1, 1, 0)`

What am I missing?
Best, 

David

**Comment by ntustison** [comment]
It works as expected for me.

```
>>> import ants
>>> probability_mask = ants.image_read("probabilities.nii")
>>> mask = ants.threshold_image(probability_mask, 0.5, 1, 1, 0)
>>> ants.plot(probability_mask, mask )
>>> ants.image_write(mask, "mask.nii.gz")
```

<img width="1080" alt="Screen Shot 2020-11-26 at 3 43 54 PM" src="https://user-images.githubusercontent.com/324811/100397387-3c9c3180-2ffe-11eb-84f6-a5a872b227d2.png">

**Comment by dpedrosac** [comment]
Thanks for the quick reply!

That's weird. Here is my output:

![Bildschirmfoto von 2020-11-27 08-25-15](https://user-images.githubusercontent.com/46906261/100422309-5d11cd80-308a-11eb-993e-ec464e1cbff0.png)

I'm using linux (Ubuntu 20.04) and the newest version of ants (repository directly from github). The code doesn't break as "masking" just multiplies everything by 1 but some of the ants functions do obviously not work (e.g. brain extraction). Any ideas where to start searching for the problem? I looked at the way threshold_image works but after seeing your results and given the fact that all these functions have not been changed for a long time, I get a hunch that it is related to my system.

**Comment by ntustison** [comment]
> I'm using linux (Ubuntu 20.04) and the newest version of ants (repository directly from github).

Just to clarify, did you install the newest version of [ANTs](https://github.com/ANTsX/ANTs) or [ANTsPy](https://github.com/ANTsX/ANTsPy) directly from GitHub?

**Comment by dpedrosac** [comment]
I installed ANTsPy from GitHub using 

git clone https://github.com/ANTsX/ANTsPy
and so on ...

**Comment by ntustison** [comment]
Then that's a tough one because I use ANTsPy (and the ``threshold_image`` function) on multiple computers (Linux and MacOS) and haven't ever encountered this problem.  And I've never seen anybody else report this problem, either.  Perhaps try to install on a different computer and see if you encounter the same problem.

**Comment by dpedrosac** [comment]
Alright, so it only happens only on my machine. I have no clue what can possibly go wrong on a boolean operation but a manual workaround does the job. Thanks for the help

**Comment by ntustison** [comment]
``ants.threshold_image`` actually calls the ANTs ``ThresholdImage`` function.  You might want to see if the other ANTs-based functions work and whether or not the stand-alone ``ThresholdImage`` program works on that system.

**Comment by dpedrosac** [comment]
Right now it’s just that function which is not overly dramatic as I can easily code a workaround. Everything else works fine, although I’m well aware that this is a very common function which may be included in other routines so that there is a risk of wrong results on that system. 

What do you mean by stand-alone `ThresholdImage`? The C++ Code? I must admit I’m not very skilled aside from Python and Matlab. May I ask for a quick help?

**Comment by ntustison** [comment]
I was just pointing out the location of where you might investigate this issue. But if you're not comfortable with C++ then you might want to pursue other options.
