### ISSUE TITLE
Behavior N4Biasfieldcorrection

### ISSUE THREAD

**Issue by Alxaline** [ANTsX/ANTsPy#239]
I have a behavior which is strange using N4Biasfieldcorrection on a brain with skull. 
As mentionned in another post, i check range of image intensities and rescale to the range [10, 100] then unscaled.. 
1) First case: default parameters and brain with skull. Results show hole in brain. (attached result), range seems to affect result
2) Same brain but skull-stripped. Results seems OK (attached result) 
3) First case but using ANTs in command line linux. Result is OK

Use of last version of ANTspy from source.

![Screenshot from 2020-12-02 20-17-27](https://user-images.githubusercontent.com/43764304/100920481-788e3580-34db-11eb-9782-704c6c8b1207.png)
![Screenshot from 2020-12-02 20-17-39](https://user-images.githubusercontent.com/43764304/100920498-7d52e980-34db-11eb-9c76-f74988e15271.png)

```
import numpy as np
import ants
from typing import Tuple

def _min_max_scaling(image: np.ndarray, scaling_range: Tuple[int, int] = (10, 100)) -> Tuple[np.ndarray, float, float]:
    image_scaled = np.copy(image).astype(np.float32)
    min_ = (scaling_range[0] - np.min(image)).astype(np.float32)
    scale_ = ((scaling_range[1] - scaling_range[0]) / (np.max(image) - np.min(image))).astype(np.float32)
    image_scaled *= scale_
    image_scaled += min_
    print(np.min(image_scaled))
    return image_scaled, min_, scale_

def _invert_min_max_scaling(image_scaled: np.ndarray, scale_: float, min_: float) -> np.ndarray:
    image_scaled -= min_
    image_scaled /= scale_
    return image_scaled

image = ants.image_read("sample_t1.nii.gz", reorient=True)
image_scaled, min_, scale_ = _min_max_scaling(image.numpy())
image = image.new_image_like(image_scaled)
img_n4 = ants.n4_bias_field_correction(image, verbose=True)

image_unscaled = _invert_min_max_scaling(img_n4.numpy(), scale_, min_)
img_n4 = image.new_image_like(image_unscaled)
ants.image_write(img_n4, "sample_t1_n4.nii.gz")
```

**Comment by ntustison** [comment]
The default parameters are different between the two interfaces.  In ANTsPy, if no mask is specified then a mask gets made using ``ANTsPy::get_mask``.  In the ANTs version, a mask equally weighting the entire image is supplied.

**Comment by Alxaline** [comment]
Ok thanks @ntustison. To be sure, specified a mask equal to the shape of the image will result in the same behavior as expected in ANTs?

**Comment by ntustison** [comment]
Perhaps not identical but closer to ANTs.  You might want to set ``verbose=True`` to verify identical parameters.

**Comment by Alxaline** [comment]
I see this parameters differs using verbose:
ANTS
```
 Convergence threshold: 0
 Number of control points: [4, 4, 4]

         LargestPossibleRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [11, 11, 11]
         BufferedRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [11, 11, 11]
         RequestedRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [11, 11, 11]
         Spacing: [29.7688, 29.7688, 21]
         Origin: [-29.7688, -29.7688, -21]


```

ANTsPy
```
Convergence threshold: 1e-07
Number of control points: [5, 5, 4]
         LargestPossibleRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [19, 19, 11]
         BufferedRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [19, 19, 11]
         RequestedRegion: 
           Dimension: 3
           Index: [0, 0, 0]
           Size: [19, 19, 11]
         Spacing: [24.8464, 24.8464, 24]
         Origin: [-24.8464, 24.8464, -24]

```
what is the number of control points and largest possible regions?

**Comment by ntustison** [comment]
They're related in that the user-specified number of control points (or spline distance) dictates the regional information for the control point grid.  ANTsPy uses 200 mm spline distance as the default parameter whereas ANTs uses a control point grid of 4x... (however many dimensions).

> Second i see that the rescaling range influence a lot the ouput image? ie [10, 100], or [10, 1000] produces very different result

Yes, because there's no constraint on the output intensity range.

**Comment by Alxaline** [comment]
Ok, I had just figured it out about the spline distance. But thanks for the clarification.

In such a case, how to choose a right scaling range so as not to alter the expected result of the bias field correction?

**Comment by ntustison** [comment]
There is no 'right" scaling range just as there is no absolute intensity range in MRI. Just make sure the range is greater than at least 1 as the intensities are log transformed.

**Comment by Alxaline** [comment]
Thank you @ntustison
