### ISSUE TITLE
Not clear about values stored in mytx['fwdtransforms']

### ISSUE THREAD

**Issue by soanduong** [ANTsX/ANTsPy#241]
Thanks for the excellent work. I really enjoy registering image using ANTsPy.

However, I would like to get more understand about values stored in `mytx['fwdtransforms']`. I have seen that there are a dict in `mytx['fwdtransforms'`] with:
- `AffineTransform_float_3_3`: 12 values
- `fixed`: 3 values

Could you please give more information about the values stored in the dict, e.g:
- Is `AffineTransform_float_3_3` the affine transformation matrix or parameters to form the affine transformation matrix?
- What are values in `fixed` mean?
- How to form the affine transformation matrix from the dict?

Thank you very much.

**Comment by ntustison** [comment]
https://itk.org/Doxygen/html/classitk_1_1AffineTransform.html

**Comment by soanduong** [comment]
> https://itk.org/Doxygen/html/classitk_1_1AffineTransform.html

Thanks for your information.

**Comment by soanduong** [comment]
FYI, I found the solution on https://sourceforge.net/p/advants/discussion/840261/thread/9fbbaab7/?fbclid=IwAR1SxkuDTEqeYWP9WhUzqE6aL8huIQagKZptiJrgLCNL2j5L6m15f4oSq5E.
Especially the MATLAB function `ea_antsmat2mat` in https://github.com/netstim/leaddbs/blob/master/helpers/ea_antsmat2mat.m.
