### ISSUE TITLE
ANTsPy registration SyNRA faster than command line antsRegistrationSyNQuick.sh

### ISSUE THREAD

**Issue by tommydino93** [ANTsX/ANTsPy#242]
**Describe the bug**
I noticed that when performing a registration with the ANTsPy, and then performing it from command line with antsRegistrationSyNQuick.sh, the second one takes longer, which makes me assume that it is also more accurate. I would like to use ANTsPy, but my pipeline is very registration-dependent so I have to ensure that I have (approximately) the same accuracy of antsRegistrationSyNQuick.sh

**To Reproduce**
The command line pseudo-code I use is:

`antsRegistrationSyNQuick.sh -m T1_atlas_path -f path/to/struct/file.nii.gz -t s -o /path/to/out/folder/out_MNI_2_struct_`

The ANTsPy psuedo-code I use is:

```
ants.registration(moving=ants.image_read(T1_atlas_path),
                           fixed=ants.image_read(path/to/struct/file.nii.gz),
                           type_of_transform="SyNRA",
                           outprefix=/path/to/out/folder/out_MNI_2_struct_
                           )
```
            
**Expected behavior**
I would expect that the two registrations take the same time because in both I specify as transform **Rigid + Affine + Deformable**

**Desktop (please complete the following information):**
 - OS: Ubuntu xenial 
 - Version: 16.04.7

**Comment by ntustison** [comment]
>  I would expect that the two registrations take the same time because in both I specify as transform Rigid + Affine + Deformable

Not the case as the parameters for ``antsRegistrationSyNQuick`` are not the same as ``SyNRA``.  See the help for ``ants.registration``---in fact, you should see an option for "antsRegistrationSyNQuick" in ``type_of_transform``.

**Comment by tommydino93** [comment]
Hi @ntustison !
Thanks for your reply. Actually, I tried the following python code, and it doesn't work:

`import ants`
`ants.registration(fixed=ants.image_read("path_to_atlas"),
                            moving=ants.image_read("path_to_structural_volume"),
                            type_of_transform="SynQuick",
                            outprefix="/home/newuser/Desktop/out_MNI_2_struct_")`

and I get the error:

raise ValueError("`type_of_transform` does not exist")
ValueError: `type_of_transform` does not exist

And indeed when I look in the [documentation](https://antspy.readthedocs.io/en/latest/registration.html), there is no SynQuick

Am I missing something?

**Comment by ntustison** [comment]
> Am I missing something?

Yes.  It's [there](https://github.com/ANTsX/ANTsPy/blob/master/ants/registration/interface.py#L188-L189) if you compile from source.

**Comment by tommydino93** [comment]
Indeed! Thank you very much ;)
