### ISSUE TITLE
Voxel-wise loss function weighting

### ISSUE THREAD

**Issue by andy-s-ding** [ANTsX/ANTsPy#244]
Hi all,

I am currently trying to register high resolution CT datasets in which the fixed dataset has been meticulously segmented (the moving dataset is not segmented). Currently, I do not see an easy way of prioritizing the quality of the registration around the region of certain segments.

I know that you can provide a mask for SyN registration, but it seems like an "all-or-nothing" kind of approach to what I am looking for.

Is it possible to add a feature in which the loss function of the registration at each voxel can be multiplied by a weight matrix of the same dimension as the dataset? Basically for each voxel, the loss function at that voxel would be multiplied by some weight.

Please let me know if there are existing features that could potentially help with this issue. Thank you!

**Comment by gdevenyi** [comment]
You could try using your segmentation + the other image as a secondary image-pair for the registration. If the segmentation has structure to it, it could provide some weight to the registration.

**Comment by andy-s-ding** [comment]
> You could try using your segmentation + the other image as a secondary image-pair for the registration. If the segmentation has structure to it, it could provide some weight to the registration.

Hi gdevenyi, thank you for your response. The segmentation definitely does have structure to it. So if I have a moving .nrrd file with its corresponding .seg.nrrd segmentation file, and I am trying to do a SyN registration onto a fixed .nrrd file, what would the commands look like to implement your suggestion of a secondary image-pair for the registration?

**Comment by gdevenyi** [comment]
I'm not a ANTsPy user, but rather an ANTs user, so I'm not sure of the *specific* usage here, but it looks like the "multivariate_extras" option is what you need to figure out. https://antspyx.readthedocs.io/en/latest/registration.html#ants.registration

**Comment by stnava** [comment]
probably addressed by https://github.com/ANTsX/ANTsPy/blob/master/tutorials/Multi-metric%20registration.ipynb ... please re-open or open a new issue if not.
