### ISSUE TITLE
Understanding Mutual Information

### ISSUE THREAD

**Issue by J-Yash** [ANTsX/ANTsPy#245]
I am using ants.image_mutual_information(fi, mi) to calculate the MI between two images, and it gives me a negative scalar value. I am trying to understand if lower values mean more similar images? Or higher values mean more similar images? 

Also, does ANTsPy provide a method to calculate Normalized Mutual Information?

**Comment by stnava** [comment]
```
fi = ants.image_read( ants.get_ants_data('r16') ).clone('float')
mi = ants.image_read( ants.get_ants_data('r27') ).clone('float')
ants.image_mutual_information(fi, mi)
ants.image_mutual_information(fi, fi) 
```

lower is better
