### ISSUE TITLE
Support reading from buffers or file-like objects

### ISSUE THREAD

**Issue by zachmullen** [ANTsX/ANTsPy#246]
**Is your feature request related to a problem? Please describe.**

It appears that the only way to read and write images in this library is via filesystem paths. I have a case in a microservice architecture where I don't have files on a filesystem, but rather streams or in-memory buffers representing images that I'd like to run Ants on.

**Describe the solution you'd like**

I'd like alternative methods to `image_read` and `image_write` that would support passing in `bytes`, or else a seekable file-like object. If metadata such as file extension is required for the operation of this library, that information can be passed into these methods by the caller.

**Describe alternatives you've considered**

My workaround is to write the file to disk as a tempfile. This works in my current environment, but certain deployment environments don't even support writing files to the filesystem. It would be nice to have an in-memory only option.

**Comment by ntustison** [comment]
Does simpleITK have similar functionality?

**Comment by zachmullen** [comment]
@thewtex do you know the answer re: simpleITK?

**Comment by thewtex** [comment]
SimpleITK does not support this.

To achieve this, use the ITK Python wrapping, xarray, zarr.

1. Convert to Zarr.

`itk.imread` -> `itk.xarray_from_image` -> xarray DataArray to xarray DataSet -> DataSet [.to_zarr](http://xarray.pydata.org/en/stable/generated/xarray.Dataset.to_zarr.html)

2. Host the default filesystem store output on whatever network storage you would like. On an HTTP server, use [fsspec](https://filesystem-spec.readthedocs.io/en/latest/) for HTTP-based hosting, or [AWS S3, GCS, ...](https://zarr.readthedocs.io/en/stable/tutorial.html?highlight=s3#distributed-cloud-storage).

3. Reverse the process: [xarray open_zarr](http://xarray.pydata.org/en/stable/generated/xarray.open_zarr.html) -> get DataArray in DataSet -> `itk.image_from_xarray` -> ANTsPy

**Comment by ntustison** [comment]
That's great to know, @thewtex .  Thanks.
