### ISSUE TITLE
How to get morphed coordinates?

### ISSUE THREAD

**Issue by mariakesa** [ANTsX/ANTsPy#247]
Hello,

I have a question. After I morph an image onto another image, how can I apply the morphing transform to an array of positions (x,y) that represent landmarks or other features of data (for example in my case, cell coordinates)?

Thanks so much!
Maria

**Comment by ntustison** [comment]
``ants.apply_transforms_to_points``

**Comment by mariakesa** [comment]
Great, thanks so much!!
