### ISSUE TITLE
image pixel labels changing post registration

### ISSUE THREAD

**Issue by dmnburrows** [ANTsX/ANTsPy#248]
Hi there,

I'm having some issues with pixel label values changing (I think due to interpolation) after applying a transformation - I ideally need the pixel labels values to stay the same after rigid and non-linear registrations. 

here's my workflow:

1. register 2 images together - fixed = zbb, moving = f5

f5_rigid = ants.registration(zbb, f5, type_of_transform = 'Rigid') 

2. generate label image - this image matches my f5 ants_image but with each pixel entry having a integer label value

3. apply the above warping to my atlas labels image (labelimg)

labelimg_trans = ants.apply_transforms(zbb, labelimg, f5_rigid['fwdtransforms'])

When I use default interpolation method the transform correctly warps the labelimg, however the pixel intensities are changed so they are no longer integers and I can't map them back to their distinct labels.

I've tried using genericLabel or multiLabel interpolation methods but they both methods provide poor matching to my fixed image and also reduce down the number of labels.

Is there some way of retaining my exact labels from before?

Thanks!

**Comment by ntustison** [comment]
Have you tried

``interpolator = "nearestNeighbor``

?

**Comment by dmnburrows** [comment]
This has solved it, thanks!
