### ISSUE TITLE
Registering images that are very misaligned

### ISSUE THREAD

**Issue by evanmy** [ANTsX/ANTsPy#250]
Hi, 

I have been working with ants.registration to affine register two MRI images. For example, It works very well if the moving imagine is transformed by a small degrees. But it fails if the moving image is very misaligned. For example 90+ degree rotation on random axis. Can ants recover large degree of misalignment? Thank you for your time.

**Comment by stnava** [comment]
it can be done but not with these types of gradient based methods. we provide  `help( ants.affine_initializer )` to overcome large differences in initialization.  we also have feature detection methods that are faster but these are currently only available in R.

**Comment by evanmy** [comment]
If I understand correctly, I use `affine_initializer` to have a rough alignment first then apply `ants.registration`?

**Comment by stnava** [comment]
yes - @cookpa may have some recommendations for how to set parameter or just refer to how it is used in the script https://github.com/ANTsX/ANTs/blob/682939639093ac595c0849b9767bc50277dc2638/Scripts/antsBrainExtraction.sh#L464-L471

**Comment by evanmy** [comment]
Thank you!

**Comment by cookpa** [comment]
Hi,

This should probably be a Wiki article but here's some quick thoughts. 

The example call linked above is

```
          exe_initial_align="${ANTSPATH}/antsAI -d ${DIMENSION} -v 1"
          exe_initial_align="${exe_initial_align} -m Mattes[ ${EXTRACTION_INITIAL_AFFINE_FIXED},${EXTRACTION_INITIAL_AFFINE_MOVING},32,Regular,0.2 ]"
          exe_initial_align="${exe_initial_align} -t Affine[ 0.1 ]"
          exe_initial_align="${exe_initial_align} -s [ 20,0.12 ]"
          exe_initial_align="${exe_initial_align} -g [ 40,0x40x40 ]"
          exe_initial_align="${exe_initial_align} -p 0"
          exe_initial_align="${exe_initial_align} -c 10"
          exe_initial_align="${exe_initial_align} -o ${EXTRACTION_INITIAL_AFFINE}"
```

This starts from a center of mass (COM) alignment of the two images, and searches rotations and translations about that starting point. 

The rotations are described by the `-s` parameter. The first parameter is the spacing between sample points, in degrees. The second is an arc parameter, between 0 and 1, where we search +/- (180 * arc) along the three principal axes of the fixed space.

In the above, 180 * 0.12 = 21.6, so for each axis, we start the search at -21.6, (-21.6 + 20 = -1.6), (-1.6 + 20 = 18.4) degrees rotation.

The `-g`parameter controls translation. I'm not sure if this is implemented in antspy as it was a later addition. This moves the moving image in a grid centered on the COM alignment. The first parameter is the step size in mm, and the second is a grid describing the maximum extent of the search. The default here searches (-40, 0, 40) mm in y and z. It doesn't search x to save time and I've found that left-right alignment is usually closer in human brain structural MRI.

All this adds up to a grid.

for z rotation in range (-arc, step, +arc) 
  for y rotation in range (-arc, step, +arc) 
    for x rotation in range (-arc, step, +arc) 
      for z translation in range (-bound, step, +bound) 
        for y rotation in range (-bound, step, +bound) 
          for x rotation in range (-bound, step, +bound)
            1. Translate and rotate moving image to start point
            2. Do a quick registration
            3. Assess image similarity
          done
        done
      done
    done
  done
done  
          
This can add up to a lot of start points! Unfortunately I've not been able to add a progress indicator to this program, though I think there's a way to do it.

You can break up the grid by searching rotation and translation separately, but this risks not finding the right combination of rotation and translation that works. If you have a prior that one or the other is more important, you can adjust the bounds accordingly so you search fewer rotations or translations.

You should definitely downsample the images first so this happens in a reasonable time. I think in the ANTs script we use 4mm, but you might get away with 5 or 6mm. You can also try reducing iterations `-c` from 10 to 5. I've not done rigorous experiments on Affine vs Rigid transformations but I've generally found affine works better. Nothing is foolproof and occasionally a weird combination of large rotation and scaling comes out best on the metric. But it gets a good starting point in the majority of data I've seen.

**Comment by evanmy** [comment]
Thank you Philip for the detailed explanation! I will definitely try your setup
