### ISSUE TITLE
Issue with antspy jointlabelfusion

### ISSUE THREAD

**Issue by RakNiaz** [ANTsX/ANTsPy#251]
I registered 10 T1 weighted images to a reference T1 weighted image, and used the obtained deformations to warp the gray matter labels of each individual to the reference space. Then used joint_label_fusion in antspy to create the gray matter labels for the reference image. But the labels in the output of joint_label_fusion seem to have changed the sequence. 

There were 84 gray matter labels in each of the warped images. But the output of joint label fusion has 83 labels and they seem to have changed sequences. The labels start from 8 and are not in arithmetic sequence. It can be seen in the example images below, label 8 (the first label) in one of the warped images is 0 (clear label) in the output of joint label fusion, and label 10 in the warped images is label 8 in the output of joint label fusion. Label 2035 (the last label) in the warped images is not present in the output of joint label fusion.

Your advice on why this is happening and how it can be solved would be highly appreciated.

Best,
Niaz

<img width="450" alt="Screen Shot 2021-02-02 at 5 10 46 PM" src="https://user-images.githubusercontent.com/78449282/106675627-0f7a7b00-657b-11eb-89e2-ab0d0571c91c.png">
<img width="511" alt="Screen Shot 2021-02-02 at 5 10 52 PM" src="https://user-images.githubusercontent.com/78449282/106675629-10131180-657b-11eb-8f23-7501f648c9fe.png">

**Comment by stnava** [comment]
a bug in an old version.  install from source.   assume you used pip for
this.

brian

**Comment by stnava** [comment]
updated PyPI versions of ants -- so a new pip install is likely to fix this.
