### ISSUE TITLE
Perform registration on two pairs simultaneously

### ISSUE THREAD

**Issue by braincharter** [ANTsX/ANTsPy#252]
**Is your feature request related to a problem? Please describe.**
I was wondering if it was possible to perform registration on two pairs of images simultaneously. For example, in ants, I used both the whole image and vascular features to perform a robust registration:

```
antsRegistration -d 3 -n Linear  \
        -t SyN[0.1,3,0] -c [30x15x1x0,1e-7,10] -f 8x4x2x1 -s 2x1x1x1 -u 1 -z 1 -l 1 \
        -m CC[T1_f.nii, T1_m.nii , 0.9, 32, Regular, 0.25] \
        -m CC[T1_f_veins.nii,   T1_m_veins.nii ,  0.1, 32, Regular, 0.25] \
        -o [T1f_2_T1m, T1f_2_T1m.nii ]
```

**Describe the solution you'd like**
I would like to translate this to its equivalent in ANTsPy, but it seems to be limited to presets.
I saw that in ANTsR there is something equivalent to what I aim to achieve:

> multivariateExtras | list of additional images and metrics which will trigger the use of multiple metrics in the registration process in the deformable stage. Multivariate metrics needs 5 entries: name of metric, fixed, moving, weight, samplingParam. the list should be of the form list( list( "nameOfMetric2", img, img, weight, metricParam ) ) . Another example would be list( list( "MeanSquares", f2, m2, 0.5, 0 ), list( "CC", f2, m2, 0.5, 2 ) ) . This is only compatible with the SyNOnly or ElasticOnly transformation.

However this argument does not seem to be present in ANTsPy (and I am having a hard time figuring out how to make it works).

On a side note, It would be great to include more complex examples of the different functions in ANTsPy.

**Comment by stnava** [comment]
see https://github.com/ANTsX/ANTsPy/blob/master/tutorials/Multi-metric%20registration.ipynb

**Comment by braincharter** [comment]
Thank you for your quick reply!

I saw this on ANTsR's documentation

> multivariateExtras | list of additional images and metrics which will trigger the use of multiple metrics in the registration process in the deformable stage.

Does that mean that 'multivariateExtras' is ignored if I perform an Affine-only transformation?

**Comment by stnava** [comment]
here is the documentation

   multivariate_extras : additional metrics for multi-metric registration
        list of additional images and metrics which will
        trigger the use of multiple metrics in the registration
        process in the deformable stage. Each multivariate metric needs 5
        entries: name of metric, fixed, moving, weight,
        samplingParam. the list of lists should be of the form ( (
        "nameOfMetric2", img, img, weight, metricParam ) ). Another
        example would be  ( ( "MeanSquares", f2, m2, 0.5, 0
          ), ( "CC", f2, m2, 0.5, 2 ) ) .  **This is only compatible
        with the SyNOnly transformation.**

**Comment by braincharter** [comment]
Ok! Then it is not possible to do a multi-metric registration with rigid transformations only? 

I think that this could a useful feature, for example in cases with partial MRI images with very low SNR..

**Comment by stnava** [comment]
ANTsX is open source and you can implement such things yourself if you think it is worth your time.
