### ISSUE TITLE
Transformation parameters

### ISSUE THREAD

**Issue by alexeytopolnitskiy** [ANTsX/ANTsPy#255]
Hello! I performed registration using *ants.registration()* using Rigid transformation type and I have some questions.

1. After registration of two 3D models, how can I obtain changes that were made to moved 3D model, e.g. rotation angle, translation, etc.
2. How can I limit range of changes before registration, e.g. limit range of angles for rotation and so on.

**Comment by stnava** [comment]
see:

`help( ants.read_transform )`

and then you would need to convert the matrix to angles ( google how to do this )

the underlying ANTs toolkit allows some limits on the transformation parameters but it is not intuitive to use for rigid transformations and not currently supported in the python version under discussion here.

an alternative is to initialize with some known sets of rotations etc and then do just a little bit of optimization from each starting point.  then take the best result.

you would need to spend some time learning the toolkit to do this in the right way.

 read the various tutorials to help you get there.

**Comment by alexeytopolnitskiy** [comment]
@stnava Thank you for your answer!
Could you specify about the first statement?
Let's say I performed 3D-3D registration and got the AntsTransform `mytx` object which is:
```
{'warpedmovout': ANTsImage (RAI)
 	 Pixel Type : float (float32)
 	 Components : 1
 	 Dimensions : (300, 300, 200)
 	 Spacing    : (1.0, 1.0, 1.0)
 	 Origin     : (0.0, 0.0, 0.0)
 	 Direction  : [1. 0. 0. 0. 1. 0. 0. 0. 1.],
 'warpedfixout': ANTsImage (RAI)
 	 Pixel Type : float (float32)
 	 Components : 1
 	 Dimensions : (300, 300, 200)
 	 Spacing    : (1.0, 1.0, 1.0)
 	 Origin     : (0.0, 0.0, 0.0)
 	 Direction  : [1. 0. 0. 0. 1. 0. 0. 0. 1.],
 'fwdtransforms': ['/tmp/tmpu2ygfjoa0GenericAffine.mat'],
 'invtransforms': ['/tmp/tmpu2ygfjoa0GenericAffine.mat']}
```

As I understood, the `'/tmp/tmpu2ygfjoa0GenericAffine.mat'` is a argument that I need to use as an input to `ants.read_transform()`.
After I did it I got `tx2` object which is:
```
ANTsTransform
	 Type       : AffineTransform
	 Dimension  : 3
	 Precision  : float
```

And when I use `tx2.parameters` it returns me an array of length 12. I did not find any information of what these parameters mean and how to use them to find rotation parameters. Am I doing everything right or there is another way to obtain it?

**Comment by stnava** [comment]
quoting from ITK help


"As described in the class documentation [1], "the first (NDimension x
NDimension) parameters defines the matrix in row-major order (where
the column index varies the fastest). The last NDimension parameters
defines the translation in each dimensions."

HTH,
Matt

[1] http://www.itk.org/Doxygen/html/classitk_1_1AffineTransform.html"

**Comment by alexeytopolnitskiy** [comment]
@stnava Thank you for the answer! I think I'm close to the understanding.

I did not quite get what "where the column index varies the fastest" means. E.g. my first 9 parameters are: 
```
[9.99734461e-01,  2.29931790e-02,  1.52090285e-03, -
2.30041966e-02, 9.99705911e-01,  7.67454691e-03, 
-1.34399335e-03, -7.70749617e-03, 9.99969423e-01]
``` 
which can be transformed into 3 by 3 matrix:
```
[[ 0.99973446,  0.02299318,  0.0015209 ],
  [-0.0230042 ,  0.99970591,  0.00767455],
  [-0.00134399, -0.0077075 ,  0.99996942]]
```
I have gone through the documentation but I did not find any explanation of what is the sequence of dimensions (xyz or zxy, etc.). And also, what these numbers mean. I understand the principle of using transformation matrix but there are must be 3 of them (for x, y and z), but there is only one.

**Comment by stnava** [comment]
this matrix represents the rigid transformation that maps the 3D space of one image onto the other.

perhaps you should read: 

https://itk.org/ITKSoftwareGuide/html/Book2/ITKSoftwareGuide-Book2ch3.html#x26-1170003.9

and pay attention to transformation definitions.
