### ISSUE TITLE
Metric for checking registration quality - antsRegistrationSyNQuick

### ISSUE THREAD

**Issue by tommydino93** [ANTsX/ANTsPy#256]
**Describe the bug**
I am running the SynQuick registration for many patients. I was wondering: is it possible to compute a metric that accounts for registration quality? Basically, at the end of the computation, I would like to know the patients for which the registration was imprecise/incorrect.

**To Reproduce**
I will be using the [registration](https://github.com/ANTsX/ANTsPy/blob/19e2f51cb4ae987254e0653cd7e831390e449560/ants/registration/interface.py#L20) method, specifying `type_of_transform="antsRegistrationSyNQuick[x]"`

**Expected behavior**
I would like to have a numerical value in some output file that roughly tracks the registration quality

**Desktop (please complete the following information):**
 - OS: Ubuntu Xenial
 - Version: 16.04.7

**Comment by stnava** [comment]
`help( ants.image_similarity )`

**Comment by gdevenyi** [comment]
Any such metric would be circular because that metric is used to drive registration. See the original ants paper for details of how to appropriately evaluate registration quality via the overlap comparison of manually delimited regions.

**Comment by tommydino93** [comment]
Thank you both very much! I will check both [image_similarity](https://antspy.readthedocs.io/en/latest/_modules/ants/utils/image_similarity.html) and the original paper

**Comment by tommydino93** [comment]
Sorry to re-open this. I just noticed something unexpected.

Is it normal that the values I get with `image_similarity` setting

`ANTSNeighborhoodCorrelation` and `MattesMutualInformation` are **negative**?

I would expect positive values. How should I interpret these values? 

I checked visually and I noticed that

- the lower the value obtained with `ANTSNeighborhoodCorrelation`, the worse is the registration
- the higher the value obtained with `MattesMutualInformation`, the worse is the registration.

Is this always the case?

Thanks a lot in advance

**Comment by stnava** [comment]
yes - it's normal.

**Comment by stnava** [comment]
just to clarify - see below

```
import ants
x = ants.image_read(ants.get_ants_data('r16'))
y = ants.image_read(ants.get_ants_data('r30'))
for m in ['Correlation','ANTsNeighborhoodCorrelation','MattesMutualInformation']:
  print(m)
  print( ants.image_similarity(x,x,metric_type=m,sampling_strategy='None') )
  print( ants.image_similarity(x,y,metric_type=m) )
```

**Comment by tommydino93** [comment]
Thank you very much!
