### ISSUE TITLE
Build a template from Mindboggle data using ants.build_template

### ISSUE THREAD

**Issue by Hangphuong** [ANTsX/ANTsPy#259]
Hi everyone,
I am a new user in ANTsPy. Now I have a small project that I need to build a template from 3D images using ANTsPy.
Therefore, firstly, I test with a part of Mindboggle data (it is OASIS-TRT-20_volumes which include 20 datasets of brain images).
I used this kind of data (t1weighted_brain.nii.gz) and then built the template following these code lines.

And I compared the result  with the Braintemplate that is available on the website (https://osf.io/wprc4/)
However, the result is different from the available. It is so blurred.

I attached the visualization and file.nii for convenience.
Can you help me with this situation, and give me some advice, please?

This is a visualization in ANTsPy of template in Mindboggle.

![template_available](https://user-images.githubusercontent.com/18043318/112258207-6d892c00-8ca9-11eb-877c-f71eb2d0c340.png)

[Brain_VolumeTemplate_OASIS-TRT-20.nii.gz](https://github.com/ANTsX/ANTsPy/files/6194512/Brain_VolumeTemplate_OASIS-TRT-20.nii.gz)

This is a visualization in ANTsPy of my result.

![template_test](https://user-images.githubusercontent.com/18043318/112258438-de304880-8ca9-11eb-9307-5d4091ef026e.png)

 [test_template.nii.gz](https://github.com/ANTsX/ANTsPy/files/6194522/test_template.nii.gz)

#################################
import ants
import os
import glob
dataDirectory = 'D:/ANTs/Mindboggle/Mindboggle-101 manually labeled individual brains/Data sets/OASIS-TRT-20_volumes/test_OASIS/'
populationFiles = glob.glob( dataDirectory + "OASIS*t1weighted_brain.nii.gz" )
population = list()

for i in range(len(populationFiles)):
	population.append( ants.image_read( populationFiles[i]) )

template = ants.build_template(initial_template=None,image_list=population,iteration=4,gradient_step=0.2,syn_metric="mattes")

##################################

**Comment by stnava** [comment]
there was a bug in this code long ago - several years.  maybe you have an old version.  but maybe not.

anyway, to get the template to "look the same" you'd have to pass some custom parameters to ants.registration (via build template) that would match whatever was done to create the reference template.  it might take you a  couple days to figure out how this works if you do this in 3D.   we recommend using 2D examples to learn what you are  doing and then apply the same approach in 3D.   the difference is experimenting at the scale of seconds/minutes (2D) vs minutes/hours (3D) - especially when it comes to building templates. 

if you don't want to experiment on your own, then take a look at the ANTs documentation for instance 

https://github.com/ntustison/TemplateBuildingExample

**Comment by Hangphuong** [comment]
Thank you so much for your reply.
Actually, I used the 2D Brainslice example, and I have a question related to templateCommandSyN.py.
I downloaded all data from the TemplateBuildingExample, and then I run the templateCommandSyN.py.
However, the template that I got is blurred and different from your result.
I attached the result for your convenience.
Please give me some explanation for my case. Why is there this difference?
![template_2D](https://user-images.githubusercontent.com/18043318/112400814-80a10800-8d4c-11eb-89dd-59547b128c1c.png)

**Comment by Hangphuong** [comment]
About the ANTsPy version I installed on my computer, I read issue number #28 and used this wheel for the installation
pip install https://github.com/SGotla/ANTsPy/releases/download/0.1.7Win64/antspy-0.1.7-cp37-cp37m-win_amd64.whl

**Comment by stnava** [comment]
See my original comment regarding old versions having a bug

**Comment by ntustison** [comment]
@Hangphuong, these ANTs toolkits are rather active in terms of development so we advise, if possible, to compile directly from source.

**Comment by Hangphuong** [comment]
@ntustison Thank you for your advice, I will re-install ANTsPy again directly from the source.

**Comment by Hangphuong** [comment]
@ntustison 
I compiled ANTsPy on Windows 64, python3.7 following that
git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python setup.py install

But I had the error "No local ITK installation found... Building ITK now...". 
Actually, I had this same error before, so that's why I used the wheel for the installation
pip install https://github.com/SGotla/ANTsPy/releases/download/0.1.7Win64/antspy-0.1.7-cp37-cp37m-win_amd64.whl

I read issue number #28 many times, but the error always appears.
Could you give me some comments about this?

**Comment by ntustison** [comment]
The output "No local ITK installation found... Building ITK now..." is not an error.  ANTsPy has to download and compile ITK as a first step to building the rest of the toolkit.  Can you provide more details if you think there is an  actual error?

**Comment by Hangphuong** [comment]
Hi Nick.
Thank you for your reply.
The below lines are what I did for the installation and information from the installation process.

C:\Users\user>git clone https://github.com/ANTsX/ANTsPy.git
Cloning into 'ANTsPy'...
remote: Enumerating objects: 209, done.
remote: Counting objects: 100% (209/209), done.
remote: Compressing objects: 100% (148/148), done.
remote: Total 5333 (delta 131), reused 110 (delta 61), pack-reused 5124Receiving objects: 100% (5333/5333), 91.61 MiB | 4.73 MiB/s
Receiving objects: 100% (5333/5333), 91.88 MiB | 3.99 MiB/s, done.
Resolving deltas: 100% (3649/3649), done.

C:\Users\user>cd ANTsPy

C:\Users\user\ANTsPy>python setup.py install
running install
running build_py
running build_ext
Configuring ITK
No local ITK installation found... Building ITK now...
error: [WinError 193] %1 is not a valid Win32 application

Yesterday, I copied all function files (file.py) from the ANTsPy.git, and then replaced them in the folder of ants in python (the folder I built from the https://github.com/SGotla/ANTsPy/releases/download/0.1.7Win64/antspy-0.1.7-cp37-cp37m-win_amd64.whl).


The result from building BrainSliceTemplate is better but not the same as your result.
The below images are shown that.

(old result) 
![template_2D](https://user-images.githubusercontent.com/18043318/112569011-c6320380-8e26-11eb-8c69-a987f0f29c41.png)
(new result)
![template_2D_new](https://user-images.githubusercontent.com/18043318/112569037-cf22d500-8e26-11eb-9d27-88dda3b8487d.png)
(Your result)
![BrainSlicesResult](https://user-images.githubusercontent.com/18043318/112569119-ef529400-8e26-11eb-9127-98dd61e0ad92.png)

I think it caused by these functions are not supported by the SGotla's wheel

from .addNoiseToImage import *
from .fitBsplineObjectToScatteredData import *
from .fitBsplineDisplacementField import *
from .fitBsplineDisplacementFieldToScatteredData import *
from .histogramMatchImage import *
from .labelOverlapMeasures import *
from .simulateDisplacementField import *
from .integrateVelocityField import *

Can you give me some comments for building these functions from LOCAL_.cxx files?

**Comment by ntustison** [comment]
To be honest, I don't work much with Windows (nor does @stnava) so our ability to help is going to be limited.  So even though we wrote all those functions, I don't know how to build them locally on a Windows machine.

**Comment by Hangphuong** [comment]
Thank you so much for all of your comments and advice, again.
