### ISSUE TITLE
cannot "import ants" ( Library not loaded: libvtkRenderingOpenGL2-8.1.1.dylib )

### ISSUE THREAD

**Issue by scott-love** [ANTsX/ANTsPy#26]
Using os x 10.13.2.
After doing 
pip install https://github.com/ANTsX/ANTsPy/releases/download/Weekly/antspy-0.1.4-cp36-cp36m-macosx_10_7_x86_64.whl

I get the error below when trying to import ants.

There is indeed no libvtkRenderingOpenGL2-8.1.1.dylib on my machine. 

I would be grateful for any pointers on how to solve this?

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-78f96f50f910> in <module>()
----> 1 import ants

/anaconda3/lib/python3.6/site-packages/ants/__init__.py in <module>()
      5     pass
      6 
----> 7 from .core import *
      8 from .utils import *
      9 from .segmentation import *

/anaconda3/lib/python3.6/site-packages/ants/core/__init__.py in <module>()
      1 
----> 2 from .ants_image import *
      3 from .ants_image_io import *
      4 
      5 from .ants_transform import *

/anaconda3/lib/python3.6/site-packages/ants/core/ants_image.py in <module>()
     25 import inspect
     26 
---> 27 from .. import utils, registration, segmentation, viz
     28 from . import ants_image_io as iio2
     29 

/anaconda3/lib/python3.6/site-packages/ants/utils/__init__.py in <module>()
      1 
----> 2 from .bias_correction import *
      3 from .channels import *
      4 from .convert_nibabel import *
      5 from .crop_image import *

/anaconda3/lib/python3.6/site-packages/ants/utils/bias_correction.py in <module>()
      7 
      8 
----> 9 from . import process_args as pargs
     10 from .get_mask import get_mask
     11 from .iMath import iMath

/anaconda3/lib/python3.6/site-packages/ants/utils/process_args.py in <module>()
     11 
     12 from ..core import ants_image as iio
---> 13 from .. import lib
     14 
     15 _short_ptype_map = {'unsigned char' : 'UC',

/anaconda3/lib/python3.6/site-packages/ants/lib/__init__.py in <module>()
      2 
      3 ## LOCAL ##
----> 4 from .antiAlias import *
      5 from .antsImage import *
      6 from .antsImageClone import *

ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/ants/lib/antiAlias.cpython-36m-darwin.so, 2): Library not loaded: libvtkRenderingOpenGL2-8.1.1.dylib
  Referenced from: /anaconda3/lib/python3.6/site-packages/ants/lib/antiAlias.cpython-36m-darwin.so
  Reason: image not found

**Comment by ejolly** [comment]
+1 to the same issue:
OSX 10.11.6
Python 3.6.2 (Anaconda install)

It looks like the installer is not automatically installing VTK as per the README.

**Comment by ncullen93** [comment]
sorry for the late response. going to revamp the setup file asap and hopefully fix the vtk issues.

**Comment by roschkoenig** [comment]
Running into the same problem as well
macOS 10.13.4
Python 3.6.5 (Anaconda install)

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy/issues/36#issuecomment-415897349

compiling from source is the only solution
