### ISSUE TITLE
Registration: Both masks, fixed and moving

### ISSUE THREAD

**Issue by andife** [ANTsX/ANTsPy#260]
Hello,
the "original" ANTs allows to specify two masks. One "moving_image_mask"
and a "fixed_image_mask". 

It seems that at the moment at ANTsPy only the fixed image mask is supported?
Any plans to add the functionality for the moving mask?

Thank you
Andreas

**Comment by stnava** [comment]
No plans for that.  you can make a pull request if you want to add it.
