### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by J-Yash** [ANTsX/ANTsPy#261]
Can ANTsPy use GPUs for registration? If not, are there any other recommended ways to make registration faster? Specifically, I am using the SynRA method for registration.

**Comment by stnava** [comment]
no it cannot - but you can use this at the beginning of your script to speed things up

```
os.environ["ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS"] = "8"
```

if you have multiple threads.  you'd want to adjust the 8 according the number of threads you would want.
