### ISSUE TITLE
Why are the images corrected by antspy vague, like adding a mismatched mask? THANKS

### ISSUE THREAD

**Issue by ctwangtz** [ANTsX/ANTsPy#267]
ON WINDOWS
import SimpleITK as sitk
import os
print('START')
in_path, out_path='F:/h14s.nii.gz', './h14s.nii.gz'
input_image = sitk.ReadImage(in_path)
mask_image = sitk.OtsuThreshold(input_image,0,1,200)
input_image = sitk.Cast(input_image,sitk.sitkFloat32)
corrector = sitk.N4BiasFieldCorrectionImageFilter()
output_image = corrector.Execute(input_image,mask_image)
output_image = sitk.Cast(output_image, sitk.sitkInt16)
sitk.WriteImage(output_image, out_path)
print('finish')
![SITK](https://user-images.githubusercontent.com/60605437/114889665-e446be80-9e3c-11eb-88f7-5b17a5760c5b.JPG)

ON UBUNTU
import ants
file = 'F:/h14s.nii.gz'
out_file = 'F:/out/h14s_n4.nii.gz'
data = ants.image_read(file)
data = ants.n4_bias_fild_correction(data)
ants.image_write(data,out_file)

![ANTS](https://user-images.githubusercontent.com/60605437/114889695-e9a40900-9e3c-11eb-8166-208d41629af1.JPG)

**Comment by ntustison** [comment]
What do you mean by the images being "vague"?  Also, what is meant by "adding a mismatched mask"?

Just so you're aware---although the core ITK filter is in common, there are several default options that vary between the two python interfaces.

**Comment by ctwangtz** [comment]
> What do you mean by the images being "vague"? Also, what is meant by "adding a mismatched mask"?
> 
> Just so you're aware---although the core ITK filter is in common, there are several default options that vary between the two python interfaces.

![ANTS](https://user-images.githubusercontent.com/60605437/114892486-659f5080-9e3f-11eb-970f-d5570e8437b8.JPG)

**Comment by ntustison** [comment]
When you click on a "new issue", there's an entire set of questions that you should answer to facilitate these discussions.  They are not only for your benefit but they're also for our benefit as our time is limited.  Please go back and answer those questions in a detailed manner and I'll be happy to revisit this issue.

**Comment by Jose-Verdu-Diaz** [comment]
I had the same issue and I will reopen and answer this just in case anyone else ends up here. I will make the assumption that the user was asking about the "sharp contrast shapes" in the corrected image.

The n4_bias_field_correction() method requires an image mask. If none is provided, then it will be done automatically. If the automatic masking is inaccurate, it is reflected in the resulting corrected image as the user has shown. An easy test is to mask the image and compare the mask with the corrected image to confirm that the sharp edges coincide:

```python
corrected = ants.n4_bias_field_correction(img, verbose=True)
mask = img.get_mask()
```

![image](https://user-images.githubusercontent.com/21974160/211884218-d482d281-4d98-4705-895c-c0e8e045a017.png)

Fortunately the `get_mask()` method has some parameters that can be tweaked to improve the mask, and if it still doesn't make the job you can apply a custom masking method.

I hope I guessed the objective of the issue properly, and I also hope the user reads [this](https://upthemes.com/blog/2014/02/writing-useful-github-issues/) before posting a new issue.

**Comment by stnava** [comment]
very helpful - thank you
