### ISSUE TITLE
When using reference to apply transform, resultant image is empty

### ISSUE THREAD

**Issue by sarthakpati** [ANTsX/ANTsPy#268]
**Describe the bug**
When applying a transform to an image with a reference, the resulting image is empty.

**To Reproduce**
```python
from ants import image_read, read_transform, image_write, dicom_read
segmentation_ants = image_read(args.input) # read the original segmentation
original_image = image_read(args.reference)

# read transform and invert, if requested
transform = read_transform(args.transform)

# apply the transform to original image
print(np.max(transform.apply_to_image(segmentation_ants).numpy()))
## 4.0
print(np.max(transform.apply_to_image(segmentation_ants,reference=original_image).numpy()))
## 0.0
```

**Expected behavior**
Expecting non-zero when reference is passed

**Screenshots**
N.A.

**Desktop (please complete the following information):**
N.A.

**Smartphone (please complete the following information):**
N.A.

**Additional context**
Unfortunately, can't upload data because of PHI.

**Comment by ntustison** [comment]
Please try to reproduce with something that can be shared so that we can reproduce on our end.  There are also images available through ANTsPy, see ``help(ants.get_data)``.

**Comment by sarthakpati** [comment]
[mni.nii.gz](https://github.com/ANTsX/ANTsPy/files/6320081/mni.nii.gz)
[TCGA-02-0003_1997.06.08_seg.nii.gz](https://github.com/ANTsX/ANTsPy/files/6320089/TCGA-02-0003_1997.06.08_seg.nii.gz)
[TCGA-02-0003_1997.06.08_flair.nii.gz](https://github.com/ANTsX/ANTsPy/files/6320091/TCGA-02-0003_1997.06.08_flair.nii.gz)

```python
import ants
import numpy as np
seg="/path/to/TCGA-02-0003_1997.06.08_seg.nii.gz"
image="/path/to/TCGA-02-0003_1997.06.08_flair.nii.gz"
ref="/path/to/mni.nii.gz"
fi=ants.image_read(ref)
mi=ants.image_read(image)
registration=ants.registration(fixed=fi,moving=mi)
transform=ants.read_transform(transform['fwdtransforms'][1])
seg_image=ants.image_read(seg)
print(np.max(transform_temp.apply_to_image(seg_image).numpy()))
## 0.0
np.max(seg_image.numpy())
## 4.0
```

It's not exactly the same, but it reproduces the problem. Hope this helps!

**Comment by ntustison** [comment]
The ``read_transform`` and related functions are for a separate set of transform applications.  See ``help( ants.read_transform).``

What you want is the following:
```
>>> fi = ants.image_read("/Users/ntustison/Desktop/mni.nii")
>>> mi = ants.image_read("/Users/ntustison/Desktop/TCGA-02-0003_1997.06.08_flair.nii")
>>> seg = ants.image_read("/Users/ntustison/Desktop/TCGA-02-0003_1997.06.08_seg.nii")
>>> registration=ants.registration(fixed=fi,moving=mi)
>>> seg_warped = ants.apply_transforms(fi, seg, interpolator="nearestNeighbor", transformlist=registration['fwdtransforms'])
>>> np.max(seg_warped.numpy())
4.0
```

**Comment by sarthakpati** [comment]
Well, this was an example where I was trying to reproduce the problem since I cannot share the original data. The original data has a composite transform (and its inverse) in h5 format, which I am trying to read using `read_transform` and then apply to the image.

**Comment by ntustison** [comment]
``read_transform`` is for a different use case.  Instead of 

```
transformlist=registration['fwdtransforms']
```

try 

```
transformlist="/path/to/h5/file.h5"
```

**Comment by sarthakpati** [comment]
Tried that but still saw an empty image. :(

**Comment by ntustison** [comment]
Then I'm guessing your generation of the original transform file is incorrect.  I don't have a problem getting the expected result following the directions I provided.  Here's a quicker example:

```
>>> import ants
>>> fi = ants.image_read(ants.get_data("r16"))
>>> mi = ants.image_read(ants.get_data("r64"))
>>> seg = ants.otsu_segmentation(mi, k=4)
 Otsu Thresh with 4 thresholds
>>> ants.plot(mi, seg)
>>> reg = ants.registration(fixed=fi, moving=mi, write_composite_transform=True)
>>> reg['fwdtransforms']
'/var/folders/ty/33w2ntbj3kn_m_8jxvkzh6t80000gn/T/tmpnx4p_upmComposite.h5'
>>> seg_warped = ants.apply_transforms(fixed=fi, moving=seg, interpolator="nearestNeighbor", transformlist='/var/folders/ty/33w2ntbj3kn_m_8jxvkzh6t80000gn/T/tmpnx4p_upmComposite.h5')
>>> import numpy as np
>>> np.max(seg_warped.numpy())
4.0
```

**Comment by sarthakpati** [comment]
Okay, thank you! I am closing this, for now. Will comment if I need more help. Cheers!
