### ISSUE TITLE
TypeError: set_direction(): incompatible function arguments.

### ISSUE THREAD

**Issue by ivjia** [ANTsX/ANTsPy#27]
tried to write header info "direction" to nifti file. exactly passed the required args but still got the errer:

```

> TypeError: set_direction(): incompatible function arguments. The following argument types are supported:
>     1. (self: ants.lib.antsImage.ANTsImageF3, arg0: array) -> None
> 
> Invoked with: <ants.lib.antsImage.ANTsImageF3 object at 0x7ff0281a95e0>, [[1.0, -0.0, 0.0], [-0.0, -1.0, 0.0], [0.0, 0.0, 1.0]]

```

when typing: 

> a.set_direction(info['direction'])

while my a is an antsImage data and my info['direction'] printed as:

> In [164]: print(info['direction'])
[[1.0, -0.0, 0.0], [-0.0, -1.0, 0.0], [0.0, 0.0, 1.0]]

Is this a bug of ants when dealing with nifti image?

**Comment by ncullen93** [comment]
ah, no it's because the function expects a numpy array and you passed a python list. i will fix it, thanks.
