### ISSUE TITLE
Confusing Log message in terminal from ants.apply_transforms ordering

### ISSUE THREAD

**Issue by neshdev** [ANTsX/ANTsPy#271]
I am confused by the logs when invoking the ants.apply_transforms function.

```python
fixed = ...
moving = ...
tx = ants.registration(fixed,moving,"Syn")

# tx looks like the following which will be used in the transform
#tx["invtransforms"] == ['.../0GenericAffine.mat', '.../1InverseWarp.nii.gz']

fixed_in_moving = ants.apply_transforms_to_points(
    fixed=moving, 
    moving=fixed,
    transformlist=tx["invtransforms"],
    whichtoinvert=[True,False],
    verbose=True)

```
I am confused by the following output produced in the logs (terminal of the jupyter notebook):

```cmd
output from logs:The composite transform comprises the following transforms (in order): 
  1. 1InverseWarp.nii.gz (type = DisplacementFieldTransform)
  2. 0GenericAffine.mat (type = AffineTransform)
```

I passed in the tranformation list as `['0GenericAffine.mat', '1InverseWarp.nii.gz']`
Can someone please interpret the logs? Is it performing the 1InverseWarp and then 0GenericAffine or is it using the order specified in my parameters?

**Comment by stnava** [comment]
the logs are reporting information about internal operations - not meant to
be interpreted by users but by developers.  the help/tutorial material is
on what you should rely.  if you want to know more about transformations
and how they are applied in different scenarios, please read
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

>

**Comment by neshdev** [comment]
Thank you. I was already looking at that guide but just wanted confirmation.
