### ISSUE TITLE
Making resampling optional

### ISSUE THREAD

**Issue by SadeghMSalehi** [ANTsX/ANTsPy#272]
In the current version, it's hardcoded that if the spacing is very unbalanced, visualization makes interpolating it to isotropic. This should be optional IMO.   
https://github.com/ANTsX/ANTsPy/blob/82b662c9ff0b574da8a21be7d2a2fb14574afc4c/ants/viz/plot.py#L2340

**Comment by SadeghMSalehi** [comment]
```
(base) HYP-ssalehi-Mac:ants ssalehi$ git push origin add_resample_option_in_plot
ERROR: Permission to ANTsX/ANTsPy.git denied to SadeghMSalehi.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by stnava** [comment]
fork first + follow github instructions

brian
