### ISSUE TITLE
it keeps telling me there is no "ANTSImage"

### ISSUE THREAD

**Issue by dh928** [ANTsX/ANTsPy#274]
i have been trying to install ants for at least 9 hrs on my macbook.... but after finally i thought i was able to use it, it told me "ANTsImage was not  declared

So i tried to build from source, but i keep on getting this error saying:
  Could not find a package configuration file provided by "ITK" with any of
  the following names:

    ITKConfig.cmake
    itk-config.cmake

im really not sure what to do..... would really appreciate any help. i tired all the methods mentioned in the documents..... i just want to cry

**Comment by stnava** [comment]
`pip install antspyx`

**Comment by stnava** [comment]
also - it would help us if you use the issue templates .... e.g. if you had told us you were using windows, then we would say "use the windows linux subsystem" .... different response for different OS.   you also need to have cmake and a compiler if you are trying to install from source.

**Comment by dh928** [comment]
> also - it would help us if you use the issue templates .... e.g. if you had told us you were using windows, then we would say "use the windows linux subsystem" .... different response for different OS. you also need to have cmake and a compiler if you are trying to install from source.

Thank you for the help!

I initially used:

pip install antspyx

I think I was able to successfully import ants in jupyter notebook, but then when I start running with ants, it says there is no "AntsImage"

Then I tried:

git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install


I kept on getting the following error:

Could not find a package configuration file provided by "ITK" with any of
the following names:

ITKConfig.cmake
itk-config.cmake


I think I do have cmak, but I'm not sure what is wrong.

Then I also tried the following line:

pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.8/antspyx-0.1.8-cp37-cp37m-macosx_10_14_x86_64.whl

But then I got an error saying it is not supported on the platform.


Lastly, I tried running the following lines:

git clone https://github.com/ANTsX/ANTsPy.git
cd ANTsPy
python setup.py install --novtk

but then I got another error saying "--novtk" is not recognized


I am trying to install this on a MacBook, and I really don;t have a Linux device, and it seems like the library is even harder to get installed on PCs. I really need ants for a project. But I've almost tried everything

**Comment by ntustison** [comment]
Go back to the first set of commands you tried:

```
git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install
```

Completely remove anything you've done and start from scratch.  

I'd like to see a copy of the error messages.   Either take a screenshot or cut and paste the entire screen dump to a log file and paste it in the response.

**Comment by stnava** [comment]
the devs use OS X and LINUX so we know its pretty bomb proof there - and will work for you.   just slow down, take a breath and carefully explain what is happening.   please see the issue templates as well as https://stackoverflow.com/help/minimal-reproducible-example

**Comment by dh928** [comment]
> the devs use OS X and LINUX so we know its pretty bomb proof there - and will work for you. just slow down, take a breath and carefully explain what is happening. please see the issue templates as well as https://stackoverflow.com/help/minimal-reproducible-example

Thank you so much! I really appreciate it! I will definitely try again and send in the detailed error code.

**Comment by dh928** [comment]
> the devs use OS X and LINUX so we know its pretty bomb proof there - and will work for you. just slow down, take a breath and carefully explain what is happening. please see the issue templates as well as https://stackoverflow.com/help/minimal-reproducible-example



> Go back to the first set of commands you tried:
> 
> ```
> git clone https://github.com/ANTsX/ANTsPy
> cd ANTsPy
> python3 setup.py install
> ```
> 
> Completely remove anything you've done and start from scratch.
> 
> I'd like to see a copy of the error messages. Either take a screenshot or cut and paste the entire screen dump to a log file and paste it in the response.

thank you I will definitely try that!

**Comment by dh928** [comment]
this morning when I ran it again with:
pip install antspyx
It suddenly worked!!!!!
I do find deleting the old ANTspy folder from home very useful!

Thank you to everyone that reached out to help!
