### ISSUE TITLE
No source distribution for v0.2.7

### ISSUE THREAD

**Issue by pafonta** [ANTsX/ANTsPy#281]
Dear maintainers,
Please consider releasing a source distribution for ANTsPy v0.2.7.
Without a source distribution, we cannot use ANTsPY on our HPC system which uses [Spack](https://github.com/spack/spack) to install softwares.
Thank you for your time.

**Describe the bug**
There is no source distribution for ANTsPy v0.2.7, both on PyPI and on GitHub.
Regarding GitHub, there is indeed no tag for v0.2.7.

**To Reproduce**
There should be a source distribution for v0.2.7 on PyPI here: https://pypi.org/project/antspyx/#files.
At least, there should be a tag for v0.2.7 on GitHub here: https://github.com/ANTsX/ANTsPy/tags.

**Expected behavior**
One could install v0.2.7 from source from PyPI.
At least, one could retrieve v0.2.7 from a tag on GitHub.

**Additional context**
Not having a source distribution for ANTsPy v0.2.7 is `a blocker` for using it in a [Spack](https://github.com/spack/spack) environment.

**Comment by stnava** [comment]
I added the correct tag here https://github.com/ANTsX/ANTsPy/tags but I don't see an easy way to add the files to PyPI.

will make a note in my [instructions](https://github.com/ANTsX/ANTsPy/wiki/Building-portable-wheels-for-ANTsPy) which I mindlessly follow when building releases.

**Comment by pafonta** [comment]
Hello @stnava,

Thank you for your prompt reply and adding the tag for v0.2.7 on GitHub!
The `tag` on GitHub unblocks us.

If it could be of any help, I had a look at the [instructions you mention](https://github.com/ANTsX/ANTsPy/wiki/Building-portable-wheels-for-ANTsPy).
That's strange that there is no source distribution as a `.tar.gz` (on UNIX) or `.zip` (on Windows) file at the end. Indeed, I see that in the section _build wheels for various platforms of the instructions_, there is the command `${PYBIN} setup.py sdist bdist_wheel`. According to the documentation of setuptools, the `sdist` argument asks for a source distribution. So, in the folder there should be a source distribution that could be put on PyPI with `twine upload <filepath>`.
