### ISSUE TITLE
resampling to target for MNI not aligning image. 

### ISSUE THREAD

**Issue by alpha-neuro** [ANTsX/ANTsPy#282]
Using scans from OASIS. After brain extraction, I'm unable to reliably center the brains on the MNI template. In fact, nearly all of them are **_consistently_** misaligned. Here is my code to generate the segmentation.

```
ants_orig_img = ants.image_read(y)
ants_ss_n4 = ants.n4_bias_field_correction(ants_orig_img)
ans_ss_n4_mni = ants.resample_image_to_target(ants_orig_img, ants_mni, verbose=True)
ans_ss_n4_mni_seg = ans_ss_n4_mni.kmeans_segmentation(k=3)['segmentation']   
```
And when I plot the ans_ss_n4_mni_seg image onto slicer I get something that's completely off from the MNI template: [Here's an image of what I'm talking about](https://imgur.com/JaHMlgA). 

I thought at first it was potentially an issue with the resampling function, I changed it to a few different ones and got the same result. The images are reportedly centered at the same origin, same orientation, same voxel spacing, etc ("resample to target" task is to do all of these things). I'm really at my wits end. Any tips/advice?

**Comment by gdevenyi** [comment]
> ans_ss_n4_mni = ants.resample_image_to_target(ants_orig_img, ants_mni, verbose=True)

You're not doing any registration

**Comment by stnava** [comment]
@gdevenyi is correct - you need `ants.registration` and `ants.apply_transforms` - please try reading tutorials and help.

**Comment by alpha-neuro** [comment]
Thank you.
