### ISSUE TITLE
iMath - Label stats

### ISSUE THREAD

**Issue by eriktaylor** [ANTsX/ANTsPy#283]
Hello, I've tried to run LabelStats in iMath using antsPy as below to calculate Atlas label statistics. The output error is also below:

ants.iMath(atlas_reg_label,'LabelStats')

You have reached an umimplemented section of code by calling:
iMath 3 0x5558cb26c880 LabelStats 0x5558caf2cb90 

Any suggestions for this?

**Comment by stnava** [comment]
try `help( ants.label_stats )`
