### ISSUE TITLE
Resampling large image stacks 

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#284]
I have a .nii.gz file which is 6 gb. I am trying to resample it using antspy. I am on a computer with 32 cores and 126 gb ram but i observe that this ram is not enough for the operation. If i load the image stack. The ram usage goes from 24 to 67.7 and upon running the resample_image cell it goes to 126 and then the kernel dies. Is there a way to do this by restricting the ram usage in antspy

**Comment by stnava** [comment]
you can split the image into slices and resample them that way, slice by slice.   see `ants.slice_image`

there is no way to "restrict RAM" other than by doing things differently.
