### ISSUE TITLE
Joint Landmark and Intensity Based Registration

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#286]
There is this paper "Lagrangian frame diffeomorphic image registration: Morphometric comparison of human and chimpanzee cortex" by Brian Avants one of the authors of ANTs. I was wondering why this is not implemented in ANTs. Is it some kind of performance issue, does this algorithm work well in practice. I was thinking of implementing it as it looks useful for my project. But since its not in ANTs I was curious about the reason

**Comment by stnava** [comment]
it works as described.  for reasons too technical to go into here (ITK related), we did not implement this in the ITK framework.   as such, it's not in ANTs.  the best you could do is approximate it with the multivariate metrics ( see tutorials ).   metric one would be CC.   metric two would be the mean squared metric operating on the distance map or gaussian blob denoting the first landmark position.   metric `n+1` would correspond to the landmark `n`. 

that would result in a similar method but perhaps would not be as efficient as directly using landmark points as metrics.

we may implement it some day but not right now.  

another option is to do a pure landmark matching first and initialize eg SyN with that solution.
