### ISSUE TITLE
ImportError: cannot import name 'utils' from partially initialized module 'ants' (most likely due to a circular import)

### ISSUE THREAD

**Issue by WilBeaul** [ANTsX/ANTsPy#288]
**Describe the bug**
I just download ants, and when I try to import it in a jupyter notebook (I'm following the 10 minutes tutorial), i get the error in the title

**To Reproduce**
Import ants in a jupyter notebook

**Expected behavior**
Import ants.

**Screenshots**
![image](https://user-images.githubusercontent.com/73796790/124940904-5e1fbb80-dfd8-11eb-8a73-f160c5bc3c3b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser : Chrome
 - Version : 90

**Comment by stnava** [comment]
cannot reproduce on OSX with python3.9

can you provide more details about how you installed antspy?

clearly, circular imports would also prevent testing from passing so literally nothing would work; wondering how/why your system would show this and not others.

**Comment by WilBeaul** [comment]
I installed it on a conda virtual environnement with this line of code:
` pip install git+https://github.com/ANTsX/ANTsPy.git`

**Comment by stnava** [comment]
can you try

`pip install antspyx`

**Comment by WilBeaul** [comment]
Already done, when I redo, it's tell me:
`Requirement already satisfied`

**Comment by WilBeaul** [comment]
I tried other things and now I got this:
![image](https://user-images.githubusercontent.com/73796790/124947538-e94f8000-dfdd-11eb-8ed2-5598b479612e.png)

**Comment by stnava** [comment]
did you uninstall antspyx and reinstall from pip?

**Comment by WilBeaul** [comment]
Seem to work now thanks!
