### ISSUE TITLE
I am working on the below code but not getting output

### ISSUE THREAD

**Issue by SoveshMohapa** [ANTsX/ANTsPy#289]
from nipype.interfaces.ants import ApplyTransforms
>>> at = ApplyTransforms()
>>> at.inputs.dimension = 3
>>> at.inputs.input_image = 'moving1.nii'
>>> at.inputs.reference_image = 'fixed1.nii'
>>> at.inputs.output_image = 'deformed_moving1.nii'
>>> at.inputs.interpolation = 'Linear'
>>> at.inputs.default_value = 0
>>> at.inputs.transforms = ['ants_Warp.nii.gz', 'trans.mat']
>>> at.inputs.invert_transform_flags = [False, False]
>>> at.cmdline 
'antsApplyTransforms --default-value 0 --dimensionality 3 --input moving1.nii --interpolation Linear --output deformed_moving1.nii --reference-image fixed1.nii --transform [ ants_Warp.nii.gz, 0 ] --transform [ trans.mat, 0 ]'

I dont understand what should be the output image

**Comment by ntustison** [comment]
Your best bet would be to clarify usage over with the nipype folk.   The output image should be what is specified by the ``--output`` option.
