### ISSUE TITLE
Coregistration of 4D fMRI with 3D T1w MRI

### ISSUE THREAD

**Issue by aksh-ai** [ANTsX/ANTsPy#294]
Hi,

Thanks for the great work. I tried running the co-registration process by looping time-points in the 4D fMRI time series and then using the `ants.registration` to register each fMRI image with the 3D T1w MRI. The fMRI image is getting resampled to the T1 image's space and size. Is there a way to perform the co-registration process without resampling to the moving image's space or any other efficient solutions? 

Your help and feedback would be much appreciated.

Regards,
Akshay

**Comment by ntustison** [comment]
The moving image will always be resampled to some reference space.  So, for example, if you want the warped fMRI image to maintain the same resolution (ie, spacing), you can downsample the T1 to that resolution and use that as your fixed/reference image.

**Comment by aksh-ai** [comment]
Got it. Thanks a lot for the quick reply and solution. :)
