### ISSUE TITLE
Ants.registration() with same parameters does nor reproduce the results

### ISSUE THREAD

**Issue by asmaharry** [ANTsX/ANTsPy#297]
Hello,
Using the ants.registration() function in python, but with the same inputs not able to produce the same results when run it at two different times.

When checked for the solution, it has been suggested to use the fix random seed and single thread will help to reproduce the results. but this issue related to the antR code, How to set these parameters in antPy.

any other suggestions that will help me to reproduce the results in antsPy?

Thank you in advance.

**Comment by stnava** [comment]
there are several ways to achieve this - see the ANTs wiki for details and the ANTsPy wiki too - both mention environment variables that let you set default seeds and threads.

however, that approach can result in slow registration.   as such, we provide  `*Repro` options for `type_of_transform` - see `help( ants.registration )` .  these set the affine metric and the deformable metric such that you will get reproducible results regardless of envt variables.

**Comment by asmaharry** [comment]
Thank you, for the information.
Now set the random_seed=1 in my code.
It works fine for some of the subjects but then encountered a problem; process automatically killed and it happened several times.

Then reinstall the ants to fix this issue. After reinstallation got another error
 File "<stdin>", line 1, in <module>
AttributeError: module 'ants' has no attribute 'image_read'

unable to understand what is going on. 

Please suggest me the solution.

**Comment by stnava** [comment]
this is unrelated to the original issue. please  open a new issue where you fill in the relevant issue template.
