### ISSUE TITLE
Failed importing 4D NIFITI file

### ISSUE THREAD

**Issue by dpaniukov** [ANTsX/ANTsPy#30]
I'm trying to import 4D NIFTI file. On this code:
`cbf = "file.nii.gz"
 cbf_img = ants.image_read(cbf, pixeltype='float')
 cbf_array = cbf_img.numpy()`
I'm getting:
`Traceback (most recent call last):
  File "/home/dmitrii/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-55d262118e20>", line 21, in <module>
    cbf_img = ants.image_read(cbf, pixeltype='float')
  File "/home/dmitrii/anaconda3/lib/python3.6/site-packages/ants/core/ants_image_io.py", line 405, in image_read
    libfn = utils.get_lib_fn(_image_read_dict[pclass][ptype][ndim])
KeyError: 4`
Any suggestions how to solve it? Currently using nibabel, works fine.

**Comment by ncullen93** [comment]
much apologies for the late response. that's a very strange error seemingly unrelated to this package. if you want to upload an example file (perhaps with the values zeroed out if necessary), then i will take a look. closing in the meantime.

**Comment by stnava** [comment]
i pushed a change that may help - not sure.  dont have time to reinstall /
retry myself right now.

brian
