### ISSUE TITLE
Template building with segmented images

### ISSUE THREAD

**Issue by codeenthusiast** [ANTsX/ANTsPy#307]
I have build a template registering several CT's together using build_template script from ANTs. Works great! I now want to do two things:
1) register multiple CT's that have different anatomical regions segmented with the template demonstrating the overall average as well as the segmented section
2) I want to use a segmented template where I feed an unsegmented non-registered CT to have it segmented.

Are scripts available for this?

**Comment by gdevenyi** [comment]
1.Generate the template with all the  images.
2. Resample the segmentations from the images with them using the template transforms.
3. Vote/merge the segmentations in template space.
4. Back transform the consensus segmentations onto the unlabelled images

**Comment by codeenthusiast** [comment]
For step 1, this is generating a template from the segmented images? or the unsegmented images?
I'm not sure how to go about steps 2-4, are there possible functions/scripts I can be directed to for this?
This is more challenging as I'm from a clinical background and very novice into coding. Thanks again.

**Comment by gdevenyi** [comment]
For 1 it is all.

2 and 4 and antsApplyTransforms.

I'm not sure antspy has the merging functions. I use the command line exclusively.

**Comment by stnava** [comment]
there is jointLabelFusion in antspy

brian

**Comment by codeenthusiast** [comment]
Thank you, I've been able to propagate the segmentation from a template image to my target image.

I have a question regarding my template construction. I am currently using the build_template script which works well with registering unsegmented images.

If I want to create a template image which includes the average segmentation, should I run the build_template script twice? i.e. once for the unsegmented scans and the second run for the segmentations themselves.
