### ISSUE TITLE
Publish wheels to pypi

### ISSUE THREAD

**Issue by cancan101** [ANTsX/ANTsPy#31]
It looks like the newest wheel on pypi is a bit stale: https://pypi.org/project/antspy/#history

**Comment by stnava** [comment]
it would be nice to update the wheels but the main developer ( @ncullen93  ) is on hiatus from this project.   there are testing issues that need to be resolve as can be seen here [https://travis-ci.org/ANTsX/ANTsPy/jobs/304831710](https://travis-ci.org/ANTsX/ANTsPy/jobs/304831710)

**Comment by ncullen93** [comment]
i'll try to update this ASAP. it's difficult because i have to manually do it due to our wheels being over the allowed file limit.

**Comment by ncullen93** [comment]
Ah I just looked at this... we can't be on PyPi because we are way over the filesize limit :(. i've updated the wheels on the github releases page though - download them from there and run `pip install ...` . Let me know if you have any issues.

**Comment by cancan101** [comment]
How large is the wheel?

**Comment by ncullen93** [comment]
~200 mb

**Comment by cancan101** [comment]
wow, why so big?

**Comment by stnava** [comment]
​templated c++ underneath the py code​


brian

**Comment by ncullen93** [comment]
it includes a full ITK build as well. I requested an exemption forever ago and they never responded. i will try again.
