### ISSUE TITLE
How to write transformation from 'ants.build_template' ?

### ISSUE THREAD

**Issue by sindhura234** [ANTsX/ANTsPy#310]
`import ants`
`image = ants.image_read('volume-485.nii')`
`image2 = ants.image_read('volume-486.nii' )`

`timage = ants.build_template( image_list = (image, image2 ))`

I want to save the **transformation file** as well. How could I do this?

**Comment by ntustison** [comment]
That is currently not available with this implementation of template building.  You would have to compute the transformations using the resulting template and another round of pairwise registrations, which one should most likely do anyway.

**Comment by sindhura234** [comment]
Thanks for quick reply...Please correct my understanding if I am wrong...

1. 10 images used for template building
2. I take each of these images and register with the template created to get transformation. So I might be getting 10 transformations? 
Is this what you mean?

**Comment by ntustison** [comment]
Yes.
