### ISSUE TITLE
Is it possible to apply transforms from cropped image to original image?

### ISSUE THREAD

**Issue by mertyergin** [ANTsX/ANTsPy#311]
Hi,

I have segmentations of an organ in two different modalities that I want to register.
To fasten the registration process, I cropped both modalities according to the segmentation map. It worked well but I am wondering is it possible that I use `fwdtransforms` (came from cropped image registration) to register non-cropped moving images to non-cropped fixed images.

Note: I tried to use `fwdtransforms` from cropped image registration to apply non-cropped images. But the images were getting shrink after applying the transformation.

Thanks

**Comment by ntustison** [comment]
> It worked well but I am wondering is it possible that I use fwdtransforms (came from cropped image registration) to register non-cropped moving images to non-cropped fixed images.

In general, no.

**Comment by mertyergin** [comment]
> > It worked well but I am wondering is it possible that I use fwdtransforms (came from cropped image registration) to register non-cropped moving images to non-cropped fixed images.
> 
> In general, no.

Thanks
