### ISSUE TITLE
SyN implementation

### ISSUE THREAD

**Issue by anorak94** [ANTsX/ANTsPy#313]
Hey 

This is not a bug report. I was trying to implement the SyN algorithm using an autodiff package for the gradient updates etc. And I had some doubts about the algorithm

## SyN Algorithm

**For each level of the gaussian pyramid**

**1. If not initialized yet -**

       1. Initialize a displacement field fix_to_middle and mov_to_middle and expand to current shape
       If the displacement field has been initialized this step carries it forward to the next step
       
**2. Dowsample fix and moving images to the current resolution and smoothing of the gaussian pyramid**

**3. For each level run the opitmization iterations ---**

       1. warp the fix and moving to the middle using respective displacement transform
       2. compute the loss and gradient wrt to the displacement field (using autodiff)
       3. set bc condition i.e. set displacement gradient at boundaries to be 0
       4. set the step_size of gradient descent update to be step_size = step_size / (grad / spacing).norm().max()
       5. update the displacement field as field = field - step_size * (smooth_gaussian_filter(grads)) for both fields
       6. monitor loss and convergence
       
**4. At the end of this level**

       1. Compute inverse of the displacement moving to middle, and fix to middle (use sitk.InvertDisplacementField)
       2. The full mapping is now given by moving to middle $\circ$ middle to fix and vice versa 
       

This is my current understanding of whats happening under the hood. But in the actual algorithm do we keep a running update of the displacement field or the entire deformation mapping phi i.e. identity_map + displacement field. Because in the paper. A reproducible evaluation of ANTs similarity metric it says that the gradient is computed wrt to phi and the new field is given by the gradient update composed with the deformation map phi. If this is the case then when we are inverting the displacement field. Do we subtract the identity mapping from the deformation map phi and then invert it. 

Also for Step 4 in the SyN algorithm. My understanding is that greedy part comes from the fact that we optimize only the midpoint of the deformation map phi. And the symmetric part is the fix to middle and middle to fix. And do we ensure the inverse consistency. by computing an inverse that is subpixel accurate etc. Because we only ever optimize the two halves and never the inverses

**Comment by ntustison** [comment]
This is a significant endeavor.  I would recommend referring to the [ITK implementation](https://itk.org/Doxygen/html/classitk_1_1SyNImageRegistrationMethod.html) to help with your questions.

**Comment by anorak94** [comment]
Yeah thats true especially the composing and inverting of the displacement fields and making sure all the transforms and interpolation functions etc are working with the right spacing and other parameters.

**Comment by anorak94** [comment]
Hey I think I did it. It works now my composite transform function wasnt working properly. This is what i have done. https://colab.research.google.com/drive/1-yG4ZY5vHBJBljqpA8Dt0uTMcTIY_Rsz

Ill just leave it here in case its useful or just plain wrong

**Comment by anorak94** [comment]
i have updated the share permissions

**Comment by stnava** [comment]
thanks for sharing the example.  it's interesting.   I think your inversion steps are a little different - that's a very sensitive process and it caused us some trouble in the v4  reimplementation of the original work.   probably this implementation is little closer to an elastic (vs fluid) version of syn.   you should certainly compare performance with the original method as available in either antspy or sitk.

**Comment by anorak94** [comment]
Thanks for looking through it. If i understand correctly a fluid version of SyN would mean parameterizing the displacement field with a stationary velocity field and then we follow the same steps as above except that the `displacement_fix_to_middle` and `displacement_mov_to_middle` are given by `(time=.5)*v`. And the smoothing is done on the velocity field estimate. 

So the gradient field update for the velocity field going both ways would be `v_new = v_old - delta * grad_v_after_scaling`

**Comment by stnava** [comment]
syn is a class of methods that incorporates different choices for regularization, metrics, optimization, etc.  you implemented perhaps one variant.  the original "award winning" version is fluid based, uses CC metric and specific choices of parameters.  however, the various challenges won by this class of methods differ to a degree in the details of the above choices.   yes- the composition needs to be done incrementally --- take a look at the syn code in itk.

**Comment by anorak94** [comment]
Thanks for your clarifications. I looked at the syn registration code in itk. And there it declares a displacement field transform for the fixed to middle and moving to middle so i guess it has the elastic version implemented. I just have one small doubt there are some papers which say that the deformation field and its inverse can be computed by a scaling and squaring law. Did you try this approach and what was the accuracy of this approach compared to the fixed point iterative method implemented in SyN by NJ Tustison and B Avants

**Comment by stnava** [comment]
the method in itk supports either fluid or elastic regularization.

**Comment by stnava** [comment]
yes - scaling and squaring can be used.   however they don't provide any direct control over the term

\norm(  phi^{-1}( \phi( x ) ) - Id )

**Comment by anorak94** [comment]
> yes - scaling and squaring can be used. however they don't provide any direct control over the term
> 
> \norm( phi^{-1}( \phi( x ) ) - Id )

Yes thats a very good point. I don't know the details of how the inverse is computed yet. I just used sitk for that. I guess that is the reason its claimed in the paper that the inverse is guaranteed to be sub-pixel accurate everywhere. 


Regarding the first point I am sorry if this is a basic question but elastic regularisation is simply penalising the displacement field through a differential operator either norm of the field or the laplacian or some other differential operator as given in the papers. And a fluid regularization would mean regularizing the velocity field through a differential operator. But since the velocity is just a `d(displacement)/dt` doesnt it all boil down to choosing a differential operator to regularise the displacement field.

**Comment by stnava** [comment]
well - I think you should look closely at the original itk code.

**Comment by anorak94** [comment]
Yes!!! Thanks a lot i will close this issue
