### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mrjeffs** [ANTsX/ANTsPy#32]
using install method 2 - git clone and python setup.py install
on ubuntu 16.04 clean install i get this error

-- Check the value of the 22nd bit of a 32-bit quiet-NaN - 1
CMake Error at Modules/Bridge/VtkGlue/itk-module-init.cmake:9 (find_package):
  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMake/ITKModuleEnablement.cmake:316 (include)
  CMakeLists.txt:337 (include)

-- Configuring incomplete, errors occurred!
See also "/home/toddr/Software/ANTsPy/itkbuild/CMakeFiles/CMakeOutput.log".
See also "/home/toddr/Software/ANTsPy/itkbuild/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
Configuring ANTs core
Cloning into 'pybind11'...
remote: Counting objects: 8720, done.
remote: Total 8720 (delta 0), reused 0 (delta 0), pack-reused 8720
Receiving objects: 100% (8720/8720), 2.91 MiB | 0 bytes/s, done.
Resolving deltas: 100% (5855/5855), done.
Checking connectivity... done.
Cloning into 'antsrepo'...
remote: Counting objects: 21016, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 21016 (delta 1), reused 3 (delta 1), pack-reused 21009
Receiving objects: 100% (21016/21016), 19.06 MiB | 18.85 MiB/s, done.
Resolving deltas: 100% (14515/14515), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Already up-to-date.
Note: checking out 'fb874ebe977b84b57b7c5a2b124608f748e8e1e2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at fb874eb... ENH: add pixeltype option to resampleImage
Configuring ANTsPy library
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The imported target "vtkgdcm" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkgdcm.so.2.6.3"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmsharpglue" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkgdcmsharpglue.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmJava" references the file
   "/usr/lib/x86_64-linux-gnu/jni/libvtkgdcmJava.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmPython" references the file
   "/usr/lib/python/dist-packages/libvtkgdcmPython.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmPythonD" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkgdcmPythonD.so.2.6.3"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/toddr/Software/ANTsPy/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 148, in <module>
    classifiers=['Programming Language :: Python :: 3.6'],
  File "/home/toddr/Software/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 53, in run
    self.run_command("build_py")
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 38, in run
    self.run_command("build_ext")
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 101, in run
    self.build_extension(ext)
  File "setup.py", line 130, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/toddr/Software/anaconda2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/toddr/Software/ANTsPy/ants/lib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/toddr/Software/ANTsPy/ants/lib/', '-DPYTHON_EXECUTABLE=/home/toddr/Software/anaconda2/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1

**Comment by mrjeffs** [comment]
on rerunning setup.py i get:
python setup.py install
running install
running build_py
running build_ext
Configuring VTK
Using local VTK already built for this package
Configuring ITK
Using local ITK already built for this package
Configuring ANTs core
fatal: destination path 'pybind11' already exists and is not an empty directory.
Configuring ANTsPy library
-- The imported target "vtkgdcm" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkgdcm.so.2.6.3"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmsharpglue" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkgdcmsharpglue.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmJava" references the file
   "/usr/lib/x86_64-linux-gnu/jni/libvtkgdcmJava.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmPython" references the file
   "/usr/lib/python/dist-packages/libvtkgdcmPython.so"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

-- The imported target "vtkgdcmPythonD" references the file
   "/usr/lib/x86_64-linux-gnu/libvtkgdcmPythonD.so.2.6.3"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   "/usr/lib/x86_64-linux-gnu/gdcm-2.6/GDCMTargets.cmake"
but not all the files it references.

CMake Error at CMakeLists.txt:14 (find_package):
  By not providing "FindVTK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "VTK", but
  CMake did not find one.

  Could not find a package configuration file provided by "VTK" with any of
  the following names:

    VTKConfig.cmake
    vtk-config.cmake

  Add the installation prefix of "VTK" to CMAKE_PREFIX_PATH or set "VTK_DIR"
  to a directory containing one of the above files.  If "VTK" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/toddr/Software/ANTsPy/build/temp.linux-x86_64-2.7/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 148, in <module>
    classifiers=['Programming Language :: Python :: 3.6'],
  File "/home/toddr/Software/anaconda2/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 53, in run
    self.run_command("build_py")
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 38, in run
    self.run_command("build_ext")
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/toddr/Software/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 101, in run
    self.build_extension(ext)
  File "setup.py", line 130, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/toddr/Software/anaconda2/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/home/toddr/Software/ANTsPy/ants/lib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/toddr/Software/ANTsPy/ants/lib/', '-DPYTHON_EXECUTABLE=/home/toddr/Software/anaconda2/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1

**Comment by stnava** [comment]
We probably need some community support to get this rebuilding.

(Lack of) response may give us an indication about how much interest there
is in keeping this project alive.

If nothing happens for long enough then I may give it a shot myself but not
likely soon.

It looks like there may be need for a new cmake, new vtk and ITK tags and
potentially a new git tag for ants as well.

**Comment by mrjeffs** [comment]
thanks for your reply. seems the vtk portion of make is getting bollucksed. tried earlier compiler (4.8) but not successful either. regular ants  with new clone compiles fine.

**Comment by jcreinhold** [comment]
For what it is worth, I get the same error when I try to build from source on a Linux box. However, I am able to successfully build from source on a Mac. 

I can provide more details on the errors I am receiving on the Linux box, I would just have to regenerate the errors (if it is of interest). I believe that my errors stem from VTK neither being found nor built properly when the build starts from the install script in ANTsPy. The VTK build fails on my Linux box because it states that OpenGL cannot be found (even though OpenGL is definitely installed on the system). The specific error I receive in the build is: "Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)"). Note that this fails to build, but the build script keeps plugging away (i.e., VTK tries to build and fails, then ITK tries to build and fails because VTK isn't built, and then ANTsPy tries to build and is the final failure; then the errors that @mrjeffs sees appears).

By the way, I'm interested in keeping the project alive. Let me know if there are other helpful details I can provide for this issue or, potentially, support for the project.

**Comment by stnava** [comment]
what i've learned from reading these comments:

* compilation of the individual code bases does not appear to be an issue
* linking / include parameters that connect vtk/itk/ants, as determined by cmake, appear to be broken at the vtk step
* possible that fixing the vtk setup would repair subsequent issues
*  as a further note, antspy is behind the other projects (itk, ants, antsr) in terms of versions

path toward a solution:

* read the `setup.py` and compare to how vtk/itk/ants are compiled at https://github.com/ANTsX/ANTs
* make the setup.py consistent with above, potentially taking into account new cmake and updated versions

noting that @ncullen93 appears to be generally inactive wrt development,  i wonder if @gdevenyi or @satra may have some insight

**Comment by ncullen93** [comment]
sorry been off for a bit. Will take a look at the setup.py file, but the VTK install part has always been a disaster for many reasons. I think if you install VTK separately then it may work. I will get back to this asap.

**Comment by stnava** [comment]
it may be easiest to maintain if you just accept the default superbuild options offered within ants.   this seems to work ok for vtk-itk-ants on most platforms.

**Comment by stnava** [comment]
an approach that is likely to work longer term regardless of ANTsPy internal attempts to build ITK or VTK:

1.  build ANTs via cmakewith USE_VTK set to ON
2.  cd ANTsPy
3.  export ITK_DIR=~/code/ants-src/bin/ITKv4-build
4.  export VTK_DIR=~/code/ants-src/bin/VTK-build
5. python setup.py install

however, one would also likely need to checkout the correct edition of ants, currently:  fb874ebe977b84b57b7c5a2b124608f748e8e1e2

**Comment by stnava** [comment]
see https://github.com/ANTsX/ANTsPy/issues/36 --- might be worth trying source install again with latest git version

**Comment by seralouk** [comment]
What about python 2.7? Is is possible to use ANTs with python 2.7 ?

**Comment by stnava** [comment]
i do not think 2.x works. 3.x appears to be fine on linux and osx (source install)

```
python3 setup install
```

see the .travis.yml for one way to do this.
