### ISSUE TITLE
Error installing ANTsPyx on mac

### ISSUE THREAD

**Issue by mayayab** [ANTsX/ANTsPy#321]
Trying to install ANTsPyx on my mac machine (Catalina, 10.15.7). "pip install ANTsPyx" didn't work so I tried installing from the source code (with these commands: git clone https://github.com/ANTsX/ANTsPy.git
cd ANTsPy
python setup.py install )
First I got an error about not having CMake installed, after installing CMake I reran setup.py and got the following error about ITK:
"CMake Error at CMakeLists.txt:10 (find_package):
By not providing "FindITK.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "ITK", but
CMake did not find one.
Could not find a package configuration file provided by "ITK" with any of
the following names:
ITKConfig.cmake
itk-config.cmake
Add the installation prefix of "ITK" to CMAKE_PREFIX_PATH or set "ITK_DIR"
to a directory containing one of the above files.  If "ITK" provides a
separate development package or SDK, be sure it has been installed."
I'd appreciate any pointers to how to solve this issue with ITK!

On a different machine, running Big Sur, the installation worked smoothly with "pip install antspyx". There seem to be some inconsistencies in the installation versions for different platforms, and different documentation pages point to slightly different installations (https://github.com/ANTsX/ANTsPy/blob/master/README.md compared with https://github.com/ANTsX/ANTsPy/blob/master/tutorials/InstallingANTsPy.md)
Thanks!

**Comment by stnava** [comment]
please refer to the README.

I've heard of this happening before but have never been able to reproduce the issue.  Probably some system specific issue.   

I have no recommendations other than starting with a clean build environment and trying again.

**Comment by pgclemens** [comment]
Bumped into the same error. Solved by installing libpng with homebrew as such `brew install libpng`. Then running `pip install antspyx` one more time. Something similar to this was suggested in the readme under "other notes on compilation".
