### ISSUE TITLE
ANTsPy help

### ISSUE THREAD

**Issue by MostafaI** [ANTsX/ANTsPy#322]
I want to move to ANTsPy. Could you please help me in rewriting this code in antspy? Do I need to do multiple ants.registrations? Also how do I define -c,-s,-f,metricWeight,radius,samplingStrategy, and samplingPercentage? 

antsRegistration -d 3 
                 -o ${outputPrefix} \
                 -r [${fix},${mov},1] \
                 -t Rigid[0.2] \
                 -m MI[${fix},${mov},1,8,Regular,0.15] \
                 -c 100x100x50 \
                 -s 4x2x1 \
                 -f 8x6x4 \
                 -t Affine[0.2] \
                 -m MI[${fix},${mov},1,8,Regular,0.15] \
                 -c 100x100x50 \
                 -s 4x2x1 \
                 -f 8x6x4 \
                 -t BSplineSyN[0.2,40,0] \
                 -m MSQ[${fix},${mov},1,1] \
                 -c 100x50x0 \
                 -s 2x1x0 \
                 -f 4x2x1  

Also Is the python version slower than ANTs?

**Comment by rueberger** [comment]
antspy is just a set of bindings for the c code. The performance is the same. 

I believe the documentation covers your question https://antspy.readthedocs.io/en/latest/registration.html
