### ISSUE TITLE
Understanding Preprocessing in DKT

### ISSUE THREAD

**Issue by Jeffotter** [ANTsX/ANTsPy#323]
Hi, I am very new to all this and might have somewhat of a novice question. I am attempting to DKT parcellate a brain from a well-known ANDI Dataset in python. I understand that the preprocessing for the Desekan_Killany_Tourville function uses "croppedMni152" to aid in registration during its preprocessing. Is it wrong for me to utilize this preprocessing on an already skull-stripped data set? Or does the Ants account for this? Thank you in advance!

**Comment by ntustison** [comment]
I mentioned this over in the ANTsX issue you opened but the function in question is in ANTsPyNet so please open an issue over there.

https://github.com/ANTsX/ANTsPyNet/issues
