### ISSUE TITLE
Image opening failure

### ISSUE THREAD

**Issue by brosscle** [ANTsX/ANTsPy#329]
Hello,
First thanks for this toolbox !
I found an issue when opening a nifti image with the function image_read. This file can be correctly opened on FSL or ITK viewers so I guess that the file is not corrupt, but with antspy I get the following error:

`File "/Users/clement/opt/anaconda3/envs/radiomic/lib/python3.9/site-packages/ants/core/ants_image_io.py", line 517, in image_read`
    `hinfo = image_header_info(filename)`

  `File "/Users/clement/opt/anaconda3/envs/radiomic/lib/python3.9/site-packages/ants/core/ants_image_io.py", line 434, in image_header_info`
    `retval = libfn(filename)`

`RuntimeError: /Users/stnava/Downloads/temp/ANTsPy3.6.12/ANTsPy/itksource/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1972:
itk::ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!`

Unfortunately I cannot share the nifti file that produces this error but I reproduced the bug on Ubuntu and MacOS and I currently use version 0.3.1 of antspy, which is the latest I guess.

I remember having the same issue in the past at the opening with ITK toolboxes and I had to install an older version of the toolbox to make it work. Do you have any clue about how to fix this issue ?

Thanks a lot !
Clément

**Comment by ntustison** [comment]
See if this is the relevant issue.

https://github.com/ANTsX/ANTs/issues/1294

**Comment by brosscle** [comment]
Hi, thanks for your quick answer !
Yes it is, sorry for that.
I changed the qform_code from 'unknown' to 'scanner' (ie from 0 to 1) and now it seems to work.
It's strange because all my images are stored with a qform_code set to 'unknown' and I only had an issue with this one.
Thanks for your help !
