### ISSUE TITLE
ants.apply_transforms causes segmentation fault (Ubuntu 18.04.5 LTS and MacOS 12.2.1)

### ISSUE THREAD

**Issue by andy-s-ding** [ANTsX/ANTsPy#334]
I wrote a script to apply a list of transforms to an ANTs Image loaded from an NRRD file. To test, I just tried to apply an Affine transformation that I had previously saved (.mat) to a certain volume file (.nrrd) and its associated segmentation file (.seg.nrrd). The code works fine for the volume file, but not for the .seg.nrrd file.

The files are successfully loaded in as ANTs Images. The moment ants.apply_transforms() is applied, I get the following error:

```
['-d', '3', '-i', '0x6000039dc0b0', '-o', '0x6000039d3070', '-r', '0x6000039dc090', '-n', 'genericLabel', '-t', '/Users/andyding/Desktop/ants_apply_transforms/Affine.mat']
Using single precision for computations.
Input scalar image: 0x6000039dc0b0
Reference image: 0x6000039dc090
zsh: segmentation fault  python3 apply_transforms.py --fixed  --moving  --transforms  --segmentations
```

I have tried reinstalling both ANTsPy and ANTs without success. This has been reproducible in both Ubuntu 18.04.5 LTS and MacOS 12.2.1. I read that segmentation faults can be caused by relative pathnames, so I tried with absolute pathnames and still had the same error.

Any ideas for why ants.apply_transforms() is throwing a segmentation fault? Attached is a .zip file to reproduce the issue. Example usage is commented in the last line of apply_transforms.py. Thank you for your help!
[ants_apply_transforms.zip](https://github.com/ANTsX/ANTsPy/files/8105840/ants_apply_transforms.zip)

**Comment by stnava** [comment]
you have a multi-channel fixed image.   probably being interpreted as something else.  eg one fix that gets it working but may not be correct for your purposes.

```
        fixed_image = ants.split_channels( fixed_image )[0]
```

**Comment by andy-s-ding** [comment]
Got it, that definitely fixed the issue. For my purposes, I really just needed the fixed image as a reference point to make sure the moving image is in the right coordinate space. For that reason, using only one of the channels works just fine. Thank you for your insight! I will close this issue.
