### ISSUE TITLE
Fail to install ANTsPyx on Mac M1

### ISSUE THREAD

**Issue by mikami520** [ANTsX/ANTsPy#335]
**Describe the bug**
I use "pip install antspyx" to install antspyx but it gives an error while building Cmake files.

**To Reproduce**
1. Open a terminal
2. type "pip install antspyx"
3. See error

**Expected behavior**
Antspyx is successfullt installed

**Screenshots**
![Screen Shot 2022-02-23 at 20 41 15](https://user-images.githubusercontent.com/70731556/155441321-d5c39035-c882-4df0-b698-d077612583c2.png)

![Screen Shot 2022-02-23 at 20 45 25](https://user-images.githubusercontent.com/70731556/155441394-c8450d06-3f08-47b8-b9c5-5f9777bef9cc.png)

![Screen Shot 2022-02-23 at 20 45 39](https://user-images.githubusercontent.com/70731556/155441530-861bcfd6-b5b0-414c-bef4-4f9533994453.png)

**Desktop (please complete the following information):**
    MacOS 
    Monterey 12.2.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ntustison** [comment]
Have you tried installing directly from Github?

```
git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install
```

**Comment by mikami520** [comment]
> Have you tried installing directly from Github?
> 
> ```
> git clone https://github.com/ANTsX/ANTsPy
> cd ANTsPy
> python3 setup.py install
> ```

Yes, I tried that way before, it gave same errors.

**Comment by ntustison** [comment]
That's difficult, then, for us --- neither @stnava nor I have the new M1 chip (although we're hoping to get one soon).  Are you able to test installation on a different platform?

**Comment by mikami520** [comment]
> That's difficult, then, for us --- neither @stnava nor I have the new M1 chip (although we're hoping to get one soon). Are you able to test installation on a different platform?

Currently I only have one laptop. But I successfully installed antspyx on Google Colab and Linux (a remote GPU)

**Comment by stnava** [comment]
I believe this will be resolved when we update itk + ants tags - but that may not happen too soon.  does "regular" ants compile on the M1?

**Comment by mikami520** [comment]
> I believe this will be resolved when we update itk + ants tags - but that may not happen too soon. does "regular" ants compile on the M1?

I guess it could. Since yesterday I used SuperBuild to compile the ANTs on M1

**Comment by stnava** [comment]
ok - we have not updated the itk/ants tags for antspyx for quite some time.   it generally takes me a day or so to update pypi ... don't have that time now.   but I pushed updates to the tags just now.   you might try to compile from source again ( may need a fresh clone )

**Comment by mikami520** [comment]
> ok - we have not updated the itk/ants tags for antspyx for quite some time. it generally takes me a day or so to update pypi ... don't have that time now. but I pushed updates to the tags just now. you might try to compile from source again ( may need a fresh clone )

Sounds good, I will have a try later today. thank you so much

**Comment by stnava** [comment]
I pushed a bunch of  changes to pybind11 as well as various  antspyx things .... I had to remove some functionality that is probably not used much anyway as I didn't have time to think through the fixes for those ... might address the comp issues though.

**Comment by ntustison** [comment]
Thanks, @stnava.  I'll check out the latest repo for a test drive on some of the stuff I'm working on and let you know if I encounter anything.

**Comment by mikami520** [comment]
> I pushed a bunch of changes to pybind11 as well as various antspyx things .... I had to remove some functionality that is probably not used much anyway as I didn't have time to think through the fixes for those ... might address the comp issues though.

Hi @stnava, I have clone the latest repository and install the antspyx. It can now install successfully, but some required modules or dependencies will not automatically installed. It should be done manually. Hope this could be solved in the next version.

**Comment by stnava** [comment]
ok - I just pushed a few fixes minutes ago  .... I think this latest push gets us very close to full functionality and probably successful on M1.

**Comment by mikami520** [comment]
> ok - I just pushed a few fixes minutes ago .... I think this latest push gets us very close to full functionality and probably successful on M1.

Sounds great. Thanks @stnava .

**Comment by mikami520** [comment]
> ok - I just pushed a few fixes minutes ago .... I think this latest push gets us very close to full functionality and probably successful on M1.

Hi @stnava , when I try to import ants, it gives an error. Here is the screenshot:
![Screen Shot 2022-02-25 at 16 35 04](https://user-images.githubusercontent.com/70731556/155806218-e0f7c23d-ba24-45df-a031-666306fe4632.png)

**Comment by stnava** [comment]
looks like a PIL issue - maybe reinstall PIL?   anyway, I cannot reproduce this one.   it may be a couple months or so before we have our own M1 machines on which to test.

**Comment by mikami520** [comment]
> looks like a PIL issue - maybe reinstall PIL? anyway, I cannot reproduce this one. it may be a couple months or so before we have our own M1 machines on which to test.

I think it may be the error of conda environment, since I can import ants successfully on virtual environment or without conda.

**Comment by stnava** [comment]
ok - that symbol `_xcb_connect` is not something I've ever seen in connection with ITK or ANTs.

**Comment by andreped** [comment]
Any update? Having ANTsPy working on M1 would be great for a software we are developing.

**Comment by mikami520** [comment]
> Any update? Having ANTsPy working on M1 would be great for a software we are developing.

I am sorry, I tried on two different M1 Macs, it did not work well

**Comment by dipterix** [comment]
@stnava Can I ask for the shell script that you used to build wheels on M1? I would like a try to build it for cp310 and cp311.

**Comment by stnava** [comment]
nothing special - just : 

```
rm -r -f build/ antspymm.egg-info/ dist/
python3 setup.py sdist bdist_wheel
```

**Comment by dipterix** [comment]
Hi @stnava I used the code you sent to me to build antspyx from conda environment. They are uploaded here https://github.com/dipterix/rpyANTs/releases/tag/0.0.1.9000

The source file uses the source code from the latest release on Github.
