### ISSUE TITLE
Problem with ants import

### ISSUE THREAD

**Issue by codeenthusiast** [ANTsX/ANTsPy#341]
I have been able to successfully install ants on both a virtual environment and Conda. However, upon importing ants with the command (import ants), I get the following error. Could you please advise?

ImportError                               Traceback (most recent call last)
Untitled-[1]().ipynb Cell 1' in <cell line: 1>()
----> 1[ import ants
File ~/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/__init__.py:7, in <module>
      ]()[4]()[ except:
      ]()[5]()[     pass
----> ]()[7]()[ from .core import *
      ]()[8]()[ from .utils import *
      ]()[9]()[ from .segmentation import *

File ~/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/core/__init__.py:2, in <module>
----> ]()[2]()[ from .ants_image import *
      ]()[3]()[ from .ants_image_io import *
      ]()[5]()[ from .ants_transform import *

File ~/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/core/ants_image.py:27, in <module>
     ]()[23]()[     HAS_PY3 = False
     ]()[25]()[ import inspect
---> ]()[27]()[ from .. import utils, registration, segmentation, viz
     ]()[28]()[ from . import ants_image_io as iio2
     ]()[31]()[ _supported_ptypes = {'unsigned char', 'unsigned int', 'float', 'double'}

File ~/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/utils/__init__.py:2, in <module>
      ]()[1]()[ from .add_noise_to_image import *
----> ]()[2]()[ from .bias_correction import *
      ]()[3]()[ from .channels import *
      ]()[4]()[ from .convert_nibabel import *

File ~/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/utils/bias_correction.py:4, in <module>
      ]()[1]()[ __all__ = ["n3_bias_field_correction", "n3_bias_field_correction2", "n4_bias_field_correction", "abp_n4"]
----> ]()[4]()[ from . import process_args as pargs
      ]()[5]()[ from .get_mask import get_mask
      ]()[6]()[ from .iMath import iMath

File ~/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/utils/process_args.py:14, in <module>
      ]()[5]()[ __all__ = [
      ]()[6]()[     "get_pointer_string",
      ]()[7]()[     "short_ptype",
   (...)
     ]()[10]()[     "get_lib_fn",
     ]()[11]()[ ]
     ]()[13]()[ from ..core import ants_image as iio
---> ]()[14]()[ from .. import lib
     ]()[16]()[ _short_ptype_map = {
     ]()[17]()[     "unsigned char": "UC",
     ]()[18]()[     "unsigned int": "UI",
     ]()[19]()[     "float": "F",
     ]()[20]()[     "double": "D",
     ]()[21]()[ }
     ]()[24]()[ def short_ptype(pixeltype):

File ~/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/lib/__init__.py:2, in <module>
      ]()[1]()[ ## LOCAL ##
----> ]()[2]()[ from .addNoiseToImage import *
      ]()[3]()[ from .antiAlias import *
      ]()[4]()[ from .antsImage import *

ImportError: dlopen(/Users/usr/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/lib/addNoiseToImage.cpython-39-darwin.so, 0x0002): Library not loaded: /opt/X11/lib/libpng16.16.dylib
  Referenced from: /Users/usr/opt/anaconda3/envs/DS/lib/python3.9/site-packages/ants/lib/addNoiseToImage.cpython-39-darwin.so
  Reason: tried: '/opt/X11/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file)]()
**To Reproduce**

**Desktop (please complete the following information):**
 - OS: Mac M1 - Monterey V12.2.1

**Comment by ntustison** [comment]
I don't think we can offer much help here---it might be an M1 issue or a Python 3.9 issue.    Regardless, the error seems to indicate something outside an ANTsPy-specific issue.

**Comment by codeenthusiast** [comment]
No problem. This is the case when I successfully install using pip install Antspyx. However, when I try to install Antspyx via git clone, cd ANTsPy, and python3 setup.py install, I get an error about CMake. Is there something different I need to do?

<img width="544" alt="Screen Shot 2022-03-14 at 5 04 31 PM" src="https://user-images.githubusercontent.com/6239462/158280492-af7c2bbe-24e0-4097-80bb-2e6bc979f8b2.png">

**Comment by ntustison** [comment]
No, that should work if everything is set up correctly.  Perhaps an old version of CMake?

**Comment by codeenthusiast** [comment]
I have done pip install cmake and I have version 3.22.3 under my virtual environment. I am not sure what else to try.

**Comment by ntustison** [comment]
Yeah, at this point I'm just guessing as well.  Are you successful installing on a different computer?

**Comment by codeenthusiast** [comment]
Have been able to install it on a Linux computer. I tried using this link pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.8/antspyx-0.1.8-cp37-cp37m-macosx_10_14_x86_64.whl and it is now working. However, it is an older version as opposed to the 0.3.2.
