### ISSUE TITLE
PyPI release 0.2.9 seems to have been pulled?

### ISSUE THREAD

**Issue by ruidc** [ANTsX/ANTsPy#342]
**Is your feature request related to a problem? Please describe.**
Is there a policy you're following for removing previous versions? doing so makes it very hard for us to have reproducible builds when releases are removed. 

**Describe the solution you'd like**
Releases to be maintained or a good reason for why they are removed - security risk etc. 

**Describe alternatives you've considered**
Is there a google group or some other forum I was unable to find where this policy or reasoning is published?

Thanks in advance

**Comment by stnava** [comment]
in brief, we ran out of space on pypi which limits total file storage.   I wasn't aware of this restriction until yesterday.  surely, I got rid of too many old releases before realizing that there was a 2nd issue:  https://github.com/pypa/pypi-support/issues/1765 ....  it's not clear to me how to handle this in the future except to minimize the number of builds or perhaps to only keep source code for old releases.

suggestions welcome.

**Comment by ruidc** [comment]
Thanks for the prompt and comprehensive response.
I've never published to pypi and the project owners I have contact with have only small, pure python packages.
[Tensorflow ](https://pypi.org/project/tensorflow/#files) seems to have obtained much larger exemptions.

What about splitting the project into the C file dependencies and the python bindings?
(or in the longer term all the .so files as separate packages)
Could the .so files be made python-version-independent, i.e. targeting the stable ABI (sorry I don't have C programming experience)?

Alternatively the .so files could remain published here on GitHub, and downloaded at install time?
There might be a more graceful way, but some packages have a download step for just this, e.g.: https://www.nltk.org/data.html#interactive-installer although that is for data rather than shared libraries.
Worst case, if you publish the wheels here, we can still pip install from git.
Ideally, at least the source for the older versions should remain published on pypi given the relatively small size.

**Comment by cookpa** [comment]
Wheel size is now much reduced, so we should be able to keep PyPI releases for much longer. Wheels for release tags are also available on Github.
