### ISSUE TITLE
os.environ[ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS] is not recognized

### ISSUE THREAD

**Issue by IlvaHou55** [ANTsX/ANTsPy#349]
Hi everyone,

For perfectly reproducible results from the ANTsPy registration it is suggested to set ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS to 1. 

I simply tried this, by following some examples online using:

```
import os
os.environ[ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS]=1

import ants
```

However, this environment is not existing in my case (i.e. NameError: name 'ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS' is not defined). Does this have to do with the path I am calling the script from? And is it possible to solve this inside of the script I am using?

I know this is more an os issue than an ANTsPy issue, but it might help others facing the same problems if the answer to it can be found here.

Thank you!

**Comment by cookpa** [comment]
I think you want

`os.environ['ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS']='1'`
