### ISSUE TITLE
Order of transforms in ants.registration output

### ISSUE THREAD

**Issue by jcreinhold** [ANTsX/ANTsPy#35]
The output "fwdtransforms" and "invtransforms" from ants.registration do not appear to be in a consistent order. I took a screenshot of two registration results—run with the same registration settings (SyNCC, in this case but I also observed this behavior with SyN and SyNRA)—where the order is reversed in the "fwdtransforms" and "invtransforms" across the two results:

<img width="1429" alt="screen shot 2018-06-01 at 2 23 04 pm" src="https://user-images.githubusercontent.com/5241441/40857247-8e26e860-65a8-11e8-99a2-699bb870edd1.png">

<img width="1434" alt="screen shot 2018-06-01 at 2 27 41 pm" src="https://user-images.githubusercontent.com/5241441/40857255-94027ad8-65a8-11e8-9e28-7b5c6adda10a.png">

This issue arose when I used the ants.apply_transforms function which resulted in a poor registration, but was fixed when I manually ordered the transforms. This issue also arises when I do not set the "outprefix."

Note that the "warpedmovout" and "warpedfixout" appear to be correctly registered.

For more context, I built from source and am using the latest edition (0.1.5).

**Comment by stnava** [comment]
that is interesting.   it should, i think, nearly always be 

```
fwd = '1warp','0aff'
inv ='0aff','1invwarp'
```

this could arise from inconsistent ordering of output from (python version) of `Sys.glob("*")` ... is this an error that can be reproduced or does it appear to be more random?   do you have an example in code (similar to below)  that would illustrate the issue?

```
import ants
i = img read
j = img read
reg = ants.registration( i , j, ... )
etc.
```

**Comment by ncullen93** [comment]
i think Brian is correct.. [from stackoverflow](https://stackoverflow.com/questions/6773584/how-is-pythons-glob-glob-ordered?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) it appears that glob.glob() order is arbitrary or based on your filesystem. I added a sort statement so that should hopefully fix it. Let me know if it doesn't and I'll reopen.
