### ISSUE TITLE
CircleCI automated build

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPy#353]
@stnava @ntustison , the CircleCI automated build is failing, which causes the red X next to each commit. I took a look at the config and it appears to be extraneous now. What do you think about removing it? Or I can see about fixing it, it looks like it just needs a newer cmake and to update the base image.

On a related note, I can add an actions workflow for a docker build similar to what is currently in ANTsX/ANTs, if there's interest.

**Comment by ntustison** [comment]
Thanks @cookpa .  Anything you can do to fix issues like this would be greatly appreciated.

**Comment by cookpa** [comment]
I fixed the CI file, but it fails because of the one hour build limit on free plans. This was the same problem we had building ANTs. 

I can add a Github Actions workflow to build and push to dockerhub, which has a much more generous time limit, once I can figure out how to make the docker build (#355).

**Comment by cookpa** [comment]
Looking good in #369, I will document it better before merge. I tried to maintain the basic idea of #265, using buildx and miniconda, which will hopefully preserve the ability to do cross-platform builds.

**Comment by cookpa** [comment]
#369 merged, can I turn off CircleCI so it will stop emailing us?
