### ISSUE TITLE
Error during registration "Fatal Python error: Segmentation fault"

### ISSUE THREAD

**Issue by Vathsan** [ANTsX/ANTsPy#354]
**Describe the bug**
I am getting the "Fatal Python error: Segmentation fault" error while trying to register a 2D tif image. 
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00002aaf4c202b73 in ?? ()
[Current thread is 1 (LWP 26052)]
```

As I checked the error is thrown upon executing,
`ants.registration(fixed=fixed, moving=moving, type_of_transform='SyNOnly')`

Following is a sample .tif image header information,
`ants size:  {'pixelclass': 'rgb', 'pixeltype': 'unsigned char', 'nDimensions': 2, 'nComponents': 3, 'dimensions': (2400.0, 864.0), 'spacing': (1.0, 1.0), 'origin': (0.0, 0.0), 'direction': array([[1., 0.], [0., 1.]])} `

ANTsImage is read from file,
`fixed = ants.image_read(fixed_tif, dimension = 3)`

I could see the following details when printing the ANTsImage,
```
ANTsImage (RAI)
	 Pixel Type : float (float32)
	 Components : 3 (RGB)
	 Dimensions : (1200, 864, 1)
	 Spacing    : (1.0, 1.0, 1.0)
	 Origin     : (0.0, 0.0, 0.0)
	 Direction  : [1. 0. 0. 0. 1. 0. 0. 0. 1.]
```
Similar issue was reported in https://github.com/ANTsX/ANTsPy/issues/40. 

In my case, should not the registration work since the image dimension is 1200x864x1? Appreciate any help on this. Thanks in advance.

**Comment by ntustison** [comment]
Okay, a couple things.  This is a two-dimensional image so you'll want to read it as such, i.e., 

```
fixed = ants.image_read(fixed_tif, dimension = 2)
```

Second, registration basically operates on scalar images so you'll have to use a single channel or combine them before registration (see ``ants.split_images(...)``).

**Comment by Vathsan** [comment]
Hi @ntustison,

Thanks for the response.

I assume you meant to say `ants.split_channels(...)`. I was able to overcome the fatal error with your suggestion. 
I was wondering whether I could do something like; split the image into single channels, do the registration for each images and then merge the resulting images using `ants.merge_channels`. Does this make sense or do we have any other options?

**Comment by ntustison** [comment]
> I was wondering whether I could do something like; split the image into single channels, do the registration for each images and then merge the resulting images using ants.merge_channels. Does this make sense or do we have any other options?

No, you don't want to do this.  Rather you want to use a single channel or some combination of the channels (e.g., average) to do registration and then use ``ants.apply_transforms`` to warp each channel and then merge.

**Comment by Vathsan** [comment]
Thanks for the info. Will try that.
