### ISSUE TITLE
Registration of two FA images - Output is flipped

### ISSUE THREAD

**Issue by imagingn** [ANTsX/ANTsPy#356]
Hello,

I am trying to nonlinearly register two FA images (derived from diffusion MRI). I am particularly interested in the affine map and warp nifti file that ANTspy registration generates. I apply the transformations and save my moved file. when I load the file in any other viewer (eg: MI-Brain), the output FA image is flipped and not correctly aligned with the fixed FA file.

Here's how I load data and call the registration function:

```
import nibabel as nib
import ants
import numpy as np

ni_img1 = nib.load(path)
fixed = ants.nifti_to_ants(ni_img1)
# fixed = fixed.reorient_image2() #RAS

ni_img2 = nib.load(n_path)
moving = ants.nifti_to_ants(ni_img2)
# moving = moving.reorient_image2() #RAS

mytx = ants.registration(fixed=fixed , moving=moving, type_of_transform='SyN' )
mywarpedimage = ants.apply_transforms(fixed=fixed, moving=moving,
                                      transformlist=mytx['fwdtransforms'])

```

I think the problem could be that my data is in RAS and ants converts it into LAI space.
Here are the specs for the images.

**fixed**
ANTsImage (LAI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (182, 218, 182)
	 Spacing    : (1.0, 1.0, 1.0)
	 Origin     : (90.0, -126.0, -72.0)
	 Direction  : [-1.  0.  0.  0.  1.  0.  0.  0.  1.]

![image](https://user-images.githubusercontent.com/104227653/164800383-df16cc46-8916-415e-b6cf-23499600ab00.png)

**moving**
ANTsImage (LAI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (116, 116, 72)
	 Spacing    : (1.9828, 1.9828, 2.0)
	 Origin     : (115.0, -100.8727, -80.4458)
	 Direction  : [-1.  0.  0.  0.  1.  0.  0.  0.  1.]
![image](https://user-images.githubusercontent.com/104227653/164800406-17919049-cd95-4470-bc61-b6dacde74cfb.png)

**mywarpedimage**
ANTsImage (LAI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (182, 218, 182)
	 Spacing    : (1.0, 1.0, 1.0)
	 Origin     : (90.0, -126.0, -72.0)
	 Direction  : [-1.  0.  0.  0.  1.  0.  0.  0.  1.]

![image](https://user-images.githubusercontent.com/104227653/164801639-840fccd2-4300-4aec-853b-b06b51e0cd4c.png)

![image](https://user-images.githubusercontent.com/104227653/164800528-c497be48-6f2b-45f7-88b9-bff267e02a36.png)
![image](https://user-images.githubusercontent.com/104227653/164801653-217c6ca7-b8f4-49e1-afbe-6b3cc2c8d251.png)
![image](https://user-images.githubusercontent.com/104227653/164801669-da636be3-4ca8-4438-ada3-360e91d1fcca.png)

Results look good when visualized inside the same notebook. However, when I save the warped image to nifti file, it does not align in any other viewer. (I tried saving as ants image and also like this mywarpedimage.to_nibabel() but in all cases same results)

Here's how it looks:
Fixed image:

![fa2](https://user-images.githubusercontent.com/104227653/164801060-0df9eaa8-1856-4237-a400-9dfa43a5bf40.png)

![fa4](https://user-images.githubusercontent.com/104227653/164801072-5d8b1f38-f034-451c-8fcd-31554ea9e5c5.png)

Warped image:
![fa1](https://user-images.githubusercontent.com/104227653/164801092-75fec0e4-1f98-4fc9-8136-daed68626dc1.png)

![fa3](https://user-images.githubusercontent.com/104227653/164801103-25e939a4-9b85-48a5-8439-a6386b20fd3d.png)

Some sort of flipping. I tried changing the co-ordinate system of ants images as you can see commented lines in the code above. I tried using reorient_image2() function to have data in RAS before registration or even after registration. But in all cases, it gives me the same results.

On a side note, I tried everything, registering two images of the same size, dimensions, voxel sizes, etc. In all cases, my final output is flipped or not in the same space.

I am most interested in the transformation maps. I need them to be in the right space. Do you know what would be the solution? am I doing something wrong here?

Thank you very much for the help!

**Comment by ntustison** [comment]
Different packages use different elements of the nifti header in different ways.  It's unfortunate but we don't have the capacity to facilitate compatibilities with these other packages.  Know that transforms and orientations are mutually consistent within the ITK ecosystem (i.e., ANTs, ITK-SNAP) and so, from that perspective, they are in the right space.

**Comment by imagingn** [comment]
Hi @ntustison 

I found the solution. 

Instead of loading data with nibabel and then converting it into ants image like this:

`ni_img1 = nib.load(path)
fixed = ants.nifti_to_ants(ni_img1)
fixed = fixed.reorient_image2() #RAS`

I load data directly with ants API using `ants.image_read ` like this:

`fixed = ants.image_read(path)
fixed = fixed.reorient_image2() #RAS`

It worked like a charm ;)

I think when we load data with nibabel and convert it into ants image, we might be losing some information about the data.

**Comment by dipterix** [comment]
@cookpa I recently encountered the [same issue](https://github.com/beauchamplab/raveio/issues/20) in both ANTsPyx 0.3.8 and 0.4.2. It seems that ANTs prioritizes `qform` over `sform`. I wonder if there is any chance in `apply_transforms` & image_read to specify which transform to prioritize?

**Comment by cookpa** [comment]
Unfortunately, there isn't really a way for us to control this, because the decision is made inside the ITK read image code. It used to prefer qform in general, but later versions prefer sform in general.

There is a restriction in ITK that the transform from voxel to physical space must be rigid. This can cause incompatibility with some programs that store an affine transform (eg, to MNI space) in the sform. In that case, I believe it will fall back to qform.

I wrote this wiki page on ANTs which explains the current algorithm as I understand it. 

https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F

I'd have to check exactly which ITK version ANTsPy 0.4.2 uses to know exactly what it's doing

**Comment by dipterix** [comment]
> There is a restriction in ITK that the transform from voxel to physical space must be rigid.

Ah got it... So ITK is still using qform essentially, but it's using sform to correct the precision issue (qform is floating precision while DICOM are double). Essentially it only uses sform when sform and qform refer to "identical" transforms. 

Thanks for clarification. Your answer and wiki helps a lot.
