### ISSUE TITLE
metricWeight & numberOfBins parameter in ANTsPy

### ISSUE THREAD

**Issue by amirreza1998** [ANTsX/ANTsPy#357]
hi 
i have problem with run ants.registration and ants.image_similarity
in ANTs i use
 `-m MI[$f,$m,1,32]`
that i specify metricWeight & numberOfBins  as 1 & 32 but in ANTsPy  i don't know exactly how should pass them to function of ants.registration and ants.image_similarity
`ants.image_similarity(fname1,fname2,metric_type="MattesMutualInformation")`

**Comment by ntustison** [comment]
Those parameters aren't exposed to the ANTsPy user.  In ANTs you would use ``MeasureImageSimilarity``.
