### ISSUE TITLE
ants.registration output with mismatching dimensions is misleading

### ISSUE THREAD

**Issue by poldrack** [ANTsX/ANTsPy#359]
**Describe the bug**
When ants.registration is run with a 3d fixed image and a 4d moving image, it appears to simply return a copy of the original 4d moving image in the warpedfixout slot, without raising any warnings or errors.  No transforms are returned.  An unsuspecting user might simply use the returned 4d data without actually checking whether it was modified.

**To Reproduce**

See https://github.com/poldrack/brainsss/blob/main/ants_testing/antsreg_issue.ipynb

(this example was done on simulated data, but the problem was originally identified on real data, so it's not artifact of using simulated data)

**Expected behavior**
1) The ants.registration documentation needs to be clearer regarding the expectations regarding dimensionality matching of the fixed and moving images
2) When non-conforming data are submitted (as in the example above), the function should at best raise an exception, or at least return None in the transformed image slots along with a warning.

 - OS: Unbuntu 20.04
 - Version: antspyx 0.3.2

**Comment by ntustison** [comment]
Okay, I think this has been addressed.  @poldrack please reopen if that is not the case.

**Comment by poldrack** [comment]
confirmed, it now raises an exception when provided with inappropriately sized data.
