### ISSUE TITLE
still cannot "import ants" on MacOS

### ISSUE THREAD

**Issue by ejolly** [ANTsX/ANTsPy#36]
Still experiencing the same issue reported in https://github.com/ANTsX/ANTsPy/issues/26 on Mac OSX. This includes `pip` installing using the new wheel: `antspy-0.1.5-cp36-cp36m-macosx_10_7_x86_64.whl` or the `pip install` command listed on the README. 

It still looks like the installation doesn't do the ITK/VTK checks and installs that are in the `setup.py` file. I've tried manually executing the bash scripts that are called in `setup.py` and set the environment variables, etc, but still get the same error. 

However, installing in linux (specifically Ubuntu 16.04 in a Docker container) using the README `pip install` command works just fine.

**Comment by ncullen93** [comment]
very sorry to hear that. can you post the error code you're getting again? It could be a million things with the mac os.

**Comment by ncullen93** [comment]
man oh man that is a gnarly error. i completely removed VTK from the build process for the time being, so that being an issue is weird. I'm guessing it's an xcode issue? can you successfully install ANTs and/or ANTsR?

**Comment by ejolly** [comment]
I'm currently building ANTs on my mac from scratch so I'll let you know in about ~40 min :). I guess I'm not sure why the pre-compiled binaries aren't working using the wheel, which would be awfully more convenient. Any thoughts on what specific xcode issue could be? My experience with CMake is extremely limited. 

In general I've never compiled ANTs from source before. In the past I've installed pre-compiled binaries inside an Ubuntu docker/singularity container. Then I typically interact with it via nipype which always works fine. This shows where I usually grab the pre-compiled `.tar.gz` file from: 

https://github.com/cosanlab/cosanToolsSingularity/blob/master/Singularity#L64

**Comment by ejolly** [comment]
Ok so compiling ANTs from scratch on macOS worked just fine and testing simple programs (e.g. `PrintHeader`) seem to work just fine. Re-trying the wheel install, or the `setup.py` install, still don't work after this.

**Comment by stnava** [comment]
i can reproduce the error on mac.   i can also install from source.

note that the officially compatible vtk=>itk=>ants (pre itk v5) setup, wrt OpenGL, is here:

```
https://github.com/ANTsX/ANTs/blob/master/SuperBuild/External_VTK.cmake#L73-L103
```
my guess is that this error comes from the whl being built with some expectation of VTK existing.

we can see that this is the case by looking at the `configure_ITK*sh` scripts which have:

```
-DModule_ITKVtkGlue:BOOL=ON
```

this should be set to OFF if VTK is not available/used.

**Comment by ncullen93** [comment]
ok i set that to OFF. will recompile the wheel and re-upload, then hopefully that will work.

**Comment by stnava** [comment]
one other point: we also use
```
      -DBUILD_SHARED_LIBS:BOOL=OFF
```

**Comment by stnava** [comment]
the source compile may work now on osx and linux with recent commits

if you try it, be sure to do `pip uninstall ants`  beforehand to get rid of any junk wheels.

this does not include vtk support ( and may also allow you to read/cast short type )

**Comment by idc9** [comment]
I'm getting the same error as @ejolly above when I try to install `antspy` using method one on my mac. In particular, when I run

```
pip install https://github.com/ANTsX/ANTsPy/releases/download/Weekly/antspy-0.1.4a0-cp36-cp36m-macosx_10_7_x86_64.whl
```

```
import ants
```
I get 

```
ImportError: dlopen(/Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/ants/lib/antiAlias.cpython-36m-darwin.so, 2): Library not loaded: libvtkRenderingOpenGL2-8.1.1.dylib
  Referenced from: /Users/iaincarmichael/anaconda/envs/py36/lib/python3.6/site-packages/ants/lib/antiAlias.cpython-36m-darwin.so
  Reason: image not found
```

I'm using python 3.6 on a macOS Version 10.13.4.

**Comment by kaizhang-nines** [comment]
The problem seems to be the lack of VTK. 
This works for me:
1. Compile ANTs from source first. 
2. Install ANTsPy with either pip or setup.py.

**Comment by thefabus** [comment]
Could you elaborate more on how you got it installed? When installing the wheels I get the same issue. When compiling from source, the stage that compiles ANTs fails:

`/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:393:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 2>, itk::Image<float, 2>, itk::Image<float, 2>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2>,
      itk::Image<float, 2>, itk::Image<float, 2>, double> >'
      mimetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:558:51: note: in instantiation of function template specialization 'invariantImageSimilarity<itk::Similarity2DTransform<double>, 2>' requested here
  m.def("invariantImageSimilarity_Similarity2D", &invariantImageSimilarity<itk::Similarity2DTransform<double>,2>);
                                                  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:395:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::CorrelationImageToImageMetricv4<itk::Image<float, 2>, itk::Image<float, 2>, itk::Image<float, 2>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2>, itk::Image<float, 2>,
      itk::Image<float, 2>, double> >'
      gcmetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:393:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 3>, itk::Image<float, 3>, itk::Image<float, 3>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3>,
      itk::Image<float, 3>, itk::Image<float, 3>, double> >'
      mimetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:559:51: note: in instantiation of function template specialization 'invariantImageSimilarity<itk::Similarity3DTransform<double>, 3>' requested here
  m.def("invariantImageSimilarity_Similarity3D", &invariantImageSimilarity<itk::Similarity3DTransform<double>,3>);
                                                  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:395:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::CorrelationImageToImageMetricv4<itk::Image<float, 3>, itk::Image<float, 3>, itk::Image<float, 3>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3>, itk::Image<float, 3>,
      itk::Image<float, 3>, double> >'
      gcmetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:393:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 2>, itk::Image<float, 2>, itk::Image<float, 2>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2>,
      itk::Image<float, 2>, itk::Image<float, 2>, double> >'
      mimetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:560:46: note: in instantiation of function template specialization 'invariantImageSimilarity<itk::Euler2DTransform<double>, 2>' requested here
  m.def("invariantImageSimilarity_Rigid2D", &invariantImageSimilarity<itk::Euler2DTransform<double>,2>);
                                             ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:395:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::CorrelationImageToImageMetricv4<itk::Image<float, 2>, itk::Image<float, 2>, itk::Image<float, 2>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 2>, itk::Image<float, 2>,
      itk::Image<float, 2>, double> >'
      gcmetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:393:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::MattesMutualInformationImageToImageMetricv4<itk::Image<float, 3>, itk::Image<float, 3>, itk::Image<float, 3>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3>,
      itk::Image<float, 3>, itk::Image<float, 3>, double> >'
      mimetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:561:46: note: in instantiation of function template specialization 'invariantImageSimilarity<itk::Euler3DTransform<double>, 3>' requested here
  m.def("invariantImageSimilarity_Rigid3D", &invariantImageSimilarity<itk::Euler3DTransform<double>,3>);
                                             ^
/Users/koesterlab/code/ANTsPy/ants/lib/LOCAL_invariantImageSimilarity.cxx:395:17: error: no member named 'SetUseFixedSampledPointSet' in 'itk::CorrelationImageToImageMetricv4<itk::Image<float, 3>, itk::Image<float, 3>, itk::Image<float, 3>, double, itk::DefaultImageToImageMetricTraitsv4<itk::Image<float, 3>, itk::Image<float, 3>,
      itk::Image<float, 3>, double> >'
      gcmetric->SetUseFixedSampledPointSet( true );
      ~~~~~~~~  ^
12 errors generated.
make[2]: *** [CMakeFiles/invariantImageSimilarity.dir/LOCAL_invariantImageSimilarity.cxx.o] Error 1
make[1]: *** [CMakeFiles/invariantImageSimilarity.dir/all] Error 2
make: *** [all] Error 2
`

Compiling ANTs by itself works fine.

**Comment by stnava** [comment]
i doubt wheels will work - they are quite old.    perhaps a user will want to contribute wheel builds or a modification to travis.yml to automate their builds.

source install is:

```
 python setup.py install
```

**Comment by sromanz** [comment]
Hello!

I cloned the repository and tried to install from source using `python setup.py install` on a macos 10.14(Mojave) and Xcode 10.0.

VTK compiled without any problem. 
ITK compilation failed with these errors: 

> ~/src/ANTsPy/ants/lib/antscore/ReadWriteData.h:289:12: error: no viable conversion from returned value of type 'std::__1::nullptr_t' to function return type
>       'typename Image<double, 2>::Pointer' (aka 'SmartPointer<itk::Image<double, 2> >')

> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__nullptr:49:17: note: expanded from macro 'nullptr'
#define nullptr _VSTD::__get_nullptr_t()
                ^~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__config:447:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^
~/src/ANTsPy/ants/lib/antscore/ReadWriteData.h:416:45: note: in instantiation of function template specialization 'ReadImage<itk::Image<double, 2> >' requested here
  typename TImage::Pointer intensityImage = ReadImage<TImage>( (char *)imageFile );

**Comment by thefabus** [comment]
`python setup.py install` is what I tried. Xcode 9.2, macOS 10.13.6.
As a workaround, this old fork `https://github.com/stnava/ANTsPy.git` compiled without any problems.

**Comment by sromanz** [comment]
Thanks, this worked perfectly !

**Comment by thefabus** [comment]
Glad to hear it worked for you. However, given that this fork lacks about a year worth of commits this should not be the final solution to install on macOS.

**Comment by ejolly** [comment]
I also can't get the latest github version to install from source (i.e. cloning and running `python setup.py install`) on macOS 10.14 and Xcode 10.0. 
The error seems related to installing ITK: 
CMake Error at CMakeLists.txt:10 (find_package):
```
  By not providing "FindITK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ITK", but
  CMake did not find one.

  Could not find a package configuration file provided by "ITK" with any of
  the following names:

    ITKConfig.cmake
    itk-config.cmake
```
Also it doesn't look like the `setup.py` file can parse `--novtk` or `--noitk` flags despite what the README says; `setup.py` just errors out.

The old fork suggsted by @thefabus installs just fine for me using the same command as above. It's currently the only version of antspy that I can get working reliably on any macOS system :( 

However, that fork had a problem for me reading in 4d files (e.g. fMRI EPI series). @stnava I added a quick fix to my own fork, of that fork, that can read 4d files without the keyerror and created a PR: https://github.com/ejolly/ANTsPy

**Comment by stnava** [comment]
i've tested python3 on linux and osx - python2.x wont work ( using the current main ANTsX branch ).

there are several performance improvements in the latest version.

also, travis linux build should be working.    may potentially generate some new wheels relatively soon.

best,

b.a.

**Comment by stnava** [comment]
updated / wheels + release
