### ISSUE TITLE
Documentation: make clear that ants.image_similarity is actually a distance measure

### ISSUE THREAD

**Issue by poldrack** [ANTsX/ANTsPy#360]
**Describe the bug**
ants.image_similarity appears to be misnamed, as it actually reports image dissimilarity.

**To Reproduce**

computing correlation similarity of an image with itself:

```
testimg = ants.from_numpy(np.random.randn(20,20,20))
ants.image_similarity(testimg, testimg, metric_type='Correlation')
```

returns -1.0

**Expected behavior**
a measure of image similarity should be maximal for an image with itself.  
In the best of all worlds you would create a new function called something like `image_distance()` and deprecate image_similarity.  But at least it would be good to clearly state in the docstring that `image_similarity()` actually returns distances.

**Comment by gdevenyi** [comment]
ITK/ANTS use negative similarity for their optimizers.

**Comment by ntustison** [comment]
Naming is not a mistake but is simply based on consistency with ITK convention (image similarity measures are optimized during registration by minimizing the value).  This is also consistent across the ANTsX ecosystem (e.g., ``MeasureImageSimilarity``).  The only thing we might consider changing is adding clarifying documentation.  Pull requests are welcome.

**Comment by poldrack** [comment]
most users of antspyx will not be ITK experts so it's important to clarify this. I've pushed a PR ( #361) for image_similarity but might be good to clarify for others as well.
