### ISSUE TITLE
Possible to install on top of existing ANTs install

### ISSUE THREAD

**Issue by blakedewey** [ANTsX/ANTsPy#368]
Is it possible to install ANTsPy on top of an existing ANTs install without rebuilding all of the libraries? We have lots of existing ANTs installs (in containers, etc.) and we'd like to explore ANTsPy as an interface to those packages.

**Comment by stnava** [comment]
it's possible but you would have to make changes to the existing code base (in antspy) to do so.

**Comment by blakedewey** [comment]
Any pointers where to start? I'd be happy to look into making this work in an optional way.

**Comment by stnava** [comment]
take a look at the setup.py and follow the leads from there.   you might also look way back into the beginning of the history to see how we did this back then - it's fine but not easy to maintain.
