### ISSUE TITLE
Images not aligned when applying inverse transform

### ISSUE THREAD

**Issue by willi3by** [ANTsX/ANTsPy#374]
**Describe the bug**
I am attempting to align two images using a rigid body transformation, then applying the inverse of the registration. The initial registration works as expected but the application of the inverse does not give expected results. See screenshots for details. The first screenshot is the initial alignment and the second is the application of the inverse to the original fixed image. 

**To Reproduce**
The call for the registration is:
```
flair_txfm = ants.registration(fixed=flair_bet, moving=flair_ref, type_of_transform="Rigid")
```
Then I apply the inverse with:
```
flair_bet_reg = ants.apply_transforms(moving=flair_bet, fixed=flair_ref, transformlist=flair_txfm['invtransforms'])
```

The images are:
**flair_bet**:
ANTsImage (RPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (512, 512, 26)
	 Spacing    : (0.4297, 0.4297, 5.9996)
	 Origin     : (-138.1599, 33.0662, -70.0059)
	 Direction  : [ 0.9421  0.3352 -0.0132  0.3343 -0.9347  0.1211 -0.0282  0.1185  0.9926]

**flair_ref**:
ANTsImage (RPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (156, 156, 36)
	 Spacing    : (1.1667, 1.3974, 5.0556)
	 Origin     : (-90.0, 126.0, -72.0)
	 Direction  : [ 1.  0.  0.  0. -1.  0.  0.  0.  1.]

**Expected behavior**
I would expect the second step (applying inverse) to generate similar results to the initial transformation. In other words, I would expect the images to be aligned. 

**Screenshots**
<img width="462" alt="CleanShot 2022-05-31 at 14 51 10@2x" src="https://user-images.githubusercontent.com/42728698/171263520-7e082e4c-b48a-4377-8a1d-bbbd59a92211.png">

<img width="391" alt="CleanShot 2022-05-31 at 14 52 02@2x" src="https://user-images.githubusercontent.com/42728698/171263541-d607f74f-4ad9-412d-b8de-729bfe7c797c.png">

**Environment**
 - OS: MacOS 11.5
 - antspy 0.3.2
 - python 3.9

Please let me know if you need any other info. 

Thanks!

**Comment by ntustison** [comment]
What are you using for visualization?

**Comment by willi3by** [comment]
My apologies. I should have included that. The first screenshot was generated with:
flair_bet.plot(overlay=flair_txfm['warpedmovout'], overlay_alpha=0.5)

The second was generated with:
flair_ref.plot(overlay=flair_bet_reg, overlay_alpha=0.5)

Thanks

**Comment by stnava** [comment]
probably need invert=True or invert=[True]

**Comment by ntustison** [comment]
Can you post the data?

**Comment by willi3by** [comment]
Sure. Let me know if this works.
[T2_FLAIR_bet.nii.gz](https://github.com/ANTsX/ANTsPy/files/8809788/T2_FLAIR_bet.nii.gz)
[T2_FLAIR_template_resamp_low.nii.gz](https://github.com/ANTsX/ANTsPy/files/8809791/T2_FLAIR_template_resamp_low.nii.gz)

Where the T2_FLAIR_bet.nii.gz is `flair_bet` and T2_FLAIR_template_resamp_low.nii.gz is `flair_ref`

**Comment by ntustison** [comment]
<img width="830" alt="Screen Shot 2022-05-31 at 4 06 51 PM" src="https://user-images.githubusercontent.com/324811/171298113-a651f8bd-a292-4ea3-b535-4506a4386768.png">

Turn on the verbose output and make sure your output looks something like:
```
>>> flair_bet_reg = ants.apply_transforms(flair_ref, flair_bet, transformlist=flair_txfm['invtransforms'], whichtoinvert=[True], verbose=True)
['-d', '3', '-i', '0x600002c30d80', '-o', '0x600002c246c0', '-r', '0x600002c24780', '-n', 'linear', '-t', '[/var/folders/ty/33w2ntbj3kn_m_8jxvkzh6t80000gn/T/tmphzmyojtr0GenericAffine.mat,1]']
Using single precision for computations.
Input scalar image: 0x600002c30d80
Reference image: 0x600002c24780
=============================================================================
The composite transform comprises the following transforms (in order): 
  1. inverse of /var/folders/ty/33w2ntbj3kn_m_8jxvkzh6t80000gn/T/tmphzmyojtr0GenericAffine.mat (type = AffineTransform)
=============================================================================
Default pixel value: 0.0000e+00
Interpolation type: LinearInterpolateImageFunction
Output warped image: 0x600002c246c0
>>> ants.image_write(flair_bet_reg, "~/Desktop/inverseWarped.nii.gz")
>>> flair_ref.plot(overlay=flair_bet_reg, overlay_alpha=0.5)
```

**Comment by willi3by** [comment]
That did it! I used the incorrect flag invert=[True] instead of whichtoinvert=[True]. Sorry about the confusion and thanks for the help. 

Just out of curiosity, why is it necessary to both apply the inverse transform and indicate whichtoinvert? 

Thanks again

**Comment by ntustison** [comment]
The set of "inverse transforms" is simply the list of transform files stored in the correct order.  However, in the case of a linear transform, we only write the forward transform to disk and depend on the user to specify the linear transform which needs to be inverted on the fly.  It's a bit suboptimal but this choice is also based on a legacy relationship with both the ANTsR implementation and the original C++ command line version.
