### ISSUE TITLE
Modes of calling ants.registration

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPy#375]
Hi @stnava @ntustison , I'm working on a fix to catch registration failures and raise appropriate exceptions, while in the code I noticed there are some undocumented alternative ways of calling registration. The first appears to be using a list as the fixed image:

https://github.com/ANTsX/ANTsPy/blob/a05ff4bda6fe5c53f54f92d1e669f5246e321de4/ants/registration/interface.py#L213-L217

which I think is saying to process the list as command line args and run the program. This reminds me of ANTsR where one could pass a list of command line args like `["-d", "3", "-t", "-f", "2x1",...]`.

The case that puzzles me is on L317, if fixed is a string, append some args and then call libfn:

```
    if not isinstance(fixed, str):
       # Do normal arg processing assuming fixed is an ants.image
```

This matches an else on L1456:

```
    else:
        args.append("--float")
        args.append("1")
        args.append("--write-composite-transform")
        args.append(write_composite_transform * 1)
        if verbose:
            args.append("-v")
            args.append("1")
            processed_args = utils._int_antsProcessArguments(args)
            libfn = utils.get_lib_fn("antsRegistration")
            libfn(processed_args)
            return 0
```

But I think this can not work because all the work of making an `args` array that the ANTs CLI would understand is in the above `if` statement, and will be skipped. Also, it will only run anything if the verbose option is True, which seems strange. In any case, if "fixed" is a string, the NaN checks on L228 will fail, so this block is unreachable

https://github.com/ANTsX/ANTsPy/blob/a05ff4bda6fe5c53f54f92d1e669f5246e321de4/ants/registration/interface.py#L228

I'm thinking to remove the if statement, and check that if fixed is not a list, it is in fact an ants.image. But I want to ask in case I've missed something and there's some use case where "fixed" is a string, that should be supported?

**Comment by ntustison** [comment]
Yeah, it looks like this is probably wrong.

**Comment by stnava** [comment]
agree - not sure it's worth supporting filenames
