### ISSUE TITLE
installations issues with CentOS7 affecting 0.3.3 and 0.3.2

### ISSUE THREAD

**Issue by rueberger** [ANTsX/ANTsPy#381]
couple of potentially related issues here

- pip ignores the wheel and installs the sdist for 0.3.3
- `setup.py install` fails similarly to #274 for 0.3.3 and 0.3.2

I did not test older versions.

pip installs the wheel with no problems for 0.3.2

Tried building from source with pip and by directly checking out the source, all resulted in:

```
  CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindITK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ITK", but
  CMake did not find one.

  Could not find a package configuration file provided by "ITK" with any of
  the following names:

    ITKConfig.cmake
    itk-config.cmake

  Add the installation prefix of "ITK" to CMAKE_PREFIX_PATH or set "ITK_DIR"
  to a directory containing one of the above files.  If "ITK" provides a
  separate development package or SDK, be sure it has been installed.
```

# Environment 

CentOS 7.9.2009
Python 3.9
cmake 3.23.1

cycler==0.10.0
distlib==0.3.4
filelock==3.6.0
imageio==2.19.3
joblib==1.1.0
kiwisolver==1.3.1
matplotlib==3.4.2
networkx==2.8.4
nibabel==4.0.1
numpy==1.20.3
packaging==21.3
pandas==1.3.1
patsy==0.5.2
Pillow==9.1.1
platformdirs==2.5.2
pyparsing==3.0.9
python-dateutil==2.8.1
pytz==2021.1
PyWavelets==1.3.0
scikit-image==0.19.3
scikit-learn==1.0.2
scipy==1.6.3
six==1.16.0
statsmodels==0.13.2
threadpoolctl==3.0.0
tifffile==2022.5.4
torch==1.11.0a0+gitunknown
virtualenv==20.14.1

**Comment by tangqishi** [comment]
I met with the same problem. Have you solved it?
