### ISSUE TITLE
Multi resolution (quantitatively)/"reg_iterations"

### ISSUE THREAD

**Issue by ninusch** [ANTsX/ANTsPy#385]
I have a question concerning the „reg_iterations“ parameter. I understand that this is the iterations per level in Multi resolution but how does the resolution change between the levels? The respective resolution in mm or also the ratio between two levels would be great to know. I couldn’t find it in the source code unfortunately. Thanks already!

**Comment by ntustison** [comment]
If you choose the verbose option, it should print the ``--shrink-factors`` which tells you how the resolution changes between levels.  [This](https://itk.org/Doxygen/html/classitk_1_1ShrinkImageFilter.html) is the underlying filter in case you need more detail.
