### ISSUE TITLE
Kelly Kapowski algorithm  for computing cortical thickness takes too long to execute

### ISSUE THREAD

**Issue by InderdeepSync** [ANTsX/ANTsPy#388]
Hi,
I need to compute the cortical thickness of a 3D t1-weighted image (.nii.gz) of dimensions 256 by 256 by 256, but the `ants.segmentation.kelly_kapowski` function simply takes too long to complete. I cannot downsize the image to a lower dimension as I cannot afford to lose precision.

I have set the environmental variable as follows =>  `os.environ["ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS"] = "8"`, in accordance with one of the other issue comments. But that still isn't enough. Apparently there is no GPU support to accelerate this function. If there is, I'd love to know more about it.

Here's the nifti image => [https://file.io/q5z0PS5GuGnD](https://file.io/q5z0PS5GuGnD)

Here's the code I am executing:
```

img = ants.image_read('./images/raw_t1_subject_01.nii.gz')
mask = ants.get_mask( img )
segs = ants.kmeans_segmentation( img, k=3, kmask = mask)
thick = ants.kelly_kapowski(s=segs['segmentation'], g=segs['probabilityimages'][1],
                                w=segs['probabilityimages'][2], its=45,
                                r=0.5, m=1)
```

This has been directly borrowed from the docs. 

Am I missing something? Is there some optimization I could do? I really need to get this done, but there isn't enough help out there for those unfamiliar with medical imaging concepts.

Please help me out. What steps can I take to utilize this library to accomplish the task? Is there some other function that might be the right-fit for my use? Kindly let me know.

**Comment by cookpa** [comment]
The link doesn't work for me.

What system is this running on? How long does it take to run? How much faster do you need it to be?

**Comment by InderdeepSync** [comment]
Wow. I appreciate the quick response.

> The link doesn't work for me.

I apologize. Here it is: [raw_t1_subject_01.nii.gz](https://github.com/ANTsX/ANTsPy/files/9218197/raw_t1_subject_01.nii.gz)


> What system is this running on?

The system is somewhat old actually. Here's the output of the `lscpu` command:

```
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    CPU family:          6
    Model:               78
    Thread(s) per core:  2
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            3
    CPU(s) scaling MHz:  96%
    CPU max MHz:         2800.0000
    CPU min MHz:         400.0000
    BogoMIPS:            4801.00
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art a
                         rch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse
                         4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi 
                         flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida ara
                         t pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
Virtualization features: 
  Virtualization:        VT-x
Caches (sum of all):     
  L1d:                   64 KiB (2 instances)
  L1i:                   64 KiB (2 instances)
  L2:                    512 KiB (2 instances)
  L3:                    3 MiB (1 instance)
NUMA:                    
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:         
  Itlb multihit:         KVM: Mitigation: VMX disabled
  L1tf:                  Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
  Mds:                   Mitigation; Clear CPU buffers; SMT vulnerable
  Meltdown:              Mitigation; PTI
  Mmio stale data:       Mitigation; Clear CPU buffers; SMT vulnerable
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
  Srbds:                 Mitigation; Microcode
  Tsx async abort:       Not affected
```
If there is something specific you're looking for, let me know which command I may execute to get it for you. I am running `Linux 5.15.55-1-MANJARO #1 SMP PREEMPT x86_64 GNU/Linux`.


> How long does it take to run?

That's the problem. It's been running for over nine hours now. Have no idea how long it might go on.

> How much faster do you need it to be?

Ideally, I need it to complete execution within an hour, I guess. I am no expert in medical imaging by any means. 

I am willing to make optimizations & put in some work to reduce the execution time, even if it means having a solution that isn't truly perfect (in terms of smoothness or other parameters, perhaps). I cannot reduce downscale it though. I had tried, and the algorithm does complete if the image is downgraded to 64 by 64 by 64 from the original 256 by 256 by 256, but then the resolution is lost.

I did try to crop out the parts of image on the sides which are simply zeros, but I am not sure if the `ants.kmeans_segmentation` function would work as expected then.

I have no idea what values to pass to parameters such as `r `and `s` in the above function call. I am just passing the values shown in docs. Maybe changing those to something else might do the trick? Would  be grateful for suggestions. 

Would performing some preprocessing on the image data help make it go faster? Is there something we can do to help the function reach convergence faster?

I tried this function `ants.segmentation.kelly_kapowski` on the image provided by `ants.get_ants_data('mni')`, following same steps as outlined in last comment. It did complete successfully, though I cannot recall how long it took. Should have timed it. This leads me to believe there must be some workaround to convince the algorithm to terminate for this input as well.

I am all out of ideas. Kindly help me out. I really need to get this done, but I do not possess the domain knowledge and expertise to figure this out. 

Thank you for your assistance.

**Comment by cookpa** [comment]
I ran the code and looked at the output in ITK-SNAP. The default masking did not do a good job, which will result in extra work for KellyKapowski.

<img width="754" alt="image" src="https://user-images.githubusercontent.com/611507/181793835-c76ce33a-c680-429d-ae5c-9ad718139278.png">

The fastest way to improve this would be to use the [ANTsPyNet cortical thickness pipeline](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/cortical_thickness.py). Alternatively, use one of the ANTs templates (https://figshare.com/articles/dataset/ANTs_ANTsR_Brain_Templates/915436) like the OASIS template, to register the subject brain and then warp a brain mask and priors to the subject space for a prior-based segmentation using six classes - it will segment subcortical GM, brainstem, and cerebellum separately. You only want to compute thickness on cortical GM.

Thickness computation is completely dependent on a good segmentation, don't bother to run kelly_kapowski until you're happy with the segmentation.

One other thing I noticed about the data, it appears to have been preprocessed and truncated quite severely, such that there is little contrast in the frontal white matter. This may result in worse segmentation, but I think it's not the biggest concern. Getting a good brain extraction and then doing a six-class segmentation will reduce the workload for computing thickness significantly.

**Comment by InderdeepSync** [comment]
Hi,
Thank you for the information. It was very helpful.

I used the AntsPyNet pipeline as you had suggested in a Google Colab Notebook. I had not set the environment variable `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS` at this time (to get a better understanding of the execution time), but had configured the runtime to have GPU (within the free tier). 

I am glad to report that it did produce a solid output after running for 2 hours 51 minutes. The verbosity argument of the function being set certainly helped as well.

I am very happy with the results. Have shared a screenshot from the MRIcron interface for anyone who would like to see a sample of what the results might end up looking like.
![Screenshot from 2022-07-30 02-58-00](https://user-images.githubusercontent.com/54172887/181845587-5f101fa3-b70a-422c-9484-fab65ee6c55d.png)

The quality of the image is superior. My only question now is whether its possible to improve the overall runtime any further. Is there a way to communicate to the algorithm to terminate processing early, even at the cost of achieving, say only 80% perfection, solely in order to save processing and time.

I imagine this is a very common use case. Is there some combination of `r` and `w` parameters being passed to `kelly_kapowski` that might achieve this. Ordinarily, I would do a trial-and-error, but given the huge execution times, it is very time-consuming. 

I have no prior experience in this field. Would it be possible for you to perhaps tell me how to achieve this use case. I would like to improve its execution by at least 6 times.

Once again, thank you for your help. I really appreciate your guidance and time.

**Comment by InderdeepSync** [comment]
I just examined the pipeline code in AntsPyNet closely and there is an `its` parameter to specify the number of iterations. Let me try to tweak that and observe the difference in time taken to execute. Might just work

**Comment by InderdeepSync** [comment]
Hi,
I reran the algorithm with `its` parameter to `kelly_kapowski` equal to 1 instead of the default 45 configured in the `cortical_thickness` pipeline. The execution time reduced by around by a meager 15-20 mins only. It seems to me that the first iteration takes the longest, while the subsequent iterations are primarily contributing to refining the resultant image somehow.

It still took around 2 hours 35 mins on Google Colab with free tier GPU (Same setup as last time, but with fewer iterations).

I measured, and the segmentation process using `deep_atropos` isn't taking too long at all(less than 4 mins). 

The `kelly_kapowski` call is the culprit here. Could you please suggest some way to speed up this function call further? 

Looking forward to your response. Thank you!

**Comment by cookpa** [comment]
With two threads on the latest Intel Mac, I ran KK in a little over an hour. I don't know the specs of the machine you're running on, but you want to use all the available cores, and ensure there's enough RAM.

**Comment by cookpa** [comment]
Looks like the "its" parameter is not working properly, I'll fix that.

**Comment by cookpa** [comment]
Immediate workaround is to use `its="[25]"`, or whatever number of iterations you have. This should speed things up. The trade-off between its and accuracy is likely data dependent and something you would have to evaluate yourself.

**Comment by cookpa** [comment]
Iterations spec fixed in #389

**Comment by InderdeepSync** [comment]
> Iterations spec fixed in #389

Great! Thank you.


> The trade-off between its and accuracy is likely data dependent and something you would have to evaluate yourself.

Alright.

**Comment by InderdeepSync** [comment]
I do have another issue. Upon running `deep_atropos` available in `antspynet.utilities`, sometimes (not always though) I am getting this warning:

```
WARNING:tensorflow:5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fc8c0628d40> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7fc8c0628680> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
```

I verified this by running `antspynet.utilities.deep_atropos` multiple times. There doesn't seem to be a pattern to this occurrence. At least none that I could observe. My question is that why do I get it sometimes, but not always? 

I know its only a warning, but for the same data input, I don't expect such behavior. Is this acceptable?

**Comment by InderdeepSync** [comment]
Also, one last thing - are you aware of `kelly_kapowski` yielding inconsistent results when executing the pipeline on Google Colab? I was executing the code available in [https://colab.research.google.com/drive/1S83yqq-UulxFusy6TVf4v4MYW-iLkk4-?usp=sharing](url). This is pretty much inspired from the antspynet pipeline, except I modified it to exclude those parts I was never going to need for my particular use-case. Nothing new has been added. It is a very carefully extracted subset of the utilities and functions available in `antspynet`. I can assure you the code here is logically equivalent to the pipeline, as it is mostly borrowed from there. You see, I cannot have a dependency on `antspynet`.

I have successfully run the above notebook a few times on two images. The image to process may be specified via `t1_image_path` within the notebook. But it seems occasionally I get erroneous results. 

I have tested this several times before seeking clarification. I am sure of this. For instance, upon running the above notebook code on the image: [raw_t1_subject_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9264156/raw_t1_subject_02.nii.gz), on two SEPARATE runs, I have obtained the following vastly different thickness outputs:
 - [mine_thickness_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9264137/mine_thickness_sub_02.nii.gz). This is incorrect. It is to be noted that the algorithm did terminate a little faster than usual during this run.
 - [faulty_thickness_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9264133/faulty_thickness_sub_02.nii.gz). This output is perfect.

For the same code and input, I have obtained two outputs. I really do need the algorithm to be consistent. 

Do you have any idea what might be causing such varying results? Could the execution environment have anything to do with it?

I am at my wits end here. Is the incorrect output image indicative of something?

**Comment by ntustison** [comment]
Are you able to reproduce these errors using the antspynet utilities?

**Comment by ntustison** [comment]
I mean just using antspynet utilities.

**Comment by InderdeepSync** [comment]
> I mean just using antspynet utilities.

It takes too much time to run. Almost 2.5hrs on Google Colab. There isn't much scope for trial and error here. I like to be exhaustive with my experimentation, but time is a huge factor here. I only have limited computation time on Colab before I am throttled.

> Upon running `deep_atropos` available in `antspynet.utilities`, sometimes (not always though) I am getting this warning

This one I have seen several times with the official `antspynet` utilities as well, not just mine. This function takes around 3 minutes to run, hence testing was possible.

**Comment by ntustison** [comment]
> It takes too much time to run. Almost 2.5hrs on Google Colab. 

I'm confused, then---how does Google Colab allow you to test in a way that you can't with the antspynet pipeline?

Regardless, the problem is that you're running a modified pipeline on a platform that we don't support.  And despite your assurances that your modifications are sound, we've been using kelly kapowski in large-scale studies for quite some time and so I would guess that the issue is due to platform-specific issues and/or your modifications.  So in order for me to look more closely at this problem, you would have to reproduce the errors using strictly our code on a platform that we support.

**Comment by InderdeepSync** [comment]
> on a platform that we don't support

Is Google Colab not supported? I wasn't aware of that. I do not have GPU configured on my system, hence I was leveraging the free tier from Colab. I tried running the official pipeline again, but was throttled halfway through execution. Might give it another shot later.

> how does Google Colab allow you to test in a way that you can't with the antspynet pipeline

Again, I just can't have the explicit dependency on `antspynet` in my project due to certain constraints. Colab simply offers a fast way to get started, nothing more than that.

> I would guess that the issue is due to platform-specific issues and/or your modifications.

In order to ascertain once and for all whether it is my modifications that caused the problem or not, I executed my version of `deep_atropos` from the notebook and the official version separately and compared the outputs, namely, the segmentation image, and the white and grey probability priors. The following are the results:

 - Official `antspynet.utilities.deep_atropos` results: 
 [official_segment_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9270483/official_segment_sub_02_xxx.nii.gz),
  [official_white_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9269871/official_white_sub_02.nii.gz), 
[official_gray_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9269874/official_gray_sub_02.nii.gz)

- My Modified deep_atropos (from the notebook) results: 
[mine_white_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9270495/mine_white_sub_02.nii.gz)
[mine_grey_sub_02(1).nii.gz](https://github.com/ANTsX/ANTsPy/files/9270504/mine_grey_sub_02.1.nii.gz)
[mine_segment_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9270493/mine_segment_sub_02.nii.gz)

These outputs were obtained on [raw_t1_subject_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9270520/raw_t1_subject_02.nii.gz).

As you may verify, these results match exactly. I am inclined to believe my minor modifications were not the cause for faulty results.

If I were to examine the `antspynet.utilities.cortical_thickness` pipeline closely, at a high level, the `deep_atropos` is responsible for a good segmentation via deep learning. Now the output images from `deep_atropos` are subsequently passed into `kelly_kapowski`, which is some sort of a wrapper over an underlying `.cxx` file that is the actual algorithm. 

Since the modified deep_atropos I have has been verified to work correctly, I assumed there might be a probabilistic element to `kelly_kapowski` itself, where it might give a wrong result sometimes. I haven't touched the `kelly_kapowski` at all. The exact same arguments are being passed.

Is there any reason why the code would yield different outputs for same input during different runs? As you said, I suspect there might be something platform specific that is causing this, which may not even be possible to determine.

I would not have bothered you if I was unable to generate the desired result even once, but the code did work at least once.

**Comment by ntustison** [comment]
> Since the modified deep_atropos I have has been verified to work correctly, I assumed there might be a probabilistic element to kelly_kapowski itself, where it might give a wrong result sometimes. I haven't touched the kelly_kapowski at all. The exact same arguments are being passed.  Is there any reason why the code would yield different outputs for same input during different runs? As you said, I suspect there might be something platform specific that is causing this, which may not even be possible to determine.

Thanks.  This is the kind of thing we need to know.  But, no, there isn't a probabilistic element in kk which sometimes results in an incorrect result.  We've run it on multiple large-scale data sets including all ~50000 UK Biobank image subjects and haven't encountered this issue where the segmentation is correct but the thickness results are not.  But we don't use Google Colab and so aren't aware of any potential nuances which might cause this (which is what I meant by Google Colab not being supported).

**Comment by InderdeepSync** [comment]
Thank you for your valuable insights. I really appreciate it :)

Google Colab was my only way of executing such complex code. It would have been helpful to have some resources in the form of computation power from my institution to facilitate this task.

At least I did obtain the thickness image once, so there's that.

> haven't encountered this issue where the segmentation is correct but the thickness results are not.

To summarize, may I safely conclude that if my version of `deep_atropos` produces a segmentation that is proper and matches the output generated by the original `antspynet.utilities.deep_atropos`, the subsequent `kelly_kapowski` algorithm would successfully return with the correct results with 100% certainty, in the presence of an environment officially supported?

**Comment by InderdeepSync** [comment]
Also, is there an official(or semi-official) list of supported environments for running `ants` programs?

**Comment by ntustison** [comment]
> To summarize, may I safely conclude that if my version of deep_atropos produces a segmentation that is proper and matches the output generated by the original antspynet.utilities.deep_atropos, the subsequent kelly_kapowski algorithm would successfully return with the correct results with 100% certainty, in the presence of an environment officially supported?

That would be a safe assumption to make.  I can't recall ever seeing an incorrect output if kk has the correct input.  In the basic pipeline steps for cortical thickness:  1) brain extraction, 2) brain segmentation, and 3) kk;  the kk step is probably the most robust.

> Also, is there an official(or semi-official) list of supported environments for running ants programs?

No, it is basically the platforms available to us which are primarily mac and linux.  The underlying ITK is much more explicit in specifying supported platforms and since ANTs is developed on ITK, ANTs should also work on those platforms as well but we don't have the resources to guarantee the same compatibility.

**Comment by InderdeepSync** [comment]
Alright, Thank you.

**Comment by cookpa** [comment]
So I understand, you're saying that if I do this:

```
import ants 
seg = ants.image_read('official_segment_sub_02_xxx.nii.gz')
gm = ants.image_read('official_gray_sub_02.nii.gz')
wm = ants.image_read('official_white_sub_02.nii.gz')

for idx in range(0,5):
  thick = ants.kelly_kapowski(seg, gm, wm, verbose=1)
  ants.image_write(thick, f"thickness{idx}.nii.gz")
```

it will return different results? I agree with @ntustison that this would be very surprising. As far as I know, kelly_kapowski is deterministic and should return identical results with identical input.

**Comment by InderdeepSync** [comment]
Hi @cookpa. yes, that is exactly what happened. I was bewildered as well. That's why I had shared the two distinct thickness outputs. I had thought maybe looking at the faulty image (in comparison to the correct one) might give at least an idea as to what might have potentially gone wrong in the algorithm execution.

**Comment by InderdeepSync** [comment]
I had a suggestion...

Here's the [code](https://gist.github.com/InderdeepSync/2706d7baccb80de9c3795ab47ddc1423) I am attempting to execute on Colab. I have thoroughly verified MULTIPLE times the correctness of the segmentation process.

Can you please attempt to run it once on your system? It should be a breeze on your system, and if the output is as expected, I can rest easy, and know that whatever the issue was can be chalked up to environment troubles on Colab. Testing on Google Colab has been not-so-pleasant until now, and I can't reasonably run this on my system. I just want it to execute correctly one final time.

I know this is beyond your responsibility, but I am quite stressed due to the nearing of the deadline and this last step has left me hanging.

This should be the expected output: [mine_thickness_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9271575/mine_thickness_sub_02.nii.gz)

I would be very, very grateful if you could kindly help me out here. I won't bother you anymore after this. :)

**Comment by cookpa** [comment]
I don't have time to run custom code, sorry. But I can confirm that `kelly_kapowski` is reproducible with your segmentation data, as it is with any other data I've tried.

We'll investigate bug reports if there's a reproducible **minimal** example with code and data. For `kelly_kapowski`, that would be reading in segmentation from disk and running it, as I posted upthread.

**Comment by InderdeepSync** [comment]
Okay, I thought as much.

One last question, then let's close this thread. 

> * [faulty_thickness_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9264133/faulty_thickness_sub_02.nii.gz). This output is incorrect.

This faulty output was run with `its=45`, instead of `its="[45]"` to `kelly_kapowski`. How many iterations would the algorithm have run in that particular case?
 
Is it possible the above faulty output is simply an intermediate state of the ultimate output to be achieved after subsequent iterations? Is it possible that in this run, the algorithm prematurely finished with fewer than necessary iterations, when it shouldn't have?

Kindly examine the wrong output and let me know your thoughts.
Thanks

**Comment by ntustison** [comment]
The screen dump should provide that information. Also, the default is 45 iterations for the underlying c++ code.

**Comment by InderdeepSync** [comment]
To the best of my recollection, I don't think info pertaining to each iteration was displayed, even with verbosity on.

Also, I tried the algorithm again, where input segmentation and priors supplied were perfect, but thickness_image output was faulty. Even though Google Colab is not officially supported, I see no obvious reason the environment should have any impact. After all, it's just C++ code. And behind the scenes, they are simply connecting you to a Linux VM. 

Not everyone has their system configured properly with GPU. Colab makes this domain more accessible. Any issues someone may come across there should at least be considered.

You already have the images and sufficient data, should you be interested in examining this closely later on. Maybe its something peculiar with the input image, if nothing else. Whatever the reason may be, the output is certainly incorrect, that I am sure of.

Feel free to close this issue.

**Comment by InderdeepSync** [comment]
This time, to be absolutely sure, I compared the results of my modified deep_Atropos and the official one as follows:
```
np.count_nonzero((result_mine["segmentation_image"] - result_official["segmentation_image"]).numpy())

np.count_nonzero((result_mine["probability_images"][2] - result_official["probability_images"][2]).numpy())

np.count_nonzero((result_mine["probability_images"][3] - result_official["probability_images"][3]).numpy())

np.count_nonzero((result_mine["probability_images"][4] - result_official["probability_images"][4]).numpy())
```
All of the above returned 0. If that doesn't convince you I haven't made a mistake while refactoring, I don't know what will. 

I have got to be missing something, I just am unable to see exactly what. I will try to run the algorithm with `its=[100]` as a last resort.

**Comment by cookpa** [comment]
Just following up on a few points

> This faulty output was run with its=45, instead of its="[45]" to kelly_kapowski. How many iterations would the algorithm have run in that particular case?

It would have run 45, according to my tests, which is the default. Any value of its as a simple integer was ignored. I tried to run its=5, but it did not work, and it ran the default 45 iterations. However, its="[5]" did run only 5.


> To the best of my recollection, I don't think info pertaining to each iteration was displayed, even with verbosity on.

It should be printed if you include "verbose=1" in the call. When I did this (on Mac OS Catalina, antspyx=0.3.3), I saw

```
Running DiReCT for 3-dimensional images.

  Iteration 1 (of 45).  Current energy = 0.793247.  
  Iteration 2 (of 45).  Current energy = 0.716175.  
  Iteration 3 (of 45).  Current energy = 0.673147.  
  Iteration 4 (of 45).  Current energy = 0.6462.  
  Iteration 5 (of 45).  Current energy = 0.628965.  
  Iteration 6 (of 45).  Current energy = 0.616111.  
  Iteration 7 (of 45).  Current energy = 0.604699.  
  Iteration 8 (of 45).  Current energy = 0.598498.  
  Iteration 9 (of 45).  Current energy = 0.593765.  
  Iteration 10 (of 45).  Current energy = 0.590559.  (convergence value = 0.0168671, threshold = 0)
```

and so on. I don't know how Colab handles terminal output, but this information should definitely have been printed.


> I have got to be missing something, I just am unable to see exactly what. I will try to run the algorithm with its=[100] as a last resort.

I think it would be more informative to convince Colab to print the verbose output, and look for clues there. The bad results look like local optimization failures, with reasonable values in some voxels and very large values in others, as though something was approaching division by zero. I've never seen this before.

I found one more possibility to reproduce the error - the images I used to test were from upthread: [official_segment_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9270483/official_segment_sub_02_xxx.nii.gz),
[official_white_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9269871/official_white_sub_02.nii.gz),
[official_gray_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9269874/official_gray_sub_02.nii.gz)

The posterior official_white_sub_02.nii.gz is the sum of the WM and "deep gray" (segmentation[4]). But the segmentation image did not have these two classes combined. So I'm running again with that modification.

**Comment by InderdeepSync** [comment]
Hi @cookpa, thank you for following up :)



> The bad results look like local optimization failures, with reasonable values in some voxels and very large values in others, as though something was approaching division by zero. I've never seen this before.

That's exactly the kind of insight I was hoping for. Really helpful in getting to the root cause. I appreciate you looking into it.

**Comment by cookpa** [comment]
[thicknessWithClass4.nii.gz](https://github.com/ANTsX/ANTsPy/files/9290344/thicknessWithClass4.nii.gz)
[official_segment_sub_02_xxx_replace4.nii.gz](https://github.com/ANTsX/ANTsPy/files/9290345/official_segment_sub_02_xxx_replace4.nii.gz)
[official_white_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9290347/official_white_sub_02.nii.gz)
[official_gray_sub_02.nii.gz](https://github.com/ANTsX/ANTsPy/files/9290350/official_gray_sub_02.nii.gz)

Thickness looks good to me. I'm attaching all the files again in case you want to try to reproduce in Colab. 

```
import ants
seg = ants.image_read('official_segment_sub_02_xxx_replace4.nii.gz.nii.gz')
gm = ants.image_read('official_gray_sub_02.nii.gz')
wm = ants.image_read('official_white_sub_02.nii.gz')

thick = ants.kelly_kapowski(seg, gm, wm, its=45, r=0.025, m=1.5, x=0, verbose=1)
ants.image_write(thick, f"thickness.nii.gz")
```
