### ISSUE TITLE
module 'ants.core.ants_image' has no attribute 'ANTsImage'

### ISSUE THREAD

**Issue by joellliu** [ANTsX/ANTsPy#39]
Hi, I recently install ANTsPy via 

`pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl`

when I try to convert numpy array to ants image by `ants.from_numpy()`

I get the following error message:

> /lib/python3.6/site-packages/ants/core/ants_image_io.py in _from_numpy(data, origin, spacing, direction, has_components)
    125     if not has_components:
    126         itk_image = libfn(data, data.shape[::-1])
--> 127         ants_image = iio.ANTsImage(pixeltype=ptype, dimension=ndim, components=1, pointer=itk_image,
    128                                    origin=origin, spacing=spacing, direction=direction)
    129         ants_image._ndarr = data
AttributeError: module 'ants.core.ants_image' has no attribute 'ANTsImage'

I check the aforementioned ants_image_io.py and there is no attribute called 'ANTsImage'. It seems to be a bug. 

Does anyone know how to fix that? Thanks a lot.

**Comment by joellliu** [comment]
I managed to compile and install antspy from source code, but still think that may be an issue to be solved.

**Comment by stnava** [comment]
You can look at the testing code in order to see examples of how the
function should be used

**Comment by ncullen93** [comment]
You installed the linux version of the code, so hopefully you are using Linux or there will be an issue. If there are any issues with actual code please let me know

**Comment by joellliu** [comment]
@ncullen93 I am using Linux actually. I'm not sure if that is a common problem.

**Comment by stnava** [comment]
I think you should look at the testing code to see how you should properly
call the function. If it doesn't work then you should provide a
reproducible example of the failure.

**Comment by joellliu** [comment]
@stnava OK, here's how the failure happens and it keeps happening in three computers.
System environment: Ubuntu 16.04 LTS, miniconda with python 3.6
First, I installed ANTsPy via: 
`pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl`
Then, the failure happens if I run the following code:
<pre>import numpy as np
import ants
image_array = np.random.random((512, 512))
image = ants.from_numpy(image_array)
</pre>
And the error message is as following:

> */lib/python3.6/site-packages/ants/core/ants_image_io.py in from_numpy(data, origin, spacing, direction, has_components)
     98     """
     99     data = data.astype('float32') # need to remove this eventually.. double precision issues
--> 100     img = _from_numpy(data.T.copy(), origin, spacing, direction, has_components)
    101     return img
    102 
*/lib/python3.6/site-packages/ants/core/ants_image_io.py in _from_numpy(data, origin, spacing, direction, has_components)
    125     if not has_components:
    126         itk_image = libfn(data, data.shape[::-1])
--> 127         ants_image = iio.ANTsImage(pixeltype=ptype, dimension=ndim, components=1, pointer=itk_image,
    128                                    origin=origin, spacing=spacing, direction=direction)
    129         ants_image._ndarr = data
AttributeError: module 'ants.core.ants_image' has no attribute 'ANTsImage'

**Comment by stnava** [comment]
This issue is likely resolved by installing from the source

**Comment by joellliu** [comment]
@stnava yes,  it works after I compiled and installed antspy from source code.  Just think it will be good to let you know there may be a bug. Thanks for you reply.

**Comment by MustafaArikan** [comment]
pip install sklearn statsmodels could resolve the issue as well.
