### ISSUE TITLE
No wheel available for python 3.10 on PyPI

### ISSUE THREAD

**Issue by JescoS** [ANTsX/ANTsPy#391]
**Describe the bug**
Currently, no wheel is available for python version 3.10 on PyPI, while wheels for python version 3.6–3.9 are available (see [here](https://pypi.org/project/antspyx/0.3.3/#files)). This leads to the package being built from source on `pip install` and therefore increased install times. It does seem like a wheel is built for python 3.10 in the GitHub workflows (see [here](https://github.com/ANTsX/ANTsPy/runs/6774886594?check_suite_focus=true) for antspyx version 3.3). Would it be possible for a wheel be made available for python version 3.10?

**To Reproduce**
1. Go to the [PyPI files listing for antspyx](https://pypi.org/project/antspyx/0.3.3/#files).
2. No `.whl` file for python version 3.10 (cp310) is listed.

Alternatively:
4. Run `pip download --python-version "3.10" --no-deps antspyx`
5. Pip downloads a `.tar.gz` file, not a `.whl` file.

**Expected behavior**
A wheel for python version 3.10 being available on PyPI.

**Comment by stnava** [comment]
will address with next release.
