### ISSUE TITLE
Different result when the type_of_transform is 'antsRegistrationSyNRepro[r]' and 'Affine' 

### ISSUE THREAD

**Issue by conglin10** [ANTsX/ANTsPy#393]
I jast use the code  :
`ants.registration(fixed=f_img, moving=m_img, type_of_transform='antsRegistrationSyNRepro[r]',  verbose=False) `
to reg two brain dcm image.Fix img is T1WI,moving img is T2flair.
when I use  'antsRegistrationSyNRepro[r]' as the type_of_transform,it gives a WARNING:

```
WARNING: In /build101/ANTsPy/itksource/Modules/Registration/Metricsv4/include/itkCorrelationImageToImageMetricv4HelperThreader.hxx, line 85
CorrelationImageToImageMetricv4HelperThreader (0x55aa7fd470e0): collected only zero points

WARNING: In /build101/ANTsPy/itksource/Modules/Numerics/Optimizersv4/include/itkObjectToObjectMetric.hxx, line 579
CorrelationImageToImageMetricv4 (0x55aa7eff5170): No valid points were found during metric evaluation. For image metrics, verify that the images o
verlap appropriately. For instance, you can align the image centers by translation. For point-set metrics, verify that the fixed points, once transformed into the virtual domain space, actually lie within the virtual domain.
```

And the moving img is not aligned.
But when use  'Affine' as the type_of_transform,the reslut is good.

I'm wondering if there are some parameters I can set up to make the 'antsRegistrationSyNRepro[r]'  reslut good.Because I want a reproductive reslut .Thanks!!!
Here is the reslut with 'antsRegistrationSyNRepro[r]'.
<img width="1033" alt="微信截图_20220809205343" src="https://user-images.githubusercontent.com/28706382/183652448-28fcf4df-e6ee-4936-9bbe-06da8b8e6092.png">

**Comment by cookpa** [comment]
Two things are different in your registrations - firstly the metric, the repro mode is I think global correlation, while the affine registration would be Mattes mutual information. Secondly, the transform changes from rigid to affine. The extra degrees of freedom in the affine transform can also lead to different results.

There's a bunch of threads and examples about on "partial slab" registration like this. To make the method more robust it might be necessary to use metric masks on the fixed image.

If you want to use the reproducible metric with an affine transform you can do that with `antsRegistrationSyNRepro[a]`. But I caution that reproducible doesn't mean better, as your example dramatically shows. It just means it's deterministic, and produces the exact same result down to the last bit on subsequent runs.
