### ISSUE TITLE
resampling to new voxel 

### ISSUE THREAD

**Issue by dilekozkan** [ANTsX/ANTsPy#396]
I want to convert the 3d 1*1*1 flair image of the same patient to 3d 1*1*5 flair. 
My code:
from ants import crop_indices, pad_image, image_read,resample_image
t2_ants = image_read(t2_path)
t2_ants_resampled = resample_image(t2_ants,(1,1,5,3) , use_voxels=False, interp_type=4)

The image came in sagittal, but which I put in was the transverse plane. I couldn't understand where the wrong is.
Thanks in advance!

**Comment by ntustison** [comment]
For starters, the second argument should only have 3 elements (instead of 4).

**Comment by dilekozkan** [comment]
I write 1,1,5 in my python command.
Just here is typo. I couldnt fix the error.
My images acquired originally 3d sequence. May it be something related to that?

**Comment by dilekozkan** [comment]
Do i need to do different something from resampling? Like  multiplanar reconstruction? My original image 1*1*1 doesnt have an orientation like sagittal, i can see it every axises

**Comment by ntustison** [comment]
What program are you using to visualize your results?

**Comment by dilekozkan** [comment]
I checked python output on Itksnap.
I tried fsl for resampling and then, i checked them on fsleyes and mricron.

**Comment by ntustison** [comment]
My guess is it's an issue related to package differences ([e.g., nifty header](https://github.com/ANTsX/ANTs/wiki/How-does-ANTs-handle-qform-and-sform-in-NIFTI-1-images%3F)).  As a result, visualizations can vary.  If you want me to take a closer look, you'll need to post the data.

**Comment by dilekozkan** [comment]
[datas.zip](https://github.com/ANTsX/ANTsPy/files/9484402/datas.zip)
there are one reference image which I want the voxel size of and one input image (originally acquired 3d)
***
I add the resampled one.
[resampled.zip](https://github.com/ANTsX/ANTsPy/files/9484411/resampled.zip)

and here the command was: 
t2_ants=image_read(path_t)
t2_ants_resampled=resample_image(t2_ants, (0.67, 5.5, 0.67), use_voxels=False, interp_type=4)

thanks in advance.

**Comment by ntustison** [comment]
Yeah, it's a nifti header issue, as mentioned above.  If you open the image in ITK-SNAP, they're both consistently displayed (see below).  As explained in the Wiki page, other packages, such as FSL, treat the header information so you have to be careful when mixing inputs/outputs.

<img width="1781" alt="Screen Shot 2022-09-04 at 1 43 43 PM" src="https://user-images.githubusercontent.com/324811/188332845-6091f630-d5e7-43db-91bc-bf8640f7aace.png">

**Comment by dilekozkan** [comment]
I also displayed it this way on itk-snap. why does this python command display the sliced image this way? Shouldn't the result of the command (t2_ants_resampled=resample_image(t2_ants, **(0.67, 0.67, 5.5),** use_voxels=False, interp_type=4)) be axially sliced? **not( (0.67, 5.5, 0.67))**

**Comment by dilekozkan** [comment]
[outputfsl.zip](https://github.com/ANTsX/ANTsPy/files/9487588/outputfsl.zip)

the output of the command: flirt -in /ms/flairhigh.nii -ref /ms/flairtransvers.nii -applyxfm -out /ms/out
It is sagittal again not axial. but the reference is axial

**Comment by ntustison** [comment]
This is what I get when I resample and view the results within ANTs/ITK:

```
>>> import ants
>>> t2_ants = ants.image_read("3D_FLAIR.nii")
>>> t2_ants_resampled = ants.resample_image(t2_ants, (0.67, 0.67, 5.5), use_voxels=False, interp_type=4)
>>> t2_ants_resampled.spacing
(0.67, 0.67, 5.5)
```

We don't provide support that result from mixing packages.

**Comment by ntustison** [comment]
Note that this is a much more general problem beyond ANTs that involves multiple neuroimaging packages.  For example, see the discussion [here](https://discourse.itk.org/t/saving-non-orthogonal-volume-in-nifti-format/2760/11).
