### ISSUE TITLE
Different results using ants.image_write and .numpy()

### ISSUE THREAD

**Issue by d5423197** [ANTsX/ANTsPy#400]
Hello there,

I am using antspy to register my images. I tried to save the registration result by using ants.image_write (nii type image). I also tried to save the registration result by using the .numpy() method. But I realized that these two results are different.

Please help, Thanks.

ZD

**Comment by ntustison** [comment]
Be sure you check usage, i.e. ``help(ants.image_write)``.  Also, conversion to a numpy array will completely discard image-geometric information such as spacing and orientation so it won't be the same and is not recommended.

**Comment by d5423197** [comment]
Hello there,

Thanks for your reply. I am using the following code to export the file as nii.gz 
`
mytx = ants.registration(fixed=fixed , moving=moving, type_of_transform='Affine')
warped_moving = mytx['warpedmovout']
ants.image_write(warped_moving, "directory_name/test1.nii.gz")
`
I think I am using it right.
The conversion to numpy array gave me a better result. So as you said, the conversion to numpy is not the desired result, I should not use that. 

Thanks,

ZD
