### ISSUE TITLE
Creating Templates with Masks

### ISSUE THREAD

**Issue by FIrgolitsch** [ANTsX/ANTsPy#401]
Hello,

I've been working on getting to know ANTsPy. I was wondering if there is any option to pass masks to the registration function within the `ants.build_templates()` function. It does have a keyword argument, but that won't allow me to select the right mask for the right image passed to the function.

**Comment by gdevenyi** [comment]
I think `build_templates()` is a 1:1 port of the bash `antsMultivariateTemplateConstruction2.sh` which also doesnt' have masks.

I have a re-implementation that supports masks, lightly tested if you want to give it a try,
https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction

I can be quick about sorting any bugs that shake out.
