### ISSUE TITLE
Affine registration of T1 to T2star (Brain MRI) Problem

### ISSUE THREAD

**Issue by DimitriosGk** [ANTsX/ANTsPy#403]
Hello!

I have T1 and T2 star data, of 1 and 0.8iso respectively.  Before registration, I have brought the images in the same space (thus initially the brains have similar orientation). I also perform bias field correction and some minor denoising.  
The next step shall be and Affine transform so the volumes are same resolution and exact same space, as well as a non-linear step for 
correcting slight mis-registrations.

Unfortunately the last part doesn't work on the Affine transform, where I get odd results on the output (transformed). Please see below my exact code:

-------------------------------------------------------------------------------------
import os
import nipype.interfaces.ants as ants
import matplotlib.pyplot as plt

GRE_Magn_dir = os.path.join('........./magn_echo0000_Masked.nii.gz')
MP2RAGE_INV2_dir = os.path.join('......../T1_T1_MP2RAGE_INV2_Masked_GRESpace.nii.gz')
GRE_mask_dir = os.path.join('........../mask_GRE.nii.gz')

GRE_Magn = ants.image_read(GRE_Magn_dir)
MP2RAGE_INV2_Magn = ants.image_read(MP2RAGE_INV2_dir)
mask = ants.image_read(GRE_mask_dir )

GRE_Magn_biasCorr = ants.n4_bias_field_correction(GRE_Magn, mask=mask, shrink_factor=3, convergence={'iters': [50, 50, 50, 50], 'tol': 1e-07}, verbose=False, weight_mask=None)
MP2RAGE_INV2_Magn_biasCorr = ants.n4_bias_field_correction(MP2RAGE_INV2_Magn, mask='None', shrink_factor=3, convergence={'iters': [50, 50, 50, 50], 'tol': 1e-07}, verbose=False, weight_mask=None)

GRE_Magn_biasCorr_denoised = ants.denoise_image(GRE_Magn_biasCorr,mask)
MP2RAGE_INV2_Magn_biasCorr_denoised = ants.denoise_image(MP2RAGE_INV2_Magn_biasCorr)

reg = ants.registration(fixed=GRE_Magn_biasCorr_denoised, moving=MP2RAGE_INV2_Magn_biasCorr_denoised, type_of_transform = ['Affine'])

------------------------------------------------------------------------------------------------

and a sample of the data can be found here:
https://drive.google.com/drive/folders/1G2DctcO0ZlQjiDanOluLNA7F-v6KKVNG?usp=sharing

I would appreciate any help on the identification of the issue. Am I doing something fundamentally wrong on the usage of the ANTsPy?

Thanks a lot!
Dimitri

**Comment by stnava** [comment]
example images looked in a non-anatomical orientation .... and not consistently so.

**Comment by DimitriosGk** [comment]
Hello, 
Thanks a lot for the replies. 
@ntustison, this unfortunatelly brought no difference to the result.
@stnava, when I print the images on the different planes in python they seem to me similarly oriented. What is the issue you found? Also, if they are not, would you propose to use a tool so I can bring them along before Affine? Any example?

Thanks!
Dimitri

**Comment by DimitriosGk** [comment]
**Update**: I used the ​​ants.affine_initializer(...search_factor=20, radian_fraction=0.6...) and seems that this, along with an SyN works fine in my case. As a last input, may I ask if you have in mind another potential solution that might work faster in this case?

**Comment by ntustison** [comment]
As @stnava pointed out, they're oriented in a non-canonical way so typical approaches won't work.  Either your dicom converter or some processing step along the way discarded the correct header information.  You should first figure out how that happened to avoid these issues.  

<img width="1758" alt="Screen Shot 2022-10-04 at 6 49 01 AM" src="https://user-images.githubusercontent.com/324811/193836806-a5960fdf-3d04-4094-91af-24d0c54e579d.png">

**Comment by DimitriosGk** [comment]
Hello,

As we retrieve the data from the scanner with a functor that allows us to have the uncombined channels, and the channel combination happens later, it is a problem that I should have expected.
Unfortunately the  functor doesn't ensure proper conventional alignment as the retrieval happens in the pipeline before Siemens apply the final transformations as regards to the declared positioning of the participant in the scanner -although, since I can register, it is not a severe issue, but I will surely correct it before processing the whole cohort.

**Comment by ntustison** [comment]
``tx_inv`` should be the name of the file of the transform written to disk.

**Comment by DimitriosGk** [comment]
txfile = ants.affine_initializer( GRE_Magn_biasCorr_denoised, MP2RAGE_INV2_Magn_biasCorr_denoised, search_factor=20, radian_fraction=0.6, use_principal_axis=False, local_search_iterations=20, mask=None, txfn=None)

The txfile?
It does not accept str as input: 'TypeError: can only concatenate list (not "str") to list'

**Comment by ntustison** [comment]
Did you try

```
fullTrasform.append(txfile)
```

?

**Comment by DimitriosGk** [comment]
Worked! Thanks for the help!
