### ISSUE TITLE
cosineWindowedSinc option for resampling functions not working

### ISSUE THREAD

**Issue by spichardo** [ANTsX/ANTsPy#405]
**Describe the bug**
Hi, I'm getting the following msg when running `ants.resample_image_to_target` with `interp_type='cosineWindowedSinc'`
`Error:  Unrecognized interpolation option. cosinewindowedsinc`

**To Reproduce**
Just load two Nifti files and try to do resampling:
```python
import ants
ImgA=ants.image_read('DatasetA.nii.gz')
ImgB=ants.image_read('DatasetA.nii.gz')
ImgC=ants.resample_image_to_target(ImgA,ImgB,interp_type='cosineWindowedSinc')
...
Error: Unrecognized interpolation option. cosinewindowedsinc
```
**Expected behavior**
[Documentation](https://antspyx.readthedocs.io/en/latest/_modules/ants/registration/resample_image.html#resample_image_to_target) indicates the following interpolators are available:
_linear
nearestNeighbor
multiLabel for label images but genericlabel is preferred
gaussian
bSpline
cosineWindowedSinc
welchWindowedSinc
hammingWindowedSinc
lanczosWindowedSinc
genericLabel use this for label images_

Other interpolators such as `hammingWindowedSinc`, `welchWindowedSinc` and `lanczosWindowedSinc` are working.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Linux - Ubuntu 22.04
 - Python: 3.9  (anaconda)
 - ANTsPy: 0.3.4 (installed with `pip install antspyx`)

**Comment by ntustison** [comment]
[This](https://github.com/ANTsX/ANTs/commit/becc95ae597bf7594751a2e777709fd6e4692fec) is the bug fix.  It'll take awhile to work its way to a release but I'm closing this issue for now since it's been addressed.
