### ISSUE TITLE
Point transformation does not match image transformation after landmark registration

### ISSUE THREAD

**Issue by dakota-hawkins** [ANTsX/ANTsPy#408]
Hi there, just wanted to thank you for the work you've all done on ANTsPy, it's really been a great tool and I appreciate all the work. I'm having some issues with landmark registration, and was hoping to get some clarity:

**Describe the bug**
I have volumetric images of sea urchin embryos I am trying to orient along defined axes, as the sampling direction varies between samples. To this end, I've identified morphological landmarks that I then want to use to orient the embryo along ZYX coordinates. When I use `tx = ants.fit_transform_to_paired_points()` with a rigid transform, it correctly orients in the image, but transforming landmarks to the new space _afterwards_ (`tx.apply_to_space()`) fails to properly place the points.

**To Reproduce**

```python
import ants
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

# assume variables `img`, `reference`, and `landmarks` as 3d image to orient,
# reference points to align to, and annotated landmarks in `img`, respectively.

tx = ants.fit_transform_to_paired_points(
    landmarks.loc[reference.index, :].values,
    reference.values,
    transform_type='rigid'
)

new_points = pd.DataFrame(
    np.array(
       [tx.apply_to_point(x) for x in landmarks.values]
    ),
    columns=landmarks.columns,
    index=landmarks.index
)
 
oriented_image = tx.apply_to_image(ants.from_numpy(img)).numpy()

plt.imshow(oriented_image.max(axis=0))
plt.scatter(new_points.x, new_points.y)
```

These are the landmark points I'm using:

| label         |        z |        y |        x |
|:--------------|---------:|---------:|---------:|
| right-cluster | 164.762  | 123.213  |  33.0045 |
| left-cluster  | 164.762  | 223.643  | 203.198  |
| right-tip     | 187.289  |  42.7157 |  88.9692 |
| left-tip      | 187.289  | 135.479  | 236.931  |
| ventral-ring  | 196.943  | 174.578  | 118.101  |
| dorsal-ring   |  74.6544 | 164.611  | 116.568  |

These are the reference points I'm using:

| label         |        z |        y |        x |
|:--------------|---------:|---------:|---------:|
| right-cluster | 162.616  | 144.04   |  57.7954 |
| left-cluster  | 162.616  | 144.04   | 206.795  |
| ventral-ring  | 162.616  |  69.0399 | 132.795  |
| dorsal-ring   | 162.616  | 218.04   | 132.795  |
| right-tip     |  87.6164 | 144.04   |  57.7954 |
| left-tip      |  87.6164 | 144.04   | 206.795  |

**Expected behavior**
The transformed points should line up with their associated locations in the transformed image.

**Screenshots**
Original image, max projection along z dimension, with annotated landmarks
![original_img](https://user-images.githubusercontent.com/13321256/200181944-5f198829-a829-4af6-a4ca-85edf4033cc1.png)

Original image, viewed in Napari, red are annotated landmarks, green are reference points to align to
![to_orient](https://user-images.githubusercontent.com/13321256/200181863-f02ac2b9-a40d-460d-acb3-563693665202.png)

Transformed image, max projection along z dimension, with transformed landmarks
![transformed](https://user-images.githubusercontent.com/13321256/200182058-cd9f5db3-1d7f-4873-b982-4f6f0261c164.png)

Transformed image, viewed in Napari, red are transformed landmarks, green are aligned-to reference points
![oriented3d](https://user-images.githubusercontent.com/13321256/200182160-36afbb8e-6b47-44e1-90a4-d8ab304b8c91.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox
 - Ants Version = 0.3.3

**Additional Context**

Honestly, it feels less like a bug, and more like I'm missing something fundamental, so any insight would be greatly appreciated.

**Comment by stnava** [comment]
you probably need to apply the inverse transformation to the points.  just
a guess.  otherwise, you have some inconsistent definitions of points vs
image space.

**Comment by gdevenyi** [comment]
https://github.com/ANTsX/ANTs/wiki/Forward-and-inverse-warps-for-warping-images,-pointsets-and-Jacobians

https://github.com/stnava/chicken

**Comment by dakota-hawkins** [comment]
That was exactly it - thank you! And thanks @gdevenyi for the links, I'll be sure to read them.

Greatly appreciate the help!
