### ISSUE TITLE
Documentation Ants Parameters

### ISSUE THREAD

**Issue by ninusch** [ANTsX/ANTsPy#410]
What do the parameters "flow_sigma (scalar) – smoothing for update field" and "total_sigma (scalar) – smoothing for total field" do exactly? I don't understand from the documentation.

**Comment by ntustison** [comment]
At each iteration, the similarity metric and gradient is calculated.  That gradient field is also called the update field and is smoothed before composing with the total field (i.e., the estimate of the total transform at that iteration).  This total field can also be smoothed after each iteration.

**Comment by ncullen93** [comment]
The docs have been updated to provide more info in https://github.com/ANTsX/ANTsPy/pull/535. Closing :)
