### ISSUE TITLE
ANTs documentation

### ISSUE THREAD

**Issue by ninusch** [ANTsX/ANTsPy#417]
Is there any proper documentation about how the ANTs registration algorithm works? I am not interested in what to do with the program but how it actually manages to get things done, e.g. affine part first, then deformable or whatever...
Is there any publication about this? I couldn't find any.

**Comment by stnava** [comment]
try google scholar for details: [eg ants+avants+tustison](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C30&q=ants%2Btustison%2Bavants&btnG=)

**Comment by ncullen93** [comment]
The readme on the core ANTs page might help as well. (https://github.com/ANTsX/ANTs)
