### ISSUE TITLE
antspyx.readthedocs.io vs antspy.readthedocs.io

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPy#423]
There's two versions of docs online, one at antspyx.readthedocs.io, which is current, and one at antspy.readthedocs.io, which is outdated (caused some confusion in #422). 

Is there any way we can get the old one removed or redirecting to the current docs?

**Comment by cookpa** [comment]
You're right, I was able to find the main page. @ncullen93, could you delete the antspy.readthedocs.io instance? 

The current docs are built at antspyx.readthedocs.io, maintained by Brian. That's building successfully.

**Comment by cookpa** [comment]
Update: they freed up the antspy slug for us. I've invited you both @stnava and @ntustison just in case I lose access for any reason, so we don't get locked out again.

FYI @stnava , the RTD system is being updated and we'll have to update to use the yaml config files by September 2023. https://blog.readthedocs.com/migrate-configuration-v2/ I'll try to get it working and then hopefully it will update antspy and antspyx in sync.

**Comment by ntustison** [comment]
Awesome.  Thanks @cookpa

**Comment by cookpa** [comment]
I set up the `.readthedocs.yml`, and both antspy and antspyx RTD are now building successfully, so we are good to go.
