### ISSUE TITLE
MemoryError: std::bad_alloc when opening forward transform .mat files

### ISSUE THREAD

**Issue by nal10** [ANTsX/ANTsPy#425]
**Describe the bug**
I am trying to use the forward transform .mat file to map additional points in the transformed space. when I go to load the .mat file the program exits with:

```
Traceback (most recent call last):

  File "/opt/miniconda3/envs/ls_register/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "transform_script.py", line 12, in <module>
    transform = ants.read_transform(filename)

  File "/opt/miniconda3/envs/ls_register/lib/python3.9/site-packages/ants/core/ants_transform_io.py", line 330, in read_transform
    dimensionUse = libfn1(filename)

MemoryError: std::bad_alloc
```

This occurs if the script is run in spyder IDE or command line across Mac and Linux platforms. The file being loaded says it is 852.2MB on disk so I don't think it should be too big to load directly (Linux platform has 128GB RAM), but I am not sure.

**To Reproduce**
This code snippet produces the error:

```
import ants

filename = 'fwd_transforms.mat'
transform = ants.read_transform(filename)
```

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.0.1 & Ubuntu 18.04.6 LTS
 - python 3.9
 - ants 0.3.5

**Comment by cookpa** [comment]
How did you generate an 852Mb `.mat` file?

**Comment by ntustison** [comment]
The reported file size of that .mat file alone indicates that something went wrong with its creation.  How was it produced?

**Comment by nal10** [comment]
This is the code for making the .mat file. The image file is a 528 plane (456x320) grayscale tiff stack

```
# read images
img1 = ants.image_read('reference.tiff')
img2 = ants.image_read('img_file.tiff')

# register with ants
reg12 = ants.registration(img1, img2, "SyN", reg_iterations=[100, 10, 0])

# output
ants.image_write(reg12["warpedmovout"], "warp.tiff")
shutil.copy(reg12['fwdtransforms'][0], fwd_transform.mat)
```

**Comment by cookpa** [comment]
`reg12['fwdtransforms'][0]` - this is the warp field, not the matrix file. Changing this should fix the problem

**Comment by nal10** [comment]
Thank you. I can't quite tell from the docs how to get the matrix file from `reg12`, what would you replace `reg12['fwdtransforms'][0]` with?

**Comment by cookpa** [comment]
`reg12['fwdtransforms'][1]`

**Comment by nal10** [comment]
`reg12['fwdtransforms'][1]` does not appear to have any values.  `len(reg12['fwdtransforms'][1]) `is saying there is only one item in the list

**Comment by cookpa** [comment]
Can you run the example from the ants.registration help?

```
fi = ants.image_read(ants.get_ants_data('r16'))
mi = ants.image_read(ants.get_ants_data('r64'))
fi = ants.resample_image(fi, (60,60), 1, 0)
mi = ants.resample_image(mi, (60,60), 1, 0)
mytx = ants.registration(fixed=fi, moving=mi, type_of_transform = 'SyN' )
```

When I run this I get

```
len(mytx['fwdtransforms'])
2
```

**Comment by nal10** [comment]
This example runs as expected for me as well. Seems like it might be specific to my data. Seeing as how I ended up saving the `reg12['fwdtransforms'][0]` file instead, I can utilize the transform using the recommendation from #318. But, am a little concerned that I am not getting the matrix during registration.

**Comment by cookpa** [comment]
That is strange. I tried replicating your command line more closely:

```
mytx = ants.registration(fi, mi,  "SyN", reg_iterations=[100, 10, 0])
```

and got the same result. 

Can you try adding `verbose=True` to your registration? Please save the output to a .txt file and drop it here.
