### ISSUE TITLE
Export the n4 bias field.

### ISSUE THREAD

**Issue by WeiquanLuo** [ANTsX/ANTsPy#432]
The Linux stand alone ants::N4BiasFieldCorrection is able to output the bias field. It is possible to obtain the bias field from the antspy n4_bias_field_correction?

**Comment by ntustison** [comment]
Yes.  Look at the ``return_bias_field`` option.

**Comment by WeiquanLuo** [comment]
Thank you so much! I was looking at the old documentation: https://antspy.readthedocs.io/en/latest/_modules/ants/utils/bias_correction.html

It believe the documentation not updated then. Thank you again.

**Comment by cookpa** [comment]
That's an old version (#423), unfortunately it ranks higher in google.

Current docs are at https://antspyx.readthedocs.io/en/latest
