### ISSUE TITLE
Question: registration transform space

### ISSUE THREAD

**Issue by dipterix** [ANTsX/ANTsPy#434]
Hi @stnava , I'm trying to incorporate ANTs registration (`Rigid`) results in my electrode localization software, which overlays the raw CT with MRI. The overlay require CT scannerRAS to MRI scannerRAS transform. I wonder how can I get that transform matrix?

I tried 

```
res = ants.registration(...)
tran = ants.read_transform(res.fwdtransforms)
tran.parameters
```

I assumed `tran.parameters` was the transform. The parameters are 12-numeric vector

```
0.99182832   	-0.08990901    	0.09051423    
0.09437489    	0.99445838   	-0.04632332 
-0.08584776    	0.05448706    	0.99481720    
9.67110634 		-174.72554016  -86.74214935
```

The rotation is positive definite, hence I thought the translation along `z` axis was `-86.74`. However, when I used other software, I got the following matrix (row-major)

```
0.99	0.09 	0.088 	5.35
-0.088	0.99	-0.04	-181.31
-0.090	0.037	0.99	78.56
0	0	0	1
```

The translate along `z` axis is `78.56` (positive).

My struggle is: **How can I get CT world to MRI world matrix from ANTs?**

I checked overlay results of both methods. They looked pretty decent. I am sure both registrations are correct by overlaying the transformed CT to MRI. 

(coreg overlay via ANTs)
<img width="98" alt="image" src="https://user-images.githubusercontent.com/8163576/221197766-27fbbe66-4c73-43f9-b8a0-bd78e0cf03d4.png">

(coreg overlay via the other method)
<img width="150" alt="image" src="https://user-images.githubusercontent.com/8163576/221197903-8b181e5d-e165-4408-b8ac-34b00b25a013.png">

**Comment by stnava** [comment]
registration results are relative to the coordinate system of a specific software.  ITK-based software uses LPS which probably accounts for the sign flip. 

https://itk.org/Wiki/ITK/MetaIO/Documentation

**Comment by dipterix** [comment]
Thanks! I was nodding my head when reading the docs, until I saw something I couldn't understand. So I do have two follow-up questions (at the bottom of this comment if TL;DR).

I see nii sform:

```
srow_x: 0.89921468  -0.03544658  -0.01539038  -81.47227478
srow_y: 0.0356343  0.9291428  0.1192557  -124.3637695
srow_z: 0.01031417  -0.11976370  0.92975670  -110.31610870
```

This means voxel origin (0,0,0 at row-column-slice) will be transformed to `-81,-124,-110` in RAS coordinates (positive right-anterior-superior, right-handed)

while ANTsImage class `__str__` gives:

```
ANTsImage (LPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (192, 256, 256)
	 Spacing    : (0.9, 0.9375, 0.9375)
	 Origin     : (81.4723, 124.3638, -110.3161)
	 Direction  : [-0.9992  0.0378  0.0164 -0.0396 -0.9911 -0.1272  0.0115 -0.1277  0.9917]
```

The voxel origin `(81.4723, 124.3638, -110.3161)` confirms that the space of transform is LPS.

## My questions are:

1. when I typed `img.orientation`, the result is `LPI`. I wonder how I should interpret this orientation code?

2. the sform in nifti header is different to ANTsImage.direction. I realized the difference is `Spacing` (0.899/0.999 = 0.9, which is the first element in spacing). I wonder how ANTs transform from IJK (voxel coordinates) to LPS?

Just a bit explanation on why I asked 2. An example is that when FSL-flirt makes alignment, it disregards `Origin` and `Direction`. They only make sure the voxel sizes are correct, hence the transform matrix is `IJK -> re-scaled IJK (CT) -> FSL-affine -> re-scaled IJK (MRI)` instead of `IJK -> LPS (re-oriented, scaled, translated CT) -> CT_LPS-to-RAS_LPS -> LPS (MRI)`

I have zero experience in ITK. I wonder when ANTs reads nifti images, is "LPS" coordinates just a flip sign of "RAS"? or is there any other scaling/rotation/translation that I should apply before sign flip?

Really appreciate your helping me. Also I'm writing an R package `rpyANTs` that uses `ANTsPy`, but in R with python interpreter. The package will be on CRAN. It'll be great you have time to look at it. Comments/advice are more than welcome : )

**Comment by cookpa** [comment]
It all goes back to the underlying ITK methodology. An antsImage is an interface to an itkImage. If you want to understand how points go from index to physical space, look into TransformIndexToPhysicalPoint

https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html

https://itk.org/ITKSoftwareGuide/html/Book1/ITKSoftwareGuide-Book1ch4.html

https://discourse.itk.org/t/solved-transformindextophysicalpoint-manually/1031/2

As far as I know, the three-letter codes in ITK images are never used to transform points.

This comment is one of the best explanations I've seen 

https://github.com/InsightSoftwareConsortium/ITK/issues/1017

Note the difference between "from" codes and "to" codes.

**Comment by dipterix** [comment]
Thanks @cookpa ,

I see `PhysicalPoint = Origin + (Spacing * IdentityMatrix) * (RotationMatrix) * Index`, which confirms the guess. It's LPS and can be directly flipped from RAS. (yay!)

> As far as I know, the three-letter codes in ITK images are never used to transform points.

Then can I guess ANTs directly uses the orientation code from NIfTI, which stands for the "from" code transformed via internal `sform/qform`? Notice if you directly applies that transform to index points, then the physical points are in RAS (to code) coordinates.
