### ISSUE TITLE
Running a non-rigid deformation without any rigid deformations

### ISSUE THREAD

**Issue by ClarkQTIM** [ANTsX/ANTsPy#436]
Good afternoon. I am trying to register several images in sequence. I have found very good rigid registrations using the 'Similarity' option in ANTsPy. However, when I try and then use, say, 'SyN' or 'SyNCC' on the similarity-registered image, they are applying another rigid transformation and pulling the image to the side. Of course, 'SyN' and 'SyNCC' include rigid ('Affine') transformations, so I then attempted to use 'SyNOnly', but it still appears I am getting an affine transformation on the images. I would like to just apply 'SyN'/'SyNCC' to the similarly-registered images, but I cannot seem to do this. 

My setup is this:
```
def aff_def_reg(fixed_path, moving_path, transform):
    fixed = cv2.imread(fixed_path)
    fixed = apply_clahe(fixed).T
    fixed = ants.from_numpy(fixed)
    moving = cv2.imread(moving_path)
    moving = apply_clahe(moving).T
    moving = ants.from_numpy(moving)

    aff_tx = ants.registration(fixed=fixed , moving=moving, grad_step=1, aff_metric = 'mattes',
    random_seed=1, type_of_transform='Similarity')
    # Problem! The similarity looks great, but then the SyN has another affine part that is messing it up.
    aff_moving = ants.from_numpy(aff_tx['warpedmovout'].numpy())

    def_tx = ants.registration(fixed=fixed , moving=aff_moving, grad_step=1e-5, syn_metric = 'gc',
    type_of_transform=transform)

    return aff_tx['fwdtransforms'], def_tx['fwdtransforms']

for i in range(len(path_sequence)-1): # Creating a transformation between each ordered pair. This will give you n-1 transformations.
        if i == 0: # Creating our first transform composite 
            aff_tx, def_tx = aff_def_reg(path_sequence[0], path_sequence[1], 'SyNOnly')
            comp_transform_list = def_tx + aff_tx

            # Saving our first registration
            reg_save = Image.fromarray((full_3c).astype(np.uint8))
            save_name = path_to_save_registered_images + '/' + str(path_sequence[i+1][-16:-4]) + 'registered.jpg' 
            reg_save.save(save_name)

        else:
            aff_tx, def_tx = aff_def_reg(path_sequence[i], path_sequence[i+1], 'SyNOnly')
            comp_transform_list = comp_transform_list + def_tx + aff_tx
            full_3c = full_color_transform(path_sequence[i], path_sequence[i+1], comp_transform_list)
            
            # Saving our registered image
            reg_save = Image.fromarray((full_3c).astype(np.uint8))
            save_name = path_to_save_registered_images + '/' + str(path_sequence[i+1][-16:-4]) + 'registered.jpg' 
            reg_save.save(save_name)
```

Is there a way I can do this or an obvious flaw in my thinking/pipeline?

Thank you.

**Comment by ntustison** [comment]
The entire set of ``antsRegistrationSyN*[*]`` transforms are available in ANTsPy.  See "Notes" under ``type_of_transform`` in ``help(ants.registration)``.  Specific definitions are available [here](https://github.com/ANTsX/ANTs/blob/master/Scripts/antsRegistrationSyN.sh#L69-L77).  So something like ``type_of_transform=antsRegistrationSyNQuick[so]`` or ``type_of_transform=antsRegistrationSyNQuick[bo]`` should give you what you want.

**Comment by ClarkQTIM** [comment]
This is extremely helpful. Thank you!
