### ISSUE TITLE
reorient to LSP

### ISSUE THREAD

**Issue by scott-love** [ANTsX/ANTsPy#44]
I am starting to work with ANTsPy and hoping to stay within at least the ANTs world in my code. 

I want to reorient a bunch of images to LSP.

I have tested this in ITK-SNAP and the saved output image reopens later in the desired LSP orientation. I have tested this in c3d input.nii -orient LSP -o output.nii and the output image displays in LSP orientation.
Using ANTsPy I have tested:
img = ants.image_read('input.nii')
img = ants.reorient_image2(img,orientation='LSP)
ants.image_write(img,'output.nii')

But when displaying output.nii in ITK-SNAP it still has the original orientation - the image header has changed though.
Am I missing a step to write out the image correctly in LSP when using ANTsPy?

I know I can just use c3d in my code but I wanted to try not to.
Thanks,
Scott

**Comment by halirutan** [comment]
@stnava Simple question: I tried reorienting the example dataset as shown in the doc-comment of `reorient_image2`. Shouldn't the display in the NIFTI viewer change? Left is RPI and on the right is RAS

<img width="1238" alt="Screenshot 2020-01-15 at 14 11 19" src="https://user-images.githubusercontent.com/511683/72436518-ea18a480-37a0-11ea-8ac2-ba17c85b2e9d.png">

The `orientation` setting in the dataset did indeed change, but shouldn't this be reflected in the display?

**Comment by stnava** [comment]
this is unfortunately a very complicated issue that has undergone much discussion among different groups.   I personally don't mess with orientation codes unless forced to do so.  my guess, here, is that the viewer you are using doesn't see the orientation code the same way as what is written out by itk.  but one would have to dig in to know more.
