### ISSUE TITLE
GPU Support (How to make registration faster)

### ISSUE THREAD

**Issue by NirutaDhimal** [ANTsX/ANTsPy#441]
**Is your feature request related to a problem? Please describe.**
I am currently using ants SYNRA registration to register a ct image to a template. This registration worked for most of the cases and I would like to use this one. But it takes a lot of time. Is there any possible way which I could use to increase the speed of registration without much affecting the results.

**Describe the solution you'd like**
I would like to know if I can run the registration on GPU.

**Describe alternatives you've considered**
If there is no GPU support, I would to run the registration in parallel on multiple threads. 
If there is any parameters that I need to edit so that the speed of the registration is faster and the result is not much affected. That would be great

**Comment by cookpa** [comment]
There isn't currently a GPU implementation, but you can use multiple threads by setting the environment variable `ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS`. This variable should be set before importing ants.

**Comment by NirutaDhimal** [comment]
@cookpa  Thank you. I have tried that and the registration is faster than before.
I do have a question about the GPU implementation. Will there be any GPU implementation in future?

**Comment by ncullen93** [comment]
Hi there - GPU implementation of standard ANTs registration is not on the roadmap. The best bet would be to wait for a deep learning-based implementation of registration to come out, which is something that is being generally worked on by the community.

**Comment by rohitrango** [comment]
@NirutaDhimal if you are still looking for a solution, consider using FireANTs https://github.com/rohitrango/FireANTs/ 

It comes with a simple one-step install, and has all the functionality of ANTs based registration with advanced optimizers (diffeomorphic Adam). FireANTs is in its early stages, but I plan to make it compatible with the rest of the ANTs ecosystem so you do not have to change your existing workflows significantly.

Also checkout the associated preprint: https://arxiv.org/abs/2404.01249
Let me know if it helps, and feel free to reach out to me.
