### ISSUE TITLE
'abpBrainExtraction' function in ANTsPY

### ISSUE THREAD

**Issue by zbjbiubiubiu** [ANTsX/ANTsPy#458]
Hi. teams! Thank you for providing the python version of ants，which is very convenient and useful!
       But I have a question, there is **’abpBrainExtraction‘** function in ANTsR, but in ANTsPY, I did not find the corresponding function.
Is it only ANTsR that provides the function of 'abpBrainExtraction'? How is this function implemented in ANTsPY?
 
Thanks for your help, much appreciated.

**Comment by ntustison** [comment]
``abpBrainExtraction`` is not implemented in ANTsPy and given the existence of [``ANTsPyNet/brain_extraction.py``](https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/brain_extraction.py), such an implementation would be low priority.
