### ISSUE TITLE
Installation problem on Ubuntu 16.04.4

### ISSUE THREAD

**Issue by thomasbazeille** [ANTsX/ANTsPy#46]
Hi, 

I tried to install the latest release (v0.1.6) on Ubuntu 16.04.4 from binaries through :
`pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.6/antspy-0.1.6-cp36-cp36m-linux_x86_64.whl`

The installation went fine but when trying to import antspy, I run into the following import error : 
`/lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.27 not found (required by /home/anaconda/envs/antspy/lib/python3.6/site-packages/ants/lib/antiAlias.cpython-36m-x86_64-linux-gnu.so`
(Full traceback at the end of the comment)

I suppose because the code was compiled on Ubuntu 18 with later version of gcc. 
My cmake version 3.5.1, gcc version 5.4.0 and I cannot afford to upgrade Ubuntu hence the version of GLIBC.

I tried to build the code from source but ran into another error : 
```
make: *** No target specified and no makefile found 
Configuring ANTs core
fatal: target path 'pybind11' already existing and folder is not empty
Configuring ANTsPy library
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindITK.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ITK", but
  CMake did not find one.

  Could not find a package configuration file provided by "ITK" with any of
  the following names:

    ITKConfig.cmake
    itk-config.cmake

  Add the installation prefix of "ITK" to CMAKE_PREFIX_PATH or set "ITK_DIR"
  to a directory containing one of the above files.  If "ITK" provides a
  separate development package or SDK, be sure it has been `installed.`
```

So i'm left without any option to install antspy for ubuntu 16.04.4, do you have any pointers on anything I could try to install it in one way or another ?

Thank you very much

Full traceback of installation problem using pip install:
---------------------------------------------------------------------------
```
ImportError                               Traceback (most recent call last)
<ipython-input-2-9a98c04a2591> in <module>()
      5 import os
      6 
----> 7 from ants import registration

~/anaconda/envs/antspy/lib/python3.6/site-packages/ants/__init__.py in <module>()
      5     pass
      6 
----> 7 from .core import *
      8 from .utils import *
      9 from .segmentation import *

~/anaconda/envs/antspy/lib/python3.6/site-packages/ants/core/__init__.py in <module>()
      1 
----> 2 from .ants_image import *
      3 from .ants_image_io import *
      4 
      5 from .ants_transform import *

~/anaconda/envs/antspy/lib/python3.6/site-packages/ants/core/ants_image.py in <module>()
     25 import inspect
     26 
---> 27 from .. import utils, registration, segmentation, viz
     28 from . import ants_image_io as iio2
     29 

~/anaconda/envs/antspy/lib/python3.6/site-packages/ants/utils/__init__.py in <module>()
      1 
----> 2 from .bias_correction import *
      3 from .channels import *
      4 from .convert_nibabel import *
      5 from .crop_image import *

~/anaconda/envs/antspy/lib/python3.6/site-packages/ants/utils/bias_correction.py in <module>()
      7 
      8 
----> 9 from . import process_args as pargs
     10 from .get_mask import get_mask
     11 from .iMath import iMath

~/anaconda/envs/antspy/lib/python3.6/site-packages/ants/utils/process_args.py in <module>()
     11 
     12 from ..core import ants_image as iio
---> 13 from .. import lib
     14 
     15 _short_ptype_map = {'unsigned char' : 'UC',

~/anaconda/envs/antspy/lib/python3.6/site-packages/ants/lib/__init__.py in <module>()
      2 
      3 ## LOCAL ##
----> 4 from .antiAlias import *

      5 from .antsImage import *
      6 from .antsImageClone import *

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/parietal/tbazeill/anaconda/envs/antspy/lib/python3.6/site-packages/ants/lib/antiAlias.cpython-36m-x86_64-linux-gnu.so)`
```

**Comment by stnava** [comment]
it should install (from source) on your system, which is what we do on travis.   you might get some insight by reading:

https://github.com/ANTsX/ANTsPy/blob/master/.travis.yml

note that cmake > 3.11 or so is needed.   the procedure should be:

```
git clone https://github.com/ANTsX/ANTsPy.git
cd ANTsPy
python3 setup.py install
```

ie compile from the cloned git repo, not the source on the release tag.

**Comment by thomasbazeille** [comment]
The problem was indeed with cmake version!

Thanks a lot for the pointers and for this great package easing the use of ants for python developers.

FIY, installation documentation (and readme) was outdated as it still points to antspy v0.1.4.
Cheers

**Comment by jcreinhold** [comment]
In case someone else runs into this problem. I ran into this same error when building from source with cmake v3.11.1, but when I upgraded to version v3.13.4, the problem went away. This was with antspy v0.1.7.
