### ISSUE TITLE
antspyx==0.3.2 does not exist

### ISSUE THREAD

**Issue by JBarsotti** [ANTsX/ANTsPy#463]
**Describe the bug**

I am running the BrainAge algoirthm from https://github.com/MIDIconsortium/BrainAge.
One of the requirements is antspyx==0.3.2. However, this version does not appear to exist. Did it used to exist at some point, and is there any way to still install it?

Thanks for your help,

John

**Comment by ntustison** [comment]
I would expect just installing directly from the repo should be sufficient.

**Comment by cookpa** [comment]
This is how I get older versions:

```
pip install 'antspyx @ git+https://github.com/ANTsX/ANTsPy@v0.3.2'
```

**Comment by JBarsotti** [comment]
Honestly you all are the people who make any research possible. Thanks for your detailed replies.
