### ISSUE TITLE
'SynOnly' transform option is still performing an affine step in ANTsPy 

### ISSUE THREAD

**Issue by dontminchenit** [ANTsX/ANTsPy#466]
For AntsPy, running with the 'SyNOnly" transform option seems to still be performing an affine step, and the results are generating an additional affine matrix. From the description, this option should skip the affine step and go straight to deformable.

Commenting out the following lines:
/ANTsPy/ants/registration/interface.py
651             "-r",
652            initx,

seems to fix the issue for me, but not sure if that's the best solution.

**Comment by cookpa** [comment]
It's falling back on a center of mass transform if an initial affine is not provided. If you include initial_transform="Identity", it should respect that. You'll still get an affine matrix output but it should be identity.

**Comment by cookpa** [comment]
I think we could make the documentation clearer on this, which I can have a go at later.

**Comment by dontminchenit** [comment]
Ah, I see. That makes sense. Thanks.

**Comment by ntustison** [comment]
Although resolved, for your specific case, you have the options ``type_of_transform="antsRegistrationSyN{Quick/Repro}[so]"`` and ``type_of_transform="antsRegistrationSyN{Quick/Repro}[bo]"``.

**Comment by dontminchenit** [comment]
Thanks, Nick. I'll keep those options in mind as well.
