### ISSUE TITLE
Jacobian determinant

### ISSUE THREAD

**Issue by devDonnn** [ANTsX/ANTsPy#472]
Hi, ANTsPy `create_jacobian_determinant_image(domain_image, tx, do_log=False, geom=False)` function requires a domain image. However, ANTs command line tool `CreateJacobianDeterminantImage` does not require the domain image and is able to compute the jacobian using the provided warp image only. Can the `create_jacobian_determinant_image` function be made without requiring a domain image so the necessary info is retrieved from the warp image? The domain image appears to be redundant.

**Comment by stnava** [comment]
We won’t change the interface but but you can pass in the warp image itself
for the domain.

**Comment by cookpa** [comment]
Attempting to use the warp as the domain image fails for me because it attempts to clone as double, but double is not supported for multi-channel images.

This also prevents warps written from CLI `antsRegistration` using default params. Could I fix this by adding double types here?

https://github.com/ANTsX/ANTsPy/blob/b67c22f5896f43d3ffadbea763e57d083cc6174c/ants/lib/LOCAL_mergeChannels.cxx#L189-L210

**Comment by stnava** [comment]
yes - I think that would work

**Comment by cookpa** [comment]
OK cool. I think it would be nice to be able to read warps from ANTs into ANTsPy.

For the Jacobian use case, the image would additionally need to be split into components, so that a single-component image can be passed to the library function to store the result.

**Comment by stnava** [comment]
I think there must be some confusion here .... we can already read warps:

```python
>>> i1=ants.image_read(ants.get_data("r16"))
>>> i2=ants.image_read(ants.get_data("r64"))
>>> reg=ants.registration(i1,i2,'SyN')
>>> ants.image_read( reg['fwdtransforms'][0] )
ANTsImage
	 Pixel Type : float (float32)
	 Components : 2
	 Dimensions : (256, 256)
	 Spacing    : (1.0, 1.0)
	 Origin     : (0.0, 0.0)
	 Direction  : [1. 0. 0. 1.]
```

**Comment by stnava** [comment]
this is how one would do it

```python
dimg=ants.image_read( reg['fwdtransforms'][0] ).split_channels()[0]
ants.create_jacobian_determinant_image( dimg, reg['fwdtransforms'][0] )
```

**Comment by devDonnn** [comment]
> this is how one would do it
> 
> ```python
> dimg=ants.image_read( reg['fwdtransforms'][0] ).split_channels()[0]
> ants.create_jacobian_determinant_image( dimg, reg['fwdtransforms'][0] )
> ```

Thanks, @stnava. This works well.

**Comment by cookpa** [comment]
I guess I took the earlier comment too literally, you can't use the warp field itself as a domain image. This fails

```
warp = ants.image_read(mytx['fwdtransforms'][0])
jac = ants.create_jacobian_determinant_image(warp, warp)
```

But you can split it yourself and use the first channel. I'll update the docs to make note of this
