### ISSUE TITLE
Tutorials for T1 brain imaging processing

### ISSUE THREAD

**Issue by dipterix** [ANTsX/ANTsPy#484]
Dear ANTsPy devs,

I'm trying to build a pipeline using `ANTsPy` (and `ANTsPyNet`) to process brain T1 images. 
I wonder if there is any pipeline code that contains:

1. Motion correction
2. Intensity correction
3. Super-resolution up-sample (for clinical T1)
4. Normalization
5. Skull Strip
6. Subcortical Segmentation
7. White-matter Segmentation
8. Cortical Parcellation
9. Cortical thickness
10. Gyrification Index
11. Template mapping (both Affine and SyN) to MNI

Also it would be great if you could suggest the order of operations for the above steps (for example, should 11 based on output of 3 or 5, or just the raw image)? I found some code documentations and examples, but I'm not sure how to combine them into the pipeline. 

Thanks : )

**Comment by ntustison** [comment]
Have you explored the toolkit and looked at some of the documentation and papers that are listed?  If not, I would encourage you to do that as it will most likely answer many, if not all, of your questions..

**Comment by dipterix** [comment]
Will do. Is there any way to run `antsCorticalThickness.sh` with ANTsPy?

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTsPyNet/blob/master/antspynet/utilities/cortical_thickness.py

**Comment by dipterix** [comment]
Thanks! Another question for super resolution. I found an issue here https://github.com/ANTsX/ANTsPyNet/issues/63. I wonder do you have plans to include SynthSR (https://github.com/BBillot/SynthSR)? It worked pretty decent with pre-trained model.

By the way the examples in `antspynet.super_resolution_utilities.apply_super_resolution_model_to_image` is not working. Is there any working example?

Thanks

**Comment by ntustison** [comment]
> I wonder do you have plans to include SynthSR (https://github.com/BBillot/SynthSR)? 

No.

> By the way the examples in antspynet.super_resolution_utilities.apply_super_resolution_model_to_image is not working. Is there any working example?

Try `antspynet.mri_super_resolution`.
