### ISSUE TITLE
ANTsPy does not install (from source)

### ISSUE THREAD

**Issue by rohitrango** [ANTsX/ANTsPy#487]
**Describe the bug**
Upon trying to install ANTsPy from source, the build fails with the following error:

![image](https://github.com/ANTsX/ANTsPy/assets/15312514/d29cb69b-baa4-49fa-b73d-3cc9d1320353)

**To Reproduce**
1. git clone https://github.com/ANTsX/ANTsPy 
2. cd ANTsPy
3. python setup.py install

Commit ID: 7c9c3ed3d575ce30c4c19f6597772466d4457951 

On step 3, the setup script downloads and installs ITK, but then the error above shows up. I also tried installing ITKv5 and setting `ITK_DIR` which the setup script recognizes, but I still face an error at the same point. Note that I'm able to install and run the [original ANTs program](https://github.com/ANTsX/ANTs/tree/master) (and the bash scripts) with the installed ITK.

**Expected behavior**
Script should install ANTsPy.

**Environment**
I used a fresh conda environment to install ANTsPy. Python version 3.7 (don't think this error has anything to do with this info though).

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by ntustison** [comment]
@cookpa --- Here's the code snippet in question from above:

https://github.com/ANTsX/ANTs/blob/master/Tensor/TensorFunctions.h#L682C1-L691

That return type looks wrong.  I don't know how we haven't seen this before.

**Comment by rohitrango** [comment]
this is not the only error however, fixing these two lines of code gives a new build error later. 

![image](https://github.com/ANTsX/ANTsPy/assets/15312514/7dd5141d-762f-453e-ab19-478aa974ad18)

Perhaps its some systematic typecast error? 
Also could you let me know the latest version that builds correctly?

**Comment by ntustison** [comment]
> Perhaps its some systematic typecast error?

I doubt it.  This is at the level of ITK.  I'm going to update the ITK tag in ANTs and the ANTs tag here and then we can reassess.

**Comment by cookpa** [comment]
Hi @rohitrango , did these fixes help? The wheels are building on Ubuntu 22.04. 

If you're still having trouble, could you give some more details of your system (compiler, CMake version)?
