### ISSUE TITLE
Having trouble installing ANTS. 

### ISSUE THREAD

**Issue by YasmineMH1997** [ANTsX/ANTsPy#490]
I used the following to install ants but nothing seems to work. 

`pip install antspyx`
`git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install`
![image](https://github.com/ANTsX/ANTs/assets/128826190/76fd9945-38c3-4798-b42b-33bf02a41960)

**When did the error occur?**

[ ] CMake configuration (cmake / ccmake)
[ ] Compilation (make)
[ ] Installation (make install)

**Build environment**
 - OS: Linux
 - OS version: Ubuntu 22.04.2
 - Type of system: [PC]

**ANTs version**

**Build configuration and logs**

**Additional context**

**Comment by cookpa** [comment]
Maybe this is a Ubuntu 22 problem? Same OS as #487 

On my Ubuntu 20.04 VM, it installs and works

```
conda create -n antspypip python=3.8
conda activate antspypip
pip install antspyx
python
>>> import ants
>>> image = ants.image_read('brainMasked.nii.gz')
>>> image
ANTsImage (LPI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (224, 320, 320)
	 Spacing    : (0.8, 0.8, 0.8)
	 Origin     : (99.6298, 119.9129, -149.0895)
	 Direction  : [-0.9936  0.0182 -0.1116 -0.0188 -0.9998  0.0045 -0.1115  0.0066  0.9937]
>>> 
```

**Comment by cookpa** [comment]
@YasmineMH1997 what is your python version?

**Comment by YasmineMH1997** [comment]
At first, I tried 3.10. 
Now I am trying an environment with 3.8 python
but struggling with this error: 
![image](https://github.com/ANTsX/ANTsPy/assets/128826190/24b8f02a-32c3-4270-bbbe-fd0d4aa4de80)

**Comment by cookpa** [comment]
OK that's a lead, libstdc++ might be incompatible with the wheels.

Can you reproduce outside of a notebook? Run a minimal example from a terminal, and paste the full error?

Thanks

**Comment by YasmineMH1997** [comment]
Oh I think it worked when I ran the few lines you provided: 
```
conda create -n antspypip python=3.8
conda activate antspypip
pip install antspyx
```
![image](https://github.com/ANTsX/ANTsPy/assets/128826190/05ee4d54-c054-45bb-96ab-c7bdab6f4fe1)
![image](https://github.com/ANTsX/ANTsPy/assets/128826190/322f1658-1e72-4dac-a5de-5d70382bb9ad)


I think it goes wrong when I add these lines: 
`git clone https://github.com/ANTsX/ANTsPy cd ANTsPy python3 setup.py install`

I am not sure.

**Comment by cookpa** [comment]
Great, if `pip install` works, there's no need to clone the source and install with setup.

**Comment by YasmineMH1997** [comment]
Thank you ^__^
