### ISSUE TITLE
Rotation in registration module

### ISSUE THREAD

**Issue by Volodimirich** [ANTsX/ANTsPy#494]
Hello, I have a question about the registration module. I am solving the task of atlas overlay for brain CT and an important step in solving this task is registration. The most important step in solving this problem is the rotation of the brain, because the position of the head can deviate by +- 30 degrees.

In your library I have found a module that is perfect for this task, but there is a small problem:
```
gr_tm, br_tm = ants.from_numpy(gr_truth[120]), ants.from_numpy(brain2[120])
res_ants = ants.registration(gr_tm, br_tm, type_of_transform='Similarity', aff_metric='GC', restrict_transformation=(1,1,0))
```
After that I have the following results (third picture):
<img width="1000" alt="image" src="https://github.com/ANTsX/ANTsPy/assets/55362016/39ea5f0c-17a0-4db6-bb4f-58216e384442">
But the problem is that the brain has not only turned, but has also changed size, which is highly undesirable in this task.

I tried changing the transform type to **Rigid**, but the results are much worse that way:
<img width="972" alt="image" src="https://github.com/ANTsX/ANTsPy/assets/55362016/1b2ef5cb-c578-4c3f-b72d-cbffd73dad2b">

I tried changing the function parameters, but couldn't achieve the result. Is there any way to keep only the rotation from the first transformation? Or get the rotation matrix from the current transformation?

**Comment by ntustison** [comment]
How are you visualizing the results?  The fact that you're converting from a numpy array without any explicitly supplied image geometry information suggests that perhaps you're performing registration with potentially incorrect assumptions.

**Comment by Volodimirich** [comment]
@ntustison In both cases, the voxel size is 1 and I thought that was enough for correct visualization. Initially the data were dicom files and were read with pydicom. If I read the files through ants.core.ants_image_io.dicom_read, will the situation change?

**Comment by ntustison** [comment]
> In both cases, the voxel size is 1 and I thought that was enough for correct visualization.

That might be the case but that's not in your description and it's certainly not best practice as ANTs tools utilize the geometric information in the header.  I don't know how well-vetted ``ants.core.ants_image_io.dicom_read`` (I use [dcm2niix](https://github.com/rordenlab/dcm2niix)) but please use something so that information is not lost in the processing.  Also, if you're just starting to use ANTs, please use [ITK-SNAP](http://www.itksnap.org/pmwiki/pmwiki.php) to show results as we know the visualization is compatible with ANTs.  

Once you've done that, come back and we'll be in a shared knowledge space for fixing any issues.

**Comment by anamazingclown** [comment]
> Solved the problem by changing the matrix of the affine transformation, closing the issue
HI @Volodimirich 
Could  you please  tell me above how to change the matrix of the affine transformation?
`f_img = ants.image_read(f_npy_path) # 2d numpy data size [ 350,740]`
`m_img = ants.image_read(m_npy_path)`
`mmtf = ants.registration(fixed=f_img, moving=m_img, type_of_transform = "Affine",verbose=True)`
`mat_data = sio.loadmat(mmtf['fwdtransforms'][0])`
`affine_params = mat_data["AffineTransform_float_2_2"] #output size [6,1]`
`fixed_parameters = mat_data['fixed] #output size [2,1]` 

maybe you can know these questions's answer:
1.does the mat_data["AffineTransform_float_2_2"] which has size 6*1 output means the size [2,3] affine matrix? IF not ,what does it mean, what's the use 
2.What does mat_data['fixed'] mean? What's the use
3.My ultimate goal is to obtain the final affine matrix (I can use other libraries, such as cv2.warpAffine) and the corresponding X-axis and Y-axis offsets of all coordinates relative to the origin (0,0) (the size is [350,740,2], the last dimension is x,y respectively) or the deformation field(which i can use SpatialTransformer like Voxelmorph to get new img)

I have been stuck on the problems for several days, and looked for a lot of information but failed. I really hope that you can help me. Thank you very much. I am always waiting for your reply
