### ISSUE TITLE
Can not quit python after generating image file using ants.write_image

### ISSUE THREAD

**Issue by NemesisAmos** [ANTsX/ANTsPy#495]
Hi everyone,

I have got a problem after I generate image file using ants.write_image. I have wrote an script for brain nifti image coregistration. The code work perfectly on windows 11 operating system, but can not work on windows 7 system. 
On windows 7 system I can obtain the generated image file, but I can't quit python normally after excuting the script. I've tried os._exit(0),  os.exit(), quit() and  os.system('exit()'), but non of them works.
I tried to fix the problem. I tried to excute matplotlib plot on windows 7 system and it  works after specifying plt.ion(). It seems that the version anaconda3 2018.10 win64 can not deal with io release after generating coregistered nifti image. I was wondering if anyone have similar problem and already solved it.

Best,
Amos

**Comment by ncullen93** [comment]
Please re-submit your issue with a reproducible example, thanks!
