### ISSUE TITLE
problem with 3d registration

### ISSUE THREAD

**Issue by esther1262** [ANTsX/ANTsPy#496]
Hi, I try to register two 3d labelmaps. The fixed one is a binary mask, dim 256x256x16. The moving one has 27 regions (values 0,1,...27), dim 256x512x256. Ultimately, I am only interested in a few regions. 

```
img_mv = ants.image_read('results/templateLabels_27regions_256slices.nii.gz', dimension=3)
img_fx = ants.image_read('1.nii.gz', dimension=3) 
``` 
I think the pixel data are imported as float. Even if I specifed `pixeltype='unsigned int'` the registration results didnt improve. 

```
mytx = ants.registration(fixed=img_fx , moving=img_mv, type_to_transform='BOLDAffine')
warped_moving = mytx['warpedmovout'] 
 ```
I tried all the possible choices for `type_to_transform`. None can improve the results. 

`img_fx.plot(axis=2, slices=11, overlay=warped_moving, title='After Registration (slice 11)', overlay_alpha=0.7)`

![image](https://github.com/ANTsX/ANTsPy/assets/54929051/694a58e6-02ec-470b-9f30-d74c59aea642)

This is one of the slices that has the worse result. Majority are okay, in terms of shape. Since I have a binary map, it's difficult to register all the regions. But I want the shape to be matched at least. This one has completely different shape.

Also,  
moving labelmap
![image](https://github.com/ANTsX/ANTsPy/assets/54929051/8f8789e7-6d2f-46d5-8b1b-0cf5a2d1891b)
after registration, so much noise 
![image](https://github.com/ANTsX/ANTsPy/assets/54929051/60bc4119-b588-458b-85a0-98efe41a593e)

Anyone knows how to fix it?
Thanks

**Comment by cookpa** [comment]
The correct arg is `type_of_transform`

Registering a binary mask to a label image is an unusual use case. There's very little information in a binary mask except at the edges. I would rethink this and reformulate the registration question if possible.

**Comment by esther1262** [comment]
> The correct arg is `type_of_transform`
> 
> Registering a binary mask to a label image is an unusual use case. There's very little information in a binary mask except at the edges. I would rethink this and reformulate the registration question if possible.

typo, but they didnt make a difference

i have a mouse head mri, I want to register the labelmap template to the brain area. Thats why I created a binary map for the brain only, registration between a head and a brain image is even worse.

**Comment by cookpa** [comment]
>typo, but they didnt make a difference

If there's a typo in the function call, the argument is ignored. The default will be used.

> i have a mouse head mri, I want to register the labelmap template to the brain area. Thats why I created a binary map for the brain only, registration between a head and a brain image is even worse.

I agree you shouldnt' register head to brain. If you have a head + brain mask, you can create a brain image and register brain to brain, unless I'm missing something?

The noisy appearance in the output is from linear interpolation of the labels. You can use `ants.apply_transforms` with `interpolator= genericLabel` to avoid this.

**Comment by esther1262** [comment]
> > typo, but they didnt make a difference
> 
> If there's a typo in the function call, the argument is ignored. The default will be used.
> 
> > i have a mouse head mri, I want to register the labelmap template to the brain area. Thats why I created a binary map for the brain only, registration between a head and a brain image is even worse.
> 
> I agree you shouldnt' register head to brain. If you have a head + brain mask, you can create a brain image and register brain to brain, unless I'm missing something?
> 
> The noisy appearance in the output is from linear interpolation of the labels. You can use `ants.apply_transforms` with `interpolator= genericLabel` to avoid this.

we prefer not to change the pixel in brain images. we want to do it from the masks.
