### ISSUE TITLE
How can I transform two CTs with a known affine transformation matrix?

### ISSUE THREAD

**Issue by angolin22** [ANTsX/ANTsPy#499]
hello, thanks for your excellent work! I have a problem:
I have two 3D CT images, and I know the affine transformation matrix between them. e. g. 
`[[ 9.92477011e-01 -8.45505280e-02  8.85471061e-02  5.05205949e+01]
 [ 8.73986445e-02  9.95757283e-01 -2.87907932e-02 -5.85686522e+00]
 [-8.57371490e-02  3.63130975e-02  9.95655814e-01 -4.96898369e+01]
 [-0.00000000e+00 -0.00000000e+00 -0.00000000e+00  1.00000000e+00]]`
How can I transform CT with antspy?
Thanks

**Comment by ntustison** [comment]
``help(ants.create_ants_transform)``

**Comment by angolin22** [comment]
Thanks for your reply! But the result is not right, my code is 
```
matrix = affine_mat[0:3,0:3]
translation = affine_mat[0:3,3:].squeeze()
tx_affine = ants.create_ants_transform("AffineTransform", precision="float", dimension=3, matrix=matrix, translation=translation)
reg_moving = tx_affine.apply_to_image(moving, fixed, 'linear')
```

In addtion, I don't know these parameters `offset , cernter` in this function `ants.create_ants_transform()`, can you see what's wrong？

**Comment by ntustison** [comment]
How did you derive the original transform parameters?

**Comment by angolin22** [comment]
I use the point cloud corresponding to CT to generate the transform parameters. I use the fast global registration in the `open3d` library. The result of the point cloud is correct, but the CT image is wrong. I guess the order of the transform parameters is wrong, but I don't know what the affine transformation matrix of antspy looks like.

**Comment by ntustison** [comment]
My guess is that the open3d affine parameters aren't directly portable into the ANTs/ITK transformation framework.  I would ask over on the ITK discourse forum if anybody has any experience with what you're wanting to do.

**Comment by angolin22** [comment]
Ok, thanks! I think it's related to [this link](https://sourceforge.net/p/advants/discussion/840261/thread/9fbbaab7/?fbclid=IwAR1SxkuDTEqeYWP9WhUzqE6aL8huIQagKZptiJrgLCNL2j5L6m15f4oSq5E)

**Comment by cookpa** [comment]
See also #525. It's necessary to set both the matrix and the center of rotation (set via the "fixed parameters")
