### ISSUE TITLE
Automating wheel uploads to PyPi

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPy#502]
Note about a WIP:   automating upload of wheels on ANTsPy tags

Following these instructions:  

https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

I've completed the first few steps and reached the section https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

am not sure how to deal with this step within the current GitHub Actions.

any help/insight appreciated.

one side effect of this work is that the current wheels cannot be uploaded by me.  as such, v0.4.1 is currently in limbo with regards to pypi wheels.   I have them but cannot upload them.  something about 2FA.

**Comment by cookpa** [comment]
Hi @stnava , I'm just back from traveling, I see you have added a "PYPI_API_TOKEN" to the repo secrets and 0.4.2 wheels are up. Is this issue resolved now?

**Comment by stnava** [comment]
only partially - see my comment https://github.com/ANTsX/ANTsPy/issues/503

**Comment by stnava** [comment]
closed for now.
