### ISSUE TITLE
Releases prior to 0.3.8 yanked?

### ISSUE THREAD

**Issue by kmannislands** [ANTsX/ANTsPy#503]
**Describe the bug**
It appears all releases prior to `0.3.8` have been yanked from PyPi: https://pypi.org/project/antspyx/#history

Discovered this when attempting to run install in a project using poetry that depends on `0.3.7`.

**Expected behavior**
Prior releases should not be yanked from PyPi without a pretty extreme scenario.

Was this intentional? If not, can the prior releases be restored? If so, what was the reasoning?

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy#note-old-pip-wheels-will-be-deleted 

discussed several times but finally added to README

**Comment by gdevenyi** [comment]
Can wheels be built/attached to Github releases?

**Comment by cookpa** [comment]
@gdevenyi wheels are built on release now. I see the creation of version tags has got ahead of actual releases - will try to fix.

**Comment by stnava** [comment]
@cookpa  - I attempted to get these wheels pushed to pypi but only succeeded for linux

* currently it's done "on push" but will not overwrite old releases (to pypi) b/c I also have `skip_existing` ... this means that if the version is bumped, a new release will go to `pypi` ... probably not ideal, given the current limited storage there.
* probably better to use "on tag" or whatever the syntax is 
* probably need to add sdist to the pypi push  as well ... 
* despite above improvements, I still need to "manually" put wheels on pypi for these reasons:   1. can't push these wheels from GitHub;  2.  still would like universal2 wheels for osx;  3. still need to manually manage the releases wrt storage on pypi

**Comment by gdevenyi** [comment]
> @gdevenyi wheels are built on release now. I see the creation of version tags has got ahead of actual releases - will try to fix.

Sorry, to clarify, I mean how the ANTs zip files are being attached to releases. Github doesn't enforce the same space limits so old wheels could be manually downloadable at least.
