### ISSUE TITLE
cannot import name 'Int64Index' from 'pandas' (deprecated)

### ISSUE THREAD

**Issue by Abhinav-Ganesh** [ANTsX/ANTsPy#508]
**Describe the bug**
ImportError: cannot import name 'Int64Index' from 'pandas'

**To Reproduce**
>>pd.__version__
'2.1.1'

>>import ants
ImportError: cannot import name 'Int64Index' from 'pandas'

Side note: (having higher version of numpy causes separate error)
>>np.__version__
'1.23.5'

**Expected behavior**
import ants with no errors

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.0 Apple M1
 - antspyx Version: 0.3.8

**Comment by cookpa** [comment]
Thanks - how did you install ANTsPy?

**Comment by Abhinav-Ganesh** [comment]
I believe I installed ANTsPy with pip install antspyx. I could work around
the issue by downgrading my numpy and scipy versions to numpy-1.22.4
scipy-1.7.3.
