### ISSUE TITLE
estSmooth() in antspy?

### ISSUE THREAD

**Issue by samtorrisi** [ANTsX/ANTsPy#511]
hi there gurus

i see a reference to an estSmooth() function in antsR
but i'm curious if that function is or will be available in antspy?

and does it output smoothness estimates for all 3 dimensions separately?
thanks!

-Sam

**Comment by ntustison** [comment]
That function was part of a larger contribution made prior to the development of ANTsPy by a contributor who hasn't made any other contributions.  Although a great contribution, I don't think it has gotten used much, if at all, by the core ANTs developers so it probably won't get ported over to ANTsPy anytime soon.

**Comment by samtorrisi** [comment]
ok, i understand and thanks for the fast response.

**Comment by stnava** [comment]
side note:  something like chatgpt could probably convert it automatically.

**Comment by cookpa** [comment]
Anyone know if there is an ITK filter that does this? It would be nice to have in ImageMath

**Comment by ntustison** [comment]
My guess is no but agree that it would be a great contribution.
