### ISSUE TITLE
Install antspynet in a requriements.txt but couod not find a version that satisfies tensorflow?

### ISSUE THREAD

**Issue by citystrawman** [ANTsX/ANTsPy#520]
Hello, I am trying to install dependencies from a requirements.txt file from this github repo:  https://github.com/Angeluz-07/MRI-preprocessing-techniques. The requirements are as follows:

> ipykernel
> ipywidgets
> matplotlib
> opencv-python
> jupyter
> notebook
> antspyx
> SimpleITK
> antspynet

I opened the repo using vscode and opened a terminal and executes `pip install -r requirements.txt`. after several hours' struggling I still could not solve the issue as follows:

![image](https://github.com/ANTsX/ANTsPy/assets/9004748/2dbad614-76a7-4c48-b883-2065eefa89f0)

I've alredy installed tensorflow but I could not find the version that meets the requirements.  I appreciate if anyone could solve this issue. Thank you!

**Comment by ntustison** [comment]
I'm pretty sure I removed the only application which required tensorflow-probability so you probably don't need to worry about this error.  Check if you can import antspynet with your current set-up.

**Comment by citystrawman** [comment]
> I'm pretty sure I removed the only application which required tensorflow-probability so you probably don't need to worry about this error. Check if you can import antspynet with your current set-up.

You mean that I can remove antspynet from the requirement.txt and import it in the code where it is needed?

**Comment by ntustison** [comment]
I have no idea about antspynet dependencies in this other package.  You'll have to ask over there.  All I can address are questions about antspynet itself.
