### ISSUE TITLE
Cannot re-create affine transform from parameters

### ISSUE THREAD

**Issue by jeroen-aidence** [ANTsX/ANTsPy#525]
I have computed an affine transform. I'd like to save its parameters, store them somewhere and then recreate the affine transform later. However, the transform generated by `ants.new_ants_transform` yields a different output compared to the original transform. 

```
registration = ants.registration(
            fixed=fixed,
            moving=moving,
            type_of_transform="Affine",
        )
transform = ants.read_transform(registration['fwdtransforms'][0])
transform_new = ants.new_ants_transform(dimension=2, parameters=transform.parameters)

moved = transform.apply_to_image(moving, reference=fixed)
moved_new = transform_new.apply_to_image(moving, reference=fixed)
```

**Expected behavior**
I had expected that the resulting images `moved` and `moved_new` would be identical, which is not the case

**Screenshots**

![ants_bug](https://github.com/ANTsX/ANTsPy/assets/118726526/6224a363-2bfd-4c25-8901-750fae476fea)

**Comment by ntustison** [comment]
https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues

For an exactly reproducible affine transform, use `type_of_transform = "antsRegistrationSyNQuickRepro[a]"` or `type_of_transform = "antsRegistrationSyNRepro[a]"`.

**Comment by jeroen-aidence** [comment]
Thanks for the quick reply. That does not really seem to be my issue though. I am not re-estimating the affine transform. I'm just trying to recreate it from existing parameters using `ants.new_ants_transform`.

Changing `type_of_transform = "antsRegistrationSyNQuickRepro[a]"` in `ants.registration` does not solve the issue.

**Comment by stnava** [comment]
that's user error.  the right way is just to read the transform or to use it on disk.   there are several ways.  here is one:

```python
import ants
fi = ants.image_read(ants.get_ants_data('r16'))
mi = ants.image_read(ants.get_ants_data('r64'))
mytx = ants.registration(fixed=fi, moving=mi, type_of_transform = 'SyN' )
tx = ants.read_transform( mytx['fwdtransforms'][1] )
warped_again = tx.apply( mi, 'image', fi )
ants.plot( warped_again, mytx['warpedmovout'] )
# read this to see the parameters you should set
help( ants.create_ants_transform )
```

**Comment by jeroen-aidence** [comment]
Alright, that is indeed a workaround and in most cases the most useful one. In my case that's a little less convenient as I was hoping to only store the `transform.parameters` in a pickle with a bunch of other metadata. 

So you're saying that there is then no option to recreate a transform with either `ants.new_ants_transform` or `ants.create_ants_transform`. I am still a bit puzzled what the use of the `parameters` option then is on both functions.

**Comment by stnava** [comment]
read this to see the parameters you should set

```python
help( ants.create_ants_transform )
```

you need more than what you have done.  please read carefully.

**Comment by cookpa** [comment]
I believe the difference arises because `transform_new` gets the `parameters` array from `transform` but it does not get passed transform's `fixed_parameters`. 

While it's not an efficient way to re-use transforms, it seems wrong that there's no way to set fixed_parameters in the new_ants_transform_method. I can add fixed_parameters as an optional arg to `ants.new_ants_transform` with default None (implies an array of zeros), should be backwards compatible

**Comment by jeroen-aidence** [comment]
That explains it then. You probably would not recommend doing it this way, but setting `transform_new.set_fixed_parameters(transform.fixed_parameters)` in addition did the trick 👍

**Comment by anamazingclown** [comment]
> I believe the difference arises because `transform_new` gets the `parameters` array from `transform` but it does not get passed transform's `fixed_parameters`.
> 
> While it's not an efficient way to re-use transforms, it seems wrong that there's no way to set fixed_parameters in the new_ants_transform_method. I can add fixed_parameters as an optional arg to `ants.new_ants_transform` with default None (implies an array of zeros), should be backwards compatible


@cookpa thanks your answer
may i ask you some question?
this is my code 
`f_img = ants.image_read(f_npy_path)# the data is 2d numpy  shape : 350*740`
`m_img = ants.image_read(m_npy_path)`
`mmtf = ants.registration(fixed=f_img, moving=m_img, type_of_transform = "Affine",verbose=True)`
`mat_data = sio.loadmat(mmtf['fwdtransforms'][0])`
`affine_params = mat_data["AffineTransform_float_2_2"] # output size [6 ,1]`
`fixed_parameters = mat_data['fixed'] # output size[2，1]`
my questions are:
1. does the mat_data["AffineTransform_float_2_2"]  which has size 6*1 output  means the 2*3 affine matrix? IF not ,what does it mean, what's the use
2. What does mat_data['fixed'] mean? What's the use
3. My ultimate goal is to obtain the final affine matrix (I can use other libraries, such as cv2.warpAffine) and the corresponding X-axis and Y-axis offsets of all coordinates relative to the origin (0,0) (the size is 350*740*2, the last dimension is x,y respectively) or the deformation field(which i can use SpatialTransformer like Voxelmorph to get new img)

I have been stuck on the problems for several days, and looked for a lot of information but failed. I really hope that you can help me. Thank you very much. I am always waiting for your reply
