### ISSUE TITLE
improve test coverage or start tracking again

### ISSUE THREAD

**Issue by ncullen93** [ANTsX/ANTsPy#532]
The test coverage badge indicates the coverage is really low. I am not even certain that the test coverage is being actively tracked anymore. If not, it should be re-implemented. If it is being tracked, then the coverage should be increased.

I will assign myself this task but just want to put this out there in case anyone has insight into how to track test coverage with the current CI/CD setup.

**Comment by cookpa** [comment]
I think a lot of this kind of stuff broke when the free Travis services went away. The last build on coveralls was Feb 2020. 

It looks like coveralls itself is still free, so we could have a Github Action that runs unittest and then sends reports to coveralls

**Comment by ncullen93** [comment]
I see Cirrus, Travis, and Appveyor in the repo. Are those all used?

**Comment by cookpa** [comment]
@stnava am I right in thinking Travis and Appveyor are not being maintained any longer? Looks like Cirrus is the only external CI being updated in a long time.

**Comment by stnava** [comment]
yes I think that is the case

**Comment by ncullen93** [comment]
Ok. I got the test coverage going again so I can close this. I appreciate the help.
