### ISSUE TITLE
Error: no module named ants.lib.addNoiseToImage

### ISSUE THREAD

**Issue by QuentinMesnildrey** [ANTsX/ANTsPy#555]
Dear ANTs community, 
I am struggling for my first steps with ANTs and I might need a little help.
I am trying to use ANTs on a windows computer (via WSL). 
I successfully launched jupyter notebook in which I can see all ANTs files.
But when I try to import some modules (eg import ants), the code requires access to other submodules (eg: ants.lib.addNoiseToImage)  that I cannot find where they should be..

Did I miss something? Or do you think the install went wrong?
Thanks for your help
Best
Quentin

**Comment by ncullen93** [comment]
Hi Quentin,

You do not import anything from lib. All functions are actually available at the top level - so for instance in your case just run

`import ants`

Then all functions are directly available:

`ants.add_noise_to_image(...)`

You can look through the docs (link of main page) to see how each function works

**Comment by QuentinMesnildrey** [comment]
Dear Nick, Thanks for your reply. 

I simply ran: 

import ants

Which gives me the following error: No module named 'ants.lib.addNoiseToImage'

btw, I re-ran pip install antspyx to make sure everything is in place and the installation seems to work just fine. 

Best

**Comment by ncullen93** [comment]
Oh ok, apologies for the misunderstanding. This issue has come up before so you may find some info there - e.g., https://github.com/ANTsX/ANTsPy/issues/430 . Unfortunately I'm not too knowledgeable otherwise. I think it's an issue with the pip wheels.

**Comment by cookpa** [comment]
It's possible there's a bad wheel.

Can you uninstall and re-install antspyx with verbose output?

```
pip uninstall antspyx
pip install antspyx --no-cache-dir --verbose
```

should tell us which wheel gets installed

**Comment by cookpa** [comment]
Going to close for inactivity but will add for future searchers, if you have ANTsPy source cloned and then run python from the ANTsPY/ directory, you'll also see this error when you do `import ants`
