### ISSUE TITLE
PyPI updating strategy

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPy#581]
As discussed in #578 and #580

From @ncullen93:

>  looks like it's not the specific build size but just the total storage on pypi being over 10gb? So some old wheels need to be deleted? For what it's worth, I really don't think you need to build wheels for each python distribution specifically. I think it's more common to just build one wheel for "3.x" - see e.g., the pypi [workflow](https://github.com/ncullen93/nitrain/blob/main/.github/workflows/python-publish.yml) I use elsewhere.

I don't have permission to delete old wheels. I am not attached to building every python, I don't know if there's stats on which versions get downloaded the most but will look into it.

What do others (devs and users) think about building fewer wheels?

**Comment by cookpa** [comment]
Via pypistats, over the last 180 days:

<img width="287" alt="image" src="https://github.com/ANTsX/ANTsPy/assets/611507/45a29b21-af98-4619-9be0-97ef485e510d">

<img width="278" alt="image" src="https://github.com/ANTsX/ANTsPy/assets/611507/8c39772d-bcb1-45e8-bc52-cb43bdad8142">

**Comment by stnava** [comment]
ok - do you need pypi admin access @cookpa  ?

**Comment by stnava** [comment]
you got it

**Comment by ncullen93** [comment]
@cookpa can we try to build wheels now and see the size? When I build locally using `python -m build` it's only 16mb but that seems too small.

**Comment by cookpa** [comment]
Windows is failing because it explicitly calls setup.py, let's see if the others build

**Comment by cookpa** [comment]
On Intel Mac, there is a problem with cibuildwheel, it is getting into trouble with the MACOSX_DEPLOYMENT_TARGET. I think it might relate to this known issue with scikit-build

https://github.com/pypa/cibuildwheel/issues/952

Bumping the version of scikit-build and / or cibuildwheel might help

**Comment by ncullen93** [comment]
Yeah I see the small size is also replicated on the ci build. Hoping it is for real. I will try to fix the wheel issues.

**Comment by cookpa** [comment]
I'm hoping that setting `MACOSX_DEPLOYMENT_TARGET=10.14` in the environment will solve the problem. Somewhere it is setting a default of 10.9 and not respecting the pyproject.toml entry.

I may also have to downgrade cibuildwheel to 2.16.2 again, because the latest version appears to break the package delocalization on arm64.

**Comment by cookpa** [comment]
Wheels are looking good, they fall over occasionally but mostly seem to build. It's been a long time since a release made it to PyPI, it would be good to get a new one up.

To do:

* Make space on PyPi. They discourage deleting releases, but it seems like we've done it before, and probably have no choice but to delete at least 0.3.8. The new wheels are so much smaller, we can get 10-20 releases for the same storage, more if we don't support every python version.

* Tag new release. This should trigger the upload to PyPI, but I might need some help if it fails (ie, to manually put some uploads up)

One option would be to leave one wheel per platform of 0.3.8 for now (which?)

**Comment by cookpa** [comment]
<img width="287" alt="image" src="https://github.com/user-attachments/assets/db86786d-1b11-4e4c-924b-d3b0db0837f1">
<img width="287" alt="image" src="https://github.com/user-attachments/assets/488bad00-3dcc-4205-b9cc-74afe9213b2e">

Most recent pypi stats. Mostly Linux, less older python now. I could clean up some 0.3.8 packages and try a new release if it's OK with everyone

**Comment by ntustison** [comment]
Sure, thanks Phil.On Aug 5, 2024, at 6:56 PM, Philip Cook ***@***.***> wrote:﻿
image.png (view on web)
image.png (view on web)
Most recent pypi stats. Mostly Linux, less older python now. I could clean up some 0.3.8 packages and try a new release if it's OK with everyone

**Comment by cookpa** [comment]
Deleted 0.3.8, figure we may as well make more space and not deal with this again for longer.

I'm ready to tag v0.5.3. Do I need to do anything else before releasing? I presume after I tag, I should edit `pyproject.toml` and `ants/__init__.py`, and increment the version to 0.5.4?

**Comment by cookpa** [comment]
It worked! But the workflow only sends Linux wheels. Is there some other mechanism to upload the other platforms?

**Comment by stnava** [comment]
yes - it's via `twine` --- this is from the `ANTsPyMM` README:

```
rm -r -f build/ antspymm.egg-info/ dist/
python3 -m  build .
python3 -m pip install --upgrade twine
python3 -m twine upload --repository antspymm dist/*
```

you need to add some stuff to `pypirc` ie a secret token created on pypi .... I automated this for antspymm which uploads upon a new tag.

**Comment by cookpa** [comment]
OK thanks I will try it out

**Comment by cookpa** [comment]
I uploaded a source dist, which works, and a bunch of wheels from the Github build. Annoyingly, pip won't install the wheel for my Mac unless I do

```
SYSTEM_VERSION_COMPAT=0 pip install antspyx
```

This has long been the case for me with Github wheels. I think I tried to fix this before but will take another look. Hopefully we can get wheels building correctly for the next release

**Comment by cookpa** [comment]
I was able to make a compatible wheel with

```
export MACOSX_DEPLOYMENT_TARGET=10.14
python -m build --wheel
```

For some reason, my Intel Mac only lists 10_X as compatible targets, even though I have Mac OS 14. We might therefore want to change the wheels to target an earlier version, currently they target the runner OS (12 for Intel, 14 for ARM).

My next to-do will be to try building wheels for an earlier OS target.
