### ISSUE TITLE
plot_ortho and plot_ortho_stack orient labels left and right may be not right

### ISSUE THREAD

**Issue by qinqian** [ANTsX/ANTsPy#59]
**Describe the bug**
I tried both functions to visualize brain MRI data, the orientation labels for left and right is opposite to what is shown in ITKSNAP. So, I thought it may be not correct.

**To Reproduce**
image = ants.image_read(path_to_nii)
image.plot_ortho(orient_labels=True) # shown in figure 1
open ITKSNAP and load the nii files, the figure is shown in figure 2

The nifty files are generated by using dcm2niix.

**Expected behavior**
plot_ortho needs to be consistent with ITKSNAP. 

**Screenshots**
![Screen Shot 2019-05-21 at 11 08 59 AM](https://user-images.githubusercontent.com/884386/58065692-274c7880-7bb9-11e9-8a0c-457ab001434e.png)(Figure 1)

![Screen Shot 2019-05-21 at 11 13 56 AM](https://user-images.githubusercontent.com/884386/58065875-c3767f80-7bb9-11e9-9ebf-5dadcc878478.png)(Figure 2)

**Server (please complete the following information):**
 - OS: Ubuntu
 - ANTsPy: 0.1.5 and 0.1.8

**Comment by stnava** [comment]
thanks - I will take a look.   if you have a pull request ( a suggested fix to code ) that would be great.

**Comment by stnava** [comment]
I believe we fixed this.
