### ISSUE TITLE
TruncateIntensity segfault 

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPy#597]
[PPMI-41289-20151201-T1w-643386.nii.gz](https://github.com/ANTsX/ANTsPy/files/14824966/PPMI-41289-20151201-T1w-643386.nii.gz)

on osx using an older antspy on linux using @cookpa latest GitHub release python 3.9.*

```python
import ants
img=ants.image_read("PPMI-41289-20151201-T1w-643386.nii.gz")
ants.iMath(img,'TruncateIntensity',0.01,0.995)
```

gives `Segmentation fault: 11`

the image has the wrong physical space info but opens / loads ok in snap etc.

**Comment by cookpa** [comment]
Reproducible on the command line

```
iMath 3 tmp.nii.gz TruncateIntensity PPMI-41289-20151201-T1w-643386.nii.gz 0.01 0.995
zsh: segmentation fault  iMath 3 tmp.nii.gz TruncateIntensity  0.01 0.995
```
