### ISSUE TITLE
can use ant to register two dicom files

### ISSUE THREAD

**Issue by tanjia123456** [ANTsX/ANTsPy#600]
Hi, thanks for your contribution, 
Can this library implement rigid registration of two dicom files? like the follwing code

`import SimpleITK as sitk
import os
import ants

file_path1 = 'process1/CHEN_MING_LAN_8004816942/SE1/60.IMA'
file_path2 = 'process1/CHEN_MING_LAN_8004816942/SE0/60.IMA'

fixed = ants.image_read(file_path1)
moving = ants.image_read(file_path2)
print("\nfixed=", fixed, "moving=", moving)

SyN = ants.registration(fixed = fixed, moving = moving, typr_of_transform = 'Rigid')
result = ants.apply_transforms(fixed = fixed, moving = moving, transformlist = SyN['fwdtransforms'])`

but the error occurs:
fixed= ANTsImage (RAI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (256, 256, 1)
	 Spacing    : (0.4891, 0.4891, 1.0)
	 Origin     : (-74.7078, -100.8887, -8.1527)
	 Direction  : [ 0.9947 -0.0393  0.0945  0.0276  0.9922  0.1215 -0.0986 -0.1183  0.9881]
 moving= ANTsImage (RAI)
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (256, 256, 1)
	 Spacing    : (0.4891, 0.4891, 1.0)
	 Origin     : (-74.7078, -100.8887, -8.1527)
	 Direction  : [ 0.9947 -0.0393  0.0945  0.0276  0.9922  0.1215 -0.0986 -0.1183  0.9881]

Traceback (most recent call last):
  File "F:\zzmdata\regis_dicom.py", line 14, in <module>
    SyN = ants.registration(fixed = fixed, moving = moving, typr_of_transform = 'Rigid')
  File "D:\software\anaconda\envs\pytorch310\lib\site-packages\ants\registration\interface.py", line 1390, in registration
    raise RuntimeError(f"Registration failed with error code {reg_exit}")
RuntimeError: Registration failed with error code 1

**Comment by ncullen93** [comment]
You have a typo in your call: `typr_of_transform` instead of `type_of_transform`. Try to fix that first. Otherwise, it's also weird that you have an extra dimension in your images (256, 256, 1) - so you should remove that as well.

**Comment by ncullen93** [comment]
You have a typo in your call: `typr_of_transform` instead of `type_of_transform`. Try to fix that first. Otherwise, it's also a potential issue that you have an extra dimension in your images (256, 256, 1) - so you should remove that as well.
