### ISSUE TITLE
new_ants_metric use MeanSquares metric as MattesMutualInformation metric  

### ISSUE THREAD

**Issue by BigPandaCPU** [ANTsX/ANTsPy#602]
The source code of LOCAL_antsImageToImageMetric.h, new_ants_metric function  has an error.

![ANTs](https://github.com/ANTsX/ANTsPy/assets/25834151/282f2351-b117-4414-8144-e291ea8099e8)

The MattesMutualInformation Metrix was not implement, and it replaced by MeanSquares metric.

**Comment by ntustison** [comment]
Thanks.  Added a [pull request](https://github.com/ANTsX/ANTsPy/pull/603).
