### ISSUE TITLE
Should reorientation change the origin?

### ISSUE THREAD

**Issue by ncullen93** [ANTsX/ANTsPy#611]
If you reorient an image, should the origin really stay the same? Here is MNI in its normal form and then when I call `ants.reorient_image2(image, 'PRI')` after. Notice that the spacing does change.

```
ANTsImage (RPI)
         Pixel Type : float (float32)
         Components : 1
         Dimensions : (182, 218, 182)
         Spacing    : (1.0, 2.0, 3.0)
         Origin     : (-90.0, 126.0, -72.0)
         Direction  : [ 1.  0.  0.  0. -1.  0.  0.  0.  1.]
```
```
ANTsImage (PRI)
         Pixel Type : float (float32)
         Components : 1
         Dimensions : (218, 182, 182)
         Spacing    : (2.0, 1.0, 3.0)
         Origin     : (-90.0, 126.0, -72.0)
         Direction  : [ 0.  1.  0. -1.  0.  0.  0.  0.  1.]
```

**Comment by ntustison** [comment]
My vote would be to coordinate with ITK.  However, I don't think that this specific operation is encapsulated in a single filter in ITK so I'm guessing this isn't explicitly prescribed in ITK.  However, ITK-SNAP permits reorientation and it looks like it maintains the same origin and I would just go with that behavior.  But that's just my initial thought.

**Comment by ntustison** [comment]
It looks like SimpleITK might do [something related](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1DICOMOrientImageFilter.html#details) but it's not immediately clear if and how the origin changes.

**Comment by cookpa** [comment]
This seems like a bug to me. The origin is the physical coordinate of voxel (0,0,0). If you change the direction matrix you will change that coordinate, surely?

**Comment by ntustison** [comment]
So I don't have any strong feelings about what should happen.  However, I don't know that it's necessarily a bug but rather a consensus choice in behavior.  It's somewhat analogous to the [flip image filter](https://itk.org/Doxygen/html/classitk_1_1FlipImageFilter.html) in ITK and how this choice in origin is handled by default and the non-default behavior has to be explicitly set.

**Comment by cookpa** [comment]
Yes, you're right. If you reorient, you're changing the relationship between physical spaces and I suppose then it doesn't make sense to expect that physical coordinate (0,0,0) is going to be the same place anatomically.

**Comment by ncullen93** [comment]
Ok, I'm kind of getting the sense that this behavior is expected. I think ants matches the python ITK package so I will close the issue.

Interestingly, the origin does change for some operations - e.g., a flip from RPI to LPI with the mni image.

```python
import ants
image = ants.image_read(ants.get_data('mni'))
image2 = ants.reorient_image2(image, 'LPI')
```


image:
```
ANTsImage (RPI)
         Pixel Type : float (float32)
         Components : 1
         Dimensions : (182, 218, 182)
         Spacing    : (1.0, 1.0, 1.0)
         Origin     : (-90.0, 126.0, -72.0)
         Direction  : [ 1.  0.  0.  0. -1.  0.  0.  0.  1.]
```

image2:
```
ANTsImage (LPI)
         Pixel Type : float (float32)
         Components : 1
         Dimensions : (182, 218, 182)
         Spacing    : (1.0, 1.0, 1.0)
         Origin     : (91.0, 126.0, -72.0)
         Direction  : [-1.  0.  0.  0. -1.  0.  0.  0.  1.]
```
