### ISSUE TITLE
The impact of image normalization on antspy

### ISSUE THREAD

**Issue by yuanpengpeng** [ANTsX/ANTsPy#614]
When using antspy, can you normalize two three-dimensional images in .nii.gz format to 0-1 and then perform registration? I tried it and found that the effect after normalization was not unnormalized. Good effect

**Comment by cookpa** [comment]
Yes, you can normalize images before registration.

**Comment by cookpa** [comment]
BTW does this mean you solved #613 ? If you could add a comment explaining how you fixed it, it might help future users.

**Comment by yuanpengpeng** [comment]
> BTW does this mean you solved #613 ? If you could add a comment explaining how you fixed it, it might help future users.

yes,  you are right, I have solved #613 .
