### ISSUE TITLE
`SyNOnly` registration returns non-identity .mat

### ISSUE THREAD

**Issue by koegl** [ANTsX/ANTsPy#615]
**Describe the bug**
I have affinely registered images that I want to further register using SyN - the output I am looking for is the warped image and the corresponding displacement field in .nii.gz.

For `type_of_transform` I chose `SyNOnly`, because, according to the [documentation](https://antspy.readthedocs.io/en/latest/registration.html)

> “SyNOnly” [...] no initial transformation [...] Assumes images are aligned by an initial transformation

However, when I run the registration, the resulting .mat is not an identity, it has a non-zero translation component.

**To reproduce**
I uploaded the two .nii.gz images that I was using and the resulting affine and displacement field to [dropbox](https://www.dropbox.com/scl/fo/mw241r27llv8av0k6qfj3/ADYcBPKSfAEZdBiYCynoNz0?rlkey=g516yo5ff2v5suip8jvkepil2&st=16uzlu9t&dl=0).

This is the snippet to run the registration:
```python
import ants

fixed_image = ants.image_read("tumor1.nii.gz")
moving_image = ants.image_read("tumor2.nii.gz")

registration = ants.registration(
    fixed=fixed_image,
    moving=moving_image,
    type_of_transform='SyNOnly',
    write_composite_transform=False)
```

**Expected behavior**
The documentation suggests that the images should be already aligned, so I would expect the translation component to be 0 (and the entire .mat to be identity).

**Screenshots**

**ANTsPy installation (please complete the following information):**

 - Hardware [Lenovo ThinkPad X1]

 - OS: [Ubuntu 22.04.4 LTS]
 
 - System details [Linux 6.5.0-28-generic x86_64]
 
 - Sub-system: [None]
 
 - ANTsPy version: [0.4.2]

 - Installation type: [pip]
 - Python version: [3.10.14]

**Additional context**
My goal is to get a .nii.gz displacement field - so I would also be content with a way of transforming the composite .h5 transform (with `write_composite_transform=True` to .nii.gz)

**Comment by stnava** [comment]
see #466

**Comment by cookpa** [comment]
I see I was supposed to fix this, will document.

**Comment by cookpa** [comment]
Closed by the PR, but please re-open if needed @koegl
