### ISSUE TITLE
image_read 12M then image_write 24M

### ISSUE THREAD

**Issue by chestnut111** [ANTsX/ANTsPy#63]
hello,I find something strage when use image_read and image_write:
my code is that:
`import SimpleITK as sitk
import numpy as np
import os
import ants`

`file_3 = './input/wpre_3d.nii'
data_3 = sitk.ReadImage(file_3)`

the size of the wpre_3d.nii is 12M,the pix type read by sitk is :
`data_3.GetPixelIDTypeAsString()`
`'16-bit unsigned integer'`

the use the ant to read ：
`data_ant = ants.image_read(file_3)
data_ant`
![image](https://user-images.githubusercontent.com/26037045/60319782-28d44200-99aa-11e9-820d-c90148ae333d.png)
pix type is float 32?

the write image ：
`ants.image_write(data_ant,'data_ant.nii')`
size is the 24M。
how did it from 12M TO 24M?

thx!!

**Comment by ntustison** [comment]
ANTs typically reads/writes everything in as float by default.

**Comment by stnava** [comment]
yes - float is double the size ( in memory ) of int16.  supported types in antspy are currently:

```
Supported types are {'float', 'unsigned int', 'double', 'unsigned char'}
```
