### ISSUE TITLE
ants.iMath_histogram_equalization

### ISSUE THREAD

**Issue by mathxiaobin** [ANTsX/ANTsPy#667]
I am using the ants.iMath_histogram_equalization interface, but I don't understand what the alpha and beta parameters represent. Can someone please explain what these parameters mean?

**Comment by ntustison** [comment]
https://itk.org/Doxygen/html/classitk_1_1AdaptiveHistogramEqualizationImageFilter.html

**Comment by mathxiaobin** [comment]
Thanks！
