### ISSUE TITLE
An question about the return results of ants.registration

### ISSUE THREAD

**Issue by windyjunfeng** [ANTsX/ANTsPy#685]
Hi, I have a question about the return results of ``ants.registration``. The .mat files of 'fwdtransforms' and 'invtransforms'  involve 'fixed' vector (3 elements) except the affine matrix. What's the meaning of the 'fixed' vector? Can I ignore it and only use the affine matrix? I couldn't find any description about it in the ants documentation. Thank you~
![20fdf3ce085460bffe18fe9f9a8d161](https://github.com/user-attachments/assets/acabc511-048b-40a6-9dd5-a449ff1a63c0)

**Comment by cookpa** [comment]
The fixed parameters are the center of rotation, you can't ignore them unless they are zero

**Comment by windyjunfeng** [comment]
@cookpa Thanks for your reply very much. I read the link. I tried to utilize simpleITK and scipy to affine image by ``AffineTransform_float_3_3`` and ``fixed`` gotten by ants.registration, but failed. The transformed image isn't correct. Here are the following codes by simpleITK.
```
import SimpleITK as sitk
import numpy as np
from scipy.io import loadmat

path=r'/home/Reset_T1_brain/sub002t1_noise_corrected_brain_reset_origin.nii.gz'
image=sitk.ReadImage(path)
affine_transform=sitk.AffineTransform(3)
path_mat=r'/home/affine_matrix_forward_1mm/affine_matrix_forward.mat'
affine_matrix=loadmat(path_mat)['AffineTransform_float_3_3']
affine_matrix_reshape=affine_matrix.reshape((3,4),order='F')
affine_transform.SetMatrix(affine_matrix_reshape[:,:3].flatten().tolist())
affine_transform.SetTranslation(affine_matrix_reshape[:, 3].tolist())
rotation_center=np.squeeze(loadmat(path_mat)['fixed'])
affine_transform.SetCenter(rotation_center.tolist())
template=sitk.ReadImage(r'/home/MNI152_T1_1mm_Brain.nii.gz')
resampled_image = sitk.Resample(image, template, affine_transform, sitk.sitkLinear, 0.0, image.GetPixelID())
sitk.WriteImage(resampled_image,'/home/transformed_img_linear_sitk_1.nii.gz')
```
affine_matrix_forward.mat is the returned result of ants.registration ``fwdtransforms`` (``fixed`` is ``MNI152_T1_1mm_Brain.nii.gz``, ``moving`` is ``sub002t1_noise_corrected_brain_reset_origin.nii.gz``, and ``type_of_transform`` is ``DenseRigid``)

The result of my codes is shown as follows.
![image](https://github.com/user-attachments/assets/7e77f2b3-5766-4f11-8254-9545679daee8)

But the ``warpedmovout`` returned by ants.registration is shown as follows.
![image](https://github.com/user-attachments/assets/44fe14e0-a053-45dd-9488-3bf4f1aaf01a)

Actually, I need to get the true 4\*4 affine matrix to multiply another 4\*4 known affine matrix, which transforms a known coordinate system into subject space and then into the template space. If there isn't any good way to transform by simpleITK, any suggestions for the goal?

Besides, I hanve another question. I find the result of ``ants.apply_transforms(fixed=template, moving=seg_image, transformlist=affine_matrix_forward)`` is different from ``warpedmovout`` returned by ants.registration, in terms of the space location and voxel value (you can see the edge part carefully). I tried different interpolation methods. Why does this occur?
![image](https://github.com/user-attachments/assets/88e4a9ab-f988-4345-b4c8-78d5731f1d11)

Thanks again~

**Comment by cookpa** [comment]
SimpleITK can read the affine transform directly, you don't need to involve scipy in this case. 

```
import ants

moving = ants.image_read('t1w.nii.gz')
fixed = ants.image_read('tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz')

reg = ants.registration(fixed, moving)

ants.image_write(reg['warpedmovout'], 't1wWarped.nii.gz')

import shutil
shutil.copyfile(reg['fwdtransforms'][1], 't1wToMNI.mat')
```

This can be read into SimpleITK

```
import SimpleITK as sitk
moving = sitk.ReadImage('t1w.nii.gz')
transform = sitk.ReadTransform('t1wToMNI.mat')
fixed = sitk.ReadImage('tpl-MNI152NLin2009cAsym_res-01_T1w.nii.gz')
resampled_image = sitk.Resample(moving, fixed, transform)
sitk.WriteImage(resampled_image, 't1wWarpedSITK.nii.gz')
```

The subtle differences that remain between `t1wWarped.nii.gz` and `t1wWarpedSITK.nii.gz` are probably due to differences in the memory representation of the images and / or the transforms. ANTsPy defaults to float32 for images, but the registration call will use float64.

**Comment by windyjunfeng** [comment]
Thanks for your help! I made it. The result of SimpleITK is the same as the result of ants.apply_transforms.
