### ISSUE TITLE
ValueError: Image Size Too Large When Plotting ANTsImage Using `ants.plot()`

### ISSUE THREAD

**Issue by GayanSamuditha** [ANTsX/ANTsPy#695]
@ntustison 
**Describe the bug**
When attempting to plot an ANTsImage using **`ants.plot(img_test)`**, the program throws a `ValueError` stating that the image size of 165888x540 pixels is too large.

**To reproduce**
1. Import the necessary libraries and load an image.
   ```python
   import ants
   img_test = ants.image_read("path_to_your_image")
   ```
2. Attempt to plot the image.
   ```python
   ants.plot(img_test)
   ```

**Expected behavior**
The image should be displayed without throwing an error.

**Screenshots**
![error image antspy](https://github.com/user-attachments/assets/1086064d-7bb6-4728-a079-bd086f8b9df5)

**ANTsPy installation (please complete the following information):**
 - Hardware [HPC cluster]
 - OS: [Linux]
 - System details [Linux 4.18.0-425.10.1.el8_7.x86_64 x86_64]
 - Sub-system: [None]
 - ANTsPy version: [0.4.2]
 - Installation ty
[MRI Image 01.zip](https://github.com/user-attachments/files/16551189/MRI.Image.01.zip)
pe: [pip]

**Additional context**
This issue arises specifically when plotting images with certain dimensions. The error suggests that the calculated image size exceeds the permissible limit. I attached the MRI image here

**Comment by cookpa** [comment]
The plotting code has changed a lot since 0.4.2, with 0.5.3 I can plot the slice. But it doesn't cope well with the 3D image with one slice; instead I did this

```
ima = ants.image_read('MRI Image 01.dcm')
img2d = img[:,:,0]
ants.plot(img2d)
```
