### ISSUE TITLE
Boolean masks from `get_mask`?

### ISSUE THREAD

**Issue by dangom** [ANTsX/ANTsPy#70]
I see `mask = ants.get_mask(data)` returns a binary mask in 'float32'. I also see that `mask.astype(bool)` fails because Datatype <class 'bool'> is not supported. Is this a hard ANTs restriction or something that could be easily changed internally?

I ask so because not all nilearn functions (and other software as well) play well with floating point masks. It'd be convenient if masks could be saved as bool, or at least integer type.

I guess uint8 is not so bad as a workaround but it's an extra 7 bits of useless padding.

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy/blob/master/ants/core/ants_image.py#L31-L42

supported types.  I added a short branch to ANTsR but opted not to include it in the main repo b/c it bloats builds - every type adds compile time as well.

**Comment by stnava** [comment]
does nilearn work ok with `uchar`?
