### ISSUE TITLE
Error when installing ANTsPy: Failed to build antspyx

### ISSUE THREAD

**Issue by Lucifer201210** [ANTsX/ANTsPy#701]
Hi, I use the following code to install `ANTsPy` in my conda environment,  but it's failed.

`
git clone https://github.com/ANTsX/ANTsPy

cd ANTsPy

python -m pip install .
`
The screenshots of installation information was as follows:
![截图 2024-08-23 13-55-37](https://github.com/user-attachments/assets/e2753072-7e71-4bde-8e9c-b15fae9785fb)
![截图 2024-08-23 13-55-56](https://github.com/user-attachments/assets/1c30c436-97a1-4a8a-be15-8d891e794f49)
![截图 2024-08-23 13-56-06](https://github.com/user-attachments/assets/35a1f7ab-59ba-452c-8b6a-4c7145143b20)
![截图 2024-08-23 13-56-22](https://github.com/user-attachments/assets/fc42a17b-b5a5-457f-8614-4972adf97488)
![截图 2024-08-23 13-56-33](https://github.com/user-attachments/assets/e380ffb0-92a0-4b4d-a4b4-95e96a623e4f)
![截图 2024-08-23 13-56-40](https://github.com/user-attachments/assets/51204294-d1dd-482a-b14b-d2725c7d2cec)
![截图 2024-08-23 13-56-48](https://github.com/user-attachments/assets/b60f5269-9ee9-4069-a28e-e7e47be8fb3e)
![截图 2024-08-23 13-57-00](https://github.com/user-attachments/assets/89710eae-eb4e-40d5-9866-2bb1e6d3016e)
![截图 2024-08-23 13-57-09](https://github.com/user-attachments/assets/2be9d863-aa1c-42d8-bbbf-df0c9c28e3e0)
![截图 2024-08-23 13-58-06](https://github.com/user-attachments/assets/7b41955a-c09e-4e01-81c6-839e10523571)
![截图 2024-08-23 13-58-33](https://github.com/user-attachments/assets/d6c314b7-ddbd-4596-a872-e9717f90c120)

My OS is ubuntu 22.04. My conda environment is newly created and the python version is 3.9. `Tensorflow` and `pytorch` is not installed in my conda environment. Is it needed to intstall `Tensorfolw`, `pytorch` or any other dependencies before installing `ANTspy`?

**Comment by ntustison** [comment]
ANTsPy depends on the ITK package and it looks like you're having the same connection issues in retrieving ITK.

**Comment by cookpa** [comment]
See the cmake errors. You need zlib and png libraries.

`sudo apt-get install zlib1g zlib1g-dev libpng-dev`
