### ISSUE TITLE
Different results on different devices

### ISSUE THREAD

**Issue by conglin10** [ANTsX/ANTsPy#707]
Hi,
I want to get same results with same dicom images.
So I set ：

```
os.environ["ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS"] = "1"
ants.registration(fixed=f_img, moving=m_img, type_of_transform='Affine', verbose=False, random_seed=1)
```

I can get same results on my computer.But I will get different results on different computer.

Do you know what caused this result and how can I get same results on different computer?

**Comment by gdevenyi** [comment]
Have you read all of https://github.com/ANTsX/ANTs/wiki/antsRegistration-reproducibility-issues ?

**Comment by cookpa** [comment]
I'm not sure perfect reproducibility is possible on different machines. How different are the results?
