### ISSUE TITLE
how can i get  displacement field？

### ISSUE THREAD

**Issue by anamazingclown** [ANTsX/ANTsPy#708]
Thank you very much for your work. I have a question and hope you can answer it？
I want to obtain the displacement field from an affine transformation. 
warped_img = ants.apply_transforms(fixed=f_img, moving=m_img, transformlist=mmtf['fwdtransforms'], interpolator="linear")
How can I get a 2D flow from mmtf['fwdtransforms'] so that I can use it as a input to a Spatial Transformer, such as the one in VoxelMorph?
![image](https://github.com/user-attachments/assets/334ebd83-b56c-4a58-be04-4c7ab9ad5ebf)

I am looking forward to receiving your answer,Thanks!

**Comment by ntustison** [comment]
Actually, it looks like a default suffix is added to the file so, in the previous example, the output file would be "disp.nii.gzcomptx.nii.gz".

**Comment by ntustison** [comment]
It appears that this is being [discussed elsewhere](https://github.com/ANTsX/ANTsPy/issues/711).  CLosing.
