### ISSUE TITLE
FOV oddities when using apply_registration (as opposed to ANTs CLI)

### ISSUE THREAD

**Issue by smeisler** [ANTsX/ANTsPy#709]
**Describe the bug**
In this particular example, an MNI-to-subject registration results in the transformed image being cropped because the moving FOV is retained. I cannot show a picture due to the particular sensitivity of the problematic data.

**To reproduce**
Before applying the registration, a registration was calculated via a Robust MNI alignment nipype interface including an affine initializer followed by non-linear warp.
```
# The argument variables are paths to images as suggested by their name
mni2009_to_sub = apply_transforms(sub_t1w, mni2009_t1w, mni2009_to_sub_xfm_path, interpolator = "lanczosWindowedSinc")
mni2009_to_sub.to_filename("output.nii.gz")
```
a typical ANTs CLI produces better looking images with correct FOVs

```
antsApplyTransforms -r $SUB_T1 -i $MNI_T1 -n LanczosWindowedSinc -t $MNI_TO_SUB_XFM -o $OUT
```

**Expected behavior**

Resultant FOV after registration should match the reference, not input image.
**Screenshots**

I cannot show a picture due to the particular sensitivity of the problematic data.

**ANTsPy installation (please complete the following information):**

 - Hardware [Mac]

 - OS: [Mac]
 
 - System details [OS 15.0]
 
 - Sub-system: [None]
 
 - ANTsPy version: [0.5.3]

 - Installation type: [pip]

**Additional context**
Add any other context about the problem here. Many issues are specific to particular data
so please include example data if possible.

**Comment by cookpa** [comment]
Thanks for this.

ANTsPy devs: @smeisler is a colleague at Penn and working on qsiprep, which uses antspy (but not the latest version). I'll update this issue if there's antspy fixes to be done.

**Comment by cookpa** [comment]
This looks like it was probably a viewer issue, so closing for now
