### ISSUE TITLE
The kernel 'Python 3.12.4' died.

### ISSUE THREAD

**Issue by thanoszisis** [ANTsX/ANTsPy#712]
after importing ants (installed the antspyx==0.5.3), the kernel crashes when i try to run ants.image_read

**Comment by cookpa** [comment]
ANTsPy is building and running normally on Python 3.12 on all platforms, so I think it's something particular to your environment.

What system (computer, OS, python version and source) and antspy (installed via pip, source, wheel) are you using?

I just did (on my Intel mac)

```shell
mamba create -n antspy312 python=3.12
mamba activate antspy312 
% python
Python 3.12.6 | packaged by conda-forge | (main, Sep 30 2024, 17:55:16) [Clang 17.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ants
>>> im = ants.image_read(ants.get_ants_data('r16'))
>>> im
ANTsImage
	 Pixel Type : float (float32)
	 Components : 1
	 Dimensions : (256, 256)
	 Spacing    : (1.0, 1.0)
	 Origin     : (0.0, 0.0)
	 Direction  : [1. 0. 0. 1.]
	```

**Comment by thanoszisis** [comment]
I am using vsc on windows 11.My python version is Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32 and I am also using python v2024.14.1 extension on vsc. installed antspyx 0.5.3 via pip. Thank you for your reply

**Comment by cookpa** [comment]
We're building wheels for Windows on Python 3.12 successfully. Can you paste the full error message?

**Comment by thanoszisis** [comment]
i only get a warning stating The kernel 'Python 3.12.4' died.

**Comment by cookpa** [comment]
This sounds like a vscode issue. You might be able to edit the settings to turn on debugging logs, which might provide more clues. Or you can try to reproduce from the command line python, which would tell you if it's a system-wide issue or just something about the vscode environment.

**Comment by cookpa** [comment]
Similar issue #758 solved by installing the latest MSVC runtime https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
