### ISSUE TITLE
Building wheel for antspyx did not run successfully.

### ISSUE THREAD

**Issue by XiaopengZzh** [ANTsX/ANTsPy#715]
Bug : 

I'm trying to install antspyx on my Windows machine. I just simply did 'pip install antspyx' but something went wrong with the wheel building. It seems like cmake cannot find ITK on my machine. Is there any quick solution for this? I saw the 'building_wheels' tag is 'passing' in the readme file so I guess there should be a easy way to solve this. Please help me out.

Btw my mac and linux can install antspyx very easily by 'pip install antspyx' but not windows because of this.

This is the detailed error I got after 'pip install antspyx'

![image](https://github.com/user-attachments/assets/4a655403-fc87-4743-9d81-a42509b84f2d)

 - Hardware [ PC ]
 - OS: [ Windows ]
 - System details [ OS Name : Microsoft Windows 11 professional, OS version : 10.0.22631 N/A Build 22631, System Type : x64-based PC ]
 - Installation type: [ pip ]

**Comment by cookpa** [comment]
Can you use a pre-compiled wheel? Sometimes compatible wheels are not recognized correctly, you could try

```
SYSTEM_VERSION_COMPAT=0 pip install antspyx
```

When you build on Linux or Mac, does it build from source?

Are you using WSL or a powershell terminal here? 

There might be more clues in the full output, if you can do something like

```
pip install antspyx | tee antspy_install.txt
```

And then attach `antspy_install.txt` to a comment

**Comment by XiaopengZzh** [comment]
Thank you so much for your reply!

I didn't build from source when building on Linux and mac. A simple 'pip install antspyx' works on linux and mac.

On windows, I'm not using WSL or powershell terminal. I'm just using the command prompt. 

I got the output file from Windows. Please take a look.
[antspy_install.txt](https://github.com/user-attachments/files/17333036/antspy_install.txt)
