### ISSUE TITLE
API changes across minor versions considered harmful

### ISSUE THREAD

**Issue by rueberger** [ANTsX/ANTsPy#718]
We have a project which was developed and tested against `antspyx==0.3.2`. As we are preparing the final proofs and repo for publication I have discovered to my horror that the 0.3.2 binary is no longer available on PyPI. Further to my horror, there has been a breaking change in the API - ` ants.core.ants_image.ANTsImage` is no longer aliased to  `ants.ANTsImage`.  Needless to say this is less than ideal, and is why god invented `__init__.py`.

**Comment by cookpa** [comment]
Space limitations on pypi necessitated the removal of earlier versions. 

Now that the wheels are much smaller, the lifespan of releases on pypi should be much longer.

The antsImage import change was unintentional and was fixed in #700, but hasn't made it into a release yet.
