### ISSUE TITLE
unsupported pixel type short in ANTsPy

### ISSUE THREAD

**Issue by ronangarrison** [ANTsX/ANTsPy#72]
When reading an image, an error is returned because short data types are not a supported data type for ANTsPy. Is there a way around this to include compatibility for short data types. Or is there a good way to convert data types from short to a float for example (maybe in ants_image_io.py).

**Comment by stnava** [comment]
see discussion here:   https://github.com/ANTsX/ANTsPy/issues/37  and here https://github.com/ANTsX/ANTsPy/issues/70

**Comment by stnava** [comment]
you can also add the short type to a branch and make a pull request, as we've done with ANTsR.  if you need more feedback, please reopen the issue.

**Comment by mariecpereira** [comment]
I get the same error when reading an image of 'pixeltype': 'unsigned short', did anybody find a solution to this error? Either by adding this to ANTsPy or converting the data to another supported type?  

loaded_data = ants.core.image_read('bold.nii')
~/.conda/envs/antspy/lib/python3.6/site-packages/ants/core/ants_image_io.py in image_read(filename, dimension, pixeltype)
    401 
    402         if ptype in _unsupported_ptypes:
--> 403             raise ValueError('unsupported pixeltype %s' % ptype)
    404 
    405         libfn = utils.get_lib_fn(_image_read_dict[pclass][ptype][ndim])

ValueError: unsupported pixeltype unsigned short


When trygint to install from source code: 

449 $ pip install https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: antspy==0.1.4 from https://github.com/ANTsX/ANTsPy/releases/download/v0.1.4/antspy-0.1.4-cp36-cp36m-linux_x86_64.whl in /home/.conda/envs/antspy/lib/python3.6/site-packages (0.1.4)
