### ISSUE TITLE
ants.apply_transforms returns None

### ISSUE THREAD

**Issue by hbhutta** [ANTsX/ANTsPy#725]
**Describe the bug**
Getting None when using `ants.apply_transforms`

**To reproduce**
```python
import pickle
import ants

"""
Here I am loading the forward transforms from a previously completed registration
where an MRI (moving) image was registered to CT (fixed) image
"""
with open("testing/reg.pkl", "rb") as file:
    mytx = pickle.load(file)
"""
I double checked that mytx is just the serialized output of the registration. The serializing and loading is not affecting `apply_transforms` AFAIK
"""

print(mytx)
    
fixed = 'testing/28_proc_ct.nii'
moving = 'testing/28_proc_vent.nii'

out = ants.apply_transforms(fixed=fixed, moving=moving, transformlist=mytx['fwdtransforms'])
print(out) # None
```

**Expected behavior**

What I expect to get is a warped version of the moving image (the ventilation image) saved into the `out` variable. I should then be able to do `ants.image_write(image=out, filename=...)`

**Screenshots**

This is what I get when I run the above code (in a file called `dummy.py`):
![image](https://github.com/user-attachments/assets/e93edead-42a1-455f-8f82-1e9076ef51df)

**ANTsPy installation (please complete the following information):**

 - Hardware: On computing cluster (if this makes a difference)

 - OS: 
 
 - System details Linux 5.15.0-122-generic x86_64
 
 - Sub-system: N/A
 
 - ANTsPy version: 0.5.3

 - Installation type: `pip install antspyx`

**Additional context**
The fixed image (CT) and the moving image (MRI) that were originally registered were both masks, so there were hard boundaries defined. The ventilation image on which I am trying to apply the forward transforms from the above mentioned registration, does not have hard boundaries -- in fact it is quite a fuzzy image. Would this have any impact on the return value of `apply_transforms`?

**Comment by hbhutta** [comment]
Oh my goodness I need to pay attention, I forgot to use `ants.image_read()` 🧠

**Comment by cookpa** [comment]
The transforms are strings, they are the path to temporary files, so they may not persist between sessions. You may need to save them somewhere yourself in order to use them this way

**Comment by hbhutta** [comment]
Would I need to save these temp files even if I have serialized the registration output?

**Comment by cookpa** [comment]
From your output

```
'fwdtransforms': ['/tmp/tmpnteshf1h1Warp.nii.gz', '/tmp/tmpnteshflh0GenericAffine.mat']
```

I think if you serialize this it will save a list with these two strings that you can load later, but the files on /tmp might not exist tomorrow, or after you reboot. 

Also, I'm not sure antsImage objects can be serialized, because they are bound to C++ objects.
