### ISSUE TITLE
Reproducible memory leaks

### ISSUE THREAD

**Issue by cookpa** [ANTsX/ANTsPy#733]
**Update 2024-11-18**: a serious memory leak in `ants.image_similarity` was identified and fixed. If you have reproducible examples of memory leaks in other functions, please read on.

I'm going to ask that everyone run in a clean conda / mamba / venv. Not in a docker container, or a jupyter notebook, or any other fancy environment, just a plain terminal with python and antspyx.

Install antspyx with

```
pip install antspyx==0.5.4 --index-url https://pypi.org/simple --no-cache-dir
```

Set threads

```
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=4
```

(you can make this more, up to 8, if you like, or less, as you need. But please report what you set).

Please make a minimal script that demonstrates the issue. If possible, use `get_ants_data`. If that doesn't work, include data.

Measure python memory use in another tab with htop or top. I've tried reporting memory use in Python but I fear it might not be accurate, especially if there are C++ objects being leaked. 

Please add:

* Your script (+ data if applicable)

* python version

* OS version and hardware (eg, 2021 M1 Macbook pro, OS 14.0, Ubuntu Linux 22.04 x86_64)

* the value of ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS in your environment

* The approximate memory use at 1 min, 5 min ... after 5 min, feel free to check at whatever interval you like. 

* How you checked memory (ps, top, htop) - please specify memory use and units.

**Comment by cookpa** [comment]
My machine: 2020 Intel Macbook pro, OS 14.7

Python 3.12.7

ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=3

Script:

```
import ants
import os

# Testing for memory leaks in ants registration
# run 2D registration in a loop

fixed = ants.image_read(ants.get_ants_data('r16'))
moving = ants.image_read(ants.get_ants_data('r64'))

for i in range(1000000):
    reg = ants.registration(fixed=fixed, moving=moving, type_of_transform='SyN', aff_iterations=(10, 10, 0, 0), aff_metric='mattes', syn_metric='mattes', reg_iterations=(1, 1, 0))
    # delete transform file
    os.remove(reg['fwdtransforms'][0])
    os.remove(reg['fwdtransforms'][1])
    os.remove(reg['invtransforms'][1])
    if i % 100 == 0:
        print(i)
```

Memory measured in htop RES (M)

Numbers below approximate

```
Iteration,MemMB,TimeMin
0,197,0
1000,209,9
2000,218,17
3000,226,24
4000,232,32
```

**Comment by cookpa** [comment]
Larger images:

```
import ants
import os

# Testing for memory leaks in ants registration
# run 2D registration in a loop

fixed = ants.image_read(ants.get_ants_data('r16'))
moving = ants.image_read(ants.get_ants_data('r64'))

fixed = ants.resample_image(fixed, (512, 512), 1, 0)
moving = ants.resample_image(moving, (512, 512), 1, 0)

for i in range(1000000):
    reg = ants.registration(fixed=fixed, moving=moving, type_of_transform='SyN', aff_iterations=(10, 10, 0, 0), aff_metric='mattes', syn_metric='mattes', reg_iterations=(1, 1, 0))
    # delete transform file
    os.remove(reg['fwdtransforms'][0])
    os.remove(reg['fwdtransforms'][1])
    os.remove(reg['invtransforms'][1])
    if i % 100 == 0:
        print(i)
```

```
Iteration,MemMB,TimeMin
0,234,0
1000,314,27
```

**Comment by stnava** [comment]
note : https://github.com/ANTsX/ANTsPy/issues/117#issuecomment-584814183

**Comment by cookpa** [comment]
Thanks @stnava . It looks like the destructor was not ported over to nanobind. The bug is definitely back

```
import ants
import os

# Testing for memory leaks in ants registration
# run 2D registration in a loop

fixed = ants.image_read(ants.get_ants_data('r16'))

fixed = ants.resample_image(fixed, (512, 512), 1, 0)

for i in range(1000000):
    ants.image_similarity(fixed, fixed, metric_type='Correlation')
    if i % 100 == 0:
        print(i)
```

**Comment by cookpa** [comment]
I'm going to test adding the destructor to the nb::capsule call here

```
antsMetric.pointer           = nb::capsule(ptr);
```

**Comment by cookpa** [comment]
OK I think image_similarity is fixed in #734 - will need to review and find other instances where this is needed

**Comment by cookpa** [comment]
Merged #734 thanks @stnava @dipterix

I ran registration in a loop overnight and it seems pretty stable in memory use. It creeps up at first but I ran 80,000 2D registrations and 2000 3D registrations and it didn't crash my computer and seemed to stabilize in memory use after a while.

**Comment by dyollb** [comment]
@cookpa did you try calling the garbage collector in each iteration? We have seen similar behavior in our software and it mostly was explained by the heuristics used by Python's garbage collector, which don't work well when you have just a few objects (to collect), but each objects own lots of data.

See https://docs.python.org/3/library/gc.html#gc.set_threshold

**Comment by dipterix** [comment]
I ran registration and it seems the memory got collected: the RAM got from 12GB down to 5GB at each stage
