### ISSUE TITLE
ants.label_overlap_measures warning

### ISSUE THREAD

**Issue by stnava** [ANTsX/ANTsPy#747]
>>> import ants
>>> r16 = ants.image_read( ants.get_ants_data('r16') )
>>> r64 = ants.image_read( ants.get_ants_data('r64') )
>>> s16 = ants.kmeans_segmentation( r16, 3 )['segmentation']
>>> s64 = ants.kmeans_segmentation( r64, 3 )['segmentation']
>>> stats = ants.label_overlap_measures(s16, s64)
/Users/stnava/miniconda3/lib/python3.11/site-packages/ants/label/label_overlap_measures.py:43: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'All' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[0, 'Label'] = 'All'

just a note.   previous fix worked for me but local builds not currently working on my machine so can't test RN.

**Comment by cookpa** [comment]
OK thanks, the fix broke the GHA builds on Mac and Linux. Maybe a pandas version issue, will investigate.
