### ISSUE TITLE
kernel appears to have died. 

### ISSUE THREAD

**Issue by lucixia3** [ANTsX/ANTsPy#758]
Hello, I installed ANTSPYX few weeks ago and i use it but yesterday when I was running the code (using ants) this message appeared: appears to have died. It will restart automatically.

i try to install on another computer and the same thing happens. How can I solve this probem?

**Comment by cookpa** [comment]
What OS is this? 

Possibilities are:

1. Something wrong with your images
2. Something wrong with your environment (eg, file permissions, lack of memory)
3. Bug in basic image I/O
4. Something else (eg, dependencies, incompatible CPU)

The I/O is pretty heavily tested so I think it's unlikely that it can't read a valid image. However, it is possible it's failing and not giving an informative error. 

It's also possible that the error is being printed to a console that is not visible in your notebook. Can you try running from a terminal?

**Comment by cookpa** [comment]
Thanks, there was another report of Windows issues recently. The wheels are built on Github Actions, and are working, but that is running Windows Server 2022. I wonder if there is some kind of runtime library problem.

When you say it was working before, do you mean an older version of ANTsPy?

**Comment by luuciaborrego02** [comment]
What do you mean? the problem is with Windows Server?
Yes, sorry, when I say that it worked it is with the same version 0.5.4. If I just run 'import ants' I don't get any problem and the kernel doesn't die either.

thanks for helping

**Comment by cookpa** [comment]
The Github Actions runners run Windows Server, and they update themselves periodically.

ANTsPy is Python code but it compiles and calls C++ libraries. So it can import OK (just loads the Python), but when you read an image it calls ANTs and ITK C++ code.

Sometimes, paths or libraries from the wrong Visual Studio version can cause problems like this. For example, 

https://github.com/ANTsX/ANTs/issues/1786

this user was running ANTs (not ANTsPy) but needed to install the MSVC runtime

https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

**Comment by luuciaborrego02** [comment]
Yes!!! Now it works!!! Thank you very much!
