### ISSUE TITLE
Installation Failure on Ubuntu

### ISSUE THREAD

**Issue by rousseau** [ANTsX/ANTsPy#78]
Installation does not work on Ubuntu 18.04, Python 3.7.4 (installed with miniconda), cmake 3.14.0, pybind11 2.2.4

I've tried the following command line: 
pip install git+https://github.com/ANTsX/ANTsPy.git

Everything is fine until : 

HEAD is now at 680942c1 BUG: antsApplyTransforms -e 4 would write input image rather than deformed image
  Configuring ANTsPy library
  -- The C compiler identification is GNU 7.4.0
  -- The CXX compiler identification is GNU 7.4.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found PythonInterp: /home/rousseau/miniconda3/bin/python (found version "3.7.4")
  CMake Error at pybind11/tools/FindPythonLibsNew.cmake:122 (message):
    Python config failure: Python is 0-bit, chosen compiler is 64-bit
  Call Stack (most recent call first):
    pybind11/tools/pybind11Tools.cmake:16 (find_package)
    pybind11/CMakeLists.txt:28 (include)

It seems that cmake does not find suitable Python version through pybind11.

Any help for appropriate configuration of cmake / pybind?
Thank you.

**Comment by stnava** [comment]
hmm - I've successfully installed with 3.7.3 .... would be surprised if something failed by a .1 increment.    I think that this uses ubuntu 18.04 as well .... 

https://hub.docker.com/r/stnava/antspy

anyway, will try later.

**Comment by stnava** [comment]
can you try:

```
git clone https://github.com/ANTsX/ANTsPy
cd ANTsPy
python3 setup.py install
```

**Comment by stnava** [comment]
presuming non-issue.

**Comment by rousseau** [comment]
Sorry for the delay.

Same issue (when cloning the repository): 
Python config failure: Python is 0-biy, chosen compiler is 64 bit

**Comment by zzz123xyz** [comment]
> Sorry for the delay.
> 
> Same issue (when cloning the repository):
> Python config failure: Python is 0-bit, chosen compiler is 64 bit
> 
> HEAD is now at 680942c1 BUG: antsApplyTransforms -e 4 would write input image rather than deformed image
> Configuring ANTsPy library
> -- The C compiler identification is GNU 7.4.0
> -- The CXX compiler identification is GNU 7.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found PythonInterp: /home/rousseau/miniconda3/bin/python3 (found version "3.7.4")
> CMake Error at pybind11/tools/FindPythonLibsNew.cmake:122 (message):
> Python config failure: Python is 0-bit, chosen compiler is 64-bit
> Call Stack (most recent call first):
> pybind11/tools/pybind11Tools.cmake:16 (find_package)
> pybind11/CMakeLists.txt:28 (include)
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/rousseau/Code/ANTsPy/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
> Traceback (most recent call last):
> File "setup.py", line 147, in
> classifiers=['Programming Language :: Python :: 3.6'],
> File "/home/rousseau/miniconda3/lib/python3.7/site-packages/setuptools/**init**.py", line 145, in setup
> return distutils.core.setup(**attrs)
> File "/home/rousseau/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
> dist.run_commands()
> File "/home/rousseau/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
> self.run_command(cmd)
> File "/home/rousseau/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
> cmd_obj.run()
> File "setup.py", line 53, in run
> self.run_command("build_py")
> File "/home/rousseau/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "/home/rousseau/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
> cmd_obj.run()
> File "setup.py", line 38, in run
> self.run_command("build_ext")
> File "/home/rousseau/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
> self.distribution.run_command(command)
> File "/home/rousseau/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
> cmd_obj.run()
> File "setup.py", line 100, in run
> self.build_extension(ext)
> File "setup.py", line 129, in build_extension
> subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
> File "/home/rousseau/miniconda3/lib/python3.7/subprocess.py", line 347, in check_call
> raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['cmake', '/home/rousseau/Code/ANTsPy/ants/lib', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/rousseau/Code/ANTsPy/ants/lib/', '-DPYTHON_EXECUTABLE=/home/rousseau/miniconda3/bin/python3', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

any solution for this? I build the antspy and encounter the same problem:
subprocess.CalledProcessError: Command
