### ISSUE TITLE
affine3d does not output transform on y

### ISSUE THREAD

**Issue by jpcenteno80** [ANTsX/ANTsPy#80]
From the module in ```ants.contrib.sampling.affine3d```, the classes allow for X and y in the transform method, however when supplying X and y, only X transformed is returned (instead of the transformed tuple of X and y).
For example, in the case of the ```Shear3d``` class, this could be fixed by adding the following logic at the end of the transform method:
```
else:
    if y is None:
        return self.tx.apply_to_image(X, reference=self.reference)
    else:
        return self.tx.apply_to_image(X, reference=self.reference), self.tx.apply_to_image(y, reference=self.reference)
```

**Comment by stnava** [comment]
super - a pull request would be appreciated.

**Comment by stnava** [comment]
this request should be fulfilled with https://github.com/ANTsX/ANTsPy/commit/57df6f5916e3f4c46f3127f699c590aa2194b86a
