### ISSUE TITLE
GCC library errors running registration

### ISSUE THREAD

**Issue by Robkozol** [ANTsX/ANTsPy#82]
I recently built ANTs on our slurm based computer cluster and had to use several combinations of cmake and gcc to not receive an error. However, I am now receiving errors running the registration binary...

antsRegistration: /cm/local/apps/gcc/5.2.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by antsRegistration)
antsRegistration: /cm/local/apps/gcc/5.2.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by antsRegistration)
antsApplyTransforms: /cm/local/apps/gcc/5.2.0/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by antsApplyTransforms)
antsApplyTransforms: /cm/local/apps/gcc/5.2.0/lib64/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by antsApplyTransforms)

I was wondering, is this due to incompatible versions of these library files on the computing cluster? or should I be building with a specific version of gcc

Below is my script.

#!/bin/sh
#ANTS
cd "/home/rkozol/ANTS/ANTs1"
export ANTSPATH="/home/rkozol/bin/ants2/bin"
export ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS=80
    antsRegistration -d 3 –float 1 -o [fish/fish1_, fish1_Warped.nii.gz]-interpolation WelchWindowedSinc –use-histogram-matching 0 -r [ref/terk-ref.nii, fish/fish1–01.nii.gz,1] -t rigid[0.1] -m MI[ref/terk-ref.nii, fish1–01.nii.gz,1,32, Regular,0.25] -c [200 × 200 × 200 × 0,1e-8,10] –shrink-factors 12 × 8 × 4 × 2 –smoothing-sigmas 4 × 3 × 2 × 1vox -t Affine[0.1] -m MI[ref/terk-ref.nii, fish1–01.nii.gz,1,32, Regular,0.25] -c [200 × 200 × 200 × 0,1e-8,10] –shrink-factors 12 × 8 × 4 × 2 –smoothing-sigmas 4 × 3 × 2 × 1vox -t SyN[0.1,6,0] -m CC[ref/terk-ref.nii, fish1–01.nii.gz,1,2] -c [200 × 200 × 200 ×200 × 10,1e-7,10] –shrink-factors 12 × 8 × 4 × 2 × 1 –smoothing-sigmas 4 × 3 × 2 × 1 × 0vox
    antsApplyTransforms -d 3 -v 0 –float -n WelchWindowedSinc -i fish/fish1–02.nii.gz -r ref/terk-ref.nii -o fish1–02_Warped.nii -t fish1_1Warp.nii.gz -t fish1_0GenericAffine.mat

Thank you,
Rob

**Comment by ntustison** [comment]
This appears to be a ANTs issue.  Please post this issue over at that repo.  Thanks.
