### ISSUE TITLE
Dicom read

### ISSUE THREAD

**Issue by ryancinsight** [ANTsX/ANTsPy#84]
Hello I’ve tried the dicom read function but I don’t want the origin of my images to be the first slice.

Is there any way to implement the imageseriesreader with gdcm series I’d and filenames that itk has for dicom read?

**Comment by ntustison** [comment]
What about going through numpy as an intermediary?

**Comment by ryancinsight** [comment]
That would be fine, I believe I saw something similar image read which seems to be doing great for nifti images. I was trying to modify something similar to that but using the itk image series reader with pybind 11 but got stuck when it came to the ITK GDCM wrapping, which is probably do to my lack of understanding of pybind11 and c.

#include <pybind11/pybind11.h> // header for wrapping code
#include <pybind11/stl.h> // header for implicitly casting btwn python-cpp types

#include "itkImage.h"
#include "itkGDCMImageIO.h"
#include "itkGDCMSeriesFileNames.h"
#include "itkImageSeriesReader.h"

#include "LOCAL_antsImage.h"

namespace py = pybind11; // needed to use "py:"

template <typename NameGeneratorType>
py::capsule GDCMHelper( std::string Directory )
{
    //py::print("at imagereadhelper");
    typedef typename NameGeneratorType::Pointer         NameGeneratorPointerType;
    typedef itk::GDCMSeriesFileNames     NameGeneratorType;

    typename NameGeneratorType::Pointer nameGenerator = NameGeneratorType::New() ;
    nameGenerator->SetUseSeriesDetails(True);
    nameGenerator->AddSeriesRestriction("0008|0021");
    nameGenerator->SetGlobalWarningDisplay(False);
    nameGenerator->SetDirectory(Directory.c_str() );

    using SeriesIdContainer = std::vector< std::string >;
    const SeriesIdContainer & seriesUID = nameGenerator->GetSeriesUIDs();
    auto seriesItr = seriesUID.begin();
    auto seriesEnd = seriesUID.end();
    seriesItr = seriesUID.begin();
    seriesIdentifier = seriesItr->c_str();
    seriesItr++;
    using FileNamesContainer = std::vector< std::string >;
    return FileNamesContainer fileNames =nameGenerator->GetFileNames(seriesIdentifier);
 }
template <typename ImageIOType>
py::capsule GDCMIOHelper()
{
    typedef typename ImageIOType::Pointer ImagePointerType;
    typedef itk::GDCMImageIO  ImageIOType;
    typename ImageIOType::Pointer dicomIO = ImageIOType::New();
    return dicomIO
}

template <typename ImageType>
py::capsule imageSeriesHelper( std::string Directory )
{
    //py::print("at imagereadhelper");
    typedef typename ImageType::Pointer           ImagePointerType;
    typedef itk::ImageSeriesReader< ImageType >     ImageReaderType;

    typename ImageReaderType::Pointer image_reader = ImageReaderType::New() ;
    image_reader->SetImageIO(dicomIO<ImageIOType>);
    image_reader->SetFilesName( GDCMHelper<NameGeneratorType>(Directory)) ;
    image_reader->Update();

    ImagePointerType itkImage = image_reader->GetOutput();
    return wrap<ImageType>( itkImage );
}

template <typename ImageType>
py::capsule DicomRead( std::string Directory )
{
    py::capsule antsImage;
    antsImage = imageSeriesHelper<ImageType>( Directory );
    return antsImage;
}

**Comment by stnava** [comment]
what was the problem with this approach?   looks like you have most of the code needed.   did you follow this: 

https://github.com/ANTsX/ANTsPy/blob/master/CONTRIBUTING.md

it would most certainly be useful to have this fleshed out.

**Comment by stnava** [comment]
stale.
