### ISSUE TITLE
Undeterministic registration results

### ISSUE THREAD

**Issue by FietePfennig** [ANTsX/ANTsPy#86]
Hi
When I register two brain images with:

ants.registration(fixed=target_image_orig, moving=source_image_orig,                               type_of_transform="Rigid")

the result is not deterministic, which is bad for reproducibility testing. 

Is it possible to set a fixed seed for the random sampling ? If not, that would be my feature request ;-)

Thanks

Thomas

**Comment by stnava** [comment]
https://github.com/ANTsX/ANTsPy/commit/8c182cf7d499e3413c67280d017c8a38f873b518 might help

**Comment by stnava** [comment]
please reopen if this does not work for you.

**Comment by FietePfennig** [comment]
Wow, that was quick, thanks a lot

**Comment by stnava** [comment]
We made some small changes recently.   You can test by comparing to:

https://github.com/stnava/reproducibleANTsExample

You may need to compile from source.
