### ISSUE TITLE
Maybe error in ants.viz.plot 

### ISSUE THREAD

**Issue by Littlehhh** [ANTsX/ANTsPy#89]
**Describe the bug**
https://github.com/ANTsX/ANTsPy/blob/b488efc695e8451f16ab4afbabc16688500ed1a5/ants/viz/plot.py#L2148-L2158

Maybe the rotate180_matrix function is not same with mirror_matrix function.

**Expected behavior**
 
def rotate180_matrix(x): 
     return x[::-1, ::-1]

**Comment by stnava** [comment]
thank you.  fixed in recent commit.

**Comment by Littlehhh** [comment]
> thank you. fixed in recent commit.

Thanks for your helpful work.
