### ISSUE TITLE
image loading error

### ISSUE THREAD

**Issue by iversonicter** [ANTsX/ANTsPy#92]
TypeError: image_read() got an unexpected keyword argument 'reorient'

when runs this line, always give above error.
`img = ants.image_read( filename, reorient=True )`

Python: 3.6.3
Ubuntu OS

**Comment by halirutan** [comment]
Well, this is odd. It works for me. Can you give the output of the following:

```python
import ants
import inspect

ants.__version__
inspect.getsource(ants.image_read)
inspect.getfile(ants.image_read)
```

**Comment by stnava** [comment]
I also cannot reproduce this problem.

here is the code I used:

```
import ants
mni = ants.get_ants_data( "ch2" )
img = ants.image_read( mni, reorient=True )
img = ants.image_read( mni, reorient='LPS')
img = ants.image_read( mni, reorient='RPI')
```

tested on both osx and linux with **source install** - you may need to do the same.  we are lobbying for pypi permission but no luck so far

**Comment by iversonicter** [comment]
![image](https://user-images.githubusercontent.com/12019443/67945001-df765680-fc18-11e9-9ffa-0a58c14f0555.png)

Just show in the above image.  Does it seem there is no reorient argument?

Ants version is 0.1.4

**Comment by stnava** [comment]
see https://github.com/ANTsX/ANTsPy/issues/92#issuecomment-545410482

**Comment by iversonicter** [comment]
@stnava  Thanks for your kind reply. This problem can be fixed by source code installation. Currently, the Ants version is 0.2.2.  This error disappears now.
