### ISSUE TITLE
Set Default Value for Background After Registration

### ISSUE THREAD

**Issue by emckenzi123** [ANTsX/ANTsPy#95]
Hello,
I am trying to register CT images together.  In my CT images, the default background pixel value is -1024 (corresponding to air).  However, when I use ANTsPy to register the images, it automatically fill in the background of the moved image with 0 value pixels.  I searched through the documentation and cannot find a way to change the default background pixel value from 0 to -1024.  Am I missing a parameter setting or could this be added as an option for the end user?

Thanks!

**Comment by ntustison** [comment]
Okay, that option wasn't previously available but that should be fixed with [this pull request](https://github.com/ANTsX/ANTsPy/pull/96).

**Comment by emckenzi123** [comment]
Thank you very much!

**Comment by ntustison** [comment]
Please post a working example with data.

**Comment by emckenzi123** [comment]
Oops, sorry.  I forgot to run 'python setup.py install' after applying the changes.  It works now.  Thanks!!
