### ISSUE TITLE
missing compose_transforms_to_field

### ISSUE THREAD

**Issue by pipehappy1** [ANTsX/ANTsPy#97]
It appears compose_transforms_to_field shows up in ants/core/ants_transform_io.py.
But it's not shown up in the code.

**Comment by dagap** [comment]
I can confirm this is an issue as well as it makes it difficult to move and use ANTSpy generated transforms in other applications.

**Comment by alexluuuu** [comment]
Was anyone able to find a workaround? Would also like to use this function. Thanks!
