### ISSUE TITLE
ANTSpy initial_transfom option for registration

### ISSUE THREAD

**Issue by dagap** [ANTsX/ANTsPy#99]
I am trying to use the `initial_transform` option for doing the registration where I want to apply a useer specified transformation to initialise the registration. As an example, I tried the following:

```
ab = ants.registration(fixed=a, moving=b, type_of_transform='SyNCC')
bc = ants.registration(fixed=b, moving=c, type_of_transform='SyNCC')

tx = ab['fwdtransforms'] + bc['fwdtransforms']
ac = ants.registration(fixed=a, moving=c, type_of_transform='SyNCC', initial_transform=tx)
```

This results in an error as follows:

```
 file '/var/folders/l9/5ng0f5qs7ld8jtzypjmc016h0000gn/T/tmp31ng7aji1Warp.nii.gz' does not exist . 
Exception Object caught: 

itk::ExceptionObject (0x7fd42d8efb20)
Location: "unknown" 
File: /Users/infermatica/Dropbox/infermatica/code/mediaire/ANTsPy/ants/lib/antscore/antsCommandLineParser.h
Line: 126
Description: itk::ERROR: CommandLineParser(0x7fd42d8e5590): ERROR: Parse error occured during command line argument processing
ERROR: Unable to convert ' '/var/folders/l9/5ng0f5qs7ld8jtzypjmc016h0000gn/T/tmpzhny80so1Warp.nii.gz'' to type 't' as unsigned int

```

I have verified that all the transformation files do exist. I guess as a backup, I can perform the final registration by applying this transformation and using the resampled image for the final registration and then appending the resulting transformation. I am guessing this might result in an extra resampling but not sure.

**Comment by ntustison** [comment]
Despite what the help section says, it looks to me like the code expects "None" or the name of a single transform file (not a list).  One workaround until this is fixed is to compose the transforms using ``ants.apply_transforms`` and then use that single transform as the initial transform.

**Comment by stnava** [comment]
probably resolved by reading documentation.
